//go:build integration

package atlas_test

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"

	"go.5x5.cz/ptah/dbschema"
)

// TestCompatBinarySchemaInspectFormatLiterals exercises the compatibility
// formatter across the process, filesystem, and SQLite boundaries. The pinned
// Atlas CE v1.3.0 binary prints bare and whitespace-wrapped hcl/sql/json bodies
// literally; explicit helpers retain Ptah's complete rendering capability.
func TestCompatBinarySchemaInspectFormatLiterals(t *testing.T) {
	c := qt.New(t)
	compat := buildSchemaInspectBinary(c, "ptah-compat", "go.5x5.cz/ptah/cmd/ptah-compat")
	dir := c.TempDir()
	emptyDB := filepath.Join(dir, "empty.db")
	populatedDB := filepath.Join(dir, "populated.db")
	createSchemaInspectSQLiteDatabase(c, emptyDB)
	createSchemaInspectSQLiteDatabase(c, populatedDB,
		`CREATE TABLE users (id INTEGER PRIMARY KEY)`)

	tests := []struct {
		name   string
		dbPath string
		format string
		want   string
	}{
		{name: "bare SQL empty", dbPath: emptyDB, format: "sql", want: "sql"},
		{name: "bare SQL populated", dbPath: populatedDB, format: "sql", want: "sql"},
		{name: "bare JSON empty", dbPath: emptyDB, format: "json", want: "json"},
		{name: "bare JSON populated", dbPath: populatedDB, format: "json", want: "json"},
		{name: "bare HCL empty", dbPath: emptyDB, format: "hcl", want: "hcl"},
		{name: "bare HCL populated", dbPath: populatedDB, format: "hcl", want: "hcl"},
		{name: "wrapped SQL empty", dbPath: emptyDB, format: " sql ", want: " sql "},
		{name: "wrapped SQL populated", dbPath: populatedDB, format: " sql ", want: " sql "},
		{name: "wrapped JSON empty", dbPath: emptyDB, format: " json ", want: " json "},
		{name: "wrapped JSON populated", dbPath: populatedDB, format: " json ", want: " json "},
		{name: "wrapped HCL empty", dbPath: emptyDB, format: " hcl ", want: " hcl "},
		{name: "wrapped HCL populated", dbPath: populatedDB, format: " hcl ", want: " hcl "},
		{name: "explicit SQL empty", dbPath: emptyDB, format: `{{ sql . }}`},
		{
			name:   "explicit SQL populated",
			dbPath: populatedDB,
			format: `{{ sql . }}`,
			want:   "CREATE TABLE \"users\" (\n  \"id\" INTEGER PRIMARY KEY\n);\n",
		},
		{
			name:   "explicit JSON empty",
			dbPath: emptyDB,
			format: `{{ json . }}`,
			want:   `{"schemas":[{"name":"main"}]}`,
		},
		{
			name:   "explicit HCL stays rendered",
			dbPath: emptyDB,
			format: `{{ hcl . }}`,
			want:   "schema \"main\" {\n}\n",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			stdout, stderr, err := runSchemaInspectProcess(
				compat,
				"",
				"schema", "inspect",
				"--url", "sqlite://"+test.dbPath,
				"--format", test.format,
			)

			c.Assert(err, qt.IsNil, qt.Commentf("stderr=%s", stderr))
			c.Assert(stdout, qt.Equals, test.want)
			c.Assert(stderr, qt.Equals, "")
		})
	}
}

func TestCompatBinarySchemaInspectBareProjectFormatIsLiteralText(t *testing.T) {
	c := qt.New(t)
	compat := buildSchemaInspectBinary(c, "ptah-compat", "go.5x5.cz/ptah/cmd/ptah-compat")
	dir := c.TempDir()
	dbPath := filepath.Join(dir, "populated.db")
	createSchemaInspectSQLiteDatabase(c, dbPath,
		`CREATE TABLE users (id INTEGER PRIMARY KEY)`)
	c.Assert(os.WriteFile(filepath.Join(dir, "atlas.hcl"), []byte(`env "local" {
  url = "sqlite://`+dbPath+`"
  format {
    schema {
      inspect = "json"
    }
  }
}
`), 0o600), qt.IsNil)

	stdout, stderr, err := runSchemaInspectProcess(
		compat,
		dir,
		"schema", "inspect", "--env", "local",
	)

	c.Assert(err, qt.IsNil, qt.Commentf("stderr=%s", stderr))
	c.Assert(stdout, qt.Equals, "json")
	c.Assert(stderr, qt.Equals, "")
}

// TestNativeBinarySchemaInspectBareFormatsStillRender keeps the compatibility
// adapter from narrowing the native Ptah surface.
func TestNativeBinarySchemaInspectBareFormatsStillRender(t *testing.T) {
	c := qt.New(t)
	native := buildSchemaInspectBinary(c, "ptah", "go.5x5.cz/ptah/cmd/ptah")
	dir := c.TempDir()
	emptyDB := filepath.Join(dir, "empty.db")
	populatedDB := filepath.Join(dir, "populated.db")
	createSchemaInspectSQLiteDatabase(c, emptyDB)
	createSchemaInspectSQLiteDatabase(c, populatedDB,
		`CREATE TABLE users (id INTEGER PRIMARY KEY)`)

	tests := []struct {
		name   string
		dbPath string
		format string
		want   string
	}{
		{name: "SQL empty", dbPath: emptyDB, format: "sql"},
		{
			name:   "SQL populated",
			dbPath: populatedDB,
			format: "sql",
			want:   "CREATE TABLE \"users\" (\n  \"id\" INTEGER PRIMARY KEY\n);\n",
		},
		{
			name:   "JSON empty",
			dbPath: emptyDB,
			format: "json",
			want:   `{"schemas":[{"name":"main"}]}`,
		},
		{
			name:   "HCL empty",
			dbPath: emptyDB,
			format: "hcl",
			want:   "// Code generated by ptah; DO NOT EDIT.\n\nschema \"main\" {\n}\n\n",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			stdout, stderr, err := runSchemaInspectProcess(
				native,
				"",
				"schema", "inspect",
				"--db-url", "sqlite://"+test.dbPath,
				"--format", test.format,
			)

			c.Assert(err, qt.IsNil, qt.Commentf("stderr=%s", stderr))
			c.Assert(stdout, qt.Equals, test.want)
			c.Assert(stderr, qt.Equals, "")
		})
	}
}

func buildSchemaInspectBinary(c *qt.C, name, packagePath string) string {
	c.Helper()
	path := filepath.Join(c.TempDir(), name)
	cmd := exec.Command("go", "build", "-o", path, packagePath)
	out, err := cmd.CombinedOutput()
	c.Assert(err, qt.IsNil, qt.Commentf("build %s: %s", name, out))
	return path
}

func runSchemaInspectProcess(binary, dir string, args ...string) (stdout, stderr string, runErr error) {
	cmd := exec.Command(binary, args...)
	cmd.Dir = dir
	cmd.Env = environmentWithoutPtahVariables()
	var stdoutBuffer bytes.Buffer
	var stderrBuffer bytes.Buffer
	cmd.Stdout = &stdoutBuffer
	cmd.Stderr = &stderrBuffer
	runErr = cmd.Run()
	return stdoutBuffer.String(), stderrBuffer.String(), runErr
}

func environmentWithoutPtahVariables() []string {
	env := make([]string, 0, len(os.Environ()))
	for _, entry := range os.Environ() {
		if !strings.HasPrefix(entry, "PTAH_") {
			env = append(env, entry)
		}
	}
	return env
}

func createSchemaInspectSQLiteDatabase(c *qt.C, dbPath string, statements ...string) {
	c.Helper()
	conn, err := dbschema.ConnectToDatabase(context.Background(), "sqlite://"+dbPath)
	c.Assert(err, qt.IsNil)
	defer dbschema.CloseAndWarn(conn)

	for _, statement := range statements {
		_, err = conn.ExecContext(context.Background(), statement)
		c.Assert(err, qt.IsNil)
	}
}
