package renderer_test

import (
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"

	"ptah.run/core/platform"
	"ptah.run/core/platform/capability"
	"ptah.run/core/renderer"
	"ptah.run/core/schemamodel"
)

// identitySchema declares a key whose first value and step the author chose.
//
// Every target spells a generated key some way, so the spelling is not the
// loss. The values are, and stokaro/ptah#2969 makes that sharper than it looks:
// a PostgreSQL-family target tells the author to move an AUTO_INCREMENT start
// onto identity_start, and five targets drop that value without a word
// (stokaro/ptah#2983).
func identitySchema() *schemamodel.Database {
	return &schemamodel.Database{
		Tables: []schemamodel.Table{{StructName: "Ticket", Name: "tickets"}},
		Fields: []schemamodel.Field{{
			StructName:         "Ticket",
			Name:               "id",
			Type:               "INT",
			Primary:            true,
			IdentityGeneration: "ALWAYS",
			IdentityStart:      "500",
			IdentityIncrement:  "10",
		}},
	}
}

// TestGetOrderedCreateStatementsReportingOmissions_NamesEveryLostIdentityClause
// pins what each target keeps of a declared identity.
//
// Measured on this tree. SQL Server writes IDENTITY(500, 10) and has no ALWAYS
// or BY DEFAULT, so it loses only the generation mode. Oracle is the one that
// substitutes rather than omits: it always writes GENERATED BY DEFAULT, so a
// column declaring ALWAYS gets different semantics and no start at all.
func TestGetOrderedCreateStatementsReportingOmissions_NamesEveryLostIdentityClause(t *testing.T) {
	tests := []struct {
		name    string
		dialect string
		want    []string
	}{
		{
			name:    "mysql keeps none of the values",
			dialect: platform.MySQL,
			want:    []string{"identity generation", "identity increment", "identity start"},
		},
		{
			name:    "mariadb keeps none of the values",
			dialect: platform.MariaDB,
			want:    []string{"identity generation", "identity increment", "identity start"},
		},
		{
			name:    "sqlite keeps none of the values",
			dialect: platform.SQLite,
			want:    []string{"identity generation", "identity increment", "identity start"},
		},
		{
			name:    "sql server keeps the start and the step",
			dialect: platform.SQLServer,
			want:    []string{"identity generation"},
		},
		{
			name:    "oracle keeps none of the values",
			dialect: platform.Oracle,
			want:    []string{"identity generation", "identity increment", "identity start"},
		},
		{
			name:    "clickhouse generates no key values at all",
			dialect: platform.ClickHouse,
			want:    []string{"identity generation", "identity increment", "identity start"},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			_, omissions, err := renderer.GetOrderedCreateStatementsReportingOmissions(
				identitySchema(), test.dialect, capability.ForDialect(test.dialect))

			c.Assert(err, qt.IsNil)
			properties := make([]string, 0, len(omissions))
			for _, omission := range omissions {
				c.Assert(omission.Name, qt.Equals, "tickets.id")
				properties = append(properties, omission.Property)
			}
			c.Assert(properties, qt.DeepEquals, test.want)
		})
	}
}

// TestGetOrderedCreateStatementsReportingOmissions_PostgresKeepsEveryIdentityClause
// is the control.
//
// Every row above is satisfied by a report that fires for any identity column.
// PostgreSQL writes the mode, the start and the step, so a finding here would
// mean the check reports a declaration the target kept.
func TestGetOrderedCreateStatementsReportingOmissions_PostgresKeepsEveryIdentityClause(t *testing.T) {
	c := qt.New(t)

	statements, omissions, err := renderer.GetOrderedCreateStatementsReportingOmissions(
		identitySchema(), platform.Postgres, capability.Postgres17())

	c.Assert(err, qt.IsNil)
	c.Assert(omissions, qt.HasLen, 0)
	rendered := strings.Join(statements, "\n")
	c.Assert(rendered, qt.Contains, "GENERATED ALWAYS AS IDENTITY")
	c.Assert(rendered, qt.Contains, "START WITH 500")
	c.Assert(rendered, qt.Contains, "INCREMENT BY 10")
}

// TestGetOrderedCreateStatementsReportingOmissions_SQLServerWritesTheValuesItKeeps
// is the other half of the SQL Server row.
//
// That row claims the start and the step survive. The claim is only worth
// having if they are in the output, so it is asked for rather than trusted.
func TestGetOrderedCreateStatementsReportingOmissions_SQLServerWritesTheValuesItKeeps(t *testing.T) {
	c := qt.New(t)

	statements, _, err := renderer.GetOrderedCreateStatementsReportingOmissions(
		identitySchema(), platform.SQLServer, capability.SQLServer2022())

	c.Assert(err, qt.IsNil)
	c.Assert(strings.Join(statements, "\n"), qt.Contains, "IDENTITY(500,10)")
}

// TestGetOrderedCreateStatementsReportingOmissions_APlainKeyReportsNothing keeps
// the check from firing on the spelling of a generated key.
//
// Every target writes one some way, and a column that declared no values lost
// none. Without this, every schema with an auto-incrementing key would fail on
// six targets.
func TestGetOrderedCreateStatementsReportingOmissions_APlainKeyReportsNothing(t *testing.T) {
	tests := []struct {
		name    string
		dialect string
	}{
		{name: "mysql", dialect: platform.MySQL},
		{name: "sqlite", dialect: platform.SQLite},
		{name: "sql server", dialect: platform.SQLServer},
		{name: "oracle", dialect: platform.Oracle},
	}

	database := &schemamodel.Database{
		Tables: []schemamodel.Table{{StructName: "Ticket", Name: "tickets"}},
		Fields: []schemamodel.Field{
			{StructName: "Ticket", Name: "id", Type: "INT", Primary: true, AutoInc: true},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			_, omissions, err := renderer.GetOrderedCreateStatementsReportingOmissions(
				database, test.dialect, capability.ForDialect(test.dialect))

			c.Assert(err, qt.IsNil)
			c.Assert(omissions, qt.HasLen, 0)
		})
	}
}
