package yamlschema_test

import (
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"

	"github.com/stokaro/ptah/core/goschema"
	"github.com/stokaro/ptah/core/renderer"
	"github.com/stokaro/ptah/core/yamlschema"
)

func TestParse_IssueExampleMatchesGoAnnotations(t *testing.T) {
	c := qt.New(t)

	yamlDB, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id: { type: SERIAL, primary: true }
      email: { type: VARCHAR(255), not_null: true, unique: true }
    indexes:
      idx_users_email: { fields: [email] }
`))
	c.Assert(err, qt.IsNil)

	goDB, err := goschema.ParseSource("schema.go", `
package test

//migrator:schema:table name="users"
type User struct {
	//migrator:schema:field name="id" type="SERIAL" primary="true"
	ID int64

	//migrator:schema:field name="email" type="VARCHAR(255)" not_null="true" unique="true"
	Email string

	//migrator:schema:index name="idx_users_email" fields="email"
	_ int
}
`)
	c.Assert(err, qt.IsNil)

	yamlSQL := strings.Join(renderer.GetOrderedCreateStatements(yamlDB, "postgres"), "\n")
	goSQL := strings.Join(renderer.GetOrderedCreateStatements(&goDB, "postgres"), "\n")
	c.Assert(yamlSQL, qt.Equals, goSQL)
}

func TestParse_IdentityColumn(t *testing.T) {
	c := qt.New(t)

	db, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id:
        type: int
        not_null: true
        identity_generation: BY_DEFAULT
        identity_start: 10
        identity_increment: 5
        identity_options: START WITH 10 INCREMENT BY 5 CACHE 3
`))
	c.Assert(err, qt.IsNil)
	c.Assert(db.Fields, qt.HasLen, 1)
	c.Assert(db.Fields[0].AutoInc, qt.IsTrue)
	c.Assert(db.Fields[0].IdentityGeneration, qt.Equals, "BY_DEFAULT")
	c.Assert(db.Fields[0].IdentityStart, qt.Equals, "10")
	c.Assert(db.Fields[0].IdentityIncrement, qt.Equals, "5")
	c.Assert(db.Fields[0].IdentityOptions, qt.Equals, "START WITH 10 INCREMENT BY 5 CACHE 3")

	sql := legacyRenderedSQL(strings.Join(renderer.GetOrderedCreateStatements(db, "postgres"), "\n"))
	c.Assert(sql, qt.Contains, "GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5 CACHE 3)")
}

func TestParse_IdentityColumnRejectsInvalidGeneration(t *testing.T) {
	c := qt.New(t)

	_, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id:
        type: int
        identity_generation: BY_DEFUALT
`))
	c.Assert(err, qt.ErrorMatches, `.*unsupported identity_generation "BY_DEFUALT".*`)
}

func TestParse_IdentityColumnOptionsDefaultGeneration(t *testing.T) {
	c := qt.New(t)

	db, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id:
        type: int
        identity_options: MINVALUE 0 START WITH 0
`))
	c.Assert(err, qt.IsNil)
	c.Assert(db.Fields, qt.HasLen, 1)
	c.Assert(db.Fields[0].AutoInc, qt.IsTrue)
	c.Assert(db.Fields[0].IdentityGeneration, qt.Equals, "BY_DEFAULT")
	c.Assert(db.Fields[0].IdentityOptions, qt.Equals, "MINVALUE 0 START WITH 0")

	sql := legacyRenderedSQL(strings.Join(renderer.GetOrderedCreateStatements(db, "postgres"), "\n"))
	c.Assert(sql, qt.Contains, "GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0)")
}

func TestParse_CoversCurrentSchemaIR(t *testing.T) {
	c := qt.New(t)

	db, err := yamlschema.Parse([]byte(`
enums:
  account_status: [active, suspended]
extensions:
  pg_trgm:
    if_not_exists: true
functions:
  current_tenant:
    params: ""
    returns: TEXT
    language: SQL
    security: DEFINER
    volatility: STABLE
    body: SELECT current_setting('app.current_tenant_id')
roles:
  app_user:
    login: true
    inherit: false
grants:
  app_user_schema:
    role: app_user
    privilege: USAGE
    on_schema: public
  app_user_users:
    role: app_user
    privileges: [SELECT, INSERT]
    on_table: users
tables:
  tenants:
    columns:
      id: { type: SERIAL, primary: true }
  users:
    rls_enabled: true
    columns:
      id: { type: SERIAL, primary: true }
      tenant_id:
        type: INTEGER
        not_null: true
        foreign: tenants(id)
        foreign_key_name: fk_users_tenant
        on_delete: CASCADE
      status:
        type: account_status
        not_null: true
        default: active
      email:
        type: VARCHAR(255)
        not_null: true
        unique: true
        platform:
          mysql:
            type: VARCHAR(191)
      email_lc:
        type: TEXT
        generated: lower(email)
        stored: true
    indexes:
      idx_users_email:
        fields: [email]
        unique: true
        where: deleted_at IS NULL
    constraints:
      chk_users_email:
        type: CHECK
        check: "position('@' in email) > 1"
rls_policies:
  users_tenant_isolation:
    table: users
    for: ALL
    to: app_user
    using: tenant_id = current_tenant()::INTEGER
`))
	c.Assert(err, qt.IsNil)

	c.Assert(db.Tables, qt.HasLen, 2)
	c.Assert(db.Tables[0].Name, qt.Equals, "tenants")
	c.Assert(db.Tables[1].Name, qt.Equals, "users")
	c.Assert(db.Fields, qt.HasLen, 6)
	c.Assert(db.Fields[5].GeneratedExpression, qt.Equals, "lower(email)")
	c.Assert(db.Fields[5].GeneratedKind, qt.Equals, "STORED")
	c.Assert(db.Enums, qt.DeepEquals, []goschema.Enum{{Name: "account_status", Values: []string{"active", "suspended"}}})
	c.Assert(db.Extensions, qt.HasLen, 1)
	c.Assert(db.Functions, qt.HasLen, 1)
	c.Assert(db.Functions[0].Returns, qt.Equals, "text")
	c.Assert(db.Functions[0].Language, qt.Equals, "sql")
	c.Assert(db.Roles, qt.HasLen, 1)
	c.Assert(db.Roles[0].Inherit, qt.IsFalse)
	c.Assert(db.Grants, qt.HasLen, 2)
	c.Assert(db.Grants[0].Privileges, qt.DeepEquals, []string{"USAGE"})
	c.Assert(db.Grants[1].Privileges, qt.DeepEquals, []string{"SELECT", "INSERT"})
	c.Assert(db.Grants[1].OnTable, qt.Equals, "users")
	c.Assert(db.RLSEnabledTables, qt.HasLen, 1)
	c.Assert(db.RLSPolicies, qt.HasLen, 1)
	c.Assert(db.Constraints, qt.HasLen, 1)
	c.Assert(db.Indexes[0].Condition, qt.Equals, "deleted_at IS NULL")
	c.Assert(db.Dependencies["users"], qt.DeepEquals, []string{"tenants"})

	sql := legacyRenderedSQL(strings.Join(renderer.GetOrderedCreateStatements(db, "postgres"), "\n"))
	c.Assert(sql, qt.Contains, "email_lc TEXT GENERATED ALWAYS AS (lower(email)) STORED")
	c.Assert(sql, qt.Contains, "WHERE deleted_at IS NULL")
	c.Assert(sql, qt.Contains, `CONSTRAINT chk_users_email CHECK (position('@' in email) > 1)`)
	c.Assert(sql, qt.Contains, `ALTER TABLE users ENABLE ROW LEVEL SECURITY;`)
	c.Assert(sql, qt.Contains, `CREATE POLICY users_tenant_isolation ON users`)
	c.Assert(sql, qt.Contains, `GRANT USAGE ON SCHEMA public TO app_user;`)
	c.Assert(sql, qt.Contains, `GRANT SELECT, INSERT ON TABLE users TO app_user;`)
}

func TestParse_TrimsScalarEnumValues(t *testing.T) {
	c := qt.New(t)

	db, err := yamlschema.Parse([]byte(`
enums:
  account_status: active, suspended
`))
	c.Assert(err, qt.IsNil)
	c.Assert(db.Enums, qt.DeepEquals, []goschema.Enum{{
		Name:   "account_status",
		Values: []string{"active", "suspended"},
	}})
}

func TestParse_RejectsDuplicateOrderedMappingKeys(t *testing.T) {
	c := qt.New(t)

	_, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id: { type: SERIAL, primary: true }
      id: { type: BIGSERIAL, primary: true }
`))
	c.Assert(err, qt.ErrorMatches, `parse YAML schema: duplicate key "id"`)
}

func TestParse_RejectsDuplicateTopLevelMappingKeys(t *testing.T) {
	c := qt.New(t)

	_, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id: { type: SERIAL, primary: true }
  users:
    columns:
      id: { type: BIGSERIAL, primary: true }
`))
	c.Assert(err, qt.ErrorMatches, `(?s)parse YAML schema: .*mapping key "users" already defined.*`)
}

func TestParse_RejectsInvalidIndexesAndConstraints(t *testing.T) {
	c := qt.New(t)

	_, err := yamlschema.Parse([]byte(`
indexes:
  idx_users_email:
    fields: [email]
`))
	c.Assert(err, qt.ErrorMatches, `top-level index "idx_users_email" requires table`)

	_, err = yamlschema.Parse([]byte(`
constraints:
  chk_users_email:
    type: CHECK
    check: "position('@' in email) > 1"
`))
	c.Assert(err, qt.ErrorMatches, `top-level constraint "chk_users_email" requires table`)

	_, err = yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      email: { type: VARCHAR(255), not_null: true }
    constraints:
      chk_users_email:
        check: "position('@' in email) > 1"
`))
	c.Assert(err, qt.ErrorMatches, `constraint "chk_users_email" requires type`)
}

func TestParse_RejectsMultipleDocuments(t *testing.T) {
	c := qt.New(t)

	_, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id: { type: SERIAL, primary: true }
---
tables:
  posts:
    columns:
      id: { type: SERIAL, primary: true }
`))
	c.Assert(err, qt.ErrorMatches, `parse YAML schema: multiple YAML documents are not supported`)
}

func TestParse_ViewsMaterializedViewsAndTriggers(t *testing.T) {
	c := qt.New(t)

	db, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id: { type: SERIAL, primary: true }
views:
  active_users:
    body: SELECT id FROM users WHERE deleted_at IS NULL
    with_check: true
matviews:
  user_stats:
    body: SELECT id, COUNT(*) FROM users GROUP BY id
    refresh_strategy: concurrently
triggers:
  set_updated_at:
    table: users
    timing: before
    event: update
    body: NEW.updated_at = NOW(); RETURN NEW;
`))
	c.Assert(err, qt.IsNil)
	c.Assert(db.Views, qt.HasLen, 1)
	c.Assert(db.Views[0].Name, qt.Equals, "active_users")
	c.Assert(db.Views[0].WithCheck, qt.IsTrue)
	c.Assert(db.MaterializedViews, qt.HasLen, 1)
	c.Assert(db.MaterializedViews[0].RefreshStrategy, qt.Equals, "concurrently")
	c.Assert(db.Triggers, qt.HasLen, 1)
	c.Assert(db.Triggers[0].Table, qt.Equals, "users")
	c.Assert(db.Triggers[0].Timing, qt.Equals, "BEFORE")
	c.Assert(db.Triggers[0].Event, qt.Equals, "UPDATE")
	c.Assert(db.Triggers[0].ForEach, qt.Equals, "ROW")
}

func TestParse_RejectsIncompleteSchemaObjects(t *testing.T) {
	tests := []struct {
		name string
		yaml string
		want string
	}{
		{
			name: "view missing body",
			yaml: `
views:
  active_users: {}
`,
			want: `view "active_users" requires body`,
		},
		{
			name: "materialized view missing body",
			yaml: `
matviews:
  user_stats: {}
`,
			want: `materialized view "user_stats" requires body`,
		},
		{
			name: "trigger missing table",
			yaml: `
triggers:
  set_updated_at:
    timing: before
    event: update
    body: RETURN NEW;
`,
			want: `trigger "set_updated_at" requires table`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := qt.New(t)
			_, err := yamlschema.Parse([]byte(tt.yaml))
			c.Assert(err, qt.ErrorMatches, tt.want)
		})
	}
}

func TestParse_RejectsUnknownColumnAttributes(t *testing.T) {
	c := qt.New(t)

	_, err := yamlschema.Parse([]byte(`
tables:
  users:
    columns:
      id:
        type: SERIAL
        primarry: true
`))
	c.Assert(err, qt.ErrorMatches, `(?s)parse YAML schema: .*field primarry not found.*`)
}
