package protobufrender

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

// Header lines every generated file carries. The marker matches the wording
// used by internal/atlashclrender, internal/graphqlrender and
// internal/convert/goschematogo, and satisfies Go's canonical
// "^// Code generated .* DO NOT EDIT\.$".
//
// The block sits at the FOOT of the generated file. In the leading position it
// is the file's leading detached comment, which protoc-gen-go copies verbatim to
// the top of every .pb.go it produces: consumers' Go source carried Ptah's
// content digest, and its first "Code generated by" line named ptah instead of
// protoc-gen-go.
const (
	generatedMarker = "// Code generated by ptah schema export --to protobuf; DO NOT EDIT."
	versionPrefix   = "// ptah:protobuf-export-version="
	digestPrefix    = "// ptah:content-sha256="
	// manifestPrefix introduces the anchor file's inventory of the other files
	// the same run wrote. It is the export set's own record of itself: without
	// it a later run cannot tell a type that moved to another file from a type
	// that was deleted and recreated, and would restart its field numbers at 1.
	manifestPrefix = "// ptah:protobuf-export-files="

	// exportVersion is the format version of the generated file, and the only
	// one this exporter reads or writes. A file declaring any other version is
	// refused: a higher one was written by a newer Ptah, and a lower one is a
	// retired layout.
	//
	// Version 1 put the header block at the head of the file, which made it
	// protoc-gen-go's leading comment too. It was retired rather than migrated:
	// Ptah is pre-general-availability, so a published .proto carrying it is a
	// baseline someone can regenerate, and carrying a second reader forever to
	// save that one regeneration is the wrong trade.
	//
	// A multi-file export does NOT get a version of its own. The manifest line
	// is what distinguishes a set from a lone file, and the only thing a second
	// version number could add is a refusal aimed at a Ptah too old to read the
	// manifest -- which is compatibility with an older Ptah, and that is not
	// owed before v1.
	exportVersion = 2
)

// manifestNamePattern bounds what a manifest entry may name: a plain file name
// in the anchor's own directory. Deliberately wider than the lint-clean
// generated shape, so a name Ptah itself derived and warned about can still be
// read back, and narrow enough that no entry can escape the directory.
var manifestNamePattern = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9_.\-]*\.proto$`)

var utf8BOM = []byte{0xef, 0xbb, 0xbf}

// canonicalize produces the bytes every header check and the digest operate on.
// Scoping this to the digest alone would make a pristine CRLF or BOM checkout
// fail the *marker* check and be reported as a foreign file, whose remedy is
// deleting the compatibility baseline.
func canonicalize(raw []byte) []byte {
	out := bytes.TrimPrefix(raw, utf8BOM)
	out = bytes.ReplaceAll(out, []byte("\r\n"), []byte("\n"))
	out = bytes.ReplaceAll(out, []byte("\r"), []byte("\n"))
	return out
}

// digestLineIndexes reports the index of every line whose prefix is
// digestPrefix. The line is matched by prefix and not by value shape: a matcher
// requiring 64 hex characters would fail to strip a line whose value is corrupt,
// silently changing the canonical bytes and turning a clear digest mismatch into
// an incoherent one.
func digestLineIndexes(lines []string) []int {
	var found []int
	for i, line := range lines {
		if strings.HasPrefix(line, digestPrefix) {
			found = append(found, i)
		}
	}
	return found
}

// splitLines splits canonical bytes into lines without dropping information:
// joining the result with "\n" reproduces the input exactly.
func splitLines(canonical []byte) []string {
	return strings.Split(string(canonical), "\n")
}

// computeDigest hashes the canonical bytes with the single digest line removed,
// so the digest never covers its own value. It returns an error unless exactly
// one digest line is present.
func computeDigest(canonical []byte) (string, error) {
	lines := splitLines(canonical)
	found := digestLineIndexes(lines)
	if len(found) != 1 {
		return "", fmt.Errorf("expected exactly one %q line, found %d", strings.TrimSuffix(digestPrefix, "="), len(found))
	}
	kept := make([]string, 0, len(lines)-1)
	kept = append(kept, lines[:found[0]]...)
	kept = append(kept, lines[found[0]+1:]...)

	sum := sha256.Sum256([]byte(strings.Join(kept, "\n")))
	return hex.EncodeToString(sum[:]), nil
}

// recordedDigest returns the digest value written in the file. The value is the
// line's remainder with surrounding whitespace trimmed, so trailing whitespace
// on that one line is tolerated while every other byte stays protected.
func recordedDigest(canonical []byte) (string, error) {
	lines := splitLines(canonical)
	found := digestLineIndexes(lines)
	if len(found) != 1 {
		return "", fmt.Errorf("expected exactly one %q line, found %d", strings.TrimSuffix(digestPrefix, "="), len(found))
	}
	return strings.TrimSpace(strings.TrimPrefix(lines[found[0]], digestPrefix)), nil
}

// stampDigest replaces the digest line's value with the digest of the rest of
// the file. It is the last step before the bytes are written.
func stampDigest(rendered []byte) ([]byte, error) {
	canonical := canonicalize(rendered)
	sum, err := computeDigest(canonical)
	if err != nil {
		return nil, err
	}
	lines := splitLines(canonical)
	found := digestLineIndexes(lines)
	lines[found[0]] = digestPrefix + sum
	return []byte(strings.Join(lines, "\n")), nil
}

// manifestNames returns the base names the anchor's header records as the rest
// of its export set. A file without the line names no siblings, which is how a
// single-file baseline reads. Every entry is validated, because the names it
// carries decide which files a later run reads back and may delete.
func manifestNames(canonical []byte) ([]string, error) {
	var names []string
	seen := false
	for _, line := range splitLines(canonical) {
		if !strings.HasPrefix(line, manifestPrefix) {
			continue
		}
		if seen {
			return nil, fmt.Errorf("%w: more than one %s line",
				ErrModified, strings.TrimSuffix(manifestPrefix, "="))
		}
		seen = true
		raw := strings.TrimSpace(strings.TrimPrefix(line, manifestPrefix))
		if raw == "" {
			return nil, fmt.Errorf("%w: empty %s line", ErrModified, strings.TrimSuffix(manifestPrefix, "="))
		}
		for entry := range strings.SplitSeq(raw, ",") {
			name := strings.TrimSpace(entry)
			if !manifestNamePattern.MatchString(name) {
				return nil, fmt.Errorf("%w: %s names %q, which is not a plain .proto file name",
					ErrModified, strings.TrimSuffix(manifestPrefix, "="), name)
			}
			if slices.Contains(names, name) {
				return nil, fmt.Errorf("%w: %s names %q twice",
					ErrModified, strings.TrimSuffix(manifestPrefix, "="), name)
			}
			names = append(names, name)
		}
	}
	return names, nil
}

// ManifestNames reports the other files a previously generated anchor says its
// export set contains. The caller reads those files and hands them back through
// Options.PreviousSiblings; every one of them, and the anchor itself, is
// validated in full by Render. It deliberately does not authenticate the anchor
// first: a file that is not a Ptah export simply records no siblings and is
// refused by Render's own gate, which carries the specific remedy.
func ManifestNames(raw []byte) ([]string, error) {
	return manifestNames(canonicalize(raw))
}

// parsedHeader is what the generated header tells us about a previous export.
type parsedHeader struct {
	Version int
}

// hasHeaderMarker reports whether the generated marker sits in one of the two
// positions the exporter has ever written it: the file's trailing comment block,
// which is the only layout still written, or its first line, which is the
// retired version 1 layout.
//
// The retired position is still RECOGNIZED even though version 1 is no longer
// read, so that a version 1 file is diagnosed by its version — "delete the file
// and export again" — rather than as a foreign file, which is a different
// remedy for a different problem and would leave the reader hunting for who
// else wrote their .proto.
//
// The marker is anchored to those positions rather than searched for file-wide.
// A table comment whose text happens to reproduce the marker renders as an
// ordinary top-level comment line in the middle of the file, and a free search
// would read that line as the file's header.
//
// The trailing block is walked rather than indexed at a fixed offset so that a
// generated file missing or repeating a header line is still recognized as
// Ptah's and diagnosed by the digest gate as modified, whose remedy is restoring
// it, rather than as foreign, whose remedy is deleting the compatibility
// baseline.
func hasHeaderMarker(lines []string) bool {
	if len(lines) == 0 {
		return false
	}
	if lines[0] == generatedMarker {
		return true
	}
	for _, line := range slices.Backward(lines) {
		if line == generatedMarker {
			return true
		}
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			continue
		}
		// Reached a body line without meeting the marker.
		return false
	}
	return false
}

// parseHeader validates the marker and version lines of canonical bytes.
func parseHeader(canonical []byte) (parsedHeader, error) {
	lines := splitLines(canonical)
	if !hasHeaderMarker(lines) {
		return parsedHeader{}, fmt.Errorf("%w; %s", ErrForeignFile, remedyForeign)
	}

	for _, line := range lines {
		if !strings.HasPrefix(line, versionPrefix) {
			continue
		}
		raw := strings.TrimSpace(strings.TrimPrefix(line, versionPrefix))
		version, err := strconv.Atoi(raw)
		if err != nil {
			return parsedHeader{}, fmt.Errorf("%w: unreadable export version %q", ErrUnsupportedVersion, raw)
		}
		if version != exportVersion {
			return parsedHeader{}, fmt.Errorf(
				"%w: file declares export version %d, this Ptah reads and writes only %d; "+
					"delete the file and export again to start a new compatibility history",
				ErrUnsupportedVersion, version, exportVersion)
		}
		return parsedHeader{Version: version}, nil
	}
	return parsedHeader{}, fmt.Errorf("%w: no %s line", ErrUnsupportedVersion, strings.TrimSuffix(versionPrefix, "="))
}
