package protobufrender

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

// Header lines every generated file carries. The marker matches the wording
// used by internal/atlashclrender, internal/graphqlrender and
// internal/convert/goschematogo, and satisfies Go's canonical
// "^// Code generated .* DO NOT EDIT\.$".
const (
	generatedMarker = "// Code generated by ptah schema export --to protobuf; DO NOT EDIT."
	versionPrefix   = "// ptah:protobuf-export-version="
	digestPrefix    = "// ptah:content-sha256="
	// manifestPrefix introduces the anchor file's inventory of the other files
	// the same run wrote. It is the export set's own record of itself: without
	// it a later run cannot tell a type that moved to another file from a type
	// that was deleted and recreated, and would restart its field numbers at 1.
	manifestPrefix = "// ptah:protobuf-export-files="

	// exportVersionSingle is declared by an export that writes exactly one file.
	// It is unchanged from the first released format, so a single-file baseline
	// generated before multi-file support stays readable and rewritable.
	exportVersionSingle = 1
	// exportVersionMulti is declared by every file of a multi-file export. It is
	// a minimum reader version: a Ptah without multi-file support would read one
	// file of the set in isolation and rewrite it as a whole single-file
	// baseline, so it must refuse instead.
	exportVersionMulti = 2
	// exportVersion is the highest format version this Ptah can read.
	exportVersion = exportVersionMulti
)

// manifestNamePattern bounds what a manifest entry may name: a plain file name
// in the anchor's own directory. Deliberately wider than the lint-clean
// generated shape, so a name Ptah itself derived and warned about can still be
// read back, and narrow enough that no entry can escape the directory.
var manifestNamePattern = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9_.\-]*\.proto$`)

var utf8BOM = []byte{0xef, 0xbb, 0xbf}

// canonicalize produces the bytes every header check and the digest operate on.
// Scoping this to the digest alone would make a pristine CRLF or BOM checkout
// fail the *marker* check and be reported as a foreign file, whose remedy is
// deleting the compatibility baseline.
func canonicalize(raw []byte) []byte {
	out := bytes.TrimPrefix(raw, utf8BOM)
	out = bytes.ReplaceAll(out, []byte("\r\n"), []byte("\n"))
	out = bytes.ReplaceAll(out, []byte("\r"), []byte("\n"))
	return out
}

// digestLineIndexes reports the index of every line whose prefix is
// digestPrefix. The line is matched by prefix and not by value shape: a matcher
// requiring 64 hex characters would fail to strip a line whose value is corrupt,
// silently changing the canonical bytes and turning a clear digest mismatch into
// an incoherent one.
func digestLineIndexes(lines []string) []int {
	var found []int
	for i, line := range lines {
		if strings.HasPrefix(line, digestPrefix) {
			found = append(found, i)
		}
	}
	return found
}

// splitLines splits canonical bytes into lines without dropping information:
// joining the result with "\n" reproduces the input exactly.
func splitLines(canonical []byte) []string {
	return strings.Split(string(canonical), "\n")
}

// computeDigest hashes the canonical bytes with the single digest line removed,
// so the digest never covers its own value. It returns an error unless exactly
// one digest line is present.
func computeDigest(canonical []byte) (string, error) {
	lines := splitLines(canonical)
	found := digestLineIndexes(lines)
	if len(found) != 1 {
		return "", fmt.Errorf("expected exactly one %q line, found %d", strings.TrimSuffix(digestPrefix, "="), len(found))
	}
	kept := make([]string, 0, len(lines)-1)
	kept = append(kept, lines[:found[0]]...)
	kept = append(kept, lines[found[0]+1:]...)

	sum := sha256.Sum256([]byte(strings.Join(kept, "\n")))
	return hex.EncodeToString(sum[:]), nil
}

// recordedDigest returns the digest value written in the file. The value is the
// line's remainder with surrounding whitespace trimmed, so trailing whitespace
// on that one line is tolerated while every other byte stays protected.
func recordedDigest(canonical []byte) (string, error) {
	lines := splitLines(canonical)
	found := digestLineIndexes(lines)
	if len(found) != 1 {
		return "", fmt.Errorf("expected exactly one %q line, found %d", strings.TrimSuffix(digestPrefix, "="), len(found))
	}
	return strings.TrimSpace(strings.TrimPrefix(lines[found[0]], digestPrefix)), nil
}

// stampDigest replaces the digest line's value with the digest of the rest of
// the file. It is the last step before the bytes are written.
func stampDigest(rendered []byte) ([]byte, error) {
	canonical := canonicalize(rendered)
	sum, err := computeDigest(canonical)
	if err != nil {
		return nil, err
	}
	lines := splitLines(canonical)
	found := digestLineIndexes(lines)
	lines[found[0]] = digestPrefix + sum
	return []byte(strings.Join(lines, "\n")), nil
}

// manifestNames returns the base names the anchor's header records as the rest
// of its export set. A file without the line names no siblings, which is how a
// single-file baseline reads. Every entry is validated, because the names it
// carries decide which files a later run reads back and may delete.
func manifestNames(canonical []byte) ([]string, error) {
	var names []string
	seen := false
	for _, line := range splitLines(canonical) {
		if !strings.HasPrefix(line, manifestPrefix) {
			continue
		}
		if seen {
			return nil, fmt.Errorf("%w: more than one %s line",
				ErrModified, strings.TrimSuffix(manifestPrefix, "="))
		}
		seen = true
		raw := strings.TrimSpace(strings.TrimPrefix(line, manifestPrefix))
		if raw == "" {
			return nil, fmt.Errorf("%w: empty %s line", ErrModified, strings.TrimSuffix(manifestPrefix, "="))
		}
		for entry := range strings.SplitSeq(raw, ",") {
			name := strings.TrimSpace(entry)
			if !manifestNamePattern.MatchString(name) {
				return nil, fmt.Errorf("%w: %s names %q, which is not a plain .proto file name",
					ErrModified, strings.TrimSuffix(manifestPrefix, "="), name)
			}
			if slices.Contains(names, name) {
				return nil, fmt.Errorf("%w: %s names %q twice",
					ErrModified, strings.TrimSuffix(manifestPrefix, "="), name)
			}
			names = append(names, name)
		}
	}
	return names, nil
}

// ManifestNames reports the other files a previously generated anchor says its
// export set contains. The caller reads those files and hands them back through
// Options.PreviousSiblings; every one of them, and the anchor itself, is
// validated in full by Render. It deliberately does not authenticate the anchor
// first: a file that is not a Ptah export simply records no siblings and is
// refused by Render's own gate, which carries the specific remedy.
func ManifestNames(raw []byte) ([]string, error) {
	return manifestNames(canonicalize(raw))
}

// parsedHeader is what the generated header tells us about a previous export.
type parsedHeader struct {
	Version int
}

// parseHeader validates the marker and version lines of canonical bytes.
func parseHeader(canonical []byte) (parsedHeader, error) {
	lines := splitLines(canonical)
	if len(lines) == 0 || lines[0] != generatedMarker {
		return parsedHeader{}, fmt.Errorf("%w; %s", ErrForeignFile, remedyForeign)
	}

	for _, line := range lines {
		if !strings.HasPrefix(line, versionPrefix) {
			continue
		}
		raw := strings.TrimSpace(strings.TrimPrefix(line, versionPrefix))
		version, err := strconv.Atoi(raw)
		if err != nil {
			return parsedHeader{}, fmt.Errorf("%w: unreadable export version %q", ErrUnsupportedVersion, raw)
		}
		if version > exportVersion {
			return parsedHeader{}, fmt.Errorf("%w: file declares export version %d, this Ptah supports %d",
				ErrUnsupportedVersion, version, exportVersion)
		}
		return parsedHeader{Version: version}, nil
	}
	return parsedHeader{}, fmt.Errorf("%w: no %s line", ErrUnsupportedVersion, strings.TrimSuffix(versionPrefix, "="))
}
