package protobufrender

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/bufbuild/protocompile"
	"github.com/bufbuild/protocompile/linker"
	"github.com/bufbuild/protocompile/reporter"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Sentinel errors for the previous-output validation gate. Every one of them
// aborts the export before anything is written, so a rejected baseline is
// always left byte-identical.
// They are exported because each carries a different remedy, so a caller can
// tell them apart with errors.Is rather than by matching message text.
var (
	// ErrForeignFile reports that the output was not generated by Ptah.
	ErrForeignFile = errors.New("output file was not generated by ptah")
	// ErrUnsupportedVersion reports an export format version this Ptah cannot rewrite.
	ErrUnsupportedVersion = errors.New("unsupported ptah protobuf export version")
	// ErrModified reports that the output changed since Ptah generated it.
	ErrModified = errors.New("output file was modified since it was generated")
	// ErrMalformed reports that the output does not parse or link as protobuf.
	ErrMalformed = errors.New("output file is not valid protobuf")
	// ErrPackageMismatch reports that the output pins a different protobuf package.
	ErrPackageMismatch = errors.New("output file declares a different protobuf package")
)

const (
	remedyForeign  = "delete it to start a new compatibility history, or point --out somewhere else"
	remedyModified = "restore it from version control, or delete it to start a new compatibility history"
	remedyPackage  = "a package change starts a new compatibility history: point --out at the new package's directory, or delete the file"
)

// previousField is a field's translated Protobuf shape as the previous export
// spelled it, used to detect a wire-incompatible change.
type previousField struct {
	Type     string
	Repeated bool
}

// previousType is the compatibility state extracted from one message or enum in
// the previous generated file.
type previousType struct {
	// Numbers maps a field or enum value name to the number it holds.
	Numbers map[string]int32
	// Fields carries the previous type spelling per field name. It is empty for
	// enums, whose values have no type.
	Fields map[string]previousField
	// Reserved is every number and name the type has already retired.
	Reserved reservations
}

// used returns every number the type has ever held, live or reserved, which is
// what new allocations must exceed.
func (p previousType) used() []int32 {
	out := make([]int32, 0, len(p.Numbers)+len(p.Reserved.Numbers))
	for _, n := range p.Numbers {
		out = append(out, n)
	}
	out = append(out, p.Reserved.Numbers...)
	return out
}

// previousFile is the whole compatibility state of a previous export.
type previousFile struct {
	Package  string
	Messages map[string]previousType
	Enums    map[string]previousType
}

// loadPrevious validates raw as a Ptah-generated .proto and extracts the field
// and enum-value numbering it pins. Validation runs in a fixed order so the
// user always gets the most specific diagnosis: a foreign file is never
// reported as malformed, and a modified file is never reported as a package
// mismatch.
func loadPrevious(ctx context.Context, path string, raw []byte, wantPackage string) (*previousFile, error) {
	canonical := canonicalize(raw)

	if _, err := parseHeader(canonical); err != nil {
		return nil, err
	}

	recorded, err := recordedDigest(canonical)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrModified, err)
	}
	actual, err := computeDigest(canonical)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrModified, err)
	}
	if recorded != actual {
		return nil, fmt.Errorf("%w: recorded %s, computed %s; %s",
			ErrModified, shortDigest(recorded), shortDigest(actual), remedyModified)
	}

	fd, err := compileProto(ctx, path, string(canonical))
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrMalformed, err)
	}

	if got := string(fd.Package()); got != wantPackage {
		return nil, fmt.Errorf("%w: file declares %q, --proto-package is %q; %s",
			ErrPackageMismatch, got, wantPackage, remedyPackage)
	}

	prev := &previousFile{
		Package:  string(fd.Package()),
		Messages: map[string]previousType{},
		Enums:    map[string]previousType{},
	}
	for i := range fd.Messages().Len() {
		md := fd.Messages().Get(i)
		prev.Messages[string(md.Name())] = messageState(md, fd.Package())
	}
	for i := range fd.Enums().Len() {
		ed := fd.Enums().Get(i)
		prev.Enums[string(ed.Name())] = enumState(ed)
	}
	return prev, nil
}

func shortDigest(s string) string {
	if len(s) <= 12 {
		return s
	}
	return s[:12] + "..."
}

// messageState reads a message's live numbers, field shapes and reservations.
// Message reserved ranges carry an EXCLUSIVE end, unlike enum ranges.
func messageState(md protoreflect.MessageDescriptor, pkg protoreflect.FullName) previousType {
	state := previousType{
		Numbers: map[string]int32{},
		Fields:  map[string]previousField{},
	}
	for i := range md.Fields().Len() {
		fd := md.Fields().Get(i)
		state.Numbers[string(fd.Name())] = int32(fd.Number())
		state.Fields[string(fd.Name())] = previousField{
			Type:     fieldTypeString(fd, pkg),
			Repeated: fd.IsList(),
		}
	}
	ranges := md.ReservedRanges()
	for i := range ranges.Len() {
		r := ranges.Get(i)
		// End is EXCLUSIVE for message ranges.
		addRange(&state.Reserved, int64(r[0]), int64(r[1])-1)
	}
	names := md.ReservedNames()
	for i := range names.Len() {
		state.Reserved.addName(string(names.Get(i)))
	}
	return state
}

// enumState reads an enum's live numbers and reservations. Enum reserved ranges
// carry an INCLUSIVE end, unlike message ranges - a real asymmetry in
// protoreflect that silently drops the last reserved number if ignored.
func enumState(ed protoreflect.EnumDescriptor) previousType {
	state := previousType{Numbers: map[string]int32{}}
	for i := range ed.Values().Len() {
		vd := ed.Values().Get(i)
		state.Numbers[string(vd.Name())] = int32(vd.Number())
	}
	ranges := ed.ReservedRanges()
	for i := range ranges.Len() {
		r := ranges.Get(i)
		// End is INCLUSIVE for enum ranges.
		addRange(&state.Reserved, int64(r[0]), int64(r[1]))
	}
	names := ed.ReservedNames()
	for i := range names.Len() {
		state.Reserved.addName(string(names.Get(i)))
	}
	return state
}

// addRange records every number in [start, end] (inclusive) as reserved,
// iterating in int64 so an end of MaxInt32 cannot overflow the counter and
// stopping at maxReservedNumbers so a pathological range cannot exhaust memory.
func addRange(res *reservations, start, end int64) {
	for n := start; n <= end && res.count() < maxReservedNumbers; n++ {
		if n < 0 || n > maxFieldNumber {
			continue
		}
		res.addNumber(int32(n))
	}
}

// fieldTypeString spells a field's type exactly as the generator writes it, so
// the two can be compared to detect a wire-incompatible change. Types in the
// file's own package are written bare; everything else keeps its full name.
func fieldTypeString(fd protoreflect.FieldDescriptor, pkg protoreflect.FullName) string {
	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return relativeName(fd.Message().FullName(), pkg)
	case protoreflect.EnumKind:
		return relativeName(fd.Enum().FullName(), pkg)
	default:
		return fd.Kind().String()
	}
}

func relativeName(full, pkg protoreflect.FullName) string {
	prefix := string(pkg) + "."
	if pkg != "" && strings.HasPrefix(string(full), prefix) {
		return strings.TrimPrefix(string(full), prefix)
	}
	return string(full)
}

// compileProto parses and links src with protocompile. It is used both to read
// a previous export and to validate freshly rendered bytes before they are
// written, which catches generator bugs at generation time rather than in the
// caller's build.
func compileProto(ctx context.Context, path, src string) (protoreflect.FileDescriptor, error) {
	var problems []string
	rep := reporter.NewReporter(
		func(err reporter.ErrorWithPos) error {
			problems = append(problems, err.Error())
			return nil // keep going so every error is reported at once
		},
		nil,
	)
	compiler := protocompile.Compiler{
		Resolver: protocompile.WithStandardImports(&protocompile.SourceResolver{
			Accessor: protocompile.SourceAccessorFromMap(map[string]string{path: src}),
		}),
		SourceInfoMode: protocompile.SourceInfoStandard,
		Reporter:       rep,
	}
	files, err := compiler.Compile(ctx, path)
	if err != nil {
		if len(problems) > 0 {
			return nil, errors.New(strings.Join(problems, "; "))
		}
		return nil, err
	}
	if len(files) == 0 {
		return nil, errors.New("no file descriptor produced")
	}
	return linker.Files(files)[0], nil
}
