package protobufrender_test

import (
	"context"
	"errors"
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"

	"github.com/stokaro/ptah/internal/protobufrender"
)

// pristine is a valid previous export for the single-column "things" table,
// produced by the exporter itself rather than hand-written.
func pristine(c *qt.C) []byte {
	c.Helper()
	return mustRender(c, oneTable(column("id", "BIGINT")), baseOptions()).Data
}

// rejectionCase is one previous-output rejection: how the baseline is damaged
// and the diagnosis the caller must get back.
type rejectionCase struct {
	name         string
	damage       func(c *qt.C, good []byte) []byte
	wantMsg      string
	wantSentinel error
}

func rejectionCases() []rejectionCase {
	return []rejectionCase{{
		name: "foreign",
		damage: func(_ *qt.C, good []byte) []byte {
			// A hand-written .proto that Ptah never generated: no marker line.
			return []byte(strings.TrimPrefix(string(good), headerMarker+"\n"))
		},
		wantMsg:      "output file was not generated by ptah",
		wantSentinel: protobufrender.ErrForeignFile,
	}, {
		name: "unsupported version",
		damage: func(_ *qt.C, good []byte) []byte {
			return stampProto(strings.Replace(string(good),
				"// ptah:protobuf-export-version=1", "// ptah:protobuf-export-version=2", 1))
		},
		wantMsg:      "unsupported ptah protobuf export version: file declares export version 2, this Ptah supports 1",
		wantSentinel: protobufrender.ErrUnsupportedVersion,
	}, {
		name: "unreadable version",
		damage: func(_ *qt.C, good []byte) []byte {
			return stampProto(strings.Replace(string(good),
				"// ptah:protobuf-export-version=1", "// ptah:protobuf-export-version=next", 1))
		},
		wantMsg:      `unsupported ptah protobuf export version: unreadable export version "next"`,
		wantSentinel: protobufrender.ErrUnsupportedVersion,
	}, {
		name: "modified",
		damage: func(_ *qt.C, good []byte) []byte {
			// Edited by hand and the digest left untouched.
			return []byte(strings.Replace(string(good), "int64 id = 1;", "int64 id = 2;", 1))
		},
		wantMsg:      "output file was modified since it was generated",
		wantSentinel: protobufrender.ErrModified,
	}, {
		name: "malformed",
		damage: func(_ *qt.C, good []byte) []byte {
			// Re-stamped, so the integrity gate passes and the parser is what
			// must reject it.
			return stampProto(strings.Replace(string(good), "message Thing {", "message Thing {{", 1))
		},
		wantMsg:      "output file is not valid protobuf",
		wantSentinel: protobufrender.ErrMalformed,
	}, {
		name: "oversized reserved state",
		damage: func(_ *qt.C, _ []byte) []byte {
			return previousExport(
				"enum Huge {\n  HUGE_UNSPECIFIED = 0;\n  reserved 1 to 1048577;\n}\n")
		},
		wantMsg: "output file is not valid protobuf: enum \"Huge\": reserved ranges expand to more than 1048576 numbers; " +
			"refusing to truncate compatibility state",
		wantSentinel: protobufrender.ErrMalformed,
	}, {
		name: "unsupported negative reserved state",
		damage: func(_ *qt.C, _ []byte) []byte {
			return previousExport(
				"enum Negative {\n  NEGATIVE_UNSPECIFIED = 0;\n  reserved -1;\n}\n")
		},
		wantMsg: "output file is not valid protobuf: enum \"Negative\": " +
			"reserved range -1 to -1 is outside Ptah's supported numbering space",
		wantSentinel: protobufrender.ErrMalformed,
	}, {
		name: "package mismatch",
		damage: func(_ *qt.C, good []byte) []byte {
			return stampProto(strings.Replace(string(good),
				"package "+testPackage+";", "package acme.catalog.v1;", 1))
		},
		wantMsg: `output file declares a different protobuf package: file declares "acme.catalog.v1", ` +
			`--proto-package is "` + testPackage + `"`,
		wantSentinel: protobufrender.ErrPackageMismatch,
	}, {
		name: "no digest line",
		damage: func(c *qt.C, good []byte) []byte {
			lines := strings.Split(string(good), "\n")
			kept := make([]string, 0, len(lines))
			for _, line := range lines {
				kept = appendUnlessDigest(kept, line)
			}
			c.Assert(kept, qt.HasLen, len(lines)-1)
			return []byte(strings.Join(kept, "\n"))
		},
		wantMsg: "output file was modified since it was generated: " +
			`expected exactly one "// ptah:content-sha256" line, found 0`,
		wantSentinel: protobufrender.ErrModified,
	}, {
		name: "duplicate digest lines",
		damage: func(_ *qt.C, good []byte) []byte {
			line := digestLineOf(string(good))
			return []byte(strings.Replace(string(good), line+"\n", line+"\n"+line+"\n", 1))
		},
		wantMsg: "output file was modified since it was generated: " +
			`expected exactly one "// ptah:content-sha256" line, found 2`,
		wantSentinel: protobufrender.ErrModified,
	}}
}

func appendUnlessDigest(kept []string, line string) []string {
	if strings.HasPrefix(line, digestPrefix) {
		return kept
	}
	return append(kept, line)
}

func digestLineOf(text string) string {
	for line := range strings.SplitSeq(text, "\n") {
		if strings.HasPrefix(line, digestPrefix) {
			return line
		}
	}
	return ""
}

func TestPreviousRejectionsAreDiagnosedSpecifically(t *testing.T) {
	for _, rc := range rejectionCases() {
		t.Run(rc.name, func(t *testing.T) {
			c := qt.New(t)
			damaged := rc.damage(c, pristine(c))
			message := mustFail(c, oneTable(column("id", "BIGINT")), withPrevious(damaged))
			c.Assert(message, qt.Contains, rc.wantMsg)
		})
	}
}

func TestPreviousRejectionsAreDistinguishable(t *testing.T) {
	// The five documented refusals have five different remedies, so a caller
	// must be able to tell them apart with errors.Is rather than by matching
	// message text.
	sentinels := []error{
		protobufrender.ErrForeignFile,
		protobufrender.ErrUnsupportedVersion,
		protobufrender.ErrModified,
		protobufrender.ErrMalformed,
		protobufrender.ErrPackageMismatch,
	}

	for _, rc := range rejectionCases() {
		t.Run(rc.name, func(t *testing.T) {
			c := qt.New(t)
			damaged := rc.damage(c, pristine(c))
			_, err := protobufrender.Render(context.Background(), oneTable(column("id", "BIGINT")), withPrevious(damaged))
			c.Assert(err, qt.IsNotNil)
			c.Assert(err, qt.ErrorIs, rc.wantSentinel)
			c.Assert(matchingSentinels(err, sentinels), qt.HasLen, 1)
		})
	}
}

// matchingSentinels reports which sentinels an error matches, so a test can
// assert that a refusal is unambiguous.
func matchingSentinels(err error, sentinels []error) []error {
	var matched []error
	for _, sentinel := range sentinels {
		if errors.Is(err, sentinel) {
			matched = append(matched, sentinel)
		}
	}
	return matched
}

func TestPreviousValidationRunsMostSpecificFirst(t *testing.T) {
	c := qt.New(t)

	// A file that is simultaneously foreign, unparseable and in the wrong
	// package must be reported as foreign: the remedy for a foreign file is
	// deleting it, and the other diagnoses would send the user elsewhere.
	_, err := protobufrender.Render(context.Background(), oneTable(column("id", "BIGINT")),
		withPrevious([]byte("package acme.catalog.v1;\nmessage {{{\n")))
	c.Assert(err, qt.ErrorIs, protobufrender.ErrForeignFile)
	c.Assert(err, qt.Not(qt.ErrorIs), protobufrender.ErrMalformed)
	c.Assert(err, qt.Not(qt.ErrorIs), protobufrender.ErrPackageMismatch)

	// A modified file must never be reported as a package mismatch.
	broken := strings.Replace(string(pristine(c)), "package "+testPackage+";", "package acme.catalog.v1;", 1)
	_, err = protobufrender.Render(context.Background(), oneTable(column("id", "BIGINT")), withPrevious([]byte(broken)))
	c.Assert(err, qt.ErrorIs, protobufrender.ErrModified)
	c.Assert(err, qt.Not(qt.ErrorIs), protobufrender.ErrPackageMismatch)
}

func TestPreviousAcceptsCanonicalizationVariants(t *testing.T) {
	c := qt.New(t)

	db := oneTable(column("id", "BIGINT"))
	good := pristine(c)

	variants := map[string][]byte{
		"crlf":      []byte(strings.ReplaceAll(string(good), "\n", "\r\n")),
		"lone cr":   []byte(strings.ReplaceAll(string(good), "\n", "\r")),
		"utf-8 bom": append([]byte{0xef, 0xbb, 0xbf}, good...),
		"bom and crlf": append([]byte{0xef, 0xbb, 0xbf},
			[]byte(strings.ReplaceAll(string(good), "\n", "\r\n"))...),
		// Trailing whitespace on the digest line alone is tolerated: the
		// recorded value is the line remainder with surrounding space trimmed.
		"trailing space on the digest line": []byte(strings.Replace(string(good),
			digestLineOf(string(good)), digestLineOf(string(good))+"  \t", 1)),
	}

	for name, variant := range variants {
		c.Run(name, func(c *qt.C) {
			// A canonicalization failure would surface as "not generated by
			// ptah", whose prescribed remedy is deleting the baseline, so this
			// must succeed rather than merely produce a different error.
			res := mustRender(c, db, withPrevious(variant))
			c.Assert(res.Bootstrapped, qt.IsFalse)
			c.Assert(string(res.Data), qt.Equals, string(good))
		})
	}
}

func TestPreviousRejectsWhitespaceOutsideTheDigestLine(t *testing.T) {
	c := qt.New(t)

	// Only the digest line tolerates trailing whitespace; every other byte is
	// covered by the digest.
	damaged := strings.Replace(string(pristine(c)), "edition = \"2023\";", "edition = \"2023\";  ", 1)
	message := mustFail(c, oneTable(column("id", "BIGINT")), withPrevious([]byte(damaged)))
	c.Assert(message, qt.Contains, "output file was modified since it was generated")
}

func TestPreviousDigestDoesNotCoverItsOwnValue(t *testing.T) {
	c := qt.New(t)

	// Corrupting the digest value must produce a clean mismatch rather than an
	// incoherent one: the line is matched by prefix, not by value shape, so it
	// is still stripped before hashing.
	damaged := strings.Replace(string(pristine(c)), digestLineOf(string(pristine(c))), digestPrefix+"garbage", 1)
	message := mustFail(c, oneTable(column("id", "BIGINT")), withPrevious([]byte(damaged)))
	c.Assert(message, qt.Contains, "output file was modified since it was generated: recorded garbage, computed ")
}
