package protobufrender

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/bufbuild/protocompile"
	"github.com/bufbuild/protocompile/linker"
	"github.com/bufbuild/protocompile/reporter"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Sentinel errors for the previous-output validation gate. Every one of them
// aborts the export before anything is written, so a rejected baseline is
// always left byte-identical.
// They are exported because each carries a different remedy, so a caller can
// tell them apart with errors.Is rather than by matching message text.
var (
	// ErrForeignFile reports that the output was not generated by Ptah.
	ErrForeignFile = errors.New("output file was not generated by ptah")
	// ErrUnsupportedVersion reports an export format version this Ptah cannot rewrite.
	ErrUnsupportedVersion = errors.New("unsupported ptah protobuf export version")
	// ErrModified reports that the output changed since Ptah generated it.
	ErrModified = errors.New("output file was modified since it was generated")
	// ErrMalformed reports that the output does not parse or link as protobuf.
	ErrMalformed = errors.New("output file is not valid protobuf")
	// ErrPackageMismatch reports that the output pins a different protobuf package.
	ErrPackageMismatch = errors.New("output file declares a different protobuf package")
)

const (
	remedyForeign  = "delete it to start a new compatibility history, or point --out somewhere else"
	remedyModified = "restore it from version control, or delete it to start a new compatibility history"
	remedyPackage  = "a package change starts a new compatibility history: point --out at the new package's directory, or delete the file"
)

// previousField is a field's translated Protobuf shape as the previous export
// spelled it, used to detect a wire-incompatible change.
type previousField struct {
	Type     string
	Repeated bool
}

// previousType is the compatibility state extracted from one message or enum in
// the previous generated file.
type previousType struct {
	// Numbers maps a field or enum value name to the number it holds.
	Numbers map[string]int32
	// Fields carries the previous type spelling per field name. It is empty for
	// enums, whose values have no type.
	Fields map[string]previousField
	// Reserved is every number and name the type has already retired.
	Reserved reservations
}

// used returns every number the type has ever held, live or reserved, which is
// what new allocations must exceed.
func (p previousType) used() []int32 {
	out := make([]int32, 0, len(p.Numbers)+len(p.Reserved.Numbers))
	for _, n := range p.Numbers {
		out = append(out, n)
	}
	out = append(out, p.Reserved.Numbers...)
	return out
}

// previousSet is the whole compatibility state of a previous export, flattened
// across every file it wrote. Type names are unique across the set because all
// of its files share one protobuf package, so the numbering lookups stay
// file-agnostic and only the *File indexes know where a type lived.
type previousSet struct {
	Package  string
	Messages map[string]previousType
	Enums    map[string]previousType
	// MessageFile and EnumFile map a type name to the base name of the file that
	// declared it, which is what turns a rename-shaped diff into a detected move.
	MessageFile map[string]string
	EnumFile    map[string]string
	// Files is every base name the previous export wrote, anchor first.
	Files []string
}

// validatePreviousBytes runs the header and digest gates over one file of a
// previous export and returns its canonical bytes. It is deliberately separate
// from the compile step: every file's authenticity is settled before any of
// them is parsed, so a tampered sibling is never diagnosed as a compile error
// in the anchor.
func validatePreviousBytes(raw []byte) ([]byte, error) {
	canonical := canonicalize(raw)

	if _, err := parseHeader(canonical); err != nil {
		return nil, err
	}

	recorded, err := recordedDigest(canonical)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrModified, err)
	}
	actual, err := computeDigest(canonical)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrModified, err)
	}
	if recorded != actual {
		return nil, fmt.Errorf("%w: recorded %s, computed %s; %s",
			ErrModified, shortDigest(recorded), shortDigest(actual), remedyModified)
	}
	return canonical, nil
}

// loadPrevious validates a previous export set and extracts the field and
// enum-value numbering it pins. Validation runs in a fixed order so the user
// always gets the most specific diagnosis: a foreign file is never reported as
// malformed, and a modified file is never reported as a package mismatch.
//
// Only the anchor's own diagnostics are unprefixed. A sibling is named, because
// --out does not point at it and the message would otherwise be unactionable.
func loadPrevious(ctx context.Context, pkgDir, anchor string, raw []byte, siblings map[string][]byte, wantPackage string) (*previousSet, error) {
	order := append([]string{anchor}, sortedKeys(siblings)...)

	sources := map[string]string{}
	pathOf := map[string]string{}
	own := map[string]bool{}
	for _, name := range order {
		data := raw
		if name != anchor {
			data = siblings[name]
		}
		canonical, err := validatePreviousBytes(data)
		if err != nil {
			if name == anchor {
				return nil, err
			}
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		path := logicalPath(pkgDir, name)
		sources[path] = string(canonical)
		pathOf[name] = path
		own[path] = true
	}

	files, err := compileProtoSet(ctx, sources, order, pathOf)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrMalformed, err)
	}

	prev := &previousSet{
		Package:     wantPackage,
		Messages:    map[string]previousType{},
		Enums:       map[string]previousType{},
		MessageFile: map[string]string{},
		EnumFile:    map[string]string{},
		Files:       order,
	}
	for _, name := range order {
		fd := files[name]
		if got := string(fd.Package()); got != wantPackage {
			if name == anchor {
				return nil, fmt.Errorf("%w: file declares %q, --proto-package is %q; %s",
					ErrPackageMismatch, got, wantPackage, remedyPackage)
			}
			return nil, fmt.Errorf("%s: %w: file declares %q, --proto-package is %q; %s",
				name, ErrPackageMismatch, got, wantPackage, remedyPackage)
		}
		if err := prev.collect(name, fd, own); err != nil {
			return nil, err
		}
	}
	return prev, nil
}

// collect records one file's numbering state under its base name. own is the
// logical path of every file of the export set, which is what decides whether a
// referenced type is written bare or fully qualified.
func (p *previousSet) collect(name string, fd protoreflect.FileDescriptor, own map[string]bool) error {
	for i := range fd.Messages().Len() {
		md := fd.Messages().Get(i)
		state, err := messageState(md, fd, own)
		if err != nil {
			return fmt.Errorf("%w: %w", ErrMalformed, err)
		}
		p.Messages[string(md.Name())] = state
		p.MessageFile[string(md.Name())] = name
	}
	for i := range fd.Enums().Len() {
		ed := fd.Enums().Get(i)
		state, err := enumState(ed)
		if err != nil {
			return fmt.Errorf("%w: %w", ErrMalformed, err)
		}
		p.Enums[string(ed.Name())] = state
		p.EnumFile[string(ed.Name())] = name
	}
	return nil
}

func sortedKeys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for key := range m {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}

func shortDigest(s string) string {
	if len(s) <= 12 {
		return s
	}
	return s[:12] + "..."
}

// messageState reads a message's live numbers, field shapes and reservations.
// Message reserved ranges carry an EXCLUSIVE end, unlike enum ranges.
func messageState(md protoreflect.MessageDescriptor, file protoreflect.FileDescriptor, own map[string]bool) (previousType, error) {
	state := previousType{
		Numbers: map[string]int32{},
		Fields:  map[string]previousField{},
	}
	for i := range md.Fields().Len() {
		fd := md.Fields().Get(i)
		state.Numbers[string(fd.Name())] = int32(fd.Number())
		state.Fields[string(fd.Name())] = previousField{
			Type:     fieldTypeString(fd, file, own),
			Repeated: fd.IsList(),
		}
	}
	ranges := md.ReservedRanges()
	for i := range ranges.Len() {
		r := ranges.Get(i)
		// End is EXCLUSIVE for message ranges.
		if err := addRange(&state.Reserved, int64(r[0]), int64(r[1])-1); err != nil {
			return previousType{}, fmt.Errorf("message %q: %w", md.Name(), err)
		}
	}
	names := md.ReservedNames()
	for i := range names.Len() {
		state.Reserved.addName(string(names.Get(i)))
	}
	return state, nil
}

// enumState reads an enum's live numbers and reservations. Enum reserved ranges
// carry an INCLUSIVE end, unlike message ranges - a real asymmetry in
// protoreflect that silently drops the last reserved number if ignored.
func enumState(ed protoreflect.EnumDescriptor) (previousType, error) {
	state := previousType{Numbers: map[string]int32{}}
	for i := range ed.Values().Len() {
		vd := ed.Values().Get(i)
		state.Numbers[string(vd.Name())] = int32(vd.Number())
	}
	ranges := ed.ReservedRanges()
	for i := range ranges.Len() {
		r := ranges.Get(i)
		// End is INCLUSIVE for enum ranges.
		if err := addRange(&state.Reserved, int64(r[0]), int64(r[1])); err != nil {
			return previousType{}, fmt.Errorf("enum %q: %w", ed.Name(), err)
		}
	}
	names := ed.ReservedNames()
	for i := range names.Len() {
		state.Reserved.addName(string(names.Get(i)))
	}
	return state, nil
}

// addRange records every number in [start, end] (inclusive) as reserved,
// iterating in int64 so an end of MaxInt32 cannot overflow the counter. It
// refuses unsupported or oversized state instead of truncating it: truncation
// could make a later allocation reuse a number that remains reserved on the
// wire.
func addRange(res *reservations, start, end int64) error {
	if start < 0 || end > maxFieldNumber {
		return fmt.Errorf("reserved range %d to %d is outside Ptah's supported numbering space", start, end)
	}
	size := end - start + 1
	remaining := int64(maxReservedNumbers - res.count())
	if size > remaining {
		return fmt.Errorf(
			"reserved ranges expand to more than %d numbers; refusing to truncate compatibility state",
			maxReservedNumbers)
	}
	// protocompile has already rejected overlapping ranges. Append directly so
	// loading a large valid range stays O(n); addNumber's duplicate scan would
	// make this loop quadratic.
	for n := start; n <= end; n++ {
		// The bounds check above proves n fits the generator's int32 range.
		number := int32(n) //nolint:gosec // Conversion is guarded by the supported-numbering-space check.
		res.Numbers = append(res.Numbers, number)
	}
	return nil
}

// fieldTypeString spells a field's type exactly as the generator writes it, so
// the two can be compared to detect a wire-incompatible change. Types the export
// set itself defines are written bare, because they resolve through the package
// scope every file of the set shares; anything else keeps its full name.
//
// The test is the DEFINING FILE, not the package prefix. Trimming by package
// would also shorten "google.protobuf.Timestamp" when --proto-package is
// "google.protobuf", so the previous spelling would never match what the
// renderer writes and every run would report a spurious type change. The test
// is the whole SET rather than the one file, because an enum that a table file
// references lives in the anchor: comparing it against its fully qualified
// spelling would report a spurious type change on every regeneration.
func fieldTypeString(fd protoreflect.FieldDescriptor, file protoreflect.FileDescriptor, own map[string]bool) string {
	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return localName(fd.Message().FullName(), fd.Message().ParentFile(), file, own)
	case protoreflect.EnumKind:
		return localName(fd.Enum().FullName(), fd.Enum().ParentFile(), file, own)
	default:
		return fd.Kind().String()
	}
}

func localName(full protoreflect.FullName, definedIn, file protoreflect.FileDescriptor, own map[string]bool) string {
	if definedIn == nil || file == nil {
		return string(full)
	}
	if definedIn.Path() != file.Path() && !own[definedIn.Path()] {
		return string(full)
	}
	return strings.TrimPrefix(string(full), string(file.Package())+".")
}

// compileProtoSet parses and links every file of an export set together with
// protocompile. It is used both to read a previous export and to validate
// freshly rendered bytes before they are written, which catches generator bugs
// at generation time rather than in the caller's build. The whole set is
// compiled in one pass because the files import each other: compiling them
// one at a time would resolve a cross-file enum reference against nothing.
//
// The result is keyed by base name, so callers never have to rebuild a logical
// path to find the descriptor they asked for.
func compileProtoSet(ctx context.Context, sources map[string]string, names []string, pathOf map[string]string) (map[string]protoreflect.FileDescriptor, error) {
	var problems []string
	rep := reporter.NewReporter(
		func(err reporter.ErrorWithPos) error {
			problems = append(problems, err.Error())
			return nil // keep going so every error is reported at once
		},
		nil,
	)
	paths := make([]string, 0, len(names))
	for _, name := range names {
		paths = append(paths, pathOf[name])
	}
	compiler := protocompile.Compiler{
		Resolver: protocompile.WithStandardImports(&protocompile.SourceResolver{
			Accessor: protocompile.SourceAccessorFromMap(sources),
		}),
		SourceInfoMode: protocompile.SourceInfoStandard,
		Reporter:       rep,
	}
	files, err := compiler.Compile(ctx, paths...)
	if err != nil {
		if len(problems) > 0 {
			return nil, errors.New(strings.Join(problems, "; "))
		}
		return nil, err
	}
	if len(files) != len(paths) {
		return nil, fmt.Errorf("compiled %d file descriptor(s) for %d source file(s)", len(files), len(paths))
	}
	linked := linker.Files(files)
	out := make(map[string]protoreflect.FileDescriptor, len(names))
	for i, name := range names {
		out[name] = linked[i]
	}
	return out, nil
}
