package protobufrender

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/bufbuild/protocompile"
	"github.com/bufbuild/protocompile/linker"
	"github.com/bufbuild/protocompile/reporter"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Sentinel errors for the previous-output validation gate. Every one of them
// aborts the export before anything is written, so a rejected baseline is
// always left byte-identical.
// They are exported because each carries a different remedy, so a caller can
// tell them apart with errors.Is rather than by matching message text.
var (
	// ErrForeignFile reports that the output was not generated by Ptah.
	ErrForeignFile = errors.New("output file was not generated by ptah")
	// ErrUnsupportedVersion reports an export format version this Ptah cannot rewrite.
	ErrUnsupportedVersion = errors.New("unsupported ptah protobuf export version")
	// ErrModified reports that the output changed since Ptah generated it.
	ErrModified = errors.New("output file was modified since it was generated")
	// ErrMalformed reports that the output does not parse or link as protobuf.
	ErrMalformed = errors.New("output file is not valid protobuf")
	// ErrPackageMismatch reports that the output pins a different protobuf package.
	ErrPackageMismatch = errors.New("output file declares a different protobuf package")
)

const (
	remedyForeign  = "delete it to start a new compatibility history, or point --out somewhere else"
	remedyModified = "restore it from version control, or delete it to start a new compatibility history"
	remedyPackage  = "a package change starts a new compatibility history: point --out at the new package's directory, or delete the file"
)

// previousField is a field's translated Protobuf shape as the previous export
// spelled it, used to detect a wire-incompatible change.
type previousField struct {
	Type     string
	Repeated bool
}

// previousType is the compatibility state extracted from one message or enum in
// the previous generated file.
type previousType struct {
	// Numbers maps a field or enum value name to the number it holds.
	Numbers map[string]int32
	// Fields carries the previous type spelling per field name. It is empty for
	// enums, whose values have no type.
	Fields map[string]previousField
	// Reserved is every number and name the type has already retired.
	Reserved reservations
}

// highestUsed returns the largest number the type has ever held, live or
// reserved, which is what new allocations must exceed. It is a single number
// rather than the list of every number ever used because a reserved range may
// legally cover the whole field-number space.
func (p previousType) highestUsed() int32 {
	highest := p.Reserved.highest()
	for _, n := range p.Numbers {
		highest = max(highest, n)
	}
	return highest
}

// previousFile is the whole compatibility state of a previous export.
type previousFile struct {
	Package  string
	Messages map[string]previousType
	Enums    map[string]previousType
}

// loadPrevious validates raw as a Ptah-generated .proto and extracts the field
// and enum-value numbering it pins. Validation runs in a fixed order so the
// user always gets the most specific diagnosis: a foreign file is never
// reported as malformed, and a modified file is never reported as a package
// mismatch.
func loadPrevious(ctx context.Context, path string, raw []byte, wantPackage string) (*previousFile, error) {
	canonical := canonicalize(raw)

	if _, err := parseHeader(canonical); err != nil {
		return nil, err
	}

	recorded, err := recordedDigest(canonical)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrModified, err)
	}
	actual, err := computeDigest(canonical)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrModified, err)
	}
	if recorded != actual {
		return nil, fmt.Errorf("%w: recorded %s, computed %s; %s",
			ErrModified, shortDigest(recorded), shortDigest(actual), remedyModified)
	}

	fd, err := compileProto(ctx, path, string(canonical))
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrMalformed, err)
	}

	if got := string(fd.Package()); got != wantPackage {
		return nil, fmt.Errorf("%w: file declares %q, --proto-package is %q; %s",
			ErrPackageMismatch, got, wantPackage, remedyPackage)
	}

	prev := &previousFile{
		Package:  string(fd.Package()),
		Messages: map[string]previousType{},
		Enums:    map[string]previousType{},
	}
	for i := range fd.Messages().Len() {
		md := fd.Messages().Get(i)
		state, err := messageState(md, fd)
		if err != nil {
			return nil, fmt.Errorf("%w: %w", ErrMalformed, err)
		}
		prev.Messages[string(md.Name())] = state
	}
	for i := range fd.Enums().Len() {
		ed := fd.Enums().Get(i)
		state, err := enumState(ed)
		if err != nil {
			return nil, fmt.Errorf("%w: %w", ErrMalformed, err)
		}
		prev.Enums[string(ed.Name())] = state
	}
	return prev, nil
}

func shortDigest(s string) string {
	if len(s) <= 12 {
		return s
	}
	return s[:12] + "..."
}

// messageState reads a message's live numbers, field shapes and reservations.
// Message reserved ranges carry an EXCLUSIVE end, unlike enum ranges.
func messageState(md protoreflect.MessageDescriptor, file protoreflect.FileDescriptor) (previousType, error) {
	state := previousType{
		Numbers: map[string]int32{},
		Fields:  map[string]previousField{},
	}
	for i := range md.Fields().Len() {
		fd := md.Fields().Get(i)
		state.Numbers[string(fd.Name())] = int32(fd.Number())
		state.Fields[string(fd.Name())] = previousField{
			Type:     fieldTypeString(fd, file),
			Repeated: fd.IsList(),
		}
	}
	ranges := md.ReservedRanges()
	for i := range ranges.Len() {
		r := ranges.Get(i)
		// End is EXCLUSIVE for message ranges.
		if err := addRange(&state.Reserved, int64(r[0]), int64(r[1])-1); err != nil {
			return previousType{}, fmt.Errorf("message %q: %w", md.Name(), err)
		}
	}
	names := md.ReservedNames()
	for i := range names.Len() {
		state.Reserved.addName(string(names.Get(i)))
	}
	return state, nil
}

// enumState reads an enum's live numbers and reservations. Enum reserved ranges
// carry an INCLUSIVE end, unlike message ranges - a real asymmetry in
// protoreflect that silently drops the last reserved number if ignored.
func enumState(ed protoreflect.EnumDescriptor) (previousType, error) {
	state := previousType{Numbers: map[string]int32{}}
	for i := range ed.Values().Len() {
		vd := ed.Values().Get(i)
		state.Numbers[string(vd.Name())] = int32(vd.Number())
	}
	ranges := ed.ReservedRanges()
	for i := range ranges.Len() {
		r := ranges.Get(i)
		// End is INCLUSIVE for enum ranges.
		if err := addRange(&state.Reserved, int64(r[0]), int64(r[1])); err != nil {
			return previousType{}, fmt.Errorf("enum %q: %w", ed.Name(), err)
		}
	}
	names := ed.ReservedNames()
	for i := range names.Len() {
		state.Reserved.addName(string(names.Get(i)))
	}
	return state, nil
}

// addRange records [start, end] (inclusive) as reserved. The bounds are taken
// in int64 because a descriptor's exclusive end is one past the largest legal
// field number, which the caller decrements before it gets here.
//
// The range is kept as a range. Expanding it into individual numbers would cost
// one entry per number and force a cap on the width the loader accepts, and a
// capped loader must then refuse a reservation that protobuf itself considers
// ordinary: the legal field-number space runs to 536,870,911 and a published
// contract may legitimately retire all of it.
func addRange(res *reservations, start, end int64) error {
	// end >= start for every range protocompile produces, so bounding the end
	// bounds the start too and both conversions below are in range.
	if start < 0 || end > maxFieldNumber {
		return fmt.Errorf("reserved range %d to %d is outside Ptah's supported numbering space", start, end)
	}
	//nolint:gosec // Both conversions are guarded by the supported-numbering-space check.
	res.addRange(int32(start), int32(end))
	return nil
}

// fieldTypeString spells a field's type exactly as the generator writes it, so
// the two can be compared to detect a wire-incompatible change. Types defined by
// this file are written bare; imported types keep their full name.
//
// The test is the DEFINING FILE, not the package prefix. Trimming by package
// would also shorten "google.protobuf.Timestamp" when --proto-package is
// "google.protobuf", so the previous spelling would never match what the
// renderer writes and every run would report a spurious type change.
func fieldTypeString(fd protoreflect.FieldDescriptor, file protoreflect.FileDescriptor) string {
	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return localName(fd.Message().FullName(), fd.Message().ParentFile(), file)
	case protoreflect.EnumKind:
		return localName(fd.Enum().FullName(), fd.Enum().ParentFile(), file)
	default:
		return fd.Kind().String()
	}
}

func localName(full protoreflect.FullName, definedIn, file protoreflect.FileDescriptor) string {
	if definedIn != nil && file != nil && definedIn.Path() == file.Path() {
		prefix := string(file.Package()) + "."
		return strings.TrimPrefix(string(full), prefix)
	}
	return string(full)
}

// compileProto parses and links src with protocompile. It is used both to read
// a previous export and to validate freshly rendered bytes before they are
// written, which catches generator bugs at generation time rather than in the
// caller's build.
func compileProto(ctx context.Context, path, src string) (protoreflect.FileDescriptor, error) {
	var problems []string
	rep := reporter.NewReporter(
		func(err reporter.ErrorWithPos) error {
			problems = append(problems, err.Error())
			return nil // keep going so every error is reported at once
		},
		nil,
	)
	compiler := protocompile.Compiler{
		Resolver: protocompile.WithStandardImports(&protocompile.SourceResolver{
			Accessor: protocompile.SourceAccessorFromMap(map[string]string{path: src}),
		}),
		SourceInfoMode: protocompile.SourceInfoStandard,
		Reporter:       rep,
	}
	files, err := compiler.Compile(ctx, path)
	if err != nil {
		if len(problems) > 0 {
			return nil, errors.New(strings.Join(problems, "; "))
		}
		return nil, err
	}
	if len(files) == 0 {
		return nil, errors.New("no file descriptor produced")
	}
	return linker.Files(files)[0], nil
}
