package protobufrender_test

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"

	"github.com/stokaro/ptah/core/goschema"
	"github.com/stokaro/ptah/internal/protobufrender"
)

const (
	testPackage  = "acme.inventory.v1"
	testOutPath  = "proto/acme/inventory/v1/schema.proto"
	digestPrefix = "// ptah:content-sha256="
	headerMarker = "// Code generated by ptah schema export --to protobuf; DO NOT EDIT."
	versionLine  = "// ptah:protobuf-export-version=1"
)

// releasePolicy is the non-default name-reuse policy, spelled once so the
// numbering tests do not have to import the constant for a single use.
const releasePolicy = protobufrender.NameReuseRelease

// baseOptions is the option set every test starts from: the package and output
// path are always required, and every policy defaults to its refusing variant.
func baseOptions() protobufrender.Options {
	return protobufrender.Options{Package: testPackage, OutPath: testOutPath}
}

// withPrevious returns baseOptions carrying a compatibility baseline.
// enumCarrierType is the column type a test uses to carry inline enum values.
// goschema.ParseDir never leaves Field.Type as the literal "ENUM": for
// `type="ENUM" enum="a,b"` it rewrites the type to enum_<struct>_<field> and
// also fills Field.Enum, and for values carried on a scalar column the type
// stays that scalar. A scalar carrier exercises the inline branch the way the
// parser actually produces it.
const enumCarrierType = "VARCHAR(20)"

func withPrevious(previous []byte) protobufrender.Options {
	opts := baseOptions()
	opts.Previous = previous
	opts.HasPrevious = true
	return opts
}

func mustRender(c *qt.C, db *goschema.Database, opts protobufrender.Options) protobufrender.Result {
	c.Helper()
	res, err := protobufrender.Render(context.Background(), db, opts)
	c.Assert(err, qt.IsNil)
	return res
}

func mustRenderText(c *qt.C, db *goschema.Database, opts protobufrender.Options) string {
	c.Helper()
	return string(mustRender(c, db, opts).Data)
}

// mustFail asserts the export was refused and returns its user-facing message.
func mustFail(c *qt.C, db *goschema.Database, opts protobufrender.Options) string {
	c.Helper()
	res, err := protobufrender.Render(context.Background(), db, opts)
	c.Assert(err, qt.IsNotNil)
	c.Assert(res.Data, qt.IsNil)
	return err.Error()
}

// columns stamps a struct name onto a column list so fixtures stay readable.
func columns(structName string, fields ...goschema.Field) []goschema.Field {
	out := make([]goschema.Field, 0, len(fields))
	for _, f := range fields {
		f.StructName = structName
		out = append(out, f)
	}
	return out
}

// oneTable builds a single-table schema named "things", whose message name is
// therefore "Thing".
func oneTable(fields ...goschema.Field) *goschema.Database {
	return &goschema.Database{
		Tables: []goschema.Table{{StructName: "Thing", Name: "things"}},
		Fields: columns("Thing", fields...),
	}
}

// column is shorthand for a single column of the given type.
func column(name, columnType string) goschema.Field {
	return goschema.Field{Name: name, Type: columnType}
}

// diagnosticMessages flattens the diagnostics for substring assertions.
func diagnosticMessages(res protobufrender.Result) []string {
	out := make([]string, 0, len(res.Diagnostics))
	for _, d := range res.Diagnostics {
		out = append(out, string(d.Severity)+" "+d.Path+": "+d.Message)
	}
	return out
}

// previousExport wraps a body in the generated header and stamps a valid
// content digest, producing a baseline the exporter accepts. Hand-writing one is
// the only way to pin a field number the generator would never allocate on its
// own, such as 18999 or 536870911.
func previousExport(body string) []byte {
	return stampProto(headerMarker + "\n" + versionLine + "\n" + digestPrefix + "\n" +
		"edition = \"2023\";\n\npackage " + testPackage + ";\n\n" + body)
}

// stampProto recomputes the content digest of raw, using the same rule as the
// exporter: the digest line is removed, the remainder joined with "\n" and
// hashed, and the value written back.
func stampProto(raw string) []byte {
	lines := strings.Split(raw, "\n")
	index := -1
	for i, line := range lines {
		if strings.HasPrefix(line, digestPrefix) {
			index = i
		}
	}
	kept := make([]string, 0, len(lines)-1)
	kept = append(kept, lines[:index]...)
	kept = append(kept, lines[index+1:]...)
	sum := sha256.Sum256([]byte(strings.Join(kept, "\n")))
	lines[index] = digestPrefix + hex.EncodeToString(sum[:])
	return []byte(strings.Join(lines, "\n"))
}

// indexOf is strings.Index, named so ordering assertions read as comparisons.
func indexOf(text, needle string) int {
	return strings.Index(text, needle)
}

// enumDeclarations lists every generated enum header, for counting them.
func enumDeclarations(text string) []string {
	var out []string
	for line := range strings.SplitSeq(text, "\n") {
		if strings.HasPrefix(line, "enum ") {
			out = append(out, line)
		}
	}
	return out
}

// section returns the declaration starting at header, up to and including its
// closing brace at column zero.
func section(text, header string) string {
	start := strings.Index(text, header)
	rest := text[max(start, 0):]
	end := strings.Index(rest, "\n}")
	return rest[:min(end+2, len(rest))]
}

func TestRenderGoldenFile(t *testing.T) {
	c := qt.New(t)

	db := &goschema.Database{
		Tables: []goschema.Table{
			{StructName: "Author", Name: "authors", Comment: "People who write."},
			{StructName: "Book", Name: "books"},
		},
		Fields: []goschema.Field{
			{StructName: "Author", Name: "id", Type: "BIGSERIAL", Primary: true},
			{StructName: "Author", Name: "name", Type: "VARCHAR(255)", Comment: "Display name."},
			{StructName: "Book", Name: "id", Type: "SERIAL", Primary: true},
			{StructName: "Book", Name: "author_id", Type: "INTEGER", Foreign: "authors(id)"},
			{StructName: "Book", Name: "published_at", Type: "TIMESTAMPTZ", Nullable: true},
			{StructName: "Book", Name: "tags", Type: "TEXT[]"},
		},
	}

	opts := baseOptions()
	opts.GoPackage = "example.com/acme/gen/inventory/v1;inventoryv1"

	c.Assert(mustRenderText(c, db, opts), qt.Equals, goldenFile)
}

const goldenFile = headerMarker + `
// ptah:protobuf-export-version=1
// ptah:content-sha256=d4c7e389653ae2c4d28f1c175c9f39e605f64290af4fe9d755cd84648c054337
edition = "2023";

package acme.inventory.v1;

import "google/protobuf/timestamp.proto";

option go_package = "example.com/acme/gen/inventory/v1;inventoryv1";

// People who write.
message Author {
  int64 id = 1;
  // Display name.
  string name = 2;
}

message Book {
  int32 id = 1;
  int32 author_id = 2;
  google.protobuf.Timestamp published_at = 3;
  repeated string tags = 4;
}
`

func TestRenderIsByteIdenticalAcrossRuns(t *testing.T) {
	c := qt.New(t)

	db := oneTable(column("id", "BIGINT"), column("sku", "TEXT"))

	first := mustRender(c, db, baseOptions())
	second := mustRender(c, db, baseOptions())

	c.Assert(string(second.Data), qt.Equals, string(first.Data))

	// Regenerating from the file just produced must reproduce it exactly.
	third := mustRender(c, db, withPrevious(first.Data))
	c.Assert(string(third.Data), qt.Equals, string(first.Data))
}

func TestRenderReorderedColumnsChangeNothing(t *testing.T) {
	c := qt.New(t)

	db := oneTable(
		column("id", "BIGINT"),
		column("sku", "TEXT"),
		column("name", "TEXT"),
	)
	baseline := mustRender(c, db, baseOptions())

	reordered := oneTable(
		column("name", "TEXT"),
		column("id", "BIGINT"),
		column("sku", "TEXT"),
	)
	res := mustRender(c, reordered, withPrevious(baseline.Data))

	c.Assert(string(res.Data), qt.Equals, string(baseline.Data))
	c.Assert(string(res.Data), qt.Contains, "  int64 id = 1;\n  string sku = 2;\n  string name = 3;\n")
}

func TestRenderBootstrapWarnsAndFlagsResult(t *testing.T) {
	c := qt.New(t)

	db := oneTable(column("id", "BIGINT"))

	first := mustRender(c, db, baseOptions())
	c.Assert(first.Bootstrapped, qt.IsTrue)
	c.Assert(diagnosticMessages(first), qt.Any(qt.Contains),
		"no previous export found at "+testOutPath+
			"; field numbering starts from 1 and is not compatible with any previously published .proto")

	second := mustRender(c, db, withPrevious(first.Data))
	c.Assert(second.Bootstrapped, qt.IsFalse)
	c.Assert(second.Diagnostics, qt.HasLen, 0)
}

func TestRenderEndsWithExactlyOneNewline(t *testing.T) {
	c := qt.New(t)

	// LF newlines, one trailing newline, no BOM. A trailing blank line would
	// not be a buf format fixed point, so a `buf format -w` pre-commit hook
	// would rewrite the file, invalidate the content digest and make every
	// later export refuse to run.
	shapes := map[string]*goschema.Database{
		"scalars only": oneTable(column("id", "BIGINT")),
		"with an enum": inlineEnumTable("draft", "live"),
		"with imports": oneTable(column("meta", "JSONB"), column("at", "TIMESTAMPTZ")),
	}

	for name, db := range shapes {
		c.Run(name, func(c *qt.C) {
			text := mustRenderText(c, db, baseOptions())
			c.Assert(strings.HasSuffix(text, "}\n"), qt.IsTrue)
			c.Assert(strings.HasSuffix(text, "\n\n"), qt.IsFalse)
			c.Assert(text, qt.Not(qt.Contains), "\r")
			c.Assert(strings.HasPrefix(text, headerMarker+"\n"+versionLine+"\n"+digestPrefix), qt.IsTrue)
		})
	}
}

func TestRenderRejectsMissingInputs(t *testing.T) {
	c := qt.New(t)

	_, err := protobufrender.Render(context.Background(), nil, baseOptions())
	c.Assert(err, qt.ErrorMatches, "schema database is nil")

	opts := baseOptions()
	opts.Package = "   "
	_, err = protobufrender.Render(context.Background(), oneTable(column("id", "BIGINT")), opts)
	c.Assert(err, qt.ErrorMatches, "a protobuf package is required")
}

func TestRenderHonorsTableFilters(t *testing.T) {
	c := qt.New(t)

	db := &goschema.Database{
		Tables: []goschema.Table{
			{StructName: "Author", Name: "authors"},
			{StructName: "Book", Name: "books"},
		},
		Fields: []goschema.Field{
			{StructName: "Author", Name: "id", Type: "BIGINT"},
			{StructName: "Book", Name: "id", Type: "BIGINT"},
		},
	}

	included := baseOptions()
	included.IncludeTables = []string{"books"}
	text := mustRenderText(c, db, included)
	c.Assert(text, qt.Contains, "message Book {")
	c.Assert(text, qt.Not(qt.Contains), "message Author {")

	excluded := baseOptions()
	excluded.ExcludeTables = []string{"books"}
	text = mustRenderText(c, db, excluded)
	c.Assert(text, qt.Contains, "message Author {")
	c.Assert(text, qt.Not(qt.Contains), "message Book {")
}

func TestRenderCommentsCannotEscapeTheirContext(t *testing.T) {
	c := qt.New(t)

	db := &goschema.Database{
		Tables: []goschema.Table{{
			StructName: "Thing",
			Name:       "things",
			Comment:    "first line\n} message Injected { int32 x = 1; }\ttabbed\x07",
		}},
		Fields: columns("Thing", column("id", "BIGINT")),
	}

	text := mustRenderText(c, db, baseOptions())

	c.Assert(text, qt.Contains, "// first line\n")
	c.Assert(text, qt.Contains, "// } message Injected { int32 x = 1; } tabbed\n")
	// Every line of the comment stays a comment, so the injected declaration is
	// never a real message. Render also re-parses its own output, so reaching
	// this assertion already proves the file compiles.
	c.Assert(text, qt.Not(qt.Contains), "\nmessage Injected {")
}

func TestRenderEscapesGoPackage(t *testing.T) {
	c := qt.New(t)

	opts := baseOptions()
	opts.GoPackage = "example.com/x\"y"

	text := mustRenderText(c, oneTable(column("id", "BIGINT")), opts)
	c.Assert(text, qt.Contains, `option go_package = "example.com/x\"y";`)
}
