// Package atlashclrender renders Ptah schema IR as Atlas schema HCL.
package atlashclrender

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/stokaro/ptah/core/goschema"
)

// Severity is the diagnostic severity emitted by the exporter.
type Severity string

const (
	// SeverityWarning reports a lossy or currently unsupported export path.
	SeverityWarning Severity = "warning"
)

// Diagnostic describes an unsupported or lossy export detail.
type Diagnostic struct {
	Severity Severity
	Path     string
	Message  string
}

// Result is the rendered HCL plus loss diagnostics.
type Result struct {
	Data        []byte
	Diagnostics []Diagnostic
}

// Render renders a finalized Ptah schema IR as deterministic Atlas schema HCL.
func Render(db *goschema.Database) (Result, error) {
	if db == nil {
		return Result{}, fmt.Errorf("schema database is nil")
	}

	r := renderer{
		db: db,
	}
	r.render()
	return Result{
		Data:        []byte(r.builder.String()),
		Diagnostics: r.diagnostics,
	}, nil
}

type renderer struct {
	db          *goschema.Database
	builder     strings.Builder
	diagnostics []Diagnostic
}

func (r *renderer) render() {
	r.builder.WriteString("// Code generated by ptah schema export; DO NOT EDIT.\n\n")
	r.renderSchemas()
	r.renderExtensions()
	r.renderEnums()
	r.renderRoles()
	r.renderTables()
	r.renderFunctions()
	r.renderViews()
	r.renderMaterializedViews()
	r.renderTriggers()
	r.renderRLSPolicies()
	r.renderGrants()
}

func (r *renderer) renderSchemas() {
	schemas := append([]goschema.Schema(nil), r.db.Schemas...)
	sort.Slice(schemas, func(i, j int) bool {
		return schemas[i].Name < schemas[j].Name
	})
	for _, schema := range schemas {
		r.linef(`schema %s {`, quote(schema.Name))
		r.stringAttr(1, "comment", schema.Comment)
		r.stringAttr(1, "charset", schema.Charset)
		r.stringAttr(1, "collate", schema.Collate)
		r.line("}")
		r.line("")
	}
}

func (r *renderer) renderEnums() {
	enums := append([]goschema.Enum(nil), r.db.Enums...)
	sort.Slice(enums, func(i, j int) bool {
		return enums[i].Name < enums[j].Name
	})
	for _, enum := range enums {
		r.linef(`enum %s {`, quote(enum.Name))
		r.rawAttr(1, "values", stringList(enum.Values))
		r.line("}")
		r.line("")
	}
}

func (r *renderer) renderTables() {
	tables := append([]goschema.Table(nil), r.db.Tables...)
	sort.Slice(tables, func(i, j int) bool {
		return tables[i].QualifiedName() < tables[j].QualifiedName()
	})
	fieldsByStruct := groupFieldsByStruct(r.db.Fields)
	indexesByTable := groupIndexesByTable(r.db.Indexes, tables)
	constraintsByTable := groupConstraintsByTable(r.db.Constraints, tables)
	rlsEnabledByTable, orphanRLSEnabledTables := groupRLSEnabledByTable(r.db.RLSEnabledTables, tables)

	for _, table := range tables {
		r.renderTable(
			table,
			fieldsByStruct[table.StructName],
			indexesByTable[table.QualifiedName()],
			constraintsByTable[table.QualifiedName()],
			rlsEnabledByTable[table.QualifiedName()],
		)
	}
	for _, rlsEnabled := range orphanRLSEnabledTables {
		r.warn("rls_enabled_tables."+rlsEnabled.Table, "RLS enablement cannot be rendered because the target table is absent from the exported schema")
	}
}

func (r *renderer) renderTable(
	table goschema.Table,
	fields []goschema.Field,
	indexes []goschema.Index,
	constraints []goschema.Constraint,
	rlsEnabled *goschema.RLSEnabledTable,
) {
	r.warnOverrides("table "+table.QualifiedName(), table.Overrides)
	r.linef(`table %s {`, quote(table.Name))
	if table.Schema != "" {
		r.rawAttr(1, "schema", "schema."+table.Schema)
	}
	r.stringAttr(1, "engine", table.Engine)
	r.stringAttr(1, "charset", table.Charset)
	r.stringAttr(1, "collate", table.Collate)
	r.stringAttr(1, "comment", table.Comment)
	if table.AutoIncrement != "" {
		r.rawAttr(1, "auto_increment", table.AutoIncrement)
	}
	if table.Strict {
		r.rawAttr(1, "strict", "true")
	}
	if table.WithoutRowID {
		r.rawAttr(1, "without_rowid", "true")
	}
	r.renderRowSecurity(rlsEnabled)

	sort.SliceStable(fields, func(i, j int) bool {
		return fields[i].Name < fields[j].Name
	})
	for _, field := range fields {
		r.renderColumn(field)
	}
	r.renderPrimaryKey(table, fields)
	r.renderPartition(table.Partition)
	constraintNames := constraintNameSet(constraints)
	r.renderFieldChecks(table, fields, constraintNames)
	r.renderFieldForeignKeys(table, fields, constraintNames)
	for _, constraint := range constraints {
		r.renderConstraint(table, constraint)
	}
	for _, index := range indexes {
		r.renderIndex(index)
	}
	if table.CustomSQL != "" {
		r.warn("table "+table.QualifiedName(), "custom SQL cannot be represented in Atlas HCL")
	}
	r.line("}")
	r.line("")
}

func (r *renderer) renderColumn(field goschema.Field) {
	r.warnOverrides("column "+field.StructName+"."+field.Name, field.Overrides)
	r.linef(`  column %s {`, quote(field.Name))
	r.rawAttr(2, "type", typeExpr(field.Type))
	if field.Nullable {
		r.rawAttr(2, "null", "true")
	}
	if field.AutoInc {
		r.rawAttr(2, "auto_increment", "true")
	}
	if field.Unique {
		r.rawAttr(2, "unique", "true")
	}
	if field.DefaultExpr != "" {
		r.rawAttr(2, "default", sqlCall(field.DefaultExpr))
	} else if field.DefaultSet || field.Default != "" {
		r.rawAttr(2, "default", quote(field.Default))
	}
	if field.UpdateExpression != "" {
		r.rawAttr(2, "on_update", sqlCall(field.UpdateExpression))
	}
	if field.GeneratedExpression != "" {
		r.line("    as {")
		r.stringAttr(3, "expr", field.GeneratedExpression)
		r.stringAttr(3, "type", field.GeneratedKind)
		r.line("    }")
	}
	if field.IdentityGeneration != "" || field.IdentityStart != "" || field.IdentityIncrement != "" {
		r.line("    identity {")
		r.stringAttr(3, "generated", field.IdentityGeneration)
		r.stringAttr(3, "start", field.IdentityStart)
		r.stringAttr(3, "increment", field.IdentityIncrement)
		if field.IdentityOptions != "" {
			r.warn("column "+field.StructName+"."+field.Name, "identity_options cannot be represented in Atlas HCL")
		}
		r.line("    }")
	}
	r.stringAttr(2, "charset", field.Charset)
	r.stringAttr(2, "collate", field.Collate)
	r.stringAttr(2, "comment", field.Comment)
	if field.UniqueExpr != "" {
		r.warn("column "+field.StructName+"."+field.Name, "unique expression cannot be represented as a column unique attribute")
	}
	r.line("  }")
}

func (r *renderer) renderFieldChecks(table goschema.Table, fields []goschema.Field, constraintNames map[string]struct{}) {
	for _, field := range fields {
		if field.Check == "" {
			continue
		}
		name := field.CheckName
		if name == "" {
			name = table.Name + "_" + field.Name + "_check"
		}
		if _, ok := constraintNames[name]; ok {
			continue
		}
		r.linef(`  check %s {`, quote(name))
		r.stringAttr(2, "expr", field.Check)
		r.line("  }")
	}
}

func (r *renderer) renderFieldForeignKeys(table goschema.Table, fields []goschema.Field, constraintNames map[string]struct{}) {
	for _, field := range fields {
		if field.Foreign == "" {
			continue
		}
		name := field.ForeignKeyName
		if name == "" {
			name = "fk_" + table.Name + "_" + field.Name
		}
		if _, ok := constraintNames[name]; ok {
			continue
		}
		foreignTable, foreignColumns := parseForeignReference(field.Foreign)
		r.renderForeignKey(name, []string{field.Name}, foreignTable, foreignColumns, field.OnDelete, field.OnUpdate)
	}
}

func (r *renderer) renderPrimaryKey(table goschema.Table, fields []goschema.Field) {
	columns := table.PrimaryKey
	if len(columns) == 0 {
		for _, field := range fields {
			if field.Primary {
				columns = append(columns, field.Name)
			}
		}
	}
	if len(columns) == 0 && len(table.PrimaryKeyParts) == 0 {
		return
	}
	r.line("  primary_key {")
	if len(table.PrimaryKeyParts) > 0 && !simplePrimaryKeyParts(table.PrimaryKeyParts) {
		for _, part := range table.PrimaryKeyParts {
			r.line("    on {")
			if part.Name != "" {
				r.rawAttr(3, "column", "column."+part.Name)
			}
			r.stringAttr(3, "prefix", part.Prefix)
			if part.Desc {
				r.rawAttr(3, "desc", "true")
			}
			r.line("    }")
		}
	} else {
		r.rawAttr(2, "columns", columnRefs(columns))
	}
	if len(table.PrimaryKeyInclude) > 0 {
		r.rawAttr(2, "include", columnRefs(table.PrimaryKeyInclude))
	}
	r.line("  }")
}

func (r *renderer) renderPartition(partition *goschema.PartitionSpec) {
	if partition == nil {
		return
	}
	r.line("  partition {")
	r.stringAttr(2, "type", partition.Type)
	for _, part := range partition.Parts {
		r.line("    by {")
		if part.Name != "" {
			r.rawAttr(3, "column", "column."+part.Name)
		}
		r.stringAttr(3, "expr", part.Expr)
		r.line("    }")
	}
	r.line("  }")
}

func (r *renderer) renderConstraint(table goschema.Table, constraint goschema.Constraint) {
	switch strings.ToUpper(constraint.Type) {
	case "CHECK":
		name := constraint.Name
		if name == "" {
			name = table.Name + "_check"
		}
		r.linef(`  check %s {`, quote(name))
		r.stringAttr(2, "expr", firstNonEmpty(constraint.CheckExpression, constraint.WhereCondition))
		r.line("  }")
	case "UNIQUE":
		r.linef(`  unique %s {`, quote(constraint.Name))
		r.rawAttr(2, "columns", columnRefs(constraint.Columns))
		r.boolPtrAttr(2, "nulls_distinct", constraint.NullsDistinct)
		r.line("  }")
	case "FOREIGN KEY":
		r.renderForeignKeyConstraint(table, constraint)
	case "PRIMARY KEY":
		r.line("  primary_key {")
		r.rawAttr(2, "columns", columnRefs(constraint.Columns))
		r.line("  }")
	case "EXCLUDE":
		r.warn("constraint "+constraint.Name, "EXCLUDE constraints cannot be represented in the supported Atlas HCL subset")
	default:
		r.warn("constraint "+constraint.Name, "unknown constraint type "+strconv.Quote(constraint.Type))
	}
}

func (r *renderer) renderForeignKeyConstraint(table goschema.Table, constraint goschema.Constraint) {
	name := constraint.Name
	if name == "" {
		name = table.Name + "_fk"
	}
	r.renderForeignKey(name, constraint.Columns, constraint.ForeignTable, constraint.ForeignColumnsOrDefault(), constraint.OnDelete, constraint.OnUpdate)
}

func (r *renderer) renderForeignKey(name string, columns []string, foreignTable string, foreignColumns []string, onDelete string, onUpdate string) {
	r.linef(`  foreign_key %s {`, quote(name))
	r.rawAttr(2, "columns", columnRefs(columns))
	r.rawAttr(2, "ref_columns", tableColumnRefs(foreignTable, foreignColumns))
	r.stringAttr(2, "on_delete", onDelete)
	r.stringAttr(2, "on_update", onUpdate)
	r.line("  }")
}

func (r *renderer) renderIndex(index goschema.Index) {
	r.linef(`  index %s {`, quote(index.Name))
	if index.Unique {
		r.rawAttr(2, "unique", "true")
	}
	r.stringAttr(2, "type", index.Type)
	r.stringAttr(2, "parser", index.Parser)
	r.stringAttr(2, "where", index.Condition)
	r.boolPtrAttr(2, "nulls_distinct", index.NullsDistinct)
	if len(index.IncludeColumns) > 0 {
		r.rawAttr(2, "include", columnRefs(index.IncludeColumns))
	}
	if pages, ok := index.StorageParams["pages_per_range"]; ok {
		r.rawAttr(2, "pages_per_range", pages)
	}
	if len(index.Parts) > 0 && !simpleIndexParts(index.Parts) {
		for _, part := range index.Parts {
			r.line("    on {")
			if part.Name != "" {
				r.rawAttr(3, "column", "column."+part.Name)
			}
			r.stringAttr(3, "expr", part.Expr)
			r.stringAttr(3, "ops", part.Operator)
			r.stringAttr(3, "prefix", part.Prefix)
			if part.Desc {
				r.rawAttr(3, "desc", "true")
			}
			r.line("    }")
		}
	} else {
		r.rawAttr(2, "columns", columnRefs(firstNonEmptySlice(index.Fields, indexPartNames(index.Parts))))
	}
	if index.Operator != "" {
		r.warn("index "+index.Name, "legacy index operator field was not exported; use structured index parts")
	}
	if index.Granularity != 0 {
		r.warn("index "+index.Name, "ClickHouse granularity cannot be represented in the supported Atlas HCL subset")
	}
	if index.Comment != "" {
		r.warn("index "+index.Name, "index comments cannot be represented in Atlas HCL")
	}
	r.line("  }")
}

func (r *renderer) warnOverrides(path string, overrides map[string]map[string]string) {
	if len(overrides) == 0 {
		return
	}
	r.warn(path, "platform overrides cannot be represented exactly in Atlas HCL")
}

func (r *renderer) warn(path, message string) {
	r.diagnostics = append(r.diagnostics, Diagnostic{
		Severity: SeverityWarning,
		Path:     path,
		Message:  message,
	})
}

func (r *renderer) line(value string) {
	r.builder.WriteString(value)
	r.builder.WriteByte('\n')
}

func (r *renderer) linef(format string, args ...any) {
	r.line(fmt.Sprintf(format, args...))
}

func (r *renderer) rawAttr(indent int, name, value string) {
	if value == "" {
		return
	}
	r.linef("%s%s = %s", strings.Repeat("  ", indent), name, value)
}

func (r *renderer) stringAttr(indent int, name, value string) {
	if value == "" {
		return
	}
	r.rawAttr(indent, name, quote(value))
}

func (r *renderer) boolPtrAttr(indent int, name string, value *bool) {
	if value == nil {
		return
	}
	r.rawAttr(indent, name, strconv.FormatBool(*value))
}

func groupFieldsByStruct(fields []goschema.Field) map[string][]goschema.Field {
	result := make(map[string][]goschema.Field)
	for _, field := range fields {
		result[field.StructName] = append(result[field.StructName], field)
	}
	return result
}

func groupIndexesByTable(indexes []goschema.Index, tables []goschema.Table) map[string][]goschema.Index {
	result := make(map[string][]goschema.Index)
	for _, index := range indexes {
		table := resolveTable(tables, index.StructName, index.TableName)
		if table == nil {
			continue
		}
		result[table.QualifiedName()] = append(result[table.QualifiedName()], index)
	}
	for key := range result {
		sort.Slice(result[key], func(i, j int) bool {
			return result[key][i].Name < result[key][j].Name
		})
	}
	return result
}

func groupConstraintsByTable(constraints []goschema.Constraint, tables []goschema.Table) map[string][]goschema.Constraint {
	result := make(map[string][]goschema.Constraint)
	for _, constraint := range constraints {
		table := resolveTable(tables, constraint.StructName, constraint.Table)
		if table == nil {
			continue
		}
		result[table.QualifiedName()] = append(result[table.QualifiedName()], constraint)
	}
	for key := range result {
		sort.Slice(result[key], func(i, j int) bool {
			return result[key][i].Name < result[key][j].Name
		})
	}
	return result
}

func constraintNameSet(constraints []goschema.Constraint) map[string]struct{} {
	result := make(map[string]struct{}, len(constraints))
	for _, constraint := range constraints {
		if constraint.Name != "" {
			result[constraint.Name] = struct{}{}
		}
	}
	return result
}

func resolveTable(tables []goschema.Table, structName, tableName string) *goschema.Table {
	for i := range tables {
		table := &tables[i]
		if tableName == "" && table.StructName == structName {
			return table
		}
		if tableName != "" && (table.Name == tableName || table.QualifiedName() == tableName) {
			return table
		}
	}
	return nil
}

func simplePrimaryKeyParts(parts []goschema.PrimaryKeyPart) bool {
	for _, part := range parts {
		if part.Prefix != "" || part.Desc {
			return false
		}
	}
	return true
}

func simpleIndexParts(parts []goschema.IndexPart) bool {
	for _, part := range parts {
		if part.Expr != "" || part.Operator != "" || part.Prefix != "" || part.Desc {
			return false
		}
	}
	return true
}

func indexPartNames(parts []goschema.IndexPart) []string {
	names := make([]string, 0, len(parts))
	for _, part := range parts {
		if part.Name != "" {
			names = append(names, part.Name)
		}
	}
	return names
}

func firstNonEmptySlice(first, second []string) []string {
	if len(first) > 0 {
		return first
	}
	return second
}

func firstNonEmpty(first, second string) string {
	if first != "" {
		return first
	}
	return second
}

func parseForeignReference(value string) (string, []string) {
	value = strings.TrimSpace(value)
	open := strings.LastIndex(value, "(")
	closeParen := strings.LastIndex(value, ")")
	if open < 0 || closeParen < open {
		return value, nil
	}
	table := strings.TrimSpace(value[:open])
	rawColumns := strings.Split(value[open+1:closeParen], ",")
	columns := make([]string, 0, len(rawColumns))
	for _, rawColumn := range rawColumns {
		column := strings.TrimSpace(rawColumn)
		if column != "" {
			columns = append(columns, column)
		}
	}
	return table, columns
}

func typeExpr(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "text"
	}
	return value
}

func sqlCall(value string) string {
	return "sql(" + quote(value) + ")"
}

func quote(value string) string {
	return strconv.Quote(value)
}

func stringList(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = quote(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func columnRefs(columns []string) string {
	refs := make([]string, 0, len(columns))
	for _, column := range columns {
		if column == "" {
			continue
		}
		refs = append(refs, "column."+column)
	}
	return "[" + strings.Join(refs, ", ") + "]"
}

func tableColumnRefs(table string, columns []string) string {
	table = unqualifiedName(table)
	refs := make([]string, 0, len(columns))
	for _, column := range columns {
		if table == "" || column == "" {
			continue
		}
		refs = append(refs, "table."+table+".column."+column)
	}
	return "[" + strings.Join(refs, ", ") + "]"
}

func unqualifiedName(value string) string {
	if idx := strings.LastIndex(value, "."); idx >= 0 {
		return value[idx+1:]
	}
	return value
}
