package importer_test

import (
	"testing"
	"testing/fstest"

	qt "github.com/frankban/quicktest"

	"ptah.run/core/platform/capability"
	"ptah.run/migration/importer"
)

// parseLiquibaseFor parses files with the Liquibase parser set to render typed
// changes for dialect.
func parseLiquibaseFor(c *qt.C, dialect string, files fstest.MapFS) (*importer.ParseResult, error) {
	c.Helper()
	parser, err := importer.ParserByName("liquibase")
	c.Assert(err, qt.IsNil)
	rendering, err := importer.WithDialect(parser, dialect)
	c.Assert(err, qt.IsNil)
	return rendering.Parse(files)
}

// liquibaseXMLOneChangeSet wraps changes in a changelog holding one changeset.
func liquibaseXMLOneChangeSet(changes string) fstest.MapFS {
	return fstest.MapFS{"changelog.xml": {Data: []byte(
		`<databaseChangeLog><changeSet id="1" author="simon">` + changes + `</changeSet></databaseChangeLog>`,
	)}}
}

// The same typed changeset written three ways. XML nests its columns, and YAML
// and JSON wrap them in a `columns` list, so a reader per serialization is
// where the three would drift; one converter fed by both walks is what keeps
// them together (stokaro/ptah#3625).
const (
	liquibaseTypedXML = `<databaseChangeLog>
  <changeSet id="1" author="simon">
    <createTable tableName="subscriptions" schemaName="public">
      <column name="id" type="bigint" autoIncrement="true">
        <constraints primaryKey="true"/>
      </column>
      <column name="account_id" type="bigint">
        <constraints nullable="false"/>
      </column>
      <column name="plan" type="varchar(40)" defaultValue="starter"/>
    </createTable>
    <createIndex indexName="subscriptions_account_idx" tableName="subscriptions" schemaName="public">
      <column name="account_id"/>
    </createIndex>
  </changeSet>
</databaseChangeLog>
`
	liquibaseTypedYAML = `databaseChangeLog:
  - changeSet:
      id: "1"
      author: simon
      changes:
        - createTable:
            tableName: subscriptions
            schemaName: public
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: account_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: plan
                  type: varchar(40)
                  defaultValue: starter
        - createIndex:
            indexName: subscriptions_account_idx
            tableName: subscriptions
            schemaName: public
            columns:
              - column:
                  name: account_id
`
	liquibaseTypedJSON = `{"databaseChangeLog": [{"changeSet": {"id": "1", "author": "simon", "changes": [
  {"createTable": {"tableName": "subscriptions", "schemaName": "public", "columns": [
    {"column": {"name": "id", "type": "bigint", "autoIncrement": true, "constraints": {"primaryKey": true}}},
    {"column": {"name": "account_id", "type": "bigint", "constraints": {"nullable": false}}},
    {"column": {"name": "plan", "type": "varchar(40)", "defaultValue": "starter"}}]}},
  {"createIndex": {"indexName": "subscriptions_account_idx", "tableName": "subscriptions", "schemaName": "public",
    "columns": [{"column": {"name": "account_id"}}]}}]}}]}
`
)

func TestLiquibaseTyped_ThreeSerializationsRenderAlike_HappyPath(t *testing.T) {
	want := []importer.SourceMigration{{
		Version: 1,
		Name:    "simon_1",
		UpSQL: `-- POSTGRES TABLE: public.subscriptions --
CREATE TABLE "public"."subscriptions" (
  "id" bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "account_id" bigint NOT NULL,
  "plan" varchar(40) DEFAULT 'starter'
);
CREATE INDEX "subscriptions_account_idx" ON "public"."subscriptions" ("account_id");`,
		DownSQL: `DROP INDEX "public"."subscriptions_account_idx";
DROP TABLE "public"."subscriptions";`,
	}}
	tests := []struct {
		name    string
		file    string
		content string
	}{
		{name: "xml", file: "changelog.xml", content: liquibaseTypedXML},
		{name: "yaml", file: "changelog.yaml", content: liquibaseTypedYAML},
		{name: "json", file: "changelog.json", content: liquibaseTypedJSON},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			parsed, err := parseLiquibaseFor(c, "postgres", fstest.MapFS{test.file: {Data: []byte(test.content)}})

			c.Assert(err, qt.IsNil)
			c.Assert(parsed.Migrations, qt.DeepEquals, want)
		})
	}
}

// Each converted change type, with the rollback derived for it. A change that
// cannot be undone from the changelog alone derives none. The MySQL rows are
// the ones whose statements differ in shape rather than in quoting.
func TestLiquibaseTyped_RendersEachChangeType_HappyPath(t *testing.T) {
	tests := []struct {
		name     string
		dialect  string
		changes  string
		wantUp   string
		wantDown string
	}{
		{
			name:    "createTable with a named composite key, a named unique and a reference",
			dialect: "postgres",
			changes: `<createTable tableName="t">` +
				`<column name="a" type="int"><constraints primaryKey="true" primaryKeyName="t_pk"/></column>` +
				`<column name="b" type="java.sql.Types.VARCHAR(10)">` +
				`<constraints primaryKey="true" unique="true" uniqueConstraintName="t_b_key"/></column>` +
				`<column name="u_id" type="bigint"><constraints foreignKeyName="t_u_fk" references="u(id)" deleteCascade="true"/></column>` +
				`<column name="ts" type="timestamp" defaultValueComputed="CURRENT_TIMESTAMP"/>` +
				`</createTable>`,
			wantUp: `-- POSTGRES TABLE: t --
CREATE TABLE "t" (
  "a" int NOT NULL,
  "b" VARCHAR(10) NOT NULL,
  "u_id" bigint,
  "ts" timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "t_pk" PRIMARY KEY ("a", "b"),
  CONSTRAINT "t_b_key" UNIQUE ("b"),
  CONSTRAINT "t_u_fk" FOREIGN KEY ("u_id") REFERENCES "u"("id") ON DELETE CASCADE
);`,
			wantDown: `DROP TABLE "t";`,
		},
		{
			name:    "dropTable",
			dialect: "postgres",
			changes: `<dropTable tableName="t" schemaName="app" cascadeConstraints="true"/>`,
			wantUp:  `DROP TABLE "app"."t" CASCADE;`,
		},
		{
			name:    "renameTable",
			dialect: "postgres",
			changes: `<renameTable oldTableName="t" newTableName="t2" schemaName="app"/>`,
			wantUp: `-- ALTER statements: --
ALTER TABLE "app"."t" RENAME TO "t2";`,
			wantDown: `-- ALTER statements: --
ALTER TABLE "app"."t2" RENAME TO "t";`,
		},
		{
			name:    "addColumn",
			dialect: "postgres",
			changes: `<addColumn tableName="t"><column name="flag" type="boolean" defaultValueBoolean="false">` +
				`<constraints nullable="false"/></column></addColumn>`,
			wantUp: `-- ALTER statements: --
ALTER TABLE "t" ADD COLUMN "flag" boolean NOT NULL DEFAULT false;`,
			wantDown: `-- ALTER statements: --
ALTER TABLE "t" DROP COLUMN "flag";`,
		},
		{
			name:    "dropColumn naming two columns",
			dialect: "postgres",
			changes: `<dropColumn tableName="t"><column name="a"/><column name="b"/></dropColumn>`,
			wantUp: `-- ALTER statements: --
ALTER TABLE "t" DROP COLUMN "a";
ALTER TABLE "t" DROP COLUMN "b";`,
		},
		{
			name:    "renameColumn",
			dialect: "postgres",
			changes: `<renameColumn tableName="t" oldColumnName="a" newColumnName="b" columnDataType="int"/>`,
			wantUp: `-- ALTER statements: --
ALTER TABLE "t" RENAME COLUMN "a" TO "b";`,
			wantDown: `-- ALTER statements: --
ALTER TABLE "t" RENAME COLUMN "b" TO "a";`,
		},
		{
			name:     "createIndex unique with a descending column",
			dialect:  "postgres",
			changes:  `<createIndex indexName="i" tableName="t" unique="true"><column name="a"/><column name="b" descending="true"/></createIndex>`,
			wantUp:   `CREATE UNIQUE INDEX "i" ON "t" ("a", "b" DESC);`,
			wantDown: `DROP INDEX "i";`,
		},
		{
			name:     "createIndex on MySQL drops the index inside its table",
			dialect:  "mysql",
			changes:  `<createIndex indexName="i" tableName="t"><column name="a"/></createIndex>`,
			wantUp:   "CREATE INDEX `i` ON `t` (`a`);",
			wantDown: "DROP INDEX `i` ON `t`;",
		},
		{
			name:    "dropIndex naming its table",
			dialect: "mysql",
			changes: `<dropIndex indexName="i" tableName="t" schemaName="app"/>`,
			wantUp:  "DROP INDEX `i` ON `app`.`t`;",
		},
		{
			name:    "dropIndex naming only its schema",
			dialect: "postgres",
			changes: `<dropIndex indexName="i" schemaName="app"/>`,
			wantUp:  `DROP INDEX "app"."i";`,
		},
		{
			name:    "addPrimaryKey",
			dialect: "postgres",
			changes: `<addPrimaryKey tableName="t" columnNames="a, b" constraintName="t_pk"/>`,
			wantUp: `-- ALTER statements: --
ALTER TABLE "t" ADD CONSTRAINT "t_pk" PRIMARY KEY ("a", "b");`,
			wantDown: `-- ALTER statements: --
ALTER TABLE "t" DROP CONSTRAINT "t_pk";`,
		},
		{
			name:     "addPrimaryKey on MySQL",
			dialect:  "mysql",
			changes:  `<addPrimaryKey tableName="t" columnNames="a" constraintName="t_pk"/>`,
			wantUp:   "-- ALTER statements: --\nALTER TABLE `t` ADD PRIMARY KEY (`a`);",
			wantDown: "-- ALTER statements: --\nALTER TABLE `t` DROP PRIMARY KEY;",
		},
		{
			// The server names an unnamed key, and a drop needs that name,
			// which only the database knows.
			name:    "addPrimaryKey without a name derives no rollback",
			dialect: "postgres",
			changes: `<addPrimaryKey tableName="t" columnNames="a"/>`,
			wantUp: `-- ALTER statements: --
ALTER TABLE "t" ADD PRIMARY KEY ("a");`,
		},
		{
			name:    "addForeignKeyConstraint",
			dialect: "postgres",
			changes: `<addForeignKeyConstraint constraintName="t_u_fk" baseTableName="t" baseColumnNames="u_id" ` +
				`referencedTableName="u" referencedColumnNames="id" onDelete="SET NULL"/>`,
			wantUp: `-- ALTER statements: --
ALTER TABLE "t" ADD CONSTRAINT "t_u_fk" FOREIGN KEY ("u_id") REFERENCES "u"("id") ON DELETE SET NULL;`,
			wantDown: `-- ALTER statements: --
ALTER TABLE "t" DROP CONSTRAINT "t_u_fk";`,
		},
		{
			name:    "addForeignKeyConstraint on MySQL",
			dialect: "mysql",
			changes: `<addForeignKeyConstraint constraintName="t_u_fk" baseTableName="t" baseColumnNames="u_id" ` +
				`referencedTableName="u" referencedColumnNames="id"/>`,
			wantUp:   "-- ALTER statements: --\nALTER TABLE `t` ADD CONSTRAINT `t_u_fk` FOREIGN KEY (`u_id`) REFERENCES `u`(`id`);",
			wantDown: "-- ALTER statements: --\nALTER TABLE `t` DROP FOREIGN KEY `t_u_fk`;",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			parsed, err := parseLiquibaseFor(c, test.dialect, liquibaseXMLOneChangeSet(test.changes))

			c.Assert(err, qt.IsNil)
			c.Assert(parsed.Migrations, qt.HasLen, 1)
			c.Assert(parsed.Migrations[0].UpSQL, qt.Equals, test.wantUp)
			c.Assert(parsed.Migrations[0].DownSQL, qt.Equals, test.wantDown)
		})
	}
}

// The derived rollback undoes the last change first: the index goes before the
// table it is on, which is the only order a server accepts.
func TestLiquibaseTyped_DerivedRollbackReversesOrder_HappyPath(t *testing.T) {
	c := qt.New(t)

	parsed, err := parseLiquibaseFor(c, "postgres", liquibaseXMLOneChangeSet(
		`<createTable tableName="t"><column name="a" type="int"/></createTable>`+
			`<createIndex indexName="i" tableName="t"><column name="a"/></createIndex>`,
	))

	c.Assert(err, qt.IsNil)
	c.Assert(parsed.Migrations[0].DownSQL, qt.Equals, "DROP INDEX \"i\";\nDROP TABLE \"t\";")
}

// One change without an inverse leaves the changeset without a derived
// rollback. Undoing the reversible part alone would leave the rest applied,
// and a down file that half-undoes its up is worse than none.
func TestLiquibaseTyped_IrreversibleChangeLeavesNoDerivedRollback_HappyPath(t *testing.T) {
	tests := []struct {
		name    string
		changes string
	}{
		{
			name: "a drop",
			changes: `<createTable tableName="t"><column name="a" type="int"/></createTable>` +
				`<dropColumn tableName="u" columnName="c"/>`,
		},
		{
			name:    "SQL",
			changes: `<createTable tableName="t"><column name="a" type="int"/></createTable><sql>INSERT INTO t VALUES (1);</sql>`,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			parsed, err := parseLiquibaseFor(c, "postgres", liquibaseXMLOneChangeSet(test.changes))

			c.Assert(err, qt.IsNil)
			c.Assert(parsed.Migrations[0].DownSQL, qt.Equals, "")
		})
	}
}

// An explicit rollback wins over the derived one, including an empty rollback,
// which states that undoing the changeset takes nothing.
func TestLiquibaseTyped_ExplicitRollbackWins_HappyPath(t *testing.T) {
	tests := []struct {
		name     string
		rollback string
		wantDown string
	}{
		{name: "SQL", rollback: `<rollback>DROP TABLE t CASCADE;</rollback>`, wantDown: "DROP TABLE t CASCADE;"},
		{name: "a typed change", rollback: `<rollback><dropTable tableName="t" cascadeConstraints="true"/></rollback>`, wantDown: `DROP TABLE "t" CASCADE;`},
		{name: "empty", rollback: `<rollback/>`, wantDown: ""},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			parsed, err := parseLiquibaseFor(c, "postgres", liquibaseXMLOneChangeSet(
				`<createTable tableName="t"><column name="a" type="int"/></createTable>`+test.rollback,
			))

			c.Assert(err, qt.IsNil)
			c.Assert(parsed.Migrations[0].DownSQL, qt.Equals, test.wantDown)
		})
	}
}

// A sqlFile change reads a file below the source directory, and that file is
// accounted for as converted. Without the accounting the import would report
// the file it just read as left behind, and refuse to write ptah.sum.
func TestLiquibaseTyped_SQLFileIsReadAndAccountedFor_HappyPath(t *testing.T) {
	c := qt.New(t)
	files := fstest.MapFS{
		"changelog.xml": {Data: []byte(`<databaseChangeLog><changeSet id="1" author="simon">` +
			`<sqlFile path="sql/001_init.sql" relativeToChangelogFile="true" splitStatements="false"/>` +
			`</changeSet></databaseChangeLog>`)},
		"sql/001_init.sql": {Data: []byte("CREATE TABLE t (id int);\n")},
	}
	parser, err := importer.ParserByName("liquibase")
	c.Assert(err, qt.IsNil)

	parsed, err := parser.Parse(files)
	c.Assert(err, qt.IsNil)
	declined, err := importer.AccountForSource(files, parser, parsed)

	c.Assert(err, qt.IsNil)
	c.Assert(parsed.Migrations[0].UpSQL, qt.Equals, "CREATE TABLE t (id int);")
	c.Assert(declined, qt.HasLen, 0)
}

// Each refusal names what stopped the conversion. None of them may become a
// migration that quietly lacks something the changelog declared.
func TestLiquibaseTyped_FailurePath(t *testing.T) {
	tests := []struct {
		name    string
		dialect string
		changes string
		message string
	}{
		{
			name:    "an attribute nothing reads",
			dialect: "postgres",
			changes: `<createTable tableName="t" tablespace="fast"><column name="id" type="int"/></createTable>`,
			message: `<createTable> sets tablespace, which Ptah does not convert`,
		},
		{
			name:    "an element nothing reads",
			dialect: "postgres",
			changes: `<createIndex indexName="i" tableName="t"><column name="a"/><where>a &gt; 0</where></createIndex>`,
			message: `<createIndex> contains <where>, which Ptah does not convert`,
		},
		{
			name:    "a property reference in a name",
			dialect: "postgres",
			changes: `<createTable tableName="${prefix}t"><column name="id" type="int"/></createTable>`,
			message: `uses the property reference ${prefix}; Liquibase fills it in when it runs`,
		},
		{
			name:    "a property reference in a type",
			dialect: "postgres",
			changes: `<createTable tableName="t"><column name="id" type="${id_type}"/></createTable>`,
			message: `uses the property reference ${id_type}; Liquibase fills it in when it runs`,
		},
		{
			name:    "two defaults",
			dialect: "postgres",
			changes: `<addColumn tableName="t"><column name="c" type="int" defaultValue="1" defaultValueNumeric="1"/></addColumn>`,
			message: `declares more than one default (defaultValue, defaultValueNumeric)`,
		},
		{
			name:    "a reference without foreignKeyName",
			dialect: "postgres",
			changes: `<createTable tableName="t"><column name="u" type="int"><constraints references="u(id)"/></column></createTable>`,
			message: `references another table without foreignKeyName`,
		},
		{
			name:    "a key declared on an added column",
			dialect: "postgres",
			changes: `<addColumn tableName="t"><column name="c" type="int"><constraints primaryKey="true"/></column></addColumn>`,
			message: `<constraints> sets primaryKey, which Ptah does not convert`,
		},
		{
			name:    "a boolean that is not one",
			dialect: "postgres",
			changes: `<createIndex indexName="i" tableName="t" unique="yes"><column name="a"/></createIndex>`,
			message: `unique "yes" is not true or false`,
		},
		{
			name:    "mismatched foreign key columns",
			dialect: "postgres",
			changes: `<addForeignKeyConstraint constraintName="f" baseTableName="t" baseColumnNames="a,b" ` +
				`referencedTableName="u" referencedColumnNames="id"/>`,
			message: `pairs 2 base column(s) with 1 referenced column(s)`,
		},
		{
			name:    "an unknown referential action",
			dialect: "postgres",
			changes: `<addForeignKeyConstraint constraintName="f" baseTableName="t" baseColumnNames="a" ` +
				`referencedTableName="u" referencedColumnNames="id" onDelete="EXPLODE"/>`,
			message: `onDelete "EXPLODE" is not a referential action`,
		},
		{
			name:    "a change type outside the converted set",
			dialect: "postgres",
			changes: `<loadData tableName="t" file="rows.csv"/>`,
			message: `uses <loadData>, which is not SQL text and which Ptah does not convert`,
		},
		{
			name:    "a sqlFile path that leaves the source directory",
			dialect: "postgres",
			changes: `<sqlFile path="../secret.sql"/>`,
			message: `<sqlFile> names "../secret.sql", which is not a path inside the source directory`,
		},
		{
			name:    "a sqlFile delimiter Ptah does not split on",
			dialect: "postgres",
			changes: `<sqlFile path="a.sql" endDelimiter="/"/>`,
			message: `<sqlFile> sets endDelimiter, which Ptah does not convert`,
		},
		{
			name:    "a rollback that refers to another changeset",
			dialect: "postgres",
			changes: `<sql>SELECT 1;</sql><rollback changeSetId="x" changeSetAuthor="y"/>`,
			message: `<rollback> refers to another changeset's rollback (changeSetId, changeSetAuthor)`,
		},
		{
			// The render reports what the target could not carry, and that
			// refuses the conversion: ClickHouse has no auto-increment.
			name:    "a declaration the target renders without",
			dialect: "clickhouse",
			changes: `<createTable tableName="t"><column name="id" type="bigint" autoIncrement="true">` +
				`<constraints primaryKey="true"/></column></createTable>`,
			message: `clickhouse cannot carry the whole change: column t.id: auto-increment would be skipped`,
		},
		{
			name:    "an index drop naming no table where the target needs one",
			dialect: "mysql",
			changes: `<dropIndex indexName="i" schemaName="app"/>`,
			message: `DROP INDEX app.i names no table, and this target requires one`,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)
			files := liquibaseXMLOneChangeSet(test.changes)
			files["a.sql"] = &fstest.MapFile{Data: []byte("SELECT 1;\n")}

			parsed, err := parseLiquibaseFor(c, test.dialect, files)

			c.Assert(err, qt.IsNotNil)
			c.Assert(err.Error(), qt.Contains, test.message)
			c.Assert(parsed, qt.IsNil)
		})
	}
}

// Without a dialect a typed change has no SQL yet, and the refusal says how to
// give it one. A change type that no dialect converts is named first, with the
// typed changes waiting for a dialect named in the same message, so choosing
// one does not reveal a second refusal.
func TestLiquibaseTyped_WithoutDialect_FailurePath(t *testing.T) {
	tests := []struct {
		name    string
		changes string
		message string
	}{
		{
			name:    "a typed change",
			changes: `<createTable tableName="t"><column name="id" type="int"/></createTable>`,
			message: `uses <createTable>, which is not SQL text; Ptah renders it for one target dialect, so pass --dialect`,
		},
		{
			name:    "a typed change beside one no dialect converts",
			changes: `<loadData tableName="t" file="rows.csv"/><createTable tableName="t"><column name="id" type="int"/></createTable>`,
			message: `uses <loadData>, which is not SQL text and which Ptah does not convert; ` +
				"rewrite it as a `sql` change or import it by hand; <createTable> would also need --dialect",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)
			content := `<databaseChangeLog><changeSet id="1" author="simon">` + test.changes + `</changeSet></databaseChangeLog>`

			err := parseLiquibaseChangelogError(c, "changelog.xml", content)

			c.Assert(err, qt.IsNotNil)
			c.Assert(err.Error(), qt.Contains, test.message)
		})
	}
}

// YAML and JSON refer to another changeset's rollback with a mapping rather than
// attributes, and reach the same refusal.
func TestLiquibaseTyped_DocumentRollbackReference_FailurePath(t *testing.T) {
	c := qt.New(t)
	changelog := `databaseChangeLog:
  - changeSet:
      id: "1"
      author: simon
      changes:
        - sql: {sql: "SELECT 1;"}
      rollback:
        changeSetId: "0"
        changeSetAuthor: simon
`

	parsed, err := parseLiquibaseFor(c, "postgres", fstest.MapFS{"changelog.yaml": {Data: []byte(changelog)}})

	c.Assert(err, qt.IsNotNil)
	c.Assert(err.Error(), qt.Contains, "rollback refers to another changeset's rollback (changeSetId)")
	c.Assert(parsed, qt.IsNil)
}

func TestWithDialect_FailurePath(t *testing.T) {
	c := qt.New(t)
	flyway, err := importer.ParserByName("flyway")
	c.Assert(err, qt.IsNil)
	liquibase, err := importer.ParserByName("liquibase")
	c.Assert(err, qt.IsNil)

	tests := []struct {
		name    string
		parser  importer.Parser
		dialect string
		message string
	}{
		{
			name: "a tool whose migrations are SQL", parser: flyway, dialect: "postgres",
			message: `a target dialect applies only to a Liquibase source; flyway migrations are SQL already`,
		},
		{name: "an unknown dialect", parser: liquibase, dialect: "db2", message: `unsupported dialect "db2"`},
		{
			name: "no parser", parser: nil, dialect: "postgres",
			message: `a target dialect needs a source tool: choose or detect the parser first`,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			got, err := importer.WithDialect(test.parser, test.dialect)

			c.Assert(err, qt.ErrorMatches, test.message)
			c.Assert(got, qt.IsNil)
		})
	}
}

// WithDialect returns a new parser and leaves its argument as it was: the
// parser it was handed still refuses a typed change.
func TestWithDialect_LeavesItsArgumentUnchanged_HappyPath(t *testing.T) {
	c := qt.New(t)
	parser, err := importer.ParserByName("liquibase")
	c.Assert(err, qt.IsNil)
	files := liquibaseXMLOneChangeSet(`<createTable tableName="t"><column name="id" type="int"/></createTable>`)

	rendering, err := importer.WithDialect(parser, "postgres")
	c.Assert(err, qt.IsNil)
	_, renderedErr := rendering.Parse(files)
	_, originalErr := parser.Parse(files)

	c.Assert(renderedErr, qt.IsNil)
	c.Assert(originalErr, qt.ErrorMatches, `(?s).*pass --dialect.*`)
}

// postgresWithoutForeignKeys is the PostgreSQL preset with foreign keys, and
// the key that depends on them, taken out. No release line lacks them; the
// preset exists so a test can see whether the one handed over is the one
// rendered against.
func postgresWithoutForeignKeys() capability.Capabilities {
	caps := capability.ForDialect("postgres").Clone()
	delete(caps, capability.ForeignKeys)
	delete(caps, capability.ForeignKeysRequireUniqueReference)
	return caps
}

// liquibaseForeignKeyChangelog adds one reference, which converts under the
// default PostgreSQL preset (TestLiquibaseTyped_RendersEachChangeType_HappyPath).
func liquibaseForeignKeyChangelog() fstest.MapFS {
	return liquibaseXMLOneChangeSet(`<addForeignKeyConstraint constraintName="f" baseTableName="t" ` +
		`baseColumnNames="a" referencedTableName="u" referencedColumnNames="id"/>`)
}

// The changes are rendered against the preset the caller handed over, not the
// dialect default: the reference that converts under the default is refused
// under a preset without foreign keys.
func TestWithDialectCapabilities_RendersAgainstItsPreset_FailurePath(t *testing.T) {
	c := qt.New(t)
	parser, err := importer.ParserByName("liquibase")
	c.Assert(err, qt.IsNil)
	rendering, err := importer.WithDialectCapabilities(parser, "postgres", postgresWithoutForeignKeys())
	c.Assert(err, qt.IsNil)

	parsed, err := rendering.Parse(liquibaseForeignKeyChangelog())

	c.Assert(err, qt.ErrorMatches, `(?s).*postgres does not support foreign keys.*`)
	c.Assert(parsed, qt.IsNil)
}

// The parser keeps its own copy of the preset. Restoring foreign keys in the
// caller's map afterwards does not reach it, so it still refuses the reference.
func TestWithDialectCapabilities_KeepsItsOwnCopy_FailurePath(t *testing.T) {
	c := qt.New(t)
	caps := postgresWithoutForeignKeys()
	parser, err := importer.ParserByName("liquibase")
	c.Assert(err, qt.IsNil)
	rendering, err := importer.WithDialectCapabilities(parser, "postgres", caps)
	c.Assert(err, qt.IsNil)
	caps[capability.ForeignKeys] = true
	caps[capability.ForeignKeysRequireUniqueReference] = true

	parsed, err := rendering.Parse(liquibaseForeignKeyChangelog())

	c.Assert(err, qt.ErrorMatches, `(?s).*postgres does not support foreign keys.*`)
	c.Assert(parsed, qt.IsNil)
}

// A preset that contradicts itself is refused before anything is parsed.
func TestWithDialectCapabilities_InvalidPreset_FailurePath(t *testing.T) {
	c := qt.New(t)
	caps := capability.ForDialect("postgres").Clone()
	delete(caps, capability.ForeignKeys)
	parser, err := importer.ParserByName("liquibase")
	c.Assert(err, qt.IsNil)

	got, err := importer.WithDialectCapabilities(parser, "postgres", caps)

	c.Assert(err, qt.ErrorMatches, `invalid capabilities for postgres: .*requires "foreign_keys".*`)
	c.Assert(got, qt.IsNil)
}
