package capmatrix

import (
	"fmt"
	"io"
	"slices"
	"strings"
)

// StatusHeader marks the page body as generated.
//
// It is matched literally by scripts/check-capability-status.sh, which is what
// makes the file's provenance checkable rather than conventional: a reader who
// edits the table by hand is refused, and a reader who copies the file
// elsewhere carries the sentence saying where it came from.
const StatusHeader = "<!-- Generated by `capmatrix status`. Do not edit by hand. -->"

// Provenance is where a status file came from. Every field is an input rather
// than something the writer discovers, so the same aggregate and the same
// provenance always render the same bytes -- which is what lets a run that
// measured no change close its pull request instead of opening a new one.
type Provenance struct {
	// Measured is the run's start time, in RFC 3339. The run supplies it; the
	// writer never reads the clock.
	Measured string
	// Commit is the full SHA the matrix probed.
	Commit string
	// RunID is the Actions run that produced the results.
	RunID string
	// RunURL addresses that run. A verdict a reader cannot trace back to the
	// run behind it is an assertion rather than evidence.
	RunURL string
}

// WriteStatus renders one tier's aggregate as the tracked status file.
//
// It is the same measurement WriteAggregate puts in a job summary, in a form
// that survives the run: the summary is one page inside one Actions run, and it
// cannot be cited in a review, diffed against last night, or read by anyone who
// has not gone looking for it.
//
// Every declared line appears. A file listing the cells that reported would
// describe a smaller matrix each time one failed to start, and this repository
// has been bitten by an absent result reading as a passing one more than once.
func WriteStatus(w io.Writer, a Aggregate, p Provenance) {
	verdicts := a.Verdicts()

	// The page is published on the site rather than kept in the repository.
	// A site page linking to a repository document hands the reader a file with
	// no navigation, no version selector and no search, and
	// check-core-doc-links.mjs refuses it for that reason: the link is what
	// makes an unpublished measurement look intentional.
	fmt.Fprintf(w, "---\n")
	fmt.Fprintf(w, "title: Database capability status\n")
	fmt.Fprintf(w, "description: What the capability matrix last measured for every declared database release line.\n")
	fmt.Fprintf(w, "type: status\n")
	fmt.Fprintf(w, "audience:\n  - \"database-engineer\"\n  - \"evaluator\"\n")
	fmt.Fprintf(w, "readerQuestion: \"Did the last capability run pass for the release line I depend on?\"\n")
	fmt.Fprintf(w, "goal: \"Read the verdict the capability matrix last measured for a release line.\"\n")
	fmt.Fprintf(w, "sourceOfTruth:\n  - \"internal/capabilityprobe/cells.go\"\n  - \".github/workflows/capability-matrix.yml\"\n")
	fmt.Fprintf(w, "generated: true\n")
	fmt.Fprintf(w, "generator: internal/cmd/capmatrix\n")
	// What a person edits instead of this page. The verdict comes from a run,
	// so the editable thing is the declaration that decides which lines run at
	// all -- editing the page would be overwritten by the next matrix.
	fmt.Fprintf(w, "editSource: internal/capabilityprobe/cells.go\n")
	fmt.Fprintf(w, "lastVerified: %q\n", measuredDate(p.Measured))
	fmt.Fprintf(w, "evidence:\n  - %q\n", p.RunURL)
	fmt.Fprintf(w, "searchAliases:\n  - database capability status\n  - which database versions pass\n")
	fmt.Fprintf(w, "overlaps:\n  - \"/databases/support-matrix/\"\n  - \"/databases/support-evidence/\"\n")
	fmt.Fprintf(w, "disposition: keep\n")
	fmt.Fprintf(w, "---\n\n")

	fmt.Fprintf(w, "%s\n\n", StatusHeader)
	fmt.Fprintf(w, "What the tier %d capability matrix measured, one row per declared\n"+
		"release line. The matrix runs on every push to master and opens a pull\n"+
		"request when a verdict changes.\n\n", a.Tier)

	fmt.Fprintf(w, "- Measured: %s\n", p.Measured)
	fmt.Fprintf(w, "- Commit: `%s`\n", p.Commit)
	fmt.Fprintf(w, "- Run: [%s](%s)\n", p.RunID, p.RunURL)
	fmt.Fprintf(w, "- Declared release lines: %d. Runnable cells: %d. Results received: %d.\n",
		a.Matrix.Declared, len(a.Matrix.Cells), len(a.Results))
	fmt.Fprintf(w, "- %d passed, %d capability disagreements, %d suite failures, %d missing.\n\n",
		a.Count(Passed), a.Count(CapabilityDisagreement), a.Count(SuiteFailure), a.Count(Missing))

	// No support level here. That is a declaration, and the generated support
	// matrix is the only release-line census that carries it
	// (check-support-matrix.mjs refuses a second page repeating it). This file
	// records what a run measured; the promise and the measurement are
	// different claims and each has one home.
	fmt.Fprintf(w, "| Cell | Engine | Line | Verdict |\n")
	fmt.Fprintf(w, "| --- | --- | --- | --- |\n")
	for _, cell := range verdicts {
		fmt.Fprintf(w, "| `%s` | %s | %s | %s |\n",
			cell.Cell, cell.Dialect, cell.Line, cell.Verdict)
	}

	writeStatusFailures(w, verdicts)
	writeStatusSkipped(w, a)
}

// VerdictOf strips the provenance lines from a rendered status file, leaving
// what the run actually measured.
//
// The three provenance lines change on every run -- a new timestamp, a new
// commit, a new run id -- so a byte comparison reports a change every night and
// the pull request this file is published through would reopen for a verdict
// nobody disagreed with. Comparing the measurement is what makes an unchanged
// matrix silent.
func VerdictOf(rendered string) string {
	var kept []string
	for line := range strings.SplitSeq(rendered, "\n") {
		switch {
		case strings.HasPrefix(line, "- Measured: "),
			strings.HasPrefix(line, "- Commit: "),
			strings.HasPrefix(line, "- Run: "),
			// The frontmatter carries the same stamp in the shape the site
			// wants, so it moves for the same reason and is dropped here too.
			strings.HasPrefix(line, "lastVerified: "),
			strings.HasPrefix(line, `  - "https://github.com/stokaro/ptah/actions/runs/`):
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}

func writeStatusFailures(w io.Writer, verdicts []CellVerdict) {
	failed := slices.DeleteFunc(slices.Clone(verdicts), func(cell CellVerdict) bool {
		return cell.Verdict == Passed
	})
	if len(failed) == 0 {
		return
	}
	fmt.Fprintf(w, "\n## Why each cell failed\n\n")
	for _, cell := range failed {
		fmt.Fprintf(w, "- **%s** (%s %s) — %s\n", cell.Cell, cell.Dialect, cell.Line, cell.Verdict)
		for _, reason := range cell.Reasons {
			fmt.Fprintf(w, "  - %s\n", strings.TrimSpace(reason))
		}
	}
}

// writeStatusSkipped names the declared lines no tier can execute.
//
// They are the half a table of results would silently drop: the census identity
// is declared == runnable + skipped, and a file carrying only the runnable half
// reports a smaller matrix than the repository declares.
func writeStatusSkipped(w io.Writer, a Aggregate) {
	if len(a.Matrix.Skipped) == 0 {
		return
	}
	fmt.Fprintf(w, "\n## Declared lines this tier cannot run\n\n")
	for _, cell := range a.Matrix.Skipped {
		fmt.Fprintf(w, "- `%s` (%s %s) — %s\n", cell.ID, cell.Dialect, cell.Line, cell.Skip)
	}
}

// measuredDate takes the calendar day out of an RFC 3339 stamp for the page's
// lastVerified field, which the site's frontmatter contract wants as a date.
//
// A stamp that does not parse is passed through rather than replaced by today:
// the page would then claim a freshness nothing measured.
func measuredDate(measured string) string {
	if len(measured) >= len("2006-01-02") {
		return measured[:len("2006-01-02")]
	}
	return measured
}
