package graphqlrender

import (
	"strconv"
	"strings"
)

const (
	pageInfoType = "PageInfo"
	queryType    = "Query"
)

// gqlField is one field of a GraphQL object or input type.
type gqlField struct {
	name        string
	args        string // pre-rendered argument list, e.g. "(id: ID!)"; empty for none
	typ         string // named type (scalar, enum or object)
	nonNull     bool   // the field type is non-null (Type!)
	list        bool   // the field is a list ([Type])
	listNonNull bool   // list elements are non-null ([Type!])
	desc        string
}

// gqlType is a GraphQL object or input type.
type gqlType struct {
	name   string
	desc   string
	fields []gqlField
}

// gqlEnum is a GraphQL enum type.
type gqlEnum struct {
	name   string
	values []string
}

// render serializes the accumulated model to SDL in a fixed, deterministic
// order: custom scalars, enums, the shared PageInfo type, the Query root, then
// per table the object, input, edge and connection types.
func (b *builder) render() string {
	withConnections := len(b.connTypes) > 0
	var sb strings.Builder
	sb.WriteString("# Code generated by ptah; DO NOT EDIT.\n\n")

	for _, scalar := range sortedKeys(b.customScalars) {
		sb.WriteString("scalar " + scalar + "\n")
	}
	if len(b.customScalars) > 0 {
		sb.WriteString("\n")
	}

	for _, enum := range b.enumTypes {
		sb.WriteString("enum " + enum.name + " {\n")
		for _, value := range enum.values {
			sb.WriteString("  " + value + "\n")
		}
		sb.WriteString("}\n\n")
	}

	if withConnections {
		writePageInfo(&sb)
	}

	// A GraphQL schema must have a Query root type; emit a placeholder when there
	// is nothing to expose so the output still builds.
	if len(b.queryFields) > 0 {
		writeType(&sb, "type", gqlType{name: queryType, fields: b.queryFields})
	} else {
		sb.WriteString("type " + queryType + " {\n  _empty: Boolean\n}\n\n")
	}

	for _, object := range b.objectTypes {
		writeType(&sb, "type", object)
	}
	for _, input := range b.inputTypes {
		writeType(&sb, "input", input)
	}
	for _, edge := range b.edgeTypes {
		writeType(&sb, "type", edge)
	}
	for _, conn := range b.connTypes {
		writeType(&sb, "type", conn)
	}

	return strings.TrimRight(sb.String(), "\n") + "\n"
}

func writeType(sb *strings.Builder, keyword string, t gqlType) {
	writeDescription(sb, "", t.desc)
	sb.WriteString(keyword + " " + t.name + " {\n")
	for _, field := range t.fields {
		writeDescription(sb, "  ", field.desc)
		sb.WriteString("  " + field.name + field.args + ": " + field.typeRef() + "\n")
	}
	sb.WriteString("}\n\n")
}

// typeRef renders a field's type reference, e.g. "String", "Int!", "[UserEdge!]!".
func (f gqlField) typeRef() string {
	inner := f.typ
	if f.list {
		if f.listNonNull {
			inner += "!"
		}
		inner = "[" + inner + "]"
	}
	if f.nonNull {
		inner += "!"
	}
	return inner
}

func writePageInfo(sb *strings.Builder) {
	sb.WriteString("type " + pageInfoType + " {\n")
	sb.WriteString("  hasNextPage: Boolean!\n")
	sb.WriteString("  hasPreviousPage: Boolean!\n")
	sb.WriteString("  startCursor: String\n")
	sb.WriteString("  endCursor: String\n")
	sb.WriteString("}\n\n")
}

// writeDescription writes a GraphQL description line for a definition, if any.
func writeDescription(sb *strings.Builder, indent, desc string) {
	desc = strings.TrimSpace(desc)
	if desc == "" {
		return
	}
	sb.WriteString(indent + gqlStringLiteral(desc) + "\n")
}

// gqlStringLiteral renders s as a valid single-line GraphQL string literal.
func gqlStringLiteral(s string) string {
	s = strings.ReplaceAll(s, "\\", `\\`)
	s = strings.ReplaceAll(s, "\"", `\"`)
	s = strings.NewReplacer("\n", " ", "\r", " ", "\t", " ").Replace(s)
	return `"` + s + `"`
}

// nameRegistry assigns unique GraphQL type names, disambiguating collisions with
// a numeric suffix so the emitted schema has no duplicate definitions.
type nameRegistry struct {
	used map[string]bool
}

func newNameRegistry() *nameRegistry {
	return &nameRegistry{used: map[string]bool{}}
}

func (r *nameRegistry) reserve(name string) {
	r.used[name] = true
}

func (r *nameRegistry) unique(desired string) string {
	if desired == "" {
		desired = "Type"
	}
	if !r.used[desired] {
		r.used[desired] = true
		return desired
	}
	for i := 2; ; i++ {
		candidate := desired + strconv.Itoa(i)
		if !r.used[candidate] {
			r.used[candidate] = true
			return candidate
		}
	}
}
