package graphqlrender

import (
	"strconv"
	"strings"
)

const (
	pageInfoType = "PageInfo"
	queryType    = "Query"

	createInputSuffix = "CreateInput"
	updateInputSuffix = "UpdateInput"
)

// operationNotice heads an export that carries operation shapes. It states what
// the shapes are not, because SDL alone cannot say it and a reader meeting a
// Query root reasonably assumes something answers it.
const operationNotice = "# Operation shapes below were generated on request. They are type declarations\n" +
	"# only: Ptah generates no resolvers, no data access, no authorization or tenant\n" +
	"# isolation, and no filtering, ordering, pagination, or transaction behavior.\n\n"

// gqlField is one field of a GraphQL object or input type.
type gqlField struct {
	name        string
	args        string // pre-rendered argument list, e.g. "(id: ID!)"; empty for none
	typ         string // named type (scalar, enum or object)
	nonNull     bool   // the field type is non-null (Type!)
	list        bool   // the field is a list ([Type])
	listNonNull bool   // list elements are non-null ([Type!])
	desc        string
}

// gqlType is a GraphQL object or input type.
type gqlType struct {
	name   string
	desc   string
	fields []gqlField
}

// gqlEnum is a GraphQL enum type.
type gqlEnum struct {
	name   string
	values []string
}

// render serializes the accumulated model to SDL in a fixed, deterministic
// order: custom scalars, enums, the shared PageInfo type, the Query root, then
// the object types followed by the create inputs, update inputs, edge and
// connection types.
//
// Everything from PageInfo through the connection types is an operation shape
// and appears only when it was selected. A types-only export therefore declares
// no root operation type at all: SDL without a Query is a type-system document
// meant to be composed, which is what an export that generates no resolvers is.
func (b *builder) render() string {
	var sb strings.Builder
	sb.WriteString("# Code generated by ptah; DO NOT EDIT.\n\n")
	if b.ops.Any() {
		sb.WriteString(operationNotice)
	}

	for _, scalar := range sortedKeys(b.customScalars) {
		sb.WriteString("scalar " + scalar + "\n")
	}
	if len(b.customScalars) > 0 {
		sb.WriteString("\n")
	}

	for _, enum := range b.enumTypes {
		sb.WriteString("enum " + enum.name + " {\n")
		for _, value := range enum.values {
			sb.WriteString("  " + value + "\n")
		}
		sb.WriteString("}\n\n")
	}

	if len(b.connTypes) > 0 {
		writePageInfo(&sb)
	}

	// A schema that declares a Query root must declare a non-empty one, so a
	// selection that produced no query field still gets a placeholder rather
	// than an unparsable "type Query {}".
	if b.ops.Queries() {
		if len(b.queryFields) > 0 {
			writeType(&sb, "type", gqlType{name: queryType, fields: b.queryFields})
		} else {
			sb.WriteString("type " + queryType + " {\n  _empty: Boolean\n}\n\n")
		}
	}

	for _, object := range b.objectTypes {
		writeType(&sb, "type", object)
	}
	for _, input := range b.createInputs {
		writeType(&sb, "input", input)
	}
	for _, input := range b.updateInputs {
		writeType(&sb, "input", input)
	}
	for _, edge := range b.edgeTypes {
		writeType(&sb, "type", edge)
	}
	for _, conn := range b.connTypes {
		writeType(&sb, "type", conn)
	}

	return strings.TrimRight(sb.String(), "\n") + "\n"
}

func writeType(sb *strings.Builder, keyword string, t gqlType) {
	writeDescription(sb, "", t.desc)
	sb.WriteString(keyword + " " + t.name + " {\n")
	for _, field := range t.fields {
		writeDescription(sb, "  ", field.desc)
		sb.WriteString("  " + field.name + field.args + ": " + field.typeRef() + "\n")
	}
	sb.WriteString("}\n\n")
}

// typeRef renders a field's type reference, e.g. "String", "Int!", "[UserEdge!]!".
func (f gqlField) typeRef() string {
	inner := f.typ
	if f.list {
		if f.listNonNull {
			inner += "!"
		}
		inner = "[" + inner + "]"
	}
	if f.nonNull {
		inner += "!"
	}
	return inner
}

func writePageInfo(sb *strings.Builder) {
	sb.WriteString("type " + pageInfoType + " {\n")
	sb.WriteString("  hasNextPage: Boolean!\n")
	sb.WriteString("  hasPreviousPage: Boolean!\n")
	sb.WriteString("  startCursor: String\n")
	sb.WriteString("  endCursor: String\n")
	sb.WriteString("}\n\n")
}

// writeDescription writes a GraphQL description line for a definition, if any.
func writeDescription(sb *strings.Builder, indent, desc string) {
	desc = strings.TrimSpace(desc)
	if desc == "" {
		return
	}
	sb.WriteString(indent + gqlStringLiteral(desc) + "\n")
}

// gqlStringLiteral renders s as a valid single-line GraphQL string literal.
func gqlStringLiteral(s string) string {
	s = strings.ReplaceAll(s, "\\", `\\`)
	s = strings.ReplaceAll(s, "\"", `\"`)
	s = strings.NewReplacer("\n", " ", "\r", " ", "\t", " ").Replace(s)
	return `"` + s + `"`
}

// nameOwnership records whether a GraphQL name was derived from persistence or
// declared as part of the published contract. Keep this as an explicit enum:
// callers must state which collision policy they are requesting rather than
// passing an unexplained boolean control flag.
type nameOwnership uint8

const (
	derivedName nameOwnership = iota
	authoredName
)

// nameRegistry assigns unique GraphQL type names and records whether the name
// came from authored API metadata. Derived-only collisions keep the historical
// numeric suffix; a collision involving an authored contract name is refused
// by claim so the exporter cannot silently publish a different declaration.
type nameRegistry struct {
	owners map[string]nameOwnership
}

func newNameRegistry() *nameRegistry {
	return &nameRegistry{owners: make(map[string]nameOwnership)}
}

func (r *nameRegistry) reserve(name string) {
	r.owners[name] = derivedName
}

// claim assigns desired, preserving the historical numeric suffix only when
// both sides are derived from persistence names. The second result reports a
// collision that involves authored API metadata.
func (r *nameRegistry) claim(desired string, ownership nameOwnership) (string, bool) {
	if desired == "" {
		desired = "Type"
	}
	firstOwnership, taken := r.owners[desired]
	if !taken {
		r.owners[desired] = ownership
		return desired, false
	}
	if ownership == authoredName || firstOwnership == authoredName {
		return "", true
	}
	return r.uniqueOwned(desired, derivedName), false
}

func (r *nameRegistry) uniqueOwned(desired string, ownership nameOwnership) string {
	if desired == "" {
		desired = "Type"
	}
	if _, used := r.owners[desired]; !used {
		r.owners[desired] = ownership
		return desired
	}
	for i := 2; ; i++ {
		candidate := desired + strconv.Itoa(i)
		if _, used := r.owners[candidate]; !used {
			r.owners[candidate] = ownership
			return candidate
		}
	}
}
