package sqlschema_test

import (
	"testing"

	qt "github.com/frankban/quicktest"

	"ptah.run/core/platform"
	"ptah.run/internal/sqlschema"
)

func TestReadPostgresIdentityNullability(t *testing.T) {
	tests := []struct {
		name, declaration string
		nullable          bool
	}{
		{name: "always", declaration: "bigint GENERATED ALWAYS AS IDENTITY"},
		{name: "default", declaration: "bigint GENERATED BY DEFAULT AS IDENTITY"},
		{name: "explicit", declaration: "bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"},
		{name: "ordinary nullable column", declaration: "bigint", nullable: true},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)
			db, _, err := sqlschema.Read([]byte("CREATE TABLE events (seq "+test.declaration+");"), platform.Postgres)
			c.Assert(err, qt.IsNil)
			c.Assert(db.Fields, qt.HasLen, 1)
			c.Assert(db.Fields[0].Nullable, qt.Equals, test.nullable)
		})
	}
}
