// Code generated by ptah introspect; DO NOT EDIT.

package models

//migrator:schema:table name="comments"
type Comments struct {
	//migrator:schema:field name="id" type="INTEGER" not_null="true" primary="true" auto_increment="true"
	Id int
	//migrator:schema:field name="task_id" type="INTEGER" not_null="true" foreign="tasks(id)" foreign_key_name="fk_comments_task_id" on_delete="CASCADE" on_update="NO ACTION"
	TaskId int
	//migrator:schema:field name="author_id" type="INTEGER" not_null="true" foreign="users(id)" foreign_key_name="fk_comments_author_id" on_delete="RESTRICT" on_update="NO ACTION"
	AuthorId int
	//migrator:schema:field name="body" type="TEXT" not_null="true"
	Body string
	//migrator:schema:field name="created_at" type="TEXT" not_null="true" default_expr="CURRENT_TIMESTAMP"
	CreatedAt string
	//migrator:schema:index name="idx_comments_task" fields="task_id" table="comments"
	_ struct{}
}

//migrator:schema:table name="organizations"
type Organizations struct {
	//migrator:schema:field name="id" type="INTEGER" not_null="true" primary="true" auto_increment="true"
	Id int
	//migrator:schema:field name="name" type="TEXT" not_null="true" unique="true"
	Name string
	//migrator:schema:field name="slug" type="TEXT" not_null="true" unique="true"
	Slug string
}

//migrator:schema:constraint name="sqlite_autoindex_projects_1" type="UNIQUE" table="projects" columns="organization_id,key"
//migrator:schema:table name="projects"
type Projects struct {
	//migrator:schema:field name="id" type="INTEGER" not_null="true" primary="true" auto_increment="true"
	Id int
	//migrator:schema:field name="organization_id" type="INTEGER" not_null="true" foreign="organizations(id)" foreign_key_name="fk_projects_organization_id" on_delete="CASCADE" on_update="NO ACTION"
	OrganizationId int
	//migrator:schema:field name="owner_id" type="INTEGER" not_null="true" foreign="users(id)" foreign_key_name="fk_projects_owner_id" on_delete="RESTRICT" on_update="NO ACTION"
	OwnerId int
	//migrator:schema:field name="key" type="TEXT" not_null="true"
	Key string
	//migrator:schema:field name="name" type="TEXT" not_null="true"
	Name string
	//migrator:schema:index name="idx_projects_owner" fields="owner_id" table="projects"
	_ struct{}
}

//migrator:schema:constraint name="sqlite_autoindex_tags_1" type="UNIQUE" table="tags" columns="organization_id,name"
//migrator:schema:table name="tags"
type Tags struct {
	//migrator:schema:field name="id" type="INTEGER" not_null="true" primary="true" auto_increment="true"
	Id int
	//migrator:schema:field name="organization_id" type="INTEGER" not_null="true" foreign="organizations(id)" foreign_key_name="fk_tags_organization_id" on_delete="CASCADE" on_update="NO ACTION"
	OrganizationId int
	//migrator:schema:field name="name" type="TEXT" not_null="true"
	Name string
}

//migrator:schema:table name="task_tags" primary_key="task_id,tag_id"
type TaskTags struct {
	//migrator:schema:field name="task_id" type="INTEGER" not_null="true" foreign="tasks(id)" foreign_key_name="fk_task_tags_task_id" on_delete="CASCADE" on_update="NO ACTION"
	TaskId int
	//migrator:schema:field name="tag_id" type="INTEGER" not_null="true" foreign="tags(id)" foreign_key_name="fk_task_tags_tag_id" on_delete="CASCADE" on_update="NO ACTION"
	TagId int
	//migrator:schema:field name="tagged_by" type="INTEGER" not_null="true" foreign="users(id)" foreign_key_name="fk_task_tags_tagged_by" on_delete="RESTRICT" on_update="NO ACTION"
	TaggedBy int
}

//migrator:schema:constraint name="tasks_status_check" type="CHECK" table="tasks" check="status IN ('open', 'blocked', 'done')"
//migrator:schema:table name="tasks"
type Tasks struct {
	//migrator:schema:field name="id" type="INTEGER" not_null="true" primary="true" auto_increment="true"
	Id int
	//migrator:schema:field name="project_id" type="INTEGER" not_null="true" foreign="projects(id)" foreign_key_name="fk_tasks_project_id" on_delete="CASCADE" on_update="NO ACTION"
	ProjectId int
	//migrator:schema:field name="assignee_id" type="INTEGER" foreign="users(id)" foreign_key_name="fk_tasks_assignee_id" on_delete="SET NULL" on_update="NO ACTION"
	AssigneeId *int
	//migrator:schema:field name="reporter_id" type="INTEGER" not_null="true" foreign="users(id)" foreign_key_name="fk_tasks_reporter_id" on_delete="RESTRICT" on_update="NO ACTION"
	ReporterId int
	//migrator:schema:field name="parent_task_id" type="INTEGER" foreign="tasks(id)" foreign_key_name="fk_tasks_parent_task_id" on_delete="CASCADE" on_update="NO ACTION"
	ParentTaskId *int
	//migrator:schema:field name="title" type="TEXT" not_null="true"
	Title string
	//migrator:schema:field name="status" type="TEXT" not_null="true" default="'open'"
	Status string
	//migrator:schema:index name="idx_tasks_assignee" fields="assignee_id" table="tasks"
	_ struct{}
	//migrator:schema:index name="idx_tasks_project" fields="project_id" table="tasks"
	_ struct{}
}

//migrator:schema:table name="users"
type Users struct {
	//migrator:schema:field name="id" type="INTEGER" not_null="true" primary="true" auto_increment="true"
	Id int
	//migrator:schema:field name="organization_id" type="INTEGER" not_null="true" foreign="organizations(id)" foreign_key_name="fk_users_organization_id" on_delete="CASCADE" on_update="NO ACTION"
	OrganizationId int
	//migrator:schema:field name="email" type="TEXT" not_null="true" unique="true"
	Email string
	//migrator:schema:field name="display_name" type="TEXT" not_null="true"
	DisplayName string
	//migrator:schema:field name="manager_id" type="INTEGER" foreign="users(id)" foreign_key_name="fk_users_manager_id" on_delete="SET NULL" on_update="NO ACTION"
	ManagerId *int
	//migrator:schema:index name="idx_users_organization" fields="organization_id" table="users"
	_ struct{}
}
