package featureinventory_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"

	"go.5x5.cz/ptah/internal/featureinventory"
)

// TestCommandReference_TheGeneratedBlockMatchesTheTrees is check 5.
//
// The gate is scripts/check-command-reference.sh, and
// `scripts/check-command-reference.sh --write` regenerates the block.
func TestCommandReference_TheGeneratedBlockMatchesTheTrees(t *testing.T) {
	c := qt.New(t)
	census := shippedCensus(c)

	findings := featureinventory.CheckCommandReference(census, commandReferenceBody(c))
	c.Assert(messages(findings), qt.HasLen, 0)
}

// TestCommandReference_TheBlockIsTheWholeSurface is the control that separates
// this generated block from the one already in the tree.
//
// docs/agent-surface.md is generated by a walk over the constructed root, so its
// block holds 86 rows against 91 leaves and never mentions `completion`. A new
// generated reference built the same way would render 86 of 91 and check clean
// against itself, which is the shape AGENTS.md names: a walk over a hand-written
// list is the hand-written list it exists to guard.
func TestCommandReference_TheBlockIsTheWholeSurface(t *testing.T) {
	c := qt.New(t)
	census := shippedCensus(c)
	block := census.ReferenceBlock()
	rows := strings.Count(block, "\n") - 2 // the heading and the delimiter

	c.Assert(rows, qt.Equals, 156)
	c.Assert(block, qt.Contains, "| `ptah completion zsh` |")
	c.Assert(block, qt.Contains, "| `ptah help` |")
	c.Assert(block, qt.Contains, "| `ptah-compat help` |")
	// The namespace the hand-written reference page does not mention at all.
	c.Assert(block, qt.Contains, "| `ptah inference` |")
	// One row of each strict-mode answer, so a column that stopped varying is a
	// failure rather than a uniform table nobody reads.
	c.Assert(block, qt.Contains, "| `ptah-compat migrate apply` | `ptah-compat` | verb | registered |")
	c.Assert(block, qt.Contains, "| `ptah-compat migrate ls` | `ptah-compat` | verb | not registered |")
	c.Assert(block, qt.Contains, "| `ptah-compat schema plan` | `ptah-compat` | group | gated |")
}

// TestCommandReference_TheMarkersAreUniqueToTheDocument keeps a second copy of
// the block from going stale unchecked.
//
// The marker is what the gate finds the block by. A second file carrying it
// would be regenerated by nothing and checked by nothing, which is how a table
// that was correct once goes on being read years later.
func TestCommandReference_TheMarkersAreUniqueToTheDocument(t *testing.T) {
	c := qt.New(t)
	carriers := documentsContaining(c, featureinventory.ReferenceBegin)
	c.Assert(carriers, qt.DeepEquals, []string{featureinventory.CommandReferencePath})
}

// TestCommandReferenceSelftest_NoticesAStaleBlock plants each way the block can
// drift.
func TestCommandReferenceSelftest_NoticesAStaleBlock(t *testing.T) {
	tests := []struct {
		name   string
		mutate func(string) string
		want   string
	}{
		{
			name:   "a row deleted",
			mutate: func(block string) string { return removeRow(block, "| `ptah schema render` |") },
			want:   "missing a row the trees produce",
		},
		{
			name: "a row for a command no tree has",
			mutate: func(block string) string {
				return block + "| `ptah schema generate` | `ptah` | verb | not applicable | invented |\n"
			},
			want: "carries a row no tree produces",
		},
		{
			name:   "a strict-mode answer edited",
			mutate: func(block string) string { return strings.Replace(block, "| gated |", "| registered |", 1) },
			want:   "the generated command reference",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)
			census := fixtureCensus(c)
			block := census.ReferenceBlock()
			mutated := test.mutate(block)
			// Assert the mutation landed, not that the gate exited non-zero. A
			// replacement whose pattern matched nothing leaves the block intact,
			// and an intact block is what a passing run looks like.
			c.Assert(mutated, qt.Not(qt.Equals), block)
			body := featureinventory.ReferenceBegin + "\n" + mutated + featureinventory.ReferenceEnd + "\n"
			findings := featureinventory.CheckCommandReference(census, body)
			c.Assert(len(findings) > 0, qt.IsTrue)
			c.Assert(strings.Join(messages(findings), "\n"), qt.Contains, test.want)
		})
	}
}

// TestCommandReferenceSelftest_RefusesADocumentWithNoMarkers is the emptiness
// rule, and it is the reason this gate can be trusted at all.
//
// A document whose markers were renamed or lost in a merge would yield an empty
// block on both sides; the comparison would find them identical and report
// success at exactly the moment it stopped working. check-agent-surface.sh
// states the same rule in its own header, and a new generated block needs it
// just as much.
func TestCommandReferenceSelftest_RefusesADocumentWithNoMarkers(t *testing.T) {
	tests := []struct {
		name string
		body string
		want string
	}{
		{
			name: "no begin marker",
			body: "# Feature inventory\n\nA table with no markers around it.\n",
			want: "carries no <!-- BEGIN GENERATED COMMAND REFERENCE --> marker",
		},
		{
			name: "no end marker",
			body: featureinventory.ReferenceBegin + "\n| a | b |\n",
			want: "carries no <!-- END GENERATED COMMAND REFERENCE --> marker",
		},
		{
			name: "markers around nothing",
			body: featureinventory.ReferenceBegin + "\n" + featureinventory.ReferenceEnd + "\n",
			want: "the generated block in docs/command-reference.md is empty",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)
			findings := featureinventory.CheckCommandReference(fixtureCensus(c), test.body)
			c.Assert(messages(findings), qt.HasLen, 1)
			c.Assert(findings[0].Message, qt.Contains, test.want)
		})
	}
}

// TestCommandReferenceSelftest_TheWriteModeRewritesTheBlock drives the repair
// the gate tells a contributor to run, and requires the gate to accept what it
// produced.
//
// It always writes. With no target named it writes a copy of the committed
// document in a temporary directory, so the write path is exercised on every
// `go test ./...`; `scripts/check-command-reference.sh --write` names the real
// file and the same code runs. A write mode reachable only from the shell is a
// repair nobody has watched work.
func TestCommandReferenceSelftest_TheWriteModeRewritesTheBlock(t *testing.T) {
	c := qt.New(t)
	census := shippedCensus(c)
	target := writeTarget(c)

	before, err := os.ReadFile(target)
	c.Assert(err, qt.IsNil)

	rewritten, err := featureinventory.ReplaceBlock(string(before), census.ReferenceBlock())
	c.Assert(err, qt.IsNil)
	// #nosec G703 -- target is either a file inside this test's own TempDir or
	// the path scripts/check-command-reference.sh --write names, which is the
	// committed document this gate exists to regenerate.
	c.Assert(os.WriteFile(target, []byte(rewritten), 0o600), qt.IsNil)

	after, err := os.ReadFile(target)
	c.Assert(err, qt.IsNil)
	c.Assert(featureinventory.CheckCommandReference(census, string(after)), qt.HasLen, 0)

	// The prose around the block survives the rewrite. A write mode that
	// replaced the whole document would pass the check above and delete the
	// page.
	c.Assert(string(after), qt.Contains, "## What the strict-mode column says")
}

// TestCommandReferenceSelftest_TheWriteModeRepairsAStaleBlock is the same path
// starting from a block that does not match, so the round trip is proved to
// change something rather than to have been correct already.
func TestCommandReferenceSelftest_TheWriteModeRepairsAStaleBlock(t *testing.T) {
	c := qt.New(t)
	census := fixtureCensus(c)

	stale := featureinventory.ReferenceBegin + "\nnothing like the tree\n" + featureinventory.ReferenceEnd + "\n"
	c.Assert(len(featureinventory.CheckCommandReference(census, stale)) > 0, qt.IsTrue)

	repaired, err := featureinventory.ReplaceBlock(stale, census.ReferenceBlock())
	c.Assert(err, qt.IsNil)
	c.Assert(repaired, qt.Not(qt.Equals), stale)
	c.Assert(featureinventory.CheckCommandReference(census, repaired), qt.HasLen, 0)
}

// removeRow deletes the first row whose prefix matches.
func removeRow(block, prefix string) string {
	kept := make([]string, 0, 8)
	dropped := false
	for line := range strings.SplitSeq(block, "\n") {
		if !dropped && strings.HasPrefix(line, prefix) {
			dropped = true
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}

// documentsContaining lists the tracked documents holding a marker.
func documentsContaining(c *qt.C, marker string) []string {
	c.Helper()
	root := repoRoot(c)
	docs, err := featureinventory.DocFiles(root)
	c.Assert(err, qt.IsNil)

	var carriers []string
	for _, doc := range docs {
		body, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(doc)))
		c.Assert(err, qt.IsNil)
		if strings.Contains(string(body), marker) {
			carriers = append(carriers, doc)
		}
	}
	return carriers
}
