package featureinventory_test

import (
	"sort"
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"
	"github.com/spf13/cobra"

	"go.5x5.cz/ptah/internal/featureinventory"
)

// TestCommandCensus_SeesTheTreeTheBinaryShips pins the size of each shipped
// tree.
//
// The numbers are here rather than derived, because the whole point of this
// package is that the previous census was short and nothing said so. The Phase 1
// audit walked `cmd.Commands()` on a constructed root and reported 85 native and
// 46 compatibility paths; the binaries answer 103 and 53. Six paths per binary
// are added by the initializers ExecuteC runs, and the native tree has since
// grown the `inference` namespace, which is eleven more.
//
// docs/agent-surface.md is generated by that same constructed-tree walk and is
// gated in CI. Its generated block holds 86 rows against 91 leaves, and the word
// `completion` appears in it zero times. A check built on the same walk would
// inherit the same blind spot and pass.
func TestCommandCensus_SeesTheTreeTheBinaryShips(t *testing.T) {
	tests := []struct {
		name    string
		tree    featureinventory.Tree
		paths   int
		visible int
		leaves  int
	}{
		{name: "native", tree: featureinventory.TreeNative, paths: 103, visible: 103, leaves: 91},
		{name: "compatibility", tree: featureinventory.TreeCompat, paths: 53, visible: 53, leaves: 46},
		{name: "compatibility, strict", tree: featureinventory.TreeCompatStrict, paths: 37, visible: 25, leaves: 33},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)
			census := shippedCensus(c)
			commands := census.OfTree(test.tree)
			leaves := countLeaves(commands)
			c.Assert(commands, qt.HasLen, test.paths)
			c.Assert(census.VisiblePaths(test.tree), qt.HasLen, test.visible)
			c.Assert(leaves, qt.Equals, test.leaves)

			// The five paths the audit's walk could not see, asserted by name.
			// A count alone would still pass if the census lost these and
			// gained five elsewhere.
			for _, path := range []string{"completion", "completion bash", "completion fish", "completion powershell", "completion zsh", "help"} {
				_, found := census.Lookup(test.tree, path)
				c.Assert(found, qt.IsTrue, qt.Commentf("the %s tree ships `%s` and the census did not find it", test.tree, path))
			}
		})
	}
}

// TestCommandCensus_TheConstructedTreeIsShortAndThisOneIsNot measures both
// numbers, which is the only way to show which of the two answers this package
// gives.
//
// A census that walked the constructed root would report 97 and 52. Asserting
// only the 103 would leave the claim "and the other method would have been
// wrong" unmeasured, so both are taken here, from the same roots, one walk
// apart.
func TestCommandCensus_TheConstructedTreeIsShortAndThisOneIsNot(t *testing.T) {
	tests := []struct {
		name        string
		tree        featureinventory.Tree
		constructed int
		shipped     int
		// missing is what the constructed walk cannot see. It differs between
		// the two binaries, and the difference is the reason a check must not
		// simply exempt `completion` and `help` by name: cmd/atlas calls
		// InitDefaultCompletionCmd at construction, so its constructed tree is
		// short by `help` alone.
		missing []string
	}{
		{
			name:        "native",
			tree:        featureinventory.TreeNative,
			constructed: 97,
			shipped:     103,
			missing:     []string{"completion", "completion bash", "completion fish", "completion powershell", "completion zsh", "help"},
		},
		{
			name:        "compatibility",
			tree:        featureinventory.TreeCompat,
			constructed: 52,
			shipped:     53,
			missing:     []string{"help"},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)

			constructed := constructedPaths(shippedRoots()[test.tree])
			c.Assert(constructed, qt.HasLen, test.constructed)

			shipped := featureinventory.Walk(test.tree, shippedRoots()[test.tree])
			c.Assert(shipped, qt.HasLen, test.shipped)

			c.Assert(missingFrom(constructed, shipped), qt.DeepEquals, test.missing)
		})
	}
}

// TestCommandCensus_CobraStillRegistersWhatThisPackageAssumes drives the
// measurement that replaces a hand-written exemption.
//
// The alternative was two literal strings -- `completion` and `help` -- with a
// note that cobra adds them. This runs cobra twice on a throwaway command
// instead and compares the answers, so an initializer added upstream fails here
// rather than silently shortening every census below it.
func TestCommandCensus_CobraStillRegistersWhatThisPackageAssumes(t *testing.T) {
	c := qt.New(t)
	c.Assert(featureinventory.AssertCobraInitializerParity(), qt.IsNil)
}

// TestCommandCensus_RefusesAnEmptyTree is the control on every gate below.
//
// A census assembled from no roots would compare every document against nothing
// and find nothing wrong with any of them.
func TestCommandCensus_RefusesAnEmptyTree(t *testing.T) {
	t.Run("no trees at all", func(t *testing.T) {
		c := qt.New(t)
		census, err := featureinventory.NewCensus(make(map[featureinventory.Tree]*cobra.Command))
		c.Assert(err, qt.ErrorMatches, ".*no command trees to census.*")
		c.Assert(census, qt.IsNil)
	})
}

// TestCommandCensus_StrictModeRemovesPathsInTwoDistinguishableWays records what
// the strict profile does to the compatibility tree.
//
// The inventory needs this as a column rather than a footnote: 53 paths become
// 25, and the 28 that go do not go the same way. Sixteen are not registered at
// all, and twelve stay registered and hidden precisely so that invoking one
// produces a named abort instead of `unknown command`.
func TestCommandCensus_StrictModeRemovesPathsInTwoDistinguishableWays(t *testing.T) {
	c := qt.New(t)
	census := shippedCensus(c)

	counts := make(map[featureinventory.StrictPresence]int)
	for _, cmd := range census.OfTree(featureinventory.TreeCompat) {
		counts[census.StrictOf(cmd)]++
	}

	c.Assert(counts[featureinventory.StrictRegistered], qt.Equals, 25)
	c.Assert(counts[featureinventory.StrictGated], qt.Equals, 12)
	c.Assert(counts[featureinventory.StrictAbsent], qt.Equals, 16)
	c.Assert(counts[featureinventory.StrictGated]+counts[featureinventory.StrictAbsent], qt.Equals, 28)

	// One of each, by name, so a count that stayed right while the
	// classification moved is still a failure.
	gated, found := census.Lookup(featureinventory.TreeCompat, "schema plan")
	c.Assert(found, qt.IsTrue)
	c.Assert(census.StrictOf(gated), qt.Equals, featureinventory.StrictGated)

	absent, found := census.Lookup(featureinventory.TreeCompat, "migrate ls")
	c.Assert(found, qt.IsTrue)
	c.Assert(census.StrictOf(absent), qt.Equals, featureinventory.StrictAbsent)

	kept, found := census.Lookup(featureinventory.TreeCompat, "migrate apply")
	c.Assert(found, qt.IsTrue)
	c.Assert(census.StrictOf(kept), qt.Equals, featureinventory.StrictRegistered)
}

// TestCommandCensus_HiddenFlagsAreMeasuredRatherThanListed pins the flag census.
//
// Hidden flags decide both directions of the flag coverage rule, so the set has
// to come from pflag's own bit. Measured: four distinct names across eight
// registrations, and three native commands carry the same pair rather than one
// command carrying four.
func TestCommandCensus_HiddenFlagsAreMeasuredRatherThanListed(t *testing.T) {
	c := qt.New(t)
	census := shippedCensus(c)

	registrations, hidden := hiddenFlagRegistrations(census)

	c.Assert(registrations, qt.Equals, 8)
	c.Assert(hidden, qt.HasLen, 4)
	c.Assert(hidden, qt.Contains, "atlas-project-config")
	c.Assert(hidden, qt.Contains, "atlas-project-var")
	c.Assert(hidden, qt.Contains, "dry-run")
	c.Assert(hidden, qt.Contains, "file")
}

// TestCommandCensus_TheFlagSetIsTheTreeNotTheHelp pins the seven commands whose
// help prints no flag block while they register four flags each.
//
// It is the measurement behind reading the tree rather than `--help`: on those
// seven, help is a strict subset of the flag set, so a flag census built on help
// would report that `ptah-compat schema push --var` does not exist.
func TestCommandCensus_TheFlagSetIsTheTreeNotTheHelp(t *testing.T) {
	paths := []string{
		"migrate push", "schema push",
		"schema plan approve", "schema plan list", "schema plan pull", "schema plan push", "schema plan rm",
	}

	for _, path := range paths {
		t.Run(path, func(t *testing.T) {
			c := qt.New(t)
			census := shippedCensus(c)
			cmd, found := census.Lookup(featureinventory.TreeCompat, path)
			c.Assert(found, qt.IsTrue)
			for _, flag := range []string{"config", "env", "var", "help"} {
				_, registered := cmd.Flags[flag]
				c.Assert(registered, qt.IsTrue, qt.Commentf("`ptah-compat %s` registers --%s and the census missed it", path, flag))
			}
		})
	}
}

// constructedPaths walks a root the way the Phase 1 audit did: over
// cmd.Commands() as the constructor returned it, with none of the initializers
// ExecuteC runs.
func constructedPaths(root *cobra.Command) []string {
	var paths []string
	var visit func(cmd *cobra.Command, parent string)
	visit = func(cmd *cobra.Command, parent string) {
		path := ""
		if cmd.Parent() != nil {
			path = parent + " " + cmd.Name()
			path = trimLeadingSpace(path)
		}
		paths = append(paths, path)
		for _, sub := range cmd.Commands() {
			visit(sub, path)
		}
	}
	visit(root, "")
	return paths
}

// missingFrom lists the shipped paths a constructed walk did not produce.
func missingFrom(constructed []string, shipped []featureinventory.Command) []string {
	have := make(map[string]bool)
	for _, path := range constructed {
		have[path] = true
	}
	var missing []string
	for _, cmd := range shipped {
		if !have[cmd.Path] {
			missing = append(missing, cmd.Path)
		}
	}
	return missing
}

// The helpers below keep the conditionals out of the test bodies, which
// scripts/check-test-style.sh requires. Each takes the collection and answers a
// question about it, rather than taking a bool and choosing with it.

// countLeaves counts the commands that register no subcommands.
func countLeaves(commands []featureinventory.Command) int {
	count := 0
	for _, cmd := range commands {
		if cmd.Leaf {
			count++
		}
	}
	return count
}

// hiddenFlagRegistrations counts every hidden flag registration across two
// trees, and lists the distinct names.
func hiddenFlagRegistrations(census *featureinventory.Census) (int, []string) {
	registrations := 0
	seen := make(map[string]bool)
	var names []string
	for _, tree := range []featureinventory.Tree{featureinventory.TreeNative, featureinventory.TreeCompat} {
		for _, cmd := range census.OfTree(tree) {
			for name, flag := range cmd.Flags {
				if !flag.Hidden {
					continue
				}
				registrations++
				if !seen[name] {
					seen[name] = true
					names = append(names, name)
				}
			}
		}
	}
	sort.Strings(names)
	return registrations, names
}

// trimLeadingSpace drops the leading blanks a joined path picks up at the root.
func trimLeadingSpace(text string) string {
	return strings.TrimLeft(text, " ")
}
