// Command cmdref prints the generated half of the command reference: every
// command path both Ptah binaries ship, every flag they register, and what
// PTAH_ATLAS_STRICT_COMPAT=1 takes away from the compatibility surface.
//
// It constructs both trees in this process. Shelling out to a built binary
// would measure whichever one was on PATH, and reading `--help` output would
// measure a rendering rather than the tree that produced it.
//
// This is the second non-test file outside cmd/atlas that imports cmd/atlas,
// and the exception is deliberate: see AGENTS.md, "Dependency direction". A
// documentation generator that measures both surfaces is not the native
// product depending on the compatibility product, and the direction the rule
// protects -- shared capability below, two adapters above -- is untouched.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"go.5x5.cz/ptah/cmd/atlas"
	"go.5x5.cz/ptah/cmd/root"
	"go.5x5.cz/ptah/internal/agentsurface"
	"go.5x5.cz/ptah/internal/atlascompatpolicy"
	"go.5x5.cz/ptah/internal/cmdref"
)

const usage = `usage: cmdref native|compat|strict|flags

  native   the ptah command table
  compat   the ptah-compat command table
  strict   what PTAH_ATLAS_STRICT_COMPAT=1 removes from ptah-compat
  flags    the whole flag reference page, both binaries
`

func main() {
	if len(os.Args) != 2 {
		fmt.Fprint(os.Stderr, usage)
		os.Exit(2)
	}
	rendered, err := render(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Print(rendered)
}

func render(view string) (string, error) {
	switch view {
	case "native":
		return cmdref.Commands(nativeSurface())
	case "compat":
		return cmdref.Commands(surface(compat(atlascompatpolicy.Full())))
	case "strict":
		full := surface(compat(atlascompatpolicy.Full()))
		strict := surface(compat(atlascompatpolicy.StrictCE()))
		if len(full.Nodes) == 0 || len(strict.Nodes) == 0 {
			return "", fmt.Errorf("cmdref: a compatibility tree walked to nothing; refusing to classify it")
		}
		return cmdref.StrictCompat(full.Program, cmdref.Classify(full.Nodes, strict.Nodes))
	case "flags":
		return flagsPage()
	default:
		return "", fmt.Errorf("cmdref: unknown view %q\n%s", view, usage)
	}
}

func surface(tree *cobra.Command) cmdref.Surface {
	return cmdref.Surface{Program: tree.Name(), Nodes: agentsurface.Nodes(tree)}
}

// nativeSurface is the only classified one: internal/agentsurface classifies
// the `ptah` verbs and nothing classifies the compatibility tree.
func nativeSurface() cmdref.Surface {
	native := surface(root.NewRootCommand())
	native.Classified = true
	return native
}

func compat(policy atlascompatpolicy.Policy) *cobra.Command {
	return atlas.NewCompatCommandWithPolicy("ptah-compat", policy)
}

// flagsPage renders a whole page rather than a block, because the page is
// entirely measurement: there is no sentence on it a person would write.
// Everything a reader needs beyond the rows -- when to reach for a verb, what
// a flag means -- is on the two command pages, which stay hand-written around
// their generated tables.
func flagsPage() (string, error) {
	tables, err := cmdref.Flags([]cmdref.Surface{
		nativeSurface(),
		surface(compat(atlascompatpolicy.Full())),
	})
	if err != nil {
		return "", err
	}
	// The preamble is written with an explicit newline join rather than a raw
	// string literal, because half its lines carry code spans and a backtick
	// ends a raw literal.
	preamble := strings.Join([]string{
		"---",
		"title: Command flags",
		"description: Every flag both Ptah binaries register, with its type, default and environment variable.",
		"---",
		"",
		"<!-- Generated by internal/cmd/cmdref. Do not edit by hand: run `scripts/check-command-reference.sh --write`. -->",
		"",
		"This page is measured from the command trees the two binaries ship, one row",
		"per command and flag. It is the inventory: which spellings a command accepts,",
		"what each holds when nothing sets it, and which variable it reads. For a",
		"flag's own words run `ptah <command> --help`, which prints the same usage",
		"string this page indexes by name. What each VERB is for is on",
		"[Native commands](../native-commands/) and",
		"[Atlas-compatible commands](../atlas-commands/).",
		"",
		"Read the columns as follows.",
		"",
		"- **Default** is the value the flag holds when nothing sets one, in the",
		"  spelling the flag parser reports.",
		"- **Environment variable** is what the flag reads when it is not typed on the",
		"  command line, and an em dash means it reads none. Every `--auto-approve` and",
		"  every `--allow-database-inspect` is one of those: approval is not something",
		"  a script can grant by exporting a variable.",
		"- **Notes** carries `hidden` for a flag `--help` does not list and still",
		"  parses, and `inherited by subcommands` for one declared on a group.",
		"",
		"",
	}, "\n")

	var page strings.Builder
	page.WriteString(preamble)
	page.WriteString(tables)
	return page.String(), nil
}
