package oracle

// White-box testing required: the column read and the spelling of
// GENERATION_TYPE are package-local, and neither is reachable through an
// exported API without a live Oracle server.

import (
	"database/sql"
	"database/sql/driver"
	"errors"
	"testing"

	qt "github.com/frankban/quicktest"

	"ptah.run/internal/dbschema/dbtest"
)

// An identity column's generation mode is read from the catalog --
// stokaro/ptah#3295.
//
// IDENTITY_COLUMN answers YES for GENERATED ALWAYS and GENERATED BY DEFAULT
// alike, and only the first refuses an explicit value. A reader that set
// IsAutoIncrement and nothing else left `ptah migrations data` unable to tell
// them apart: it wrote a rollback of INSERTs into a GENERATED ALWAYS key, and
// Oracle refused each one with ORA-32795 after the up had deleted the rows.
func TestReadColumns_CarriesTheIdentityGeneration(t *testing.T) {
	c := qt.New(t)

	db := dbtest.Open(t, answeringIdentityCatalog)
	reader := &Reader{db: db.SQL, schema: "APP"}

	columns, err := reader.readColumns(t.Context())

	c.Assert(err, qt.IsNil)
	c.Assert(columns["ORDERS"], qt.HasLen, 3)
	c.Assert(columns["ORDERS"][0].IsAutoIncrement, qt.IsTrue)
	c.Assert(columns["ORDERS"][0].IdentityGeneration, qt.Equals, "ALWAYS")
	c.Assert(columns["ORDERS"][1].IsAutoIncrement, qt.IsTrue)
	c.Assert(columns["ORDERS"][1].IdentityGeneration, qt.Equals, "BY_DEFAULT")
	c.Assert(columns["ORDERS"][2].IsAutoIncrement, qt.IsFalse)
	c.Assert(columns["ORDERS"][2].IdentityGeneration, qt.Equals, "")
}

// answeringIdentityCatalog answers the column read, and refuses a projection
// that does not join the view the generation mode lives in.
//
// A fake that answers GENERATION_TYPE whatever the query selects cannot tell a
// reader that asks for it from one that stopped: the mutation dropping the join
// would survive against it.
func answeringIdentityCatalog(query string, _ []driver.NamedValue) (dbtest.QueryResult, error) {
	if !contains(query, "all_tab_identity_cols") || !contains(query, "ic.generation_type") {
		return dbtest.QueryResult{}, errUnaskedGeneration
	}
	return dbtest.QueryResult{
		Columns: []string{
			"TABLE_NAME", "COLUMN_NAME", "DATA_TYPE", "VECTOR_INFO", "CHAR_LENGTH",
			"DATA_PRECISION", "DATA_SCALE", "NULLABLE", "COLUMN_ID",
			"IDENTITY_COLUMN", "VIRTUAL_COLUMN", "DATA_DEFAULT", "COMMENTS", "GENERATION_TYPE",
		},
		Rows: [][]driver.Value{
			{"ORDERS", "ID", "NUMBER", nil, nil, int64(10), int64(0), "N", int64(1), "YES", "NO", `"APP"."ISEQ$$_1".nextval`, nil, "ALWAYS"},
			{"ORDERS", "SEQ", "NUMBER", nil, nil, int64(10), int64(0), "N", int64(2), "YES", "NO", `"APP"."ISEQ$$_2".nextval`, nil, "BY DEFAULT"},
			{"ORDERS", "CODE", "VARCHAR2", nil, int64(40), nil, nil, "N", int64(3), "NO", "NO", nil, nil, nil},
		},
	}, nil
}

var errUnaskedGeneration = errors.New("column query does not join all_tab_identity_cols")

// TestIdentityGeneration_SpellsTheCatalogValue pins the translation from what
// Oracle writes in GENERATION_TYPE to what the catalog records.
//
// The values were measured on Oracle Free 23.26.3: ALWAYS, and BY DEFAULT with
// a space for both GENERATED BY DEFAULT and GENERATED BY DEFAULT ON NULL.
func TestIdentityGeneration_SpellsTheCatalogValue(t *testing.T) {
	tests := []struct {
		name  string
		value sql.NullString
		want  string
	}{
		{name: "generated always", value: text("ALWAYS"), want: "ALWAYS"},
		{name: "generated by default", value: text("BY DEFAULT"), want: "BY_DEFAULT"},
		{name: "not an identity", value: sql.NullString{}, want: ""},
		// A spelling nobody measured is not guessed at. An empty generation
		// is "not known", and no caller reads it as a refusal.
		{name: "an unknown spelling", value: text("SOMETIMES"), want: ""},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := qt.New(t)
			c.Assert(identityGeneration(test.value), qt.Equals, test.want)
		})
	}
}
