package atlashclrender_test

import (
	"testing"

	qt "github.com/frankban/quicktest"

	"ptah.run/core/platform"
	"ptah.run/core/schemamodel"
	"ptah.run/internal/atlashcl"
	"ptah.run/internal/atlashclrender"
)

// ydbInspectedDatabase is what `schema inspect` reads from a YDB database
// holding a table at the root and one in the directory `shop`, with the column
// types, defaults and index kinds a row table carries.
func ydbInspectedDatabase() *schemamodel.Database {
	return &schemamodel.Database{
		Schemas: []schemamodel.Schema{{Name: "shop"}},
		Tables: []schemamodel.Table{
			{StructName: "Users", Name: "users", PrimaryKey: []string{"id"}},
			{StructName: "Orders", Name: "orders", Schema: "shop", PrimaryKey: []string{"id"}},
		},
		Fields: []schemamodel.Field{
			{StructName: "Users", Name: "id", Type: "Int64", AutoInc: true, Primary: true},
			{StructName: "Users", Name: "email", Type: "Utf8"},
			{StructName: "Users", Name: "nick", Type: "Utf8", Nullable: true, Default: "it's", DefaultSet: true},
			{StructName: "Users", Name: "created_at", Type: "Timestamp64", Nullable: true,
				Default: "2026-01-01T00:00:00Z", DefaultSet: true},
			{StructName: "Users", Name: "score", Type: "Int32", Nullable: true, Default: "0", DefaultSet: true},
			{StructName: "Orders", Name: "id", Type: "Uint64", Primary: true},
			{StructName: "Orders", Name: "total", Type: "Decimal(22,9)"},
			{StructName: "Orders", Name: "body", Type: "JsonDocument", Nullable: true},
		},
		Indexes: []schemamodel.Index{
			{StructName: "Users", Name: "users_email_uq", Fields: []string{"email"}, Unique: true, Type: "GLOBAL SYNC"},
			{StructName: "Users", Name: "users_score_ix", Fields: []string{"score"}, Type: "GLOBAL ASYNC",
				IncludeColumns: []string{"nick"}},
		},
	}
}

// Atlas has no HCL for YDB, so the document `schema inspect` writes for one is
// a Ptah extension, and this pins its shape: a type as YDB spells it, written
// bare, including the call form of a parameterized Decimal; a Serial column as
// its integer type with auto_increment; an index's YDB kind as its type; a
// directory as a schema block; a table at the database root, which has no
// name, with no schema reference at all; and a header recording that the
// document does not describe topics, async replications or transfers, which
// HCL has no block for. Workload feature namespaces remain uninspected when
// this document is read. Tables come in name
// order, as every inspected document orders them.
func TestRenderInspectedForAtlasCLIWritesYDBTypesAsYDBSpellsThem(t *testing.T) {
	c := qt.New(t)

	result, err := atlashclrender.RenderInspectedForAtlasCLI(ydbInspectedDatabase(), platform.YDB, "")

	c.Assert(err, qt.IsNil)
	c.Assert(string(result.Data), qt.Equals, `// Code generated by ptah; DO NOT EDIT.
// ptah:not-described replication reason=unsupported provenance=defaulted
// ptah:not-described topic reason=unsupported provenance=defaulted
// ptah:not-described transfer reason=unsupported provenance=defaulted
// ptah:not-described coordination_node

schema "shop" {
}

table "orders" {
  schema = schema.shop
  column "id" {
    type = Uint64
  }
  column "total" {
    type = Decimal(22,9)
  }
  column "body" {
    type = JsonDocument
    null = true
  }
  primary_key {
    columns = [column.id]
  }
}

table "users" {
  column "id" {
    type = Int64
    auto_increment = true
  }
  column "email" {
    type = Utf8
  }
  column "nick" {
    type = Utf8
    null = true
    default = "it's"
  }
  column "created_at" {
    type = Timestamp64
    null = true
    default = "2026-01-01T00:00:00Z"
  }
  column "score" {
    type = Int32
    null = true
    default = "0"
  }
  primary_key {
    columns = [column.id]
  }
  index "users_email_uq" {
    unique = true
    type = "GLOBAL SYNC"
    columns = [column.email]
  }
  index "users_score_ix" {
    type = "GLOBAL ASYNC"
    include = [column.nick]
    columns = [column.score]
  }
}

`)
}

// The document reads back as the schema it was written from: parsing it and
// rendering the result again writes the same bytes. No other reader exists for
// it, so a spelling the parser reads differently would be a document that
// describes one schema and applies another.
func TestRenderInspectedForAtlasCLIYDBDocumentReadsBackAsItself(t *testing.T) {
	c := qt.New(t)
	first, err := atlashclrender.RenderInspectedForAtlasCLI(ydbInspectedDatabase(), platform.YDB, "")
	c.Assert(err, qt.IsNil)

	parsed, err := atlashcl.Parse(first.Data, "schema.hcl")
	c.Assert(err, qt.IsNil)
	second, err := atlashclrender.RenderInspectedForAtlasCLI(parsed, platform.YDB, "")

	c.Assert(err, qt.IsNil)
	c.Assert(string(second.Data), qt.Equals, string(first.Data))
}
