package oracle

import (
	"fmt"
	"strings"

	"go.5x5.cz/ptah/core/ast"
	"go.5x5.cz/ptah/core/platform"
	"go.5x5.cz/ptah/core/platform/capability"
	"go.5x5.cz/ptah/internal/sqlident"
)

func renderColumn(column *ast.ColumnNode, caps capability.Capabilities) (string, error) {
	if column == nil {
		return "", fmt.Errorf("nil column")
	}
	parts := []string{"  " + escapeIdentifier(column.Name), mapColumnType(column)}

	if generatesIdentity(column) {
		// Oracle's auto-increment is an identity column rather than a type,
		// which is why mapColumnType does not answer it. Measured accepted on
		// 23.26 and 21.3: GENERATED BY DEFAULT AS IDENTITY, GENERATED ALWAYS
		// AS IDENTITY and the ON NULL variant. BY DEFAULT is the one that lets
		// a migration insert an explicit key, which is what every other
		// dialect's SERIAL allows.
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	}

	if column.GeneratedExpression != "" {
		if !caps.Has(capability.GeneratedColumns) {
			return "", unsupportedFeaturef(
				"the target Oracle does not support generated columns; column %q declares GENERATED ALWAYS AS",
				column.Name)
		}
		kind := strings.ToUpper(strings.TrimSpace(column.GeneratedKind))
		if kind == "" {
			kind = "VIRTUAL"
		}
		parts = append(parts, fmt.Sprintf("GENERATED ALWAYS AS (%s) %s", column.GeneratedExpression, kind))
	}

	switch {
	case column.Default == nil:
	case column.Default.HasLiteral():
		parts = append(parts, "DEFAULT", renderDefaultLiteral(column.Type, column.Default.Value))
	case column.Default.Expression != "":
		parts = append(parts, "DEFAULT", column.Default.Expression)
	}

	// NOT NULL follows DEFAULT in Oracle's column grammar, unlike the
	// PostgreSQL ordering the other renderers here write.
	//
	// A primary-key column is written NOT NULL whatever its flag says. Oracle
	// derives the constraint either way, so this changes no schema; what it
	// changes is the statement a key column produces when the declaration
	// leaves Nullable set, which every renderer here is required to keep
	// non-nullable.
	if !column.Nullable || column.Primary {
		parts = append(parts, "NOT NULL")
	}
	if column.Primary {
		parts = append(parts, "PRIMARY KEY")
	}
	if column.Unique {
		parts = append(parts, "UNIQUE")
	}
	if column.Check != "" {
		if column.CheckName != "" {
			parts = append(parts, "CONSTRAINT", escapeIdentifier(column.CheckName), "CHECK", "("+column.Check+")")
		} else {
			parts = append(parts, "CHECK", "("+column.Check+")")
		}
	}
	if column.ForeignKey != nil {
		parts = append(parts, renderInlineForeignKey(column.ForeignKey))
	}
	return strings.Join(parts, " "), nil
}

// mapColumnType translates a declared type to the Oracle spelling.
//
// Every mapping below was measured on 23.26 and on 21.3, by creating a column
// of the Oracle type and reading user_tab_columns back. Three of them are worth
// keeping the measurement next to:
//
//   - BOOLEAN is a real type on 23.26 and ORA-00902, invalid datatype, on 21.3.
//     It is rendered as NUMBER(1) on both lines rather than gated on a
//     capability key, because that is the spelling every supported line accepts
//     and the one an Oracle schema conventionally carries. Reading it back as a
//     boolean is the reader's job, the same normalization every dialect here
//     needs -- INTEGER also comes back as NUMBER.
//   - TEXT has no Oracle counterpart of the same shape: VARCHAR2 is capped at
//     32767 bytes even with extended sizes, so an uncapped text column becomes
//     CLOB.
//   - INTEGER, SMALLINT, DECIMAL and NUMERIC are all NUMBER in the catalog --
//     INTEGER reads back as NUMBER with a NULL precision and a scale of 0 --
//     so they are rendered as the NUMBER precisions that survive a round trip
//     rather than as the aliases Oracle accepts and then discards.
//
// isSerialType reports whether a declared type is one of the SERIAL spellings,
// which name a generated counter rather than a width.
//
// It exists because the two halves of SERIAL are separate here: mapColumnType
// answers the width, and the generation is a clause. A column declared
// type="SERIAL" does not set ColumnNode.AutoInc -- that flag comes from an
// explicit auto-increment annotation -- so without this the Oracle renderer
// wrote `id NUMBER(10) PRIMARY KEY` for a column PostgreSQL fills by itself,
// and the generation disappeared with no error anywhere: the table is created,
// the migration reports success, and the first INSERT that omits the key fails
// at runtime instead.
// generatesIdentity reports whether a column becomes an Oracle identity column.
//
// The emitter and the one-identity-per-table check must ask the same question.
// They did not at first: the check read ColumnNode.AutoInc while the emitter
// also treated a SERIAL type as generated, so a table with one AutoInc column
// and one SERIAL column passed the check and then answered ORA-30669 from the
// server. A guard that measures something narrower than what it guards is worse
// than no guard, because its refusal message names a rule the renderer does not
// actually follow.
// bareReferenceInExpression reports the expression that names a quoted column
// without quoting it.
//
// A column Oracle refuses bare -- a reserved word like `size`, or a name with a
// character outside a plain identifier -- is rendered quoted, while the CHECK,
// DEFAULT or generated expression beside it is author text this renderer does
// not rewrite. Bare `size` in that text folds to SIZE, which is not the column
// `size`, and the server answers something that names neither: measured on
// 23.26, `"size" NUMBER(10), doubled NUMBER(10) GENERATED ALWAYS AS (size * 2)
// VIRTUAL` answers ORA-00936, missing expression.
//
// This is a scan for the name as a whole word, not a parse, so it is
// deliberately one-directional: what it finds is always a real mismatch, and an
// expression it does not recognize still reaches the server, which refuses it
// the way it always did. Converting the common case into a message that names
// the column and says what to write instead is the whole of the claim.
func bareReferenceInExpression(columnName, expression string) bool {
	if expression == "" || !requiresQuoting(columnName) {
		return false
	}
	lowered := strings.ToLower(expression)
	target := strings.ToLower(columnName)
	for index := 0; ; {
		found := strings.Index(lowered[index:], target)
		if found < 0 {
			return false
		}
		found += index
		index = found + len(target)
		if found > 0 {
			previous := lowered[found-1]
			if previous == '"' || isIdentifierByte(previous) {
				continue
			}
		}
		if index < len(lowered) {
			next := lowered[index]
			if next == '"' || isIdentifierByte(next) {
				continue
			}
		}
		return true
	}
}

func requiresQuoting(name string) bool {
	return sqlident.Ident(platform.Oracle, name) != name
}

func isIdentifierByte(b byte) bool {
	return b == '_' || b == '$' || b == '#' ||
		(b >= '0' && b <= '9') || (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z')
}

func generatesIdentity(column *ast.ColumnNode) bool {
	return column != nil && (column.AutoInc || isSerialType(column.Type))
}

func isSerialType(declared string) bool {
	switch strings.ToUpper(strings.TrimSpace(declared)) {
	case "SERIAL", "BIGSERIAL", "SMALLSERIAL", "AUTO_INCREMENT", "IDENTITY":
		return true
	default:
		return false
	}
}

// renderModifiedColumn renders the column definition inside ALTER TABLE ...
// MODIFY, which is narrower than the one inside CREATE TABLE.
//
// Only the type and the nullability belong there. Measured on 23.26, carrying
// the key clause across answers ORA-02260, table can have only one primary key:
// the constraint already exists, and MODIFY restating it declares a second one.
//
// Worth recording next to this, for whoever plans these statements: Oracle's
// nullability change is NOT idempotent. `MODIFY (n NUMBER(10) NOT NULL)` on a
// column already NOT NULL answers ORA-01442, and `MODIFY (n NULL)` on one
// already nullable answers ORA-01451. A plan that emits the clause whenever it
// emits the statement therefore fails on re-application, which is a planner
// question rather than a renderer one -- ModifyColumnOperation carries the
// previous nullability for exactly this kind of decision (stokaro/ptah#1875).
func renderModifiedColumn(column *ast.ColumnNode) (string, error) {
	if column == nil {
		return "", fmt.Errorf("nil column")
	}
	parts := []string{escapeIdentifier(column.Name), mapColumnType(column)}
	switch {
	case column.Default == nil:
	case column.Default.HasLiteral():
		parts = append(parts, "DEFAULT", renderDefaultLiteral(column.Type, column.Default.Value))
	case column.Default.Expression != "":
		parts = append(parts, "DEFAULT", column.Default.Expression)
	}
	if !column.Nullable || column.Primary {
		parts = append(parts, "NOT NULL")
	}
	return strings.Join(parts, " "), nil
}

func mapColumnType(column *ast.ColumnNode) string {
	declared := strings.TrimSpace(column.Type)
	base, arguments := splitTypeArguments(strings.ToUpper(declared))

	if mapped, ok := oracleFixedTypes[base]; ok {
		return mapped
	}
	return oracleParameterizedType(base, arguments, declared)
}

// oracleFixedTypes are the declared types whose Oracle spelling carries no
// argument from the declaration.
//
// The integer family is here rather than passed through because Oracle's
// INTEGER and SMALLINT are aliases it discards: measured, a column declared
// INTEGER reads back from user_tab_columns as NUMBER with a NULL precision and
// a scale of 0, which is a different type from the NUMBER(10) a reader would
// have to compare against. Writing the NUMBER precision that survives the round
// trip is what keeps a declared column and a catalog column the same column.
var oracleFixedTypes = map[string]string{
	"BOOLEAN":          "NUMBER(1)",
	"BOOL":             "NUMBER(1)",
	"SMALLINT":         "NUMBER(5)",
	"INT2":             "NUMBER(5)",
	"INTEGER":          "NUMBER(10)",
	"INT":              "NUMBER(10)",
	"INT4":             "NUMBER(10)",
	"MEDIUMINT":        "NUMBER(10)",
	"BIGINT":           "NUMBER(19)",
	"INT8":             "NUMBER(19)",
	"SERIAL":           "NUMBER(10)",
	"AUTO_INCREMENT":   "NUMBER(10)",
	"BIGSERIAL":        "NUMBER(19)",
	"SMALLSERIAL":      "NUMBER(5)",
	"IDENTITY":         "NUMBER(19)",
	"REAL":             "BINARY_FLOAT",
	"FLOAT4":           "BINARY_FLOAT",
	"DOUBLE PRECISION": "BINARY_DOUBLE",
	"FLOAT8":           "BINARY_DOUBLE",
	"DOUBLE":           "BINARY_DOUBLE",
	// VARCHAR2 is capped at 32767 bytes even with extended sizes, so an
	// uncapped text column has to be a LOB.
	"TEXT":       "CLOB",
	"CITEXT":     "CLOB",
	"LONGTEXT":   "CLOB",
	"MEDIUMTEXT": "CLOB",
	"TINYTEXT":   "CLOB",
	"BYTEA":      "BLOB",
	"BLOB":       "BLOB",
	"LONGBLOB":   "BLOB",
	"MEDIUMBLOB": "BLOB",
	"TINYBLOB":   "BLOB",
	"VARBINARY":  "BLOB",
	"BINARY":     "BLOB",
	// 16 raw bytes rather than the 36-character text form: RAW(16) is what
	// Oracle's own SYS_GUID() produces, so a column declared UUID here and one
	// filled by the database agree.
	"UUID":                     "RAW(16)",
	"TIMESTAMPTZ":              "TIMESTAMP WITH TIME ZONE",
	"TIMESTAMP WITH TIME ZONE": "TIMESTAMP WITH TIME ZONE",
	"DATETIME":                 "TIMESTAMP",
	// Measured accepted on 23.26 and 21.3 alike, reported back as
	// data_type=JSON.
	"JSON":  "JSON",
	"JSONB": "JSON",
	"XML":   "XMLTYPE",
}

// oracleParameterizedType answers the types that carry the declaration's own
// argument list.
func oracleParameterizedType(base, arguments, declared string) string {
	switch base {
	case "DECIMAL", "NUMERIC":
		return "NUMBER" + arguments
	case "VARCHAR", "CHARACTER VARYING":
		if arguments == "" {
			return "VARCHAR2(4000)"
		}
		return "VARCHAR2" + arguments
	case "CHAR", "CHARACTER":
		return "CHAR" + arguments
	default:
		return declared
	}
}

func splitTypeArguments(upper string) (base, arguments string) {
	index := strings.Index(upper, "(")
	if index < 0 {
		return upper, ""
	}
	return strings.TrimSpace(upper[:index]), strings.TrimSpace(upper[index:])
}

// renderDefaultLiteral renders a declared default for a column of declaredType.
//
// The type is needed because BOOLEAN maps to NUMBER(1) here -- see
// oracleFixedTypes -- and the literal beside it has to follow the type it
// landed on. Measured on 23.26, only the boolean spelling is refused; Oracle
// converts a quoted number implicitly, so the other quoted literals reach a
// created table:
//
//	qty NUMBER(10) DEFAULT '5'         accepted
//	price NUMBER(10,2) DEFAULT '0.00'  accepted
//	note CLOB DEFAULT 'none'           accepted
//	flag NUMBER(1) DEFAULT 'false'     ORA-01722, unable to convert string value containing 'f' to a number
//
// So this narrows to the one case the server refuses rather than rewriting
// every literal, which would change defaults that already work.
func renderDefaultLiteral(declaredType, value string) string {
	value = strings.TrimSpace(value)
	if literal, ok := renderBooleanDefaultLiteral(declaredType, value); ok {
		return literal
	}
	if strings.HasPrefix(value, "'") && strings.HasSuffix(value, "'") {
		return value
	}
	return escapeStringLiteral(value)
}

// renderBooleanDefaultLiteral maps a declared boolean default onto the NUMBER(1)
// the type became. A value that is neither spelling is left alone: it is either
// already numeric, or something this renderer should not be inventing a
// conversion for.
func renderBooleanDefaultLiteral(declaredType, value string) (string, bool) {
	base, _ := splitTypeArguments(strings.ToUpper(strings.TrimSpace(declaredType)))
	if base != "BOOLEAN" && base != "BOOL" {
		return "", false
	}
	switch strings.ToLower(strings.Trim(value, "'")) {
	case "true":
		return "1", true
	case "false":
		return "0", true
	default:
		return "", false
	}
}

func renderConstraint(constraint *ast.ConstraintNode) (string, error) {
	if constraint == nil {
		return "", fmt.Errorf("nil constraint")
	}
	prefix := "  "
	if constraint.Name != "" {
		prefix += "CONSTRAINT " + escapeIdentifier(constraint.Name) + " "
	}
	switch constraint.Type {
	case ast.PrimaryKeyConstraint:
		return prefix + "PRIMARY KEY (" + strings.Join(escapeIdentifierList(constraint.Columns), ", ") + ")", nil
	case ast.UniqueConstraint:
		return prefix + "UNIQUE (" + strings.Join(escapeIdentifierList(constraint.Columns), ", ") + ")", nil
	case ast.ForeignKeyConstraint:
		if constraint.Reference == nil {
			return "", fmt.Errorf("foreign key constraint missing reference")
		}
		return "  " + renderNamedForeignKey(constraint.Name, constraint.Columns, constraint.Reference), nil
	case ast.CheckConstraint:
		return prefix + "CHECK (" + constraint.Expression + ")", nil
	default:
		return "", fmt.Errorf("oracle: unsupported constraint type %v", constraint.Type)
	}
}

func renderInlineForeignKey(ref *ast.ForeignKeyRef) string {
	prefix := ""
	if ref.Name != "" {
		prefix = "CONSTRAINT " + escapeIdentifier(ref.Name) + " "
	}
	return prefix + "REFERENCES " + escapeQualifiedIdentifier(ref.Table) + " (" +
		strings.Join(escapeIdentifierList(ref.ReferencedColumns()), ", ") + ")" +
		renderReferentialActions(ref) + renderDeferral(ref)
}

func renderNamedForeignKey(name string, columns []string, ref *ast.ForeignKeyRef) string {
	prefix := ""
	if name != "" {
		prefix = "CONSTRAINT " + escapeIdentifier(name) + " "
	}
	return prefix + "FOREIGN KEY (" + strings.Join(escapeIdentifierList(columns), ", ") + ") REFERENCES " +
		escapeQualifiedIdentifier(ref.Table) + " (" + strings.Join(escapeIdentifierList(ref.ReferencedColumns()), ", ") + ")" +
		renderReferentialActions(ref) + renderDeferral(ref)
}

// renderReferentialActions writes the referential actions Oracle has.
//
// Oracle carries ON DELETE CASCADE and ON DELETE SET NULL and has no ON UPDATE
// clause of any kind. An ON UPDATE the declaration asks for is dropped here
// rather than emitted, because emitting it makes the whole CREATE TABLE a
// syntax error -- the table would not exist at all, which is a worse answer
// than a table whose update rule is the default.
func renderReferentialActions(ref *ast.ForeignKeyRef) string {
	action := strings.ToUpper(strings.Join(strings.Fields(ref.OnDelete), " "))
	switch action {
	case "CASCADE", "SET NULL":
		return " ON DELETE " + action
	default:
		return ""
	}
}

// renderDeferral renders DEFERRABLE and its timing, measured accepted on both
// lines: `... REFERENCES p (id) DEFERRABLE INITIALLY DEFERRED` is created
// without error on 23.26 and on 21.3.
func renderDeferral(ref *ast.ForeignKeyRef) string {
	if !ref.Deferrable && ref.Initially == "" {
		return ""
	}
	switch strings.ToLower(strings.TrimSpace(ref.Initially)) {
	case "deferred":
		return " DEFERRABLE INITIALLY DEFERRED"
	case "immediate":
		return " DEFERRABLE INITIALLY IMMEDIATE"
	default:
		return " DEFERRABLE"
	}
}

func renderIndexParts(parts []ast.IndexPart) []string {
	rendered := make([]string, 0, len(parts))
	for _, part := range parts {
		spec := escapeQualifiedIdentifier(part.Reference())
		if part.Expr != "" {
			spec = part.Expr
		}
		if part.Desc {
			spec += " DESC"
		}
		rendered = append(rendered, spec)
	}
	return rendered
}

// sequenceOptions renders the option clauses Oracle takes beside a sequence
// name.
//
// Measured accepted whole on both lines: `CREATE SEQUENCE s START WITH 5
// INCREMENT BY 2 MAXVALUE 100 CACHE 5 CYCLE`. That is why
// SequenceStartCounterOnly is false on both presets -- it names the restriction
// Spanner has, where a bare name and a start counter are all a sequence takes.
func sequenceOptions(start, increment, minValue, maxValue *int64, cycle *bool) []string {
	var options []string
	if start != nil {
		options = append(options, fmt.Sprintf("START WITH %d", *start))
	}
	if increment != nil {
		options = append(options, fmt.Sprintf("INCREMENT BY %d", *increment))
	}
	if minValue != nil {
		options = append(options, fmt.Sprintf("MINVALUE %d", *minValue))
	}
	if maxValue != nil {
		options = append(options, fmt.Sprintf("MAXVALUE %d", *maxValue))
	}
	if cycle != nil && *cycle {
		options = append(options, "CYCLE")
	}
	return options
}

func escapeStringLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// escapeIdentifier renders a name bare when Oracle accepts it bare, and quoted
// otherwise.
//
// This is the one place the Oracle renderer departs from every other renderer
// here, which quote unconditionally, and the departure is forced. Oracle folds
// an UNQUOTED identifier to upper case and preserves a quoted one -- measured,
// `CREATE TABLE ptah_fold (...)` and `CREATE TABLE "ptah_fold" (...)` produce
// two different tables, reported by user_tables as PTAH_FOLD and ptah_fold side
// by side -- so a name has two spellings and the CHOICE has to be the same one
// everywhere the name appears.
//
// It cannot be, if the renderer quotes. A CHECK, a DEFAULT or an index
// expression is text the author wrote, and Ptah does not rewrite it. Measured
// on 23.26, with the column declared one way and the expression the other:
//
//	REFUSED  CREATE TABLE q1 ("view_count" NUMBER(10) CHECK (view_count >= 0))
//	           ORA-02438: Column check constraint cannot reference other columns
//	REFUSED  CREATE TABLE q3 ("view_count" NUMBER(10), CONSTRAINT ck CHECK (view_count >= 0))
//	           ORA-00904: "VIEW_COUNT": invalid identifier
//	ACCEPTED CREATE TABLE q2 ("view_count" NUMBER(10) CHECK ("view_count" >= 0))
//	ACCEPTED CREATE TABLE b1 (view_count NUMBER(10) CHECK (view_count >= 0))
//	REFUSED  CREATE TABLE b2 (view_count NUMBER(10) CHECK ("view_count" >= 0))
//	           ORA-02438
//
// Two of those five are accepted, and they are the two where the declaration
// and the expression agree. Quoting the column while the author's expression
// says the name bare is the third row, and it is what this renderer produced
// before: the error names a column that does not exist, because VIEW_COUNT and
// view_count are genuinely different columns.
//
// So plain names go bare, the way an Oracle schema conventionally writes them,
// and the fold to upper case is absorbed by comparing case-insensitively --
// see identifier.ForDialect. A name Oracle will not take bare is still quoted,
// because that is the only way to express it, and an author's expression
// referring to such a name must quote it too.
func escapeIdentifier(identifier string) string {
	return sqlident.Ident(platform.Oracle, unquoteIdentifier(identifier))
}

func escapeQualifiedIdentifier(identifier string) string {
	parts := splitQualifiedIdentifier(identifier)
	for i, part := range parts {
		parts[i] = escapeIdentifier(part)
	}
	return strings.Join(parts, ".")
}

func escapeIdentifierList(identifiers []string) []string {
	escaped := make([]string, len(identifiers))
	for i, identifier := range identifiers {
		escaped[i] = escapeIdentifier(identifier)
	}
	return escaped
}

func unquoteIdentifier(identifier string) string {
	if len(identifier) >= 2 {
		switch {
		case identifier[0] == '"' && identifier[len(identifier)-1] == '"':
			return strings.ReplaceAll(identifier[1:len(identifier)-1], `""`, `"`)
		case identifier[0] == '`' && identifier[len(identifier)-1] == '`':
			return strings.ReplaceAll(identifier[1:len(identifier)-1], "``", "`")
		}
	}
	return identifier
}

// splitQualifiedIdentifier splits on the dots separating name parts, leaving
// dots inside a quoted part alone. Each part is a slice of the input, for the
// reason the SQLite renderer's copy of this scan records: rebuilding it byte by
// byte re-encoded every non-ASCII byte as its own code point.
func splitQualifiedIdentifier(identifier string) []string {
	var parts []string
	start := 0
	inQuotes := false
	inBackticks := false
	for i := range len(identifier) {
		switch identifier[i] {
		case '"':
			inQuotes = !inQuotes
		case '`':
			inBackticks = !inBackticks
		case '.':
			if !inQuotes && !inBackticks {
				parts = append(parts, identifier[start:i])
				start = i + 1
			}
		}
	}
	return append(parts, identifier[start:])
}
