package oracle

import (
	"fmt"
	"strings"

	"go.5x5.cz/ptah/core/ast"
	"go.5x5.cz/ptah/core/platform"
	"go.5x5.cz/ptah/core/platform/capability"
	"go.5x5.cz/ptah/internal/oracletype"
	"go.5x5.cz/ptah/internal/sqlident"
)

func renderColumn(column *ast.ColumnNode, caps capability.Capabilities) (string, error) {
	if column == nil {
		return "", fmt.Errorf("nil column")
	}
	parts := []string{"  " + escapeIdentifier(column.Name), mapColumnType(column)}

	if generatesIdentity(column) {
		// Oracle's auto-increment is an identity column rather than a type,
		// which is why mapColumnType does not answer it. Measured accepted on
		// 23.26 and 21.3: GENERATED BY DEFAULT AS IDENTITY, GENERATED ALWAYS
		// AS IDENTITY and the ON NULL variant. BY DEFAULT is the one that lets
		// a migration insert an explicit key, which is what every other
		// dialect's SERIAL allows.
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	}

	if column.GeneratedExpression != "" {
		if !caps.Has(capability.GeneratedColumns) {
			return "", unsupportedFeaturef(
				"the target Oracle does not support generated columns; column %q declares GENERATED ALWAYS AS",
				column.Name)
		}
		kind := strings.ToUpper(strings.TrimSpace(column.GeneratedKind))
		if kind == "" {
			kind = "VIRTUAL"
		}
		parts = append(parts, fmt.Sprintf("GENERATED ALWAYS AS (%s) %s", column.GeneratedExpression, kind))
	}

	switch {
	case column.Default == nil:
	case column.Default.HasLiteral():
		parts = append(parts, "DEFAULT", renderDefaultLiteral(column.Type, column.Default.Value))
	case column.Default.Expression != "":
		parts = append(parts, "DEFAULT", column.Default.Expression)
	}

	// NOT NULL follows DEFAULT in Oracle's column grammar, unlike the
	// PostgreSQL ordering the other renderers here write.
	//
	// A primary-key column is written NOT NULL whatever its flag says. Oracle
	// derives the constraint either way, so this changes no schema; what it
	// changes is the statement a key column produces when the declaration
	// leaves Nullable set, which every renderer here is required to keep
	// non-nullable.
	if !column.Nullable || column.Primary {
		parts = append(parts, "NOT NULL")
	}
	if column.Primary {
		parts = append(parts, "PRIMARY KEY")
	}
	if column.Unique {
		parts = append(parts, "UNIQUE")
	}
	if column.Check != "" {
		if column.CheckName != "" {
			parts = append(parts, "CONSTRAINT", escapeIdentifier(column.CheckName), "CHECK", "("+column.Check+")")
		} else {
			parts = append(parts, "CHECK", "("+column.Check+")")
		}
	}
	if column.ForeignKey != nil {
		parts = append(parts, renderInlineForeignKey(column.ForeignKey))
	}
	return strings.Join(parts, " "), nil
}

// mapColumnType is [oracletype.Map], which the schema comparison calls too.
//
// One implementation rather than two: the comparison has to fold a declared
// TEXT and a catalog CLOB into one type before deciding whether a column
// changed, and it can only do that by asking the same question this renderer
// answers.
func mapColumnType(column *ast.ColumnNode) string {
	return oracletype.Map(column.Type)
}

// isSerialType reports whether a declared type is one of the SERIAL spellings,
// which name a generated counter rather than a width.
//
// It exists because the two halves of SERIAL are separate here: mapColumnType
// answers the width, and the generation is a clause. A column declared
// type="SERIAL" does not set ColumnNode.AutoInc -- that flag comes from an
// explicit auto-increment annotation -- so without this the Oracle renderer
// wrote `id NUMBER(10) PRIMARY KEY` for a column PostgreSQL fills by itself,
// and the generation disappeared with no error anywhere: the table is created,
// the migration reports success, and the first INSERT that omits the key fails
// at runtime instead.
// generatesIdentity reports whether a column becomes an Oracle identity column.
//
// The emitter and the one-identity-per-table check must ask the same question.
// They did not at first: the check read ColumnNode.AutoInc while the emitter
// also treated a SERIAL type as generated, so a table with one AutoInc column
// and one SERIAL column passed the check and then answered ORA-30669 from the
// server. A guard that measures something narrower than what it guards is worse
// than no guard, because its refusal message names a rule the renderer does not
// actually follow.
// bareReferenceInExpression reports the expression that names a quoted column
// without quoting it.
//
// A column Oracle refuses bare -- a reserved word like `size`, or a name with a
// character outside a plain identifier -- is rendered quoted, while the CHECK,
// DEFAULT or generated expression beside it is author text this renderer does
// not rewrite. Bare `size` in that text folds to SIZE, which is not the column
// `size`, and the server answers something that names neither: measured on
// 23.26, `"size" NUMBER(10), doubled NUMBER(10) GENERATED ALWAYS AS (size * 2)
// VIRTUAL` answers ORA-00936, missing expression.
//
// This is a scan for the name as a whole word, not a parse, so it is
// deliberately one-directional: what it finds is always a real mismatch, and an
// expression it does not recognize still reaches the server, which refuses it
// the way it always did. Converting the common case into a message that names
// the column and says what to write instead is the whole of the claim.
func bareReferenceInExpression(columnName, expression string) bool {
	// A column with no name names nothing in an expression, and it is also the
	// one input the scan below cannot survive: strings.Index answers 0 for an
	// empty needle in every haystack, so `index += len(target)` never advances
	// and the loop has no other exit. `ptah schema render --dialect oracle`
	// spun at 100% of one core and did not stop for SIGTERM
	// (stokaro/ptah#2608).
	//
	// core/renderer.prepareColumnNode now refuses an unnamed column before this
	// renderer is reached, so this is stated twice on purpose: a scan that
	// cannot terminate should not depend on a caller having validated its
	// input.
	if expression == "" || columnName == "" || !requiresQuoting(columnName) {
		return false
	}
	lowered := strings.ToLower(expression)
	target := strings.ToLower(columnName)
	for index := 0; ; {
		found := strings.Index(lowered[index:], target)
		if found < 0 {
			return false
		}
		found += index
		index = found + len(target)
		if found > 0 {
			previous := lowered[found-1]
			if previous == '"' || isIdentifierByte(previous) {
				continue
			}
		}
		if index < len(lowered) {
			next := lowered[index]
			if next == '"' || isIdentifierByte(next) {
				continue
			}
		}
		return true
	}
}

func requiresQuoting(name string) bool {
	return sqlident.Ident(platform.Oracle, name) != name
}

func isIdentifierByte(b byte) bool {
	return b == '_' || b == '$' || b == '#' ||
		(b >= '0' && b <= '9') || (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z')
}

func generatesIdentity(column *ast.ColumnNode) bool {
	return column != nil && (column.AutoInc || isSerialType(column.Type))
}

func isSerialType(declared string) bool {
	switch strings.ToUpper(strings.TrimSpace(declared)) {
	case "SERIAL", "BIGSERIAL", "SMALLSERIAL", "AUTO_INCREMENT", "IDENTITY":
		return true
	default:
		return false
	}
}

// renderModifiedColumn renders the column definition inside ALTER TABLE ...
// MODIFY, which is narrower than the one inside CREATE TABLE.
//
// Only the type and the nullability belong there. Measured on 23.26, carrying
// the key clause across answers ORA-02260, table can have only one primary key:
// the constraint already exists, and MODIFY restating it declares a second one.
//
// Oracle's nullability change is NOT idempotent, and that decides when the
// clause is written at all. Measured on 23.26:
//
//	MODIFY (n NUMBER(10) NOT NULL)  on a column already NOT NULL   ORA-01442
//	MODIFY (n NULL)                 on one already nullable        ORA-01451
//	MODIFY (n NUMBER(10))           on a NOT NULL column           accepted, changes nothing
//
// So the clause is written only when the nullability actually changes, which
// needs the previous value: op carries it, and until it was read here the
// relaxing direction had no branch at all. `MODIFY (n CLOB)` is a statement
// Oracle accepts and that leaves the constraint in place, so a migration
// relaxing a column reported success and did nothing (stokaro/ptah#1885).
//
// An operation that does not carry the previous value says NOTHING about
// nullability, and that is the direction the first version had backwards.
// Stating the target instead answered ORA-01442 on a column whose nullability
// had not changed at all: the planners populate the previous value exactly when
// the comparison recorded a nullability change, so "not carried" means "did not
// change" for every plan Ptah produces. Measured -- a declaration that only
// cleared a default failed on its first statement, and the relaxation queued
// behind it never ran.
//
// The default is the other half, and it needs the same treatment for the
// opposite reason. MODIFY states the whole new column definition, so a cleared
// default has to be spelled DEFAULT NULL; omitting it leaves the old default in
// place while the plan's own comment says it was cleared.
func renderModifiedColumn(op *ast.ModifyColumnOperation) (string, error) {
	if op == nil || op.Column == nil {
		return "", fmt.Errorf("nil column")
	}
	column := op.Column
	parts := []string{escapeIdentifier(column.Name), mapColumnType(column)}
	if clause := defaultClause(op); clause != "" {
		parts = append(parts, clause)
	}
	if clause := nullabilityClause(op); clause != "" {
		parts = append(parts, clause)
	}
	return strings.Join(parts, " "), nil
}

// defaultClause answers what MODIFY should say about the default.
//
// A declared default is stated. A column that declares none is left alone
// UNLESS one is being cleared, which Oracle spells DEFAULT NULL: the statement
// replaces the column definition, and a MODIFY that simply omits the clause
// keeps the old default. Measured on 23.26 -- after a plan whose own comment
// read `default_expr: 7 -> `, all_tab_cols still reported data_default = 7.
func defaultClause(op *ast.ModifyColumnOperation) string {
	column := op.Column
	switch {
	case column.Default == nil:
		if op.HasPreviousDefault && op.PreviousDefault != "" {
			return "DEFAULT NULL"
		}
		return ""
	case column.Default.HasLiteral():
		return "DEFAULT " + renderDefaultLiteral(column.Type, column.Default.Value)
	case column.Default.Expression != "":
		return "DEFAULT " + column.Default.Expression
	default:
		return ""
	}
}

// nullabilityClause answers what MODIFY should say about nullability, which is
// usually nothing.
func nullabilityClause(op *ast.ModifyColumnOperation) string {
	notNull := !op.Column.Nullable || op.Column.Primary
	if !op.HasPreviousNullable {
		return ""
	}
	previousNotNull := !op.PreviousNullable
	if notNull == previousNotNull {
		return ""
	}
	if notNull {
		return "NOT NULL"
	}
	return "NULL"
}

// renderDefaultLiteral renders a declared default for a column of declaredType.
//
// The type is needed because BOOLEAN maps to NUMBER(1) here -- see
// oracleFixedTypes -- and the literal beside it has to follow the type it
// landed on. Measured on 23.26, only the boolean spelling is refused; Oracle
// converts a quoted number implicitly, so the other quoted literals reach a
// created table:
//
//	qty NUMBER(10) DEFAULT '5'         accepted
//	price NUMBER(10,2) DEFAULT '0.00'  accepted
//	note CLOB DEFAULT 'none'           accepted
//	flag NUMBER(1) DEFAULT 'false'     ORA-01722, unable to convert string value containing 'f' to a number
//
// So this narrows to the one case the server refuses rather than rewriting
// every literal, which would change defaults that already work.
func renderDefaultLiteral(declaredType, value string) string {
	value = strings.TrimSpace(value)
	if literal, ok := renderBooleanDefaultLiteral(declaredType, value); ok {
		return literal
	}
	if strings.HasPrefix(value, "'") && strings.HasSuffix(value, "'") {
		return value
	}
	return escapeStringLiteral(value)
}

// renderBooleanDefaultLiteral maps a declared boolean default onto the NUMBER(1)
// the type became. A value that is neither spelling is left alone: it is either
// already numeric, or something this renderer should not be inventing a
// conversion for.
func renderBooleanDefaultLiteral(declaredType, value string) (string, bool) {
	base := oracletype.Base(declaredType)
	if base != "BOOLEAN" && base != "BOOL" {
		return "", false
	}
	switch strings.ToLower(strings.Trim(value, "'")) {
	case "true":
		return "1", true
	case "false":
		return "0", true
	default:
		return "", false
	}
}

func renderConstraint(constraint *ast.ConstraintNode) (string, error) {
	if constraint == nil {
		return "", fmt.Errorf("nil constraint")
	}
	prefix := "  "
	if constraint.Name != "" {
		prefix += "CONSTRAINT " + escapeIdentifier(constraint.Name) + " "
	}
	switch constraint.Type {
	case ast.PrimaryKeyConstraint:
		return prefix + "PRIMARY KEY (" + strings.Join(escapeIdentifierList(constraint.Columns), ", ") + ")", nil
	case ast.UniqueConstraint:
		return prefix + "UNIQUE (" + strings.Join(escapeIdentifierList(constraint.Columns), ", ") + ")", nil
	case ast.ForeignKeyConstraint:
		if constraint.Reference == nil {
			return "", fmt.Errorf("foreign key constraint missing reference")
		}
		return "  " + renderNamedForeignKey(constraint.Name, constraint.Columns, constraint.Reference), nil
	case ast.CheckConstraint:
		return prefix + "CHECK (" + constraint.Expression + ")", nil
	default:
		return "", fmt.Errorf("oracle: unsupported constraint type %v", constraint.Type)
	}
}

func renderInlineForeignKey(ref *ast.ForeignKeyRef) string {
	prefix := ""
	if ref.Name != "" {
		prefix = "CONSTRAINT " + escapeIdentifier(ref.Name) + " "
	}
	return prefix + "REFERENCES " + escapeQualifiedIdentifier(ref.Table) + " (" +
		strings.Join(escapeIdentifierList(ref.ReferencedColumns()), ", ") + ")" +
		renderReferentialActions(ref) + renderDeferral(ref)
}

func renderNamedForeignKey(name string, columns []string, ref *ast.ForeignKeyRef) string {
	prefix := ""
	if name != "" {
		prefix = "CONSTRAINT " + escapeIdentifier(name) + " "
	}
	return prefix + "FOREIGN KEY (" + strings.Join(escapeIdentifierList(columns), ", ") + ") REFERENCES " +
		escapeQualifiedIdentifier(ref.Table) + " (" + strings.Join(escapeIdentifierList(ref.ReferencedColumns()), ", ") + ")" +
		renderReferentialActions(ref) + renderDeferral(ref)
}

// renderReferentialActions writes the referential actions Oracle has.
//
// Oracle carries ON DELETE CASCADE and ON DELETE SET NULL and has no ON UPDATE
// clause of any kind. An ON UPDATE the declaration asks for is dropped here
// rather than emitted, because emitting it makes the whole CREATE TABLE a
// syntax error -- the table would not exist at all, which is a worse answer
// than a table whose update rule is the default.
func renderReferentialActions(ref *ast.ForeignKeyRef) string {
	action := strings.ToUpper(strings.Join(strings.Fields(ref.OnDelete), " "))
	switch action {
	case "CASCADE", "SET NULL":
		return " ON DELETE " + action
	default:
		return ""
	}
}

// renderDeferral renders DEFERRABLE and its timing, measured accepted on both
// lines: `... REFERENCES p (id) DEFERRABLE INITIALLY DEFERRED` is created
// without error on 23.26 and on 21.3.
func renderDeferral(ref *ast.ForeignKeyRef) string {
	if !ref.Deferrable && ref.Initially == "" {
		return ""
	}
	switch strings.ToLower(strings.TrimSpace(ref.Initially)) {
	case "deferred":
		return " DEFERRABLE INITIALLY DEFERRED"
	case "immediate":
		return " DEFERRABLE INITIALLY IMMEDIATE"
	default:
		return " DEFERRABLE"
	}
}

func renderIndexParts(parts []ast.IndexPart) []string {
	rendered := make([]string, 0, len(parts))
	for _, part := range parts {
		spec := escapeQualifiedIdentifier(part.Reference())
		if part.Expr != "" {
			spec = part.Expr
		}
		if part.Desc {
			spec += " DESC"
		}
		rendered = append(rendered, spec)
	}
	return rendered
}

// sequenceOptions renders the option clauses Oracle takes beside a sequence
// name.
//
// Measured accepted whole on both lines: `CREATE SEQUENCE s START WITH 5
// INCREMENT BY 2 MAXVALUE 100 CACHE 5 CYCLE`. That is why
// SequenceStartCounterOnly is false on both presets -- it names the restriction
// Spanner has, where a bare name and a start counter are all a sequence takes.
func sequenceOptions(start, increment, minValue, maxValue, cache *int64, cycle *bool) []string {
	var options []string
	if start != nil {
		options = append(options, fmt.Sprintf("START WITH %d", *start))
	}
	if increment != nil {
		options = append(options, fmt.Sprintf("INCREMENT BY %d", *increment))
	}
	if minValue != nil {
		options = append(options, fmt.Sprintf("MINVALUE %d", *minValue))
	}
	if maxValue != nil {
		options = append(options, fmt.Sprintf("MAXVALUE %d", *maxValue))
	}
	if cache != nil {
		options = append(options, fmt.Sprintf("CACHE %d", *cache))
	}
	if cycle != nil && *cycle {
		options = append(options, "CYCLE")
	}
	return options
}

func escapeStringLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// escapeIdentifier renders a name bare when Oracle accepts it bare, and quoted
// otherwise.
//
// This is the one place the Oracle renderer departs from every other renderer
// here, which quote unconditionally, and the departure is forced. Oracle folds
// an UNQUOTED identifier to upper case and preserves a quoted one -- measured,
// `CREATE TABLE ptah_fold (...)` and `CREATE TABLE "ptah_fold" (...)` produce
// two different tables, reported by user_tables as PTAH_FOLD and ptah_fold side
// by side -- so a name has two spellings and the CHOICE has to be the same one
// everywhere the name appears.
//
// It cannot be, if the renderer quotes. A CHECK, a DEFAULT or an index
// expression is text the author wrote, and Ptah does not rewrite it. Measured
// on 23.26, with the column declared one way and the expression the other:
//
//	REFUSED  CREATE TABLE q1 ("view_count" NUMBER(10) CHECK (view_count >= 0))
//	           ORA-02438: Column check constraint cannot reference other columns
//	REFUSED  CREATE TABLE q3 ("view_count" NUMBER(10), CONSTRAINT ck CHECK (view_count >= 0))
//	           ORA-00904: "VIEW_COUNT": invalid identifier
//	ACCEPTED CREATE TABLE q2 ("view_count" NUMBER(10) CHECK ("view_count" >= 0))
//	ACCEPTED CREATE TABLE b1 (view_count NUMBER(10) CHECK (view_count >= 0))
//	REFUSED  CREATE TABLE b2 (view_count NUMBER(10) CHECK ("view_count" >= 0))
//	           ORA-02438
//
// Two of those five are accepted, and they are the two where the declaration
// and the expression agree. Quoting the column while the author's expression
// says the name bare is the third row, and it is what this renderer produced
// before: the error names a column that does not exist, because VIEW_COUNT and
// view_count are genuinely different columns.
//
// So plain names go bare, the way an Oracle schema conventionally writes them,
// and the fold to upper case is absorbed by comparing case-insensitively --
// see identifier.ForDialect. A name Oracle will not take bare is still quoted,
// because that is the only way to express it, and an author's expression
// referring to such a name must quote it too.
func escapeIdentifier(identifier string) string {
	return sqlident.Ident(platform.Oracle, unquoteIdentifier(identifier))
}

func escapeQualifiedIdentifier(identifier string) string {
	parts := splitQualifiedIdentifier(identifier)
	for i, part := range parts {
		parts[i] = escapeIdentifier(part)
	}
	return strings.Join(parts, ".")
}

func escapeIdentifierList(identifiers []string) []string {
	escaped := make([]string, len(identifiers))
	for i, identifier := range identifiers {
		escaped[i] = escapeIdentifier(identifier)
	}
	return escaped
}

func unquoteIdentifier(identifier string) string {
	if len(identifier) >= 2 {
		switch {
		case identifier[0] == '"' && identifier[len(identifier)-1] == '"':
			return strings.ReplaceAll(identifier[1:len(identifier)-1], `""`, `"`)
		case identifier[0] == '`' && identifier[len(identifier)-1] == '`':
			return strings.ReplaceAll(identifier[1:len(identifier)-1], "``", "`")
		}
	}
	return identifier
}

// splitQualifiedIdentifier splits on the dots separating name parts, leaving
// dots inside a quoted part alone. Each part is a slice of the input, for the
// reason the SQLite renderer's copy of this scan records: rebuilding it byte by
// byte re-encoded every non-ASCII byte as its own code point.
func splitQualifiedIdentifier(identifier string) []string {
	var parts []string
	start := 0
	inQuotes := false
	inBackticks := false
	for i := range len(identifier) {
		switch identifier[i] {
		case '"':
			inQuotes = !inQuotes
		case '`':
			inBackticks = !inBackticks
		case '.':
			if !inQuotes && !inBackticks {
				parts = append(parts, identifier[start:i])
				start = i + 1
			}
		}
	}
	return append(parts, identifier[start:])
}
