//go:build integration

package postgres_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	qt "github.com/frankban/quicktest"
	"github.com/go-extras/go-kit/must"
	"github.com/jackc/pgx/v5"

	"ptah.run/catalog"
	"ptah.run/config"
	"ptah.run/core/schemamodel"
	"ptah.run/dbschema"
	"ptah.run/engine/builtin"
	"ptah.run/internal/builtintest"
	"ptah.run/internal/convert/dbschematogo"
	"ptah.run/internal/dbtarget"
	"ptah.run/internal/schemafile"
	"ptah.run/migration/schemadiff"
	"ptah.run/migration/schemadiff/difftypes"
)

// These tests grant on the sequence a serial or identity column owns, which
// the read describes as part of its column rather than as a sequence of its
// own. The grant is still a grant, and a declaration names it like any other:
// `GRANT USAGE ON SEQUENCE items_id_seq`. Read without it, a declared grant on
// such a sequence was planned again on every run, and a grant missing from the
// database or held beyond the declaration could not be seen (stokaro/ptah#4037).
//
// CockroachDB backs a serial column with unique_rowid() rather than a sequence
// under its default serial_normalization, so only its identity column owns
// one there.

var ownedSequenceGrantEngines = []struct {
	name   string
	engine dbtarget.Engine
	// columns are the columns of the fixture table besides its key.
	columns string
	// sequences are the sequences the fixture table's columns own.
	sequences []string
}{
	{
		name:      "PostgreSQL",
		engine:    dbtarget.PostgreSQL,
		columns:   "id bigserial PRIMARY KEY, code bigint GENERATED BY DEFAULT AS IDENTITY, title text",
		sequences: []string{"items_code_seq", "items_id_seq"},
	},
	{
		name:      "YugabyteDB",
		engine:    dbtarget.YugabyteDB,
		columns:   "id bigserial PRIMARY KEY, code bigint GENERATED BY DEFAULT AS IDENTITY, title text",
		sequences: []string{"items_code_seq", "items_id_seq"},
	},
	{
		name:      "CockroachDB",
		engine:    dbtarget.CockroachDB,
		columns:   "id INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, title STRING",
		sequences: []string{"items_id_seq"},
	},
}

// ownedSequenceGrantFixture is one throwaway schema holding a table whose
// columns own sequences, and one role granted USAGE on each of them.
type ownedSequenceGrantFixture struct {
	conn      *dbschema.DatabaseConnection
	schema    string
	role      string
	columns   string
	sequences []string
}

func newOwnedSequenceGrantFixture(c *qt.C, engine dbtarget.Engine, columns string, sequences []string) ownedSequenceGrantFixture {
	c.Helper()
	ctx := c.Context()
	conn, err := dbschema.ConnectToDatabase(ctx, dbtarget.URL(c, engine))
	c.Assert(err, qt.IsNil)
	suffix := time.Now().UnixNano()
	f := ownedSequenceGrantFixture{
		conn:      conn,
		schema:    fmt.Sprintf("ptah_owned_seq_%d", suffix),
		role:      fmt.Sprintf("ptah_owned_seq_%d", suffix),
		columns:   columns,
		sequences: sequences,
	}
	c.Cleanup(func() {
		cleanup := context.Background()
		for _, statement := range []string{
			"DROP SCHEMA IF EXISTS " + pgx.Identifier{f.schema}.Sanitize() + " CASCADE",
			"DROP ROLE IF EXISTS " + pgx.Identifier{f.role}.Sanitize(),
		} {
			_, dropErr := conn.ExecContext(cleanup, statement)
			c.Check(dropErr, qt.IsNil, qt.Commentf("statement: %s", statement))
		}
		c.Check(conn.Close(), qt.IsNil)
	})
	statements := []string{
		"CREATE SCHEMA " + pgx.Identifier{f.schema}.Sanitize(),
		"CREATE ROLE " + pgx.Identifier{f.role}.Sanitize(),
		"CREATE TABLE " + pgx.Identifier{f.schema, "items"}.Sanitize() + " (" + columns + ")",
	}
	statements = append(statements, f.grantStatements()...)
	for _, statement := range statements {
		_, err := conn.ExecContext(ctx, statement)
		c.Assert(err, qt.IsNil, qt.Commentf("statement: %s", statement))
	}
	return f
}

// grantStatements grants USAGE on every owned sequence to the fixture role.
func (f ownedSequenceGrantFixture) grantStatements() []string {
	statements := make([]string, 0, len(f.sequences))
	for _, sequence := range f.sequences {
		statements = append(statements, "GRANT USAGE ON SEQUENCE "+
			pgx.Identifier{f.schema, sequence}.Sanitize()+" TO "+pgx.Identifier{f.role}.Sanitize())
	}
	return statements
}

// schemaFile writes a SQL schema file declaring the fixture table, preceded by
// prefix and followed by suffix, and loads it.
func (f ownedSequenceGrantFixture) schemaFile(c *qt.C, prefix, suffix []string) *schemamodel.Database {
	c.Helper()
	lines := append([]string(nil), prefix...)
	lines = append(lines, "CREATE TABLE "+pgx.Identifier{f.schema, "items"}.Sanitize()+" ("+f.columns+")")
	lines = append(lines, suffix...)
	path := filepath.Join(c.TempDir(), "schema.sql")
	c.Assert(os.WriteFile(path, []byte(strings.Join(lines, ";\n")+";\n"), 0o600), qt.IsNil)
	desired, err := schemafile.LoadAll([]string{path}, schemafile.Options{YAML: builtintest.Runtime().YAML(), Dialect: f.conn.Info().Dialect})
	c.Assert(err, qt.IsNil)
	return desired
}

func (f ownedSequenceGrantFixture) read(c *qt.C) *catalog.Database {
	c.Helper()
	live, err := dbschema.ReadSchemaWithSchemasContext(c.Context(), f.conn, []string{f.schema})
	c.Assert(err, qt.IsNil)
	return live
}

// sequenceGrantsTo lists the sequence grants to role as `PRIVILEGE target`.
// The connecting user also holds the owner's privileges on each sequence, and
// which user that is depends on the URL.
func sequenceGrantsTo(grants []catalog.Grant, role string) []string {
	var kept []string
	for _, grant := range grants {
		if grant.Role != role || grant.ObjectType != "SEQUENCE" {
			continue
		}
		kept = append(kept, grant.Privilege+" "+grant.QualifiedTarget())
	}
	return kept
}

// sequenceGrantRefs lists grant refs on sequences as `PRIVILEGE target TO role`.
func sequenceGrantRefs(refs []difftypes.GrantRef) []string {
	var kept []string
	for _, ref := range refs {
		if ref.ObjectType != "SEQUENCE" {
			continue
		}
		kept = append(kept, ref.Privilege+" "+ref.ObjectName+" TO "+ref.Role)
	}
	return kept
}

// qualifiedUsage is the expected `USAGE schema.sequence` entry of each owned
// sequence, in the order the read reports them.
func (f ownedSequenceGrantFixture) qualifiedUsage() []string {
	usage := make([]string, 0, len(f.sequences))
	for _, sequence := range f.sequences {
		usage = append(usage, "USAGE "+f.schema+"."+sequence)
	}
	return usage
}

// TestOwnedSequenceGrant_LiveReadReportsTheGrant reads the schema back and finds
// the grant on each sequence a column owns.
func TestOwnedSequenceGrant_LiveReadReportsTheGrant(t *testing.T) {
	for _, engine := range ownedSequenceGrantEngines {
		t.Run(engine.name, func(t *testing.T) {
			c := qt.New(t)
			f := newOwnedSequenceGrantFixture(c, engine.engine, engine.columns, engine.sequences)

			live := f.read(c)

			c.Assert(sequenceGrantsTo(live.Grants, f.role), qt.DeepEquals, f.qualifiedUsage())
			// The sequences stay part of their columns: a grant on one does not
			// make it a sequence the description would create on its own.
			c.Assert(live.Sequences, qt.HasLen, 0)
		})
	}
}

// TestOwnedSequenceGrant_LiveSchemaFileComparesEqual compares a schema file that
// declares the same table and grants with the database, and the description of
// the database with its own read. Nothing is planned either way.
func TestOwnedSequenceGrant_LiveSchemaFileComparesEqual(t *testing.T) {
	for _, engine := range ownedSequenceGrantEngines {
		t.Run(engine.name, func(t *testing.T) {
			c := qt.New(t)
			f := newOwnedSequenceGrantFixture(c, engine.engine, engine.columns, engine.sequences)
			live := f.read(c)
			dialect := f.conn.Info().Dialect
			opts := config.DefaultCompareOptions()
			opts.Dialect = dialect

			declared := must.Must(schemadiff.CompareWithOptions(t.Context(), f.schemaFile(c, nil, f.grantStatements()), live, opts, must.Must(builtin.New())))
			described := must.Must(schemadiff.CompareWithOptions(t.Context(), must.Must(dbschematogo.ConvertDBSchemaToGoSchema(t.Context(), live, dialect, must.Must(builtin.New()))), live, opts, must.Must(builtin.New())))

			c.Assert(sequenceGrantRefs(declared.GrantsAdded), qt.HasLen, 0)
			c.Assert(sequenceGrantRefs(declared.GrantsRemoved), qt.HasLen, 0)
			c.Assert(sequenceGrantRefs(described.GrantsAdded), qt.HasLen, 0)
			c.Assert(sequenceGrantRefs(described.GrantsRemoved), qt.HasLen, 0)
		})
	}
}

// TestOwnedSequenceGrant_LiveSchemaFilePlansTheDifference compares the database
// with a schema file that differs from it in one grant, in each direction. A
// grant the database lacks is planned as a GRANT, and a grant the database
// holds beyond a declaration that manages the role is planned as a REVOKE, as
// they are for a standalone sequence.
func TestOwnedSequenceGrant_LiveSchemaFilePlansTheDifference(t *testing.T) {
	for _, engine := range ownedSequenceGrantEngines {
		t.Run(engine.name+"/declared grant the database lacks", func(t *testing.T) {
			c := qt.New(t)
			f := newOwnedSequenceGrantFixture(c, engine.engine, engine.columns, engine.sequences)
			sequence := pgx.Identifier{f.schema, engine.sequences[0]}.Sanitize()
			_, err := f.conn.ExecContext(c.Context(),
				"REVOKE USAGE ON SEQUENCE "+sequence+" FROM "+pgx.Identifier{f.role}.Sanitize())
			c.Assert(err, qt.IsNil)
			opts := config.DefaultCompareOptions()
			opts.Dialect = f.conn.Info().Dialect

			diff := must.Must(schemadiff.CompareWithOptions(t.Context(), f.schemaFile(c, nil, f.grantStatements()), f.read(c), opts, must.Must(builtin.New())))

			c.Assert(sequenceGrantRefs(diff.GrantsAdded), qt.DeepEquals, []string{
				"USAGE " + f.schema + "." + engine.sequences[0] + " TO " + f.role,
			})
			c.Assert(sequenceGrantRefs(diff.GrantsRemoved), qt.HasLen, 0)
		})
		t.Run(engine.name+"/database grant the declaration leaves out", func(t *testing.T) {
			c := qt.New(t)
			f := newOwnedSequenceGrantFixture(c, engine.engine, engine.columns, engine.sequences)
			opts := config.DefaultCompareOptions()
			opts.Dialect = f.conn.Info().Dialect
			manageRole := []string{"CREATE ROLE " + pgx.Identifier{f.role}.Sanitize()}

			diff := must.Must(schemadiff.CompareWithOptions(t.Context(), f.schemaFile(c, manageRole, f.grantStatements()[1:]), f.read(c), opts, must.Must(builtin.New())))

			c.Assert(sequenceGrantRefs(diff.GrantsAdded), qt.HasLen, 0)
			c.Assert(sequenceGrantRefs(diff.GrantsRemoved), qt.DeepEquals, []string{
				"USAGE " + f.schema + "." + engine.sequences[0] + " TO " + f.role,
			})
		})
	}
}
