//go:build integration

package postgres_test

import (
	"context"
	"fmt"
	"testing"

	qt "github.com/frankban/quicktest"
	"github.com/jackc/pgx/v5"

	"ptah.run/core/platform"
	"ptah.run/internal/dbtarget"
	"ptah.run/internal/sqlschema"
)

// Every target/grantee pair must reach PostgreSQL, including grant options.
func TestPostgresGrantListsLiveConverge(t *testing.T) {
	c := qt.New(t)
	ctx := c.Context()
	base := newTableGrantFixture(c, dbtarget.PostgreSQL)
	fixture := routineGrantFixture(base)
	secondRole := base.role + "_second"
	roleIdent := pgx.Identifier{secondRole}.Sanitize()
	c.Cleanup(func() {
		for _, statement := range []string{"DROP OWNED BY " + roleIdent, "DROP ROLE IF EXISTS " + roleIdent} {
			_, err := base.conn.ExecContext(context.Background(), statement)
			c.Check(err, qt.IsNil)
		}
	})
	fixture.exec(c, ctx, "CREATE ROLE "+roleIdent+" NOLOGIN")
	desired, _, err := sqlschema.Read([]byte(fmt.Sprintf(`
CREATE TABLE %[1]s.docs (id integer PRIMARY KEY);
CREATE TABLE %[1]s.notes (id integer PRIMARY KEY);
GRANT SELECT ON %[1]s.docs, %[1]s.notes TO %[2]s, %[3]s WITH GRANT OPTION;
`, base.schema, base.role, secondRole)), platform.Postgres)
	c.Assert(err, qt.IsNil)

	fixture.apply(c, ctx, &desired)

	for _, role := range []string{base.role, secondRole} {
		for _, table := range []string{"docs", "notes"} {
			var granted bool
			err := base.conn.QueryRowContext(ctx, "SELECT has_table_privilege($1, $2, 'SELECT WITH GRANT OPTION')", role, base.schema+"."+table).Scan(&granted)
			c.Assert(err, qt.IsNil)
			c.Assert(granted, qt.IsTrue, qt.Commentf("role %s, table %s", role, table))
		}
	}
	settled := fixture.compare(c, ctx, &desired)
	c.Assert(settled.GrantsAdded, qt.HasLen, 0, qt.Commentf("%+v", settled.GrantsAdded))
	c.Assert(settled.GrantsRemoved, qt.HasLen, 0, qt.Commentf("%+v", settled.GrantsRemoved))
}

// PostgreSQL itself supplies NOT NULL for identity declarations that omit it.
func TestPostgresIdentityImplicitNotNullLiveConverges(t *testing.T) {
	c := qt.New(t)
	fixture := newTableIdentityFixture(c)
	fixture.body = fmt.Sprintf(`CREATE TABLE %s.events (
 always_id bigint GENERATED ALWAYS AS IDENTITY,
 default_id bigint GENERATED BY DEFAULT AS IDENTITY
);
`, fixture.schema)
	fixture.execute(c, fixture.fileStatements())
	var nonNullable int
	err := fixture.conn.QueryRowContext(c.Context(), `SELECT count(*) FROM information_schema.columns
 WHERE table_schema = $1 AND table_name = 'events' AND is_nullable = 'NO'`, fixture.schema).Scan(&nonNullable)
	c.Assert(err, qt.IsNil)
	c.Assert(nonNullable, qt.Equals, 2)
	fixture.assertNothingPlannedForTheTables(c)
}
