package reusable_components_test

import (
	"slices"
	"testing"
	"testing/fstest"

	qt "github.com/frankban/quicktest"

	"go.5x5.cz/ptah/atlascompat"
	"go.5x5.cz/ptah/core/ast"
	"go.5x5.cz/ptah/core/goschema"
	"go.5x5.cz/ptah/core/platform/capability"
	"go.5x5.cz/ptah/core/renderer"
	dbschematypes "go.5x5.cz/ptah/dbschema/types"
	"go.5x5.cz/ptah/migration/lint"
	"go.5x5.cz/ptah/migration/migrator"
	"go.5x5.cz/ptah/migration/planner"
	"go.5x5.cz/ptah/migration/schemadiff"
)

func TestASTRender(t *testing.T) {
	c := qt.New(t)
	table := ast.NewCreateTable("users").
		AddColumn(ast.NewColumn("id", "SERIAL").SetPrimary()).
		AddColumn(ast.NewColumn("email", "TEXT").SetNotNull().SetUnique())

	sql, err := renderer.RenderSQL("postgres", table)

	c.Assert(err, qt.IsNil)
	c.Assert(sql, qt.Contains, `CREATE TABLE "users"`)
	c.Assert(sql, qt.Contains, `"email" TEXT UNIQUE NOT NULL`)
}

func TestGoAnnotationsToSQL(t *testing.T) {
	c := qt.New(t)
	fsys := fstest.MapFS{
		"models/user.go": {
			Data: []byte(`package models

//ptah:schema:table name="users"
type User struct {
	//ptah:schema:field name="id" type="INTEGER" primary="true"
	ID int

	//ptah:schema:field name="email" type="TEXT" not_null="true" unique="true"
	Email string
}
`),
		},
	}

	db, err := goschema.ParseFS(fsys, "models")
	c.Assert(err, qt.IsNil)

	statements, err := renderer.GetOrderedCreateStatements(db, "sqlite")

	c.Assert(err, qt.IsNil)
	c.Assert(statements, qt.HasLen, 1)
	c.Assert(statements[0], qt.Contains, `CREATE TABLE "users"`)
}

func TestAtlasHCLToSQL(t *testing.T) {
	c := qt.New(t)
	db, err := atlascompat.ParseAtlasHCL([]byte(`
schema "public" {}

table "users" {
  schema = schema.public
  column "id" {
    type = int
  }
  primary_key {
    columns = [column.id]
  }
}
`), "schema.hcl")
	c.Assert(err, qt.IsNil)

	list := atlascompat.SchemaToAST(*db, "postgres")
	sql, err := renderer.RenderSQL("postgres", list.Statements...)

	c.Assert(err, qt.IsNil)
	c.Assert(sql, qt.Contains, `CREATE TABLE "public"."users"`)
}

func TestDiffAndPlan(t *testing.T) {
	c := qt.New(t)
	desired := &goschema.Database{
		Tables: []goschema.Table{{StructName: "User", Name: "users"}},
		Fields: []goschema.Field{{
			StructName: "User",
			FieldName:  "ID",
			Name:       "id",
			Type:       "INTEGER",
			Primary:    true,
		}},
	}
	live := &dbschematypes.DBSchema{}

	diff := schemadiff.CompareWithDialect(desired, live, "sqlite")
	statements, err := planner.GenerateSchemaDiffSQLStatements(diff, desired, "sqlite")

	c.Assert(err, qt.IsNil)
	c.Assert(statements, qt.HasLen, 1)
	c.Assert(statements[0], qt.Contains, `CREATE TABLE "users"`)
}

func TestMigrationIntegrityAndLint(t *testing.T) {
	c := qt.New(t)
	fsys := fstest.MapFS{
		"0000000001_create_users.up.sql": {
			Data: []byte("CREATE TABLE users (id INTEGER PRIMARY KEY);\n"),
		},
		"0000000001_create_users.down.sql": {
			Data: []byte("DROP TABLE users;\n"),
		},
	}

	sum, err := atlascompat.ComputeSum(fsys, migrator.MigrationDirFormatPtah)
	c.Assert(err, qt.IsNil)
	c.Assert(sum.Entries, qt.HasLen, 2)

	findings, err := lint.LintFS(fsys, lint.Options{Dialect: "sqlite"})
	c.Assert(err, qt.IsNil)
	c.Assert(findings, qt.HasLen, 0)
}

func TestCustomLintRule(t *testing.T) {
	c := qt.New(t)
	fsys := fstest.MapFS{
		"0000000001_create_notes.up.sql": {
			Data: []byte("CREATE TABLE notes (id INTEGER PRIMARY KEY, body TEXT);\n"),
		},
		"0000000001_create_notes.down.sql": {
			Data: []byte("DROP TABLE notes;\n"),
		},
	}

	findings, err := lint.LintFS(fsys, lint.Options{
		Dialect: "postgres",
		ExtraRules: []lint.Rule{{
			Code:     "ORG101",
			Title:    "TEXT column without explicit limit",
			Severity: lint.SeverityWarning,
			CheckStatement: func(stmt *lint.Statement) (bool, string) {
				return slices.Contains(stmt.Words, "TEXT"), "use VARCHAR(n) so limits stay reviewable"
			},
		}},
	})

	c.Assert(err, qt.IsNil)
	c.Assert(findings, qt.HasLen, 1)
	c.Assert(findings[0].Rule, qt.Equals, "ORG101")
	c.Assert(findings[0].Severity, qt.Equals, lint.SeverityWarning)
}

func TestCapabilitiesRender(t *testing.T) {
	c := qt.New(t)
	caps := capability.ForServerVersion("postgres", "17.0")
	table := ast.NewCreateTable("accounts").
		AddColumn(ast.NewColumn("id", "INTEGER").SetIdentity("BY_DEFAULT", "1", "1").SetPrimary())

	sql, err := renderer.RenderSQLWithCapabilities("postgres", caps, table)

	c.Assert(err, qt.IsNil)
	c.Assert(sql, qt.Contains, "GENERATED BY DEFAULT AS IDENTITY")
}
