#!/usr/bin/env bash
# Checks the feature inventory against the command trees, in both directions.
#
# docs/feature-inventory.md is the hand-written half. The other half is the cobra
# trees the binaries are built out of, walked after the two initializers cobra's
# ExecuteC runs -- which is what makes this census 103 native paths and 53
# compatibility paths rather than the 97 and 52 a constructed-tree walk reports.
# docs/agent-surface.md is generated by that shorter walk and is gated in CI, so
# a check built the same way would inherit the same blind spot and pass.
#
# `--selftest` runs the fixtures instead: each one plants the defect this gate
# exists to catch, and each one requires the analyzer to name it. A gate nobody
# has watched fail is not a gate.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"
# shellcheck source=scripts/lib/featureinventory.sh
. scripts/lib/featureinventory.sh

case "${1-}" in
"")
	run_feature_inventory_gate "check-inventory-commands" 'TestInventoryCommands_' \
		"every command path the trees register is claimed by a row of docs/feature-inventory.md, and every command a row claims exists"
	;;
--selftest)
	run_feature_inventory_gate "check-inventory-commands --selftest" 'TestInventoryCommandsSelftest_' \
		"the fixtures each plant a command with no row, a row with no command, or a document the parser must refuse"
	;;
*)
	feature_inventory_usage "$0"
	;;
esac
