#!/usr/bin/env bash
# Refuses a capability status file that stopped describing the declared matrix.
#
# docs/site/src/content/docs/databases/capability-status.md is a measurement, written by `capmatrix status` from
# the results one matrix run uploaded. It cannot be regenerated here -- the
# results came from 27 containers -- so this gate cannot compare it against a
# fresh run. What it can do is refuse the two ways the file goes wrong without
# anybody noticing.
#
# A hand edit is the first. The file looks like an ordinary table, and the
# temptation to fix a row by typing is exactly what a generated file has to
# refuse: the next run overwrites it, so the edit is lost and the reader was
# told something no run measured.
#
# A shrinking census is the second, and it is the one that reads as success. The
# identity `capmatrix` holds is declared == runnable + skipped. A file that lost
# a cell describes a smaller matrix than the repository declares, and a missing
# row reads exactly like a passing one -- the same failure shape that put a
# paths filter on a workflow and made an absent check look like approval.
#
# So the gate reads the declaration, not the file's own header: every runnable
# cell must have a row, every skipped line must be named, and the counts line
# has to agree with the rows underneath it. A hand edit that flips a verdict
# without fixing the count is caught by the last one.
set -euo pipefail

STATUS_FILE="${1:-docs/site/src/content/docs/databases/capability-status.md}"

fail() {
	echo "check-capability-status: $1" >&2
	exit 1
}

[ -f "$STATUS_FILE" ] || fail "$STATUS_FILE is missing; the matrix run writes it with 'capmatrix status'"

# The header sits under the site frontmatter rather than on line one, so this
# looks for it in the opening of the file rather than at a fixed offset.
head -n 40 "$STATUS_FILE" | grep -qF "Generated by" ||
	fail "$STATUS_FILE has lost its generated header, so nothing tells a reader not to edit it"

matrix="$(mktemp)"
trap 'rm -f "$matrix"' EXIT
if [ -n "${CAPMATRIX_MATRIX_JSON:-}" ]; then
	# The self-test's seam, and the reason it exists: every declared line runs
	# today, so the skipped half of the census has no subject in the repository
	# and the rule that holds it would go unmeasured. A supplied declaration is
	# how that case still drives the gate. It fails closed -- a caller that
	# names a file this cannot read is refused rather than quietly falling back
	# to the declaration, which would make the seam a way to weaken the gate.
	cp "${CAPMATRIX_MATRIX_JSON}" "$matrix" ||
		fail "CAPMATRIX_MATRIX_JSON names ${CAPMATRIX_MATRIX_JSON}, which cannot be read"
else
	go run ./internal/cmd/capmatrix matrix >"$matrix" ||
		fail "the matrix driver failed, so the declaration this gate compares against is unknown"
fi

# The corpus floor. A declaration that stopped producing cells would let every
# check below pass over an empty list, which is the shape of a gate that reports
# nothing and reads as success.
declared="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["declared"])' "$matrix")"
[ "$declared" -ge 20 ] ||
	fail "the declared matrix reports only ${declared} release lines; that is below the floor this gate needs to mean anything"

missing=""
for cell in $(python3 -c 'import json,sys; print(" ".join(c["id"] for c in json.load(open(sys.argv[1]))["cells"]))' "$matrix"); do
	grep -qF "| \`${cell}\` |" "$STATUS_FILE" || missing="${missing} ${cell}"
done
[ -z "$missing" ] ||
	fail "runnable cells have no row, so the file describes a smaller matrix than the repository declares:${missing}"

unnamed=""
for cell in $(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(" ".join(c["id"] for c in d.get("skipped") or []))' "$matrix"); do
	grep -qF "\`${cell}\`" "$STATUS_FILE" || unnamed="${unnamed} ${cell}"
done
[ -z "$unnamed" ] ||
	fail "declared lines this tier cannot run are not named, so the census is short:${unnamed}"

rows="$(grep -c '^| `' "$STATUS_FILE" || true)"
runnable="$(python3 -c 'import json,sys; print(len(json.load(open(sys.argv[1]))["cells"]))' "$matrix")"
[ "$rows" -eq "$runnable" ] ||
	fail "the table has ${rows} rows and the matrix declares ${runnable} runnable cells"

# The counts line and the rows are two statements about one run, and a hand edit
# usually changes one of them.
counted_pass="$(grep -c '| PASS |$' "$STATUS_FILE" || true)"
claimed_pass="$(sed -n 's/^- \([0-9]*\) passed,.*/\1/p' "$STATUS_FILE" | head -n 1)"
[ -n "$claimed_pass" ] ||
	fail "$STATUS_FILE has no counts line, so nothing summarizes the table"
[ "$counted_pass" -eq "$claimed_pass" ] ||
	fail "the summary claims ${claimed_pass} passed and the table has ${counted_pass} PASS rows"

echo "check-capability-status: OK (${rows} runnable cells, ${declared} declared)"
