#!/usr/bin/env bash
# Checks the generated command reference against the command trees it describes.
#
# Three blocks and one whole page are rendered from the cobra trees the two
# binaries ship, by internal/cmd/cmdref: every command path with what it does,
# every flag with its type, default and PTAH_* variable, and what
# PTAH_ATLAS_STRICT_COMPAT=1 takes away from the compatibility surface. The
# hand-written prose around them stays hand-written; this script is what keeps
# the measured half from drifting away from the binaries.
#
# The drift it exists to stop was measured before it was written. The
# hand-written verb tables named `ptah lint`, which answers `unknown command`
# and exits 2, and never named 6 of the 92 native leaves or 17 of the 52
# compatibility paths.
#
# `--write` regenerates the blocks and the page instead of checking them.
#
# The marker and emptiness checks are not defensive padding. A file whose
# markers were renamed or lost in a merge would yield an empty block on both
# sides, the comparison would find them identical, and a gate that compares
# nothing to nothing reports success at exactly the moment it stopped working.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

mode="check"
case "${1-}" in
"") ;;
--write) mode="write" ;;
*)
	echo "usage: $0 [--write]" >&2
	exit 2
	;;
esac

readonly REFERENCE="docs/site/src/content/docs/reference"
readonly NATIVE_PAGE="$REFERENCE/native-commands.md"
readonly COMPAT_PAGE="$REFERENCE/atlas-commands.md"
readonly FLAGS_PAGE="$REFERENCE/command-flags.md"
# The banner a whole generated page carries. A hand-edit is then refused with
# an explanation rather than with a diff nobody asked for.
readonly BANNER='<!-- Generated by internal/cmd/cmdref.'

work_dir="$(mktemp -d "${TMPDIR:-/tmp}/ptah-command-reference.XXXXXX")"
trap 'rm -rf "$work_dir"' EXIT INT TERM

# The generator validates before it prints: a tree that walked to nothing, or a
# strict policy that removed nothing, is an error there rather than an empty
# table here.
go run ./internal/cmd/cmdref native >"$work_dir/native.md"
go run ./internal/cmd/cmdref compat >"$work_dir/compat.md"
go run ./internal/cmd/cmdref strict >"$work_dir/strict.md"
go run ./internal/cmd/cmdref flags >"$work_dir/flags.md"

status=0

check_block() {
	local target="$1" begin="$2" end="$3" generated="$4"

	if [ ! -s "$generated" ]; then
		echo "check-command-reference: the generator produced nothing for $begin" >&2
		return 1
	fi
	if ! grep -qF "$begin" "$target" || ! grep -qF "$end" "$target"; then
		echo "check-command-reference: $target carries no $begin markers" >&2
		return 1
	fi

	local extracted="$work_dir/extracted"
	awk -v begin="$begin" -v end="$end" '
		$0 == end { inside = 0 }
		inside { print }
		$0 == begin { inside = 1 }
	' "$target" >"$extracted"

	if [ "$mode" = write ]; then
		python3 - "$target" "$generated" "$begin" "$end" <<-'PY'
			import sys

			target, generated, begin, end = sys.argv[1:5]
			body = open(target).read()
			table = open(generated).read()
			head, _, rest = body.partition(begin + "\n")
			_, _, tail = rest.partition(end)
			open(target, "w").write(head + begin + "\n" + table + end + tail)
		PY
		echo "check-command-reference: rewrote $begin in $target"
		return 0
	fi

	if ! diff -u "$generated" "$extracted" >"$work_dir/diff"; then
		echo "check-command-reference: $target is out of date with the command tree" >&2
		echo "check-command-reference: run scripts/check-command-reference.sh --write" >&2
		sed 's/^/  /' "$work_dir/diff" >&2
		return 1
	fi
	return 0
}

# check_page compares a page that is generated in full. It is the mode neither
# check-agent-surface.sh nor check-lint-rules.sh has, and it needs one rule
# they do not: the banner has to be there, so a page whose generated origin was
# edited away is refused by name instead of reported as a large diff.
check_page() {
	local target="$1" generated="$2"

	if [ ! -s "$generated" ]; then
		echo "check-command-reference: the generator produced nothing for $target" >&2
		return 1
	fi
	if ! grep -qF "$BANNER" "$generated"; then
		echo "check-command-reference: the generator no longer emits the do-not-edit banner for $target" >&2
		return 1
	fi

	if [ "$mode" = write ]; then
		cp "$generated" "$target"
		echo "check-command-reference: rewrote $target"
		return 0
	fi

	if [ ! -f "$target" ]; then
		echo "check-command-reference: $target does not exist; run scripts/check-command-reference.sh --write" >&2
		return 1
	fi
	if ! grep -qF "$BANNER" "$target"; then
		echo "check-command-reference: $target has lost its do-not-edit banner; it is generated by internal/cmd/cmdref" >&2
		return 1
	fi
	if ! diff -u "$generated" "$target" >"$work_dir/diff"; then
		echo "check-command-reference: $target is out of date with the command trees" >&2
		echo "check-command-reference: run scripts/check-command-reference.sh --write" >&2
		sed 's/^/  /' "$work_dir/diff" >&2
		return 1
	fi
	return 0
}

check_block "$NATIVE_PAGE" \
	'<!-- BEGIN GENERATED NATIVE COMMANDS -->' \
	'<!-- END GENERATED NATIVE COMMANDS -->' \
	"$work_dir/native.md" || status=1

check_block "$COMPAT_PAGE" \
	'<!-- BEGIN GENERATED COMPAT COMMANDS -->' \
	'<!-- END GENERATED COMPAT COMMANDS -->' \
	"$work_dir/compat.md" || status=1

check_block "$COMPAT_PAGE" \
	'<!-- BEGIN GENERATED STRICT COMPAT CLASSIFICATION -->' \
	'<!-- END GENERATED STRICT COMPAT CLASSIFICATION -->' \
	"$work_dir/strict.md" || status=1

check_page "$FLAGS_PAGE" "$work_dir/flags.md" || status=1

# A second copy of any block elsewhere would go stale unchecked, so each marker
# is required to be unique to the page checked above. The pairs are listed
# rather than derived because the pairing IS the claim: a marker whose carrier
# moved must fail here rather than be discovered wherever it landed.
#
# A marker is matched anchored to its own line, not as a substring. A page that
# DOCUMENTS the marker -- docs/site/CONTENT_INVENTORY.md names it in the cell
# that says where the block comes from -- is not a second carrier of the block,
# and a check that could not tell the two apart would force the documentation
# to misspell the thing it documents.
while IFS='|' read -r begin carrier; do
	[ -n "$begin" ] || continue
	found="$(git grep -l -E -e "^${begin}\$" -- '*.md' '*.mdx' || true)"
	if [ "$found" != "$carrier" ]; then
		echo "check-command-reference: $begin appears in files this script does not check:" >&2
		echo "$found" | sed 's/^/  /' >&2
		status=1
	fi
done <<-CARRIERS
	<!-- BEGIN GENERATED NATIVE COMMANDS -->|$NATIVE_PAGE
	<!-- BEGIN GENERATED COMPAT COMMANDS -->|$COMPAT_PAGE
	<!-- BEGIN GENERATED STRICT COMPAT CLASSIFICATION -->|$COMPAT_PAGE
CARRIERS

if [ "$status" -eq 0 ] && [ "$mode" = check ]; then
	native_rows=$(($(wc -l <"$work_dir/native.md") - 2))
	compat_rows=$(($(wc -l <"$work_dir/compat.md") - 2))
	strict_rows=$(($(wc -l <"$work_dir/strict.md") - 2))
	echo "check-command-reference: OK (${native_rows} ptah paths, ${compat_rows} ptah-compat paths," \
		"${strict_rows} removed by PTAH_ATLAS_STRICT_COMPAT, and the flag page)"
fi
exit "$status"
