#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ptah_bin="${PTAH_BIN:-$repo_root/bin/ptah}"
workspace="$(mktemp -d "${TMPDIR:-/tmp}/ptah-protobuf-export-acceptance.XXXXXX")"
trap 'rm -rf "$workspace"' EXIT

proto_package="acme.inventory.v1"
proto_relative_path="acme/inventory/v1/schema.proto"
go_package="example.com/ptahprotoacceptance/acme/inventory/v1;inventoryv1"

require_command() {
	if ! command -v "$1" >/dev/null 2>&1; then
		printf 'required command is unavailable: %s\n' "$1" >&2
		exit 1
	fi
}

for command in buf protoc protoc-gen-go python3; do
	require_command "$command"
done
if [[ ! -x "$ptah_bin" ]]; then
	printf 'ptah binary is not executable: %s\n' "$ptah_bin" >&2
	exit 1
fi
if [[ -z "${PROTOC_INCLUDE:-}" || ! -d "$PROTOC_INCLUDE" ]]; then
	printf 'PROTOC_INCLUDE must name the include directory shipped with protoc: %s\n' \
		"${PROTOC_INCLUDE:-<unset>}" >&2
	exit 1
fi

write_buf_config() {
	local proto_root="$1"
	cat >"$proto_root/buf.yaml" <<'YAML'
version: v2
modules:
  - path: .
lint:
  use:
    - STANDARD
breaking:
  use:
    - WIRE_JSON
YAML
	cat >"$proto_root/buf.gen.yaml" <<'YAML'
version: v2
plugins:
  - local: protoc-gen-go
    out: ../gen
    opt: paths=source_relative
YAML
}

export_schema() {
	local source_root="$1"
	local proto_root="$2"
	shift 2
	"$ptah_bin" schema export \
		--to protobuf \
		--root-dir "$source_root" \
		--out "$proto_root/$proto_relative_path" \
		--proto-package "$proto_package" \
		--go-package "$go_package" \
		"$@"
}

check_proto_module() {
	local proto_root="$1"
	(
		cd "$proto_root"
		buf lint
		buf format --diff --exit-code
		buf build -o /dev/null
	)
}

# assert_generated_go_is_clean proves the generated header is not the .proto's
# leading detached comment. protoc-gen-go copies that comment verbatim to the top
# of every .pb.go it writes, so a header in the leading position put Ptah's
# content digest into every consumer's Go source and made the first
# "Code generated by" line of that source name ptah instead of protoc-gen-go.
assert_generated_go_is_clean() {
	local generated="$workspace/gen/${proto_relative_path%.proto}.pb.go"
	if [[ ! -f "$generated" ]]; then
		printf 'generated Go is missing: %s\n' "$generated" >&2
		exit 1
	fi
	local ptah_lines
	ptah_lines="$(grep -cE 'ptah:content-sha256|ptah:protobuf-export-version' "$generated" || true)"
	if [[ "$ptah_lines" != "0" ]]; then
		printf 'generated Go carries %s ptah header line(s): %s\n' "$ptah_lines" "$generated" >&2
		exit 1
	fi
	local first_line
	first_line="$(head -n 1 "$generated")"
	if [[ "$first_line" != "// Code generated by protoc-gen-go. DO NOT EDIT." ]]; then
		printf 'first line of generated Go is "%s", expected protoc-gen-go own marker\n' "$first_line" >&2
		exit 1
	fi
	# The .proto still satisfies the Go generated-code convention.
	if ! grep -qE '^// Code generated .* DO NOT EDIT\.$' "$base_proto/$proto_relative_path"; then
		printf 'generated .proto lost its "Code generated" marker\n' >&2
		exit 1
	fi
}

assert_changed() {
	local before="$1"
	local after="$2"
	if cmp -s "$before" "$after"; then
		printf 'expected protobuf export to change, but it remained byte-identical\n' >&2
		exit 1
	fi
	diff -u "$before" "$after" || true
}

base_proto="$workspace/proto"
mkdir -p "$(dirname "$base_proto/$proto_relative_path")"
write_buf_config "$base_proto"
export_schema "$repo_root/stubs" "$base_proto"
check_proto_module "$base_proto"

(
	cd "$base_proto"
	protoc \
		--proto_path=. \
		--proto_path="$PROTOC_INCLUDE" \
		--descriptor_set_out="$workspace/schema.pb" \
		"$proto_relative_path"
	buf generate
)

assert_generated_go_is_clean

go_language_version="$(awk '/^go /{print $2; exit}' "$repo_root/go.mod")"
cat >"$workspace/gen/go.mod" <<EOF
module example.com/ptahprotoacceptance

go ${go_language_version}

require google.golang.org/protobuf ${PROTOC_GEN_GO_VERSION:-v1.36.11}
EOF
(
	cd "$workspace/gen"
	go mod tidy
	go build ./...
)

cp "$base_proto/$proto_relative_path" "$workspace/schema.first.proto"
export_schema "$repo_root/stubs" "$base_proto"
cmp "$workspace/schema.first.proto" "$base_proto/$proto_relative_path"

baseline="$workspace/proto-baseline"
cp -R "$base_proto" "$baseline"

run_compatible_case() {
	local name="$1"
	local mutation="$2"
	shift 2
	local case_root="$workspace/cases/$name"
	local source_root="$case_root/stubs"
	local proto_root="$case_root/proto"

	mkdir -p "$case_root"
	cp -R "$repo_root/stubs" "$source_root"
	cp -R "$baseline" "$proto_root"
	python3 "$repo_root/scripts/mutate-protobuf-export-fixture.py" "$mutation" "$source_root"
	export_schema "$source_root" "$proto_root" "$@"
	check_proto_module "$proto_root"
	(
		cd "$proto_root"
		buf breaking --against "$baseline"
	)

	if [[ "$mutation" == "reorder-columns" ]]; then
		cmp "$baseline/$proto_relative_path" "$proto_root/$proto_relative_path"
	else
		assert_changed "$baseline/$proto_relative_path" "$proto_root/$proto_relative_path"
	fi
}

run_compatible_case additive add-column
run_compatible_case reordered reorder-columns
run_compatible_case removed-field remove-column
run_compatible_case tombstoned-type remove-type --proto-type-removal tombstone

# A baseline written in the retired version 1 layout must be REFUSED, and
# refused by its version rather than as a foreign file: the two diagnoses have
# different remedies, and "this file was not generated by ptah" sends the reader
# hunting for someone else's tool. The version 1 file is produced from the
# current export rather than checked in, so the case never drifts away from the
# schema next to it.
retired_root="$workspace/cases/version-one-baseline"
mkdir -p "$retired_root"
cp -R "$baseline" "$retired_root/proto"
python3 "$repo_root/scripts/downgrade-protobuf-export-to-v1.py" \
	"$retired_root/proto/$proto_relative_path"
if ! grep -q '^// ptah:protobuf-export-version=1$' "$retired_root/proto/$proto_relative_path"; then
	printf 'version 1 fixture was not produced\n' >&2
	exit 1
fi
cp "$retired_root/proto/$proto_relative_path" "$retired_root/before.proto"
if export_schema "$repo_root/stubs" "$retired_root/proto" >"$retired_root/out" 2>&1; then
	printf 'export over a version 1 baseline unexpectedly succeeded\n' >&2
	cat "$retired_root/out" >&2
	exit 1
fi
if ! grep -q 'file declares export version 1, this Ptah reads and writes only 2' "$retired_root/out"; then
	printf 'version 1 baseline was not refused by its version:\n' >&2
	cat "$retired_root/out" >&2
	exit 1
fi
if grep -q 'was not generated by ptah' "$retired_root/out"; then
	printf 'version 1 baseline was misdiagnosed as a foreign file:\n' >&2
	cat "$retired_root/out" >&2
	exit 1
fi
# A refusal must not have written anything.
cmp "$retired_root/before.proto" "$retired_root/proto/$proto_relative_path"

breaking_root="$workspace/cases/incompatible-type"
cp -R "$repo_root/stubs" "$breaking_root-stubs"
cp -R "$baseline" "$breaking_root-proto"
python3 "$repo_root/scripts/mutate-protobuf-export-fixture.py" change-type "$breaking_root-stubs"
export_schema "$breaking_root-stubs" "$breaking_root-proto" \
	--proto-on-incompatible-change renumber
check_proto_module "$breaking_root-proto"
assert_changed "$baseline/$proto_relative_path" "$breaking_root-proto/$proto_relative_path"
if (
	cd "$breaking_root-proto"
	buf breaking --against "$baseline"
); then
	printf 'buf breaking unexpectedly accepted an incompatible field-type change\n' >&2
	exit 1
fi

printf 'Protobuf export acceptance: OK\n'
