#!/usr/bin/env bash
# Proves check-capability-status.sh fails on each shape it exists to refuse.
#
# The gate reports OK over a file it never really read just as readily as over a
# correct one, and a status file is exactly the kind of artifact where nobody
# would notice: it is long, it is generated, and it is only wrong on the day the
# matrix changed. So every rule gets a mutant.
#
# Each case copies the committed file into a temp directory, breaks one thing,
# and requires the gate to refuse. A case that passes is a rule not in effect.
set -euo pipefail

STATUS_FILE="docs/site/src/content/docs/databases/capability-status.md"

failures=0
cases=0

# expect_refusal breaks a copy of the committed pair and requires a non-zero
# exit naming the rule.
expect_refusal() {
	name="$1"
	needle="$2"
	mutate="$3"

	cases=$((cases + 1))
	dir="$(mktemp -d)"
	cp "$STATUS_FILE" "${dir}/status.md"

	( cd "$dir" && eval "$mutate" )

	if output="$(scripts/check-capability-status.sh "${dir}/status.md" 2>&1)"; then
		echo "  ${name}: the gate passed over a broken file" >&2
		failures=$((failures + 1))
	elif ! printf '%s' "$output" | grep -qF "$needle"; then
		echo "  ${name}: refused, but not for the reason under test" >&2
		echo "    wanted: ${needle}" >&2
		echo "    got:    ${output}" >&2
		failures=$((failures + 1))
	fi
	rm -rf "$dir"
}

# A row deleted by hand. The census shrinks, and a missing row reads exactly
# like a passing one -- which is the whole reason this gate reads the
# declaration rather than the file's own header.
expect_refusal "a runnable cell loses its row" \
	"runnable cells have no row" \
	"grep -v '| \`postgres-18\` |' status.md >tmp && mv tmp status.md"

# The generated header removed. Nothing then tells the next reader that typing
# in this file is pointless.
expect_refusal "the generated header is gone" \
	"has lost its generated header" \
	"grep -v 'Generated by' status.md >tmp && mv tmp status.md"

# A verdict flipped by hand without touching the summary. The two statements
# describe one run and a hand edit changes one of them.
expect_refusal "a verdict is flipped and the summary is not" \
	"the summary claims" \
	"sed 's/| PASS |\$/| SUITE |/' status.md >tmp && mv tmp status.md"

# A declared line the tier cannot run, dropped. The identity is
# declared == runnable + skipped, and this is the half a table of results
# silently loses.
expect_refusal "a skipped line is not named" \
	"the census is short" \
	"grep -v 'sqlite-3' status.md >tmp && mv tmp status.md"

if [ "$failures" -ne 0 ]; then
	echo "check-capability-status --selftest: FAILED (${failures} of ${cases})" >&2
	exit 1
fi
echo "check-capability-status --selftest: OK (${cases} refusals)"
