#!/usr/bin/env python3

"""Rewrite a generated .proto into the version 1 layout.

Version 1 carried the three generated header lines at the top of the file, where
they were the file's leading detached comment and protoc-gen-go copied them into
every .pb.go. Version 2 writes the same lines at the foot instead.

Ptah only ever writes version 2, so this is the only way for an acceptance run to
obtain the on-disk shape older releases left behind and prove that it is migrated
rather than refused.
"""

import argparse
import hashlib
from pathlib import Path

MARKER = "// Code generated by ptah schema export --to protobuf; DO NOT EDIT."
VERSION_PREFIX = "// ptah:protobuf-export-version="
DIGEST_PREFIX = "// ptah:content-sha256="


def stamp(lines: list[str]) -> list[str]:
    """Write the content digest of everything except the digest line itself.

    The line list is the whole split of the file, so it ends in the empty element
    the trailing newline produces. Dropping that element here would hash bytes the
    exporter never hashes and every stamped file would read back as modified.
    """
    index = [i for i, line in enumerate(lines) if line.startswith(DIGEST_PREFIX)]
    if len(index) != 1:
        raise SystemExit(f"expected exactly one digest line, found {len(index)}")
    kept = lines[: index[0]] + lines[index[0] + 1 :]
    digest = hashlib.sha256("\n".join(kept).encode()).hexdigest()
    lines[index[0]] = DIGEST_PREFIX + digest
    return lines


def downgrade(path: Path) -> None:
    lines = path.read_text().split("\n")
    if lines[-1] != "":
        raise SystemExit(f"{path} does not end in exactly one newline")
    header, body = lines[-4:-1], lines[:-4]
    if header[0] != MARKER:
        raise SystemExit(f"{path} does not carry the header at its foot")
    if not header[1].startswith(VERSION_PREFIX):
        raise SystemExit(f"{path} does not carry a version line under its marker")
    header[1] = VERSION_PREFIX + "1"
    while body and body[-1] == "":
        body.pop()
    path.write_text("\n".join(stamp(header + body + [""])))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("proto_path", type=Path)
    downgrade(parser.parse_args().proto_path)


if __name__ == "__main__":
    main()
