// Package goschematogo renders goschema databases as annotated Go source.
package goschematogo

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"ptah.run/core/ast"
	"ptah.run/core/platform"
	"ptah.run/core/schemamodel"
	"ptah.run/internal/dialectscope"
	"ptah.run/internal/rowdeletion"
	"ptah.run/internal/schemaprep"
	"ptah.run/internal/uniquename"
	"ptah.run/internal/ydbchangefeed"
	"ptah.run/internal/ydbcoordination"
	"ptah.run/internal/ydbfamily"
	"ptah.run/internal/ydbpartition"
	"ptah.run/internal/ydbreplication"
	"ptah.run/internal/ydbtopic"
	"ptah.run/internal/ydbtype"
)

const generatedHeader = "// Code generated by ptah introspect; DO NOT EDIT.\n\n"

// Options controls annotated Go source rendering.
type Options struct {
	PackageName     string
	PerTable        bool
	SingleFile      bool
	LowercaseFields bool
	AddJSONTags     bool
	AddDBTags       bool
	// Dialect names the server the schema was read from. It decides the Go
	// type of a field where a type name means one thing on that server and
	// another elsewhere: YDB's Int8 is one byte and PostgreSQL's int8 is
	// eight, and YDB's String is bytes. Empty reads every type name the way
	// the SQL engines spell it.
	Dialect string
}

// File is one generated Go file.
type File struct {
	Name string
	Data []byte
}

type attr struct {
	name  string
	value string
	set   bool
}

// Render returns annotated Go source files for db.
func Render(db *schemamodel.Database, opts Options) ([]File, error) {
	if db == nil {
		return nil, fmt.Errorf("database schema is nil")
	}
	opts = normalizeOptions(opts)
	if err := validatePackageName(opts.PackageName); err != nil {
		return nil, err
	}
	if err := validateIndexIncludeColumns(db.Indexes); err != nil {
		return nil, err
	}
	if err := refuseNarrowedDeleteActions(db.Constraints); err != nil {
		return nil, err
	}
	// The key annotations have no attribute for a deferral (stokaro/ptah#3824).
	if keys := schemaprep.DeferrableKeys(db); len(keys) > 0 {
		return nil, fmt.Errorf("%s defers its check, which a Go annotation cannot represent", keys[0])
	}
	// Nor for a constraint the server does not check, or a foreign key's
	// MATCH type (stokaro/ptah#3853).
	if clauses := schemaprep.EnforcementAndMatch(db); len(clauses) > 0 {
		return nil, fmt.Errorf("%s, which a Go annotation cannot represent", clauses[0])
	}
	// The constraint annotation has no attribute for NOT VALID.
	if unvalidated := schemaprep.UnvalidatedConstraints(db); len(unvalidated) > 0 {
		return nil, fmt.Errorf("%s is NOT VALID, which a Go annotation cannot represent", unvalidated[0])
	}
	if platform.NormalizeDialect(opts.Dialect) == platform.YDB {
		if err := refuseNullableYDBKeys(db); err != nil {
			return nil, err
		}
	}

	ctx := newRenderContext(db, opts)
	if opts.SingleFile {
		file, err := ctx.renderSingleFile()
		if err != nil {
			return nil, err
		}
		return []File{file}, nil
	}
	return ctx.renderPerTableFiles()
}

// refuseNullableYDBKeys refuses a YDB key column the server reports as
// nullable. YDB accepts one, and takes one row whose key is NULL, but no Ptah
// declaration can ask for it: the YDB renderer writes NOT NULL on every key
// column. Written as an ordinary key field, the column would be rebuilt NOT
// NULL wherever the models are applied, and planned against the database they
// came from it is a SET NOT NULL that YDB refuses.
func refuseNullableYDBKeys(db *schemamodel.Database) error {
	tableKeys := make(map[string][]string, len(db.Tables))
	tableNames := make(map[string]string, len(db.Tables))
	for _, table := range db.Tables {
		tableKeys[table.StructName] = table.PrimaryKey
		tableNames[table.StructName] = table.QualifiedName()
	}
	for _, field := range db.Fields {
		if !field.Nullable || !field.Primary && !slices.Contains(tableKeys[field.StructName], field.Name) {
			continue
		}
		return fmt.Errorf("column %q of table %q is a nullable key column, which no Ptah declaration can "+
			"represent: Ptah writes NOT NULL on every YDB key column", field.Name, tableNames[field.StructName])
	}
	return nil
}

// refuseNarrowedDeleteActions refuses a foreign key whose ON DELETE action is
// limited to some of its columns. The foreign_key annotation has no attribute
// for the list, and writing the key without it would set every referencing
// column where the schema sets some (stokaro/ptah#3562).
func refuseNarrowedDeleteActions(constraints []schemamodel.Constraint) error {
	for _, constraint := range constraints {
		if constraint.NarrowsDeleteAction() {
			return fmt.Errorf(
				"foreign key %q limits ON DELETE %s to columns %s, which a Go annotation cannot represent",
				constraint.Name, constraint.OnDelete, strings.Join(constraint.OnDeleteColumns, ", "),
			)
		}
	}
	return nil
}

func validateIndexIncludeColumns(indexes []schemamodel.Index) error {
	for _, index := range indexes {
		for i, column := range index.IncludeColumns {
			switch {
			case column == "":
				return fmt.Errorf("index %q INCLUDE column %d is empty and cannot be represented in a Go annotation", index.Name, i+1)
			case strings.TrimSpace(column) != column:
				return fmt.Errorf(
					"index %q INCLUDE column %d %q cannot be represented in a Go annotation: leading or trailing whitespace is not allowed",
					index.Name,
					i+1,
					column,
				)
			case strings.Contains(column, ","):
				return fmt.Errorf(
					"index %q INCLUDE column %d %q cannot be represented in a Go annotation: commas delimit column names",
					index.Name,
					i+1,
					column,
				)
			}
		}
	}
	return nil
}

// WriteDir writes generated files to outDir.
func WriteDir(outDir string, files []File) error {
	if strings.TrimSpace(outDir) == "" {
		return fmt.Errorf("output directory is required")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	for _, file := range files {
		if strings.TrimSpace(file.Name) == "" {
			return fmt.Errorf("generated file has empty name")
		}
		if !isSafeFileName(file.Name) {
			return fmt.Errorf("unsafe generated file name %q", file.Name)
		}
		path := filepath.Join(outDir, file.Name)
		if err := os.WriteFile(path, file.Data, 0o600); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func normalizeOptions(opts Options) Options {
	if opts.PackageName == "" {
		opts.PackageName = "models"
	}
	if !opts.SingleFile {
		opts.PerTable = true
	}
	return opts
}

func validatePackageName(name string) error {
	if !token.IsIdentifier(name) || token.Lookup(name).IsKeyword() {
		return fmt.Errorf("invalid package name %q", name)
	}
	return nil
}

type renderContext struct {
	db                 *schemamodel.Database
	opts               Options
	enumsByName        map[string]schemamodel.Enum
	fieldsByTable      map[string][]schemamodel.Field
	indexesByTable     map[string][]schemamodel.Index
	constraintsByTable map[string][]schemamodel.Constraint
	rlsByTable         map[string][]schemamodel.RLSPolicy
	rlsEnabledByTable  map[string][]schemamodel.RLSEnabledTable
	triggersByTable    map[string][]schemamodel.Trigger
	imports            map[string]struct{}
}

func newRenderContext(db *schemamodel.Database, opts Options) *renderContext {
	ctx := &renderContext{
		db:                 db,
		opts:               opts,
		enumsByName:        make(map[string]schemamodel.Enum, len(db.Enums)),
		fieldsByTable:      make(map[string][]schemamodel.Field),
		indexesByTable:     make(map[string][]schemamodel.Index),
		constraintsByTable: make(map[string][]schemamodel.Constraint),
		rlsByTable:         make(map[string][]schemamodel.RLSPolicy),
		rlsEnabledByTable:  make(map[string][]schemamodel.RLSEnabledTable),
		triggersByTable:    make(map[string][]schemamodel.Trigger),
	}
	for _, enum := range db.Enums {
		ctx.enumsByName[enum.Name] = enum
	}
	for _, field := range db.Fields {
		ctx.fieldsByTable[field.StructName] = append(ctx.fieldsByTable[field.StructName], field)
	}
	for _, index := range db.Indexes {
		ctx.indexesByTable[indexOwner(index)] = append(ctx.indexesByTable[indexOwner(index)], index)
	}
	for _, constraint := range db.Constraints {
		ctx.constraintsByTable[constraintOwner(constraint)] = append(ctx.constraintsByTable[constraintOwner(constraint)], constraint)
	}
	for _, policy := range db.RLSPolicies {
		ctx.rlsByTable[policy.StructName] = append(ctx.rlsByTable[policy.StructName], policy)
	}
	for _, table := range db.RLSEnabledTables {
		ctx.rlsEnabledByTable[table.StructName] = append(ctx.rlsEnabledByTable[table.StructName], table)
	}
	for _, trigger := range db.Triggers {
		ctx.triggersByTable[trigger.Table] = append(ctx.triggersByTable[trigger.Table], trigger)
	}
	return ctx
}

func (ctx *renderContext) renderSingleFile() (File, error) {
	source, err := ctx.renderFile(func(w *sourceWriter) {
		ctx.writeEnums(w)
		ctx.writeGlobalObjects(w)
		for _, table := range sortedTables(ctx.db.Tables) {
			ctx.writeTable(w, table)
		}
	})
	if err != nil {
		return File{}, err
	}
	return File{Name: "schema.go", Data: source}, nil
}

func (ctx *renderContext) renderPerTableFiles() ([]File, error) {
	files := make([]File, 0, len(ctx.db.Tables)+2)
	if len(ctx.db.Enums) > 0 {
		data, err := ctx.renderFile(func(w *sourceWriter) {
			ctx.writeEnums(w)
		})
		if err != nil {
			return nil, err
		}
		files = append(files, File{Name: "enums.go", Data: data})
	}
	if ctx.hasGlobalObjects() {
		data, err := ctx.renderFile(func(w *sourceWriter) {
			ctx.writeGlobalObjects(w)
		})
		if err != nil {
			return nil, err
		}
		files = append(files, File{Name: "schema_objects.go", Data: data})
	}
	// A file name is derived by lower-casing the qualified table name, so
	// "Docs" and docs derive one, and on a case-insensitive filesystem no other
	// spelling would keep them apart. Written under one name, the second file
	// replaces the first and a table disappears from the output with no error
	// (stokaro/ptah#3647). Each table claims its file name by the rule
	// [uniquename.Next] holds, in the sorted order the tables are written in.
	taken := make(map[string]bool, len(files)+len(ctx.db.Tables))
	for _, file := range files {
		taken[strings.TrimSuffix(file.Name, ".go")] = true
	}
	for _, table := range sortedTables(ctx.db.Tables) {
		data, err := ctx.renderFile(func(w *sourceWriter) {
			ctx.writeTable(w, table)
		})
		if err != nil {
			return nil, err
		}
		name := uniquename.Next(fileBaseForTable(table), func(name string) bool { return taken[name] })
		taken[name] = true
		files = append(files, File{Name: name + ".go", Data: data})
	}
	return files, nil
}

func (ctx *renderContext) renderFile(writeBody func(*sourceWriter)) ([]byte, error) {
	ctx.imports = make(map[string]struct{})
	body := &sourceWriter{}
	writeBody(body)

	w := &sourceWriter{}
	w.writeString(generatedHeader)
	w.writeLine("package " + ctx.opts.PackageName)
	w.writeLine("")
	if len(ctx.imports) > 0 {
		w.writeLine("import (")
		for _, path := range sortedImportPaths(ctx.imports) {
			w.writeLine("\t" + strconv.Quote(path))
		}
		w.writeLine(")")
		w.writeLine("")
	}
	w.writeString(body.buf.String())

	formatted, err := format.Source(w.buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w\n%s", err, w.buf.String())
	}
	return formatted, nil
}

// hasGlobalObjects reports whether anything needs the struct the global
// annotations hang off.
//
// It decides whether that struct is written at all, so a family emitted by
// writeGlobalObjects and missing here produces a comment attached to nothing.
// The parser reads struct doc comments, so such a comment is not refused -- it
// is silently not read, and the export loses the object with every gate green.
func (ctx *renderContext) hasGlobalObjects() bool {
	return len(ctx.db.Schemas) > 0 ||
		len(ctx.db.Extensions) > 0 ||
		len(ctx.db.Functions) > 0 ||
		len(ctx.db.Views) > 0 ||
		len(ctx.db.MaterializedViews) > 0 ||
		len(ctx.db.Roles) > 0 ||
		len(ctx.db.Grants) > 0 ||
		len(ctx.db.RevokedGrants) > 0 ||
		len(ctx.db.DefaultPrivileges) > 0 ||
		len(ctx.db.CompositeTypes) > 0 ||
		len(ctx.db.Domains) > 0 ||
		len(ctx.db.Ranges) > 0 ||
		len(ctx.db.Sequences) > 0 ||
		len(ctx.db.Topics) > 0 ||
		len(ctx.db.AsyncReplications) > 0 ||
		len(ctx.db.Transfers) > 0 ||
		len(ctx.db.CoordinationNodes) > 0
}

func (ctx *renderContext) writeEnums(w *sourceWriter) {
	for _, enum := range sortedEnums(ctx.db.Enums) {
		w.writeComment(annotation("ptah:schema:enum",
			attr{name: "name", value: enum.Name, set: true},
			attr{name: "values", value: strings.Join(enum.Values, ","), set: len(enum.Values) > 0},
			attr{name: "comment", value: enum.Comment, set: enum.Comment != ""},
		))
	}
	if len(ctx.db.Enums) > 0 {
		w.writeLine("type PtahEnums struct{}")
		w.writeLine("")
	}
	for _, enum := range sortedEnums(ctx.db.Enums) {
		typeName := exportedIdentifier(enum.Name)
		w.writeLine("type " + typeName + " string")
		w.writeLine("")
		w.writeLine("const (")
		for _, value := range enum.Values {
			constName := typeName + exportedIdentifier(value)
			w.writeLine("\t" + constName + " " + typeName + " = " + strconv.Quote(value))
		}
		w.writeLine(")")
		w.writeLine("")
	}
}

func (ctx *renderContext) writeGlobalObjects(w *sourceWriter) {
	for _, schema := range sortedSchemas(ctx.db.Schemas) {
		w.writeComment(annotation("ptah:schema:schema",
			attr{name: "name", value: schema.Name, set: true},
			attr{name: "comment", value: schema.Comment, set: schema.Comment != ""},
		))
	}
	// The user types come before everything that can name one. A column
	// declared over a domain keeps the domain's name as its type, so the
	// declaration has to be in the file that carries the column.
	for _, domain := range sortedDomains(ctx.db.Domains) {
		w.writeComment(domainAnnotation(domain))
	}
	for _, composite := range sortedCompositeTypes(ctx.db.CompositeTypes) {
		w.writeComment(compositeAnnotation(composite))
	}
	for _, rangeType := range sortedRanges(ctx.db.Ranges) {
		w.writeComment(rangeAnnotation(rangeType))
	}
	for _, sequence := range sortedSequences(ctx.db.Sequences) {
		w.writeComment(sequenceAnnotation(sequence))
	}
	for _, extension := range sortedExtensions(ctx.db.Extensions) {
		w.writeComment(annotation("ptah:schema:extension",
			attr{name: "name", value: extension.Name, set: true},
			attr{name: "schema", value: extension.Schema, set: extension.Schema != ""},
			attr{name: "if_not_exists", value: strconv.FormatBool(extension.IfNotExists), set: extension.IfNotExists},
			attr{name: "version", value: extension.Version, set: extension.Version != ""},
			attr{name: "comment", value: extension.Comment, set: extension.Comment != ""},
			dialectsAttr(extension.Dialects),
		))
	}
	for _, function := range sortedFunctions(ctx.db.Functions) {
		w.writeComment(functionAnnotation(function))
	}
	for _, view := range sortedViews(ctx.db.Views) {
		w.writeComment(annotation("ptah:schema:view",
			attr{name: "name", value: view.Name, set: true},
			attr{name: "body", value: view.Body, set: true},
			attr{name: "with_check", value: strconv.FormatBool(view.WithCheck), set: view.WithCheck},
			attr{name: "comment", value: view.Comment, set: view.Comment != ""},
			dialectsAttr(view.Dialects),
		))
	}
	for _, view := range sortedMaterializedViews(ctx.db.MaterializedViews) {
		w.writeComment(annotation("ptah:schema:matview",
			attr{name: "name", value: view.Name, set: true},
			attr{name: "body", value: view.Body, set: true},
			attr{name: "comment", value: view.Comment, set: view.Comment != ""},
			dialectsAttr(view.Dialects),
		))
	}
	for _, topic := range sortedTopics(ctx.db.Topics) {
		for _, comment := range topicAnnotations(topic) {
			w.writeComment(comment)
		}
	}
	for _, replication := range sortedReplications(ctx.db.AsyncReplications) {
		for _, comment := range replicationAnnotations(replication) {
			w.writeComment(comment)
		}
	}
	for _, transfer := range sortedTransfers(ctx.db.Transfers) {
		w.writeComment(transferAnnotation(transfer))
	}
	for _, role := range sortedRoles(ctx.db.Roles) {
		w.writeComment(roleAnnotation(role))
	}
	for _, grant := range sortedGrants(ctx.db.Grants) {
		w.writeComment(grantAnnotation(grant))
	}
	for _, revoked := range sortedGrants(ctx.db.RevokedGrants) {
		w.writeComment(revokeAnnotation(revoked))
	}
	for _, privilege := range sortedDefaultPrivileges(ctx.db.DefaultPrivileges) {
		w.writeComment(defaultPrivilegeAnnotation(privilege))
	}
	ctx.writeCoordinationNodes(w)
	if ctx.hasGlobalObjects() {
		w.writeLine("type PtahSchemaObjects struct{}")
		w.writeLine("")
	}
}

// writeCoordinationNodes writes an annotation for each of the database's YDB
// coordination nodes, broken out of [renderContext.writeGlobalObjects] to
// keep that function's branching under the complexity limit.
func (ctx *renderContext) writeCoordinationNodes(w *sourceWriter) {
	for _, node := range sortedCoordinationNodes(ctx.db.CoordinationNodes) {
		w.writeComment(coordinationNodeAnnotation(node))
	}
}

func (ctx *renderContext) writeTable(w *sourceWriter, table schemamodel.Table) {
	for _, policy := range ctx.rlsByTable[table.StructName] {
		w.writeComment(rlsPolicyAnnotation(policy))
	}
	for _, enabled := range ctx.rlsEnabledByTable[table.StructName] {
		w.writeComment(annotation("ptah:schema:rls:enable",
			attr{name: "table", value: enabled.Table, set: true},
			attr{name: "comment", value: enabled.Comment, set: enabled.Comment != ""},
			dialectsAttr(enabled.Dialects),
		))
	}
	for _, trigger := range ctx.triggersByTable[table.QualifiedName()] {
		w.writeComment(triggerAnnotation(trigger))
	}
	for _, constraint := range ctx.constraintsByTable[table.StructName] {
		w.writeComment(constraintAnnotation(constraint))
	}
	w.writeComment(tableAnnotation(table))
	for _, family := range ydbfamily.Stated(table.YDBColumnFamilies) {
		w.writeComment(annotation("ptah:schema:columnfamily", columnFamilyAttrs(family)...))
	}
	for _, changefeed := range table.Changefeeds {
		w.writeComment(annotation("ptah:schema:changefeed", changefeedAttrs(changefeed)...))
		for _, consumer := range changefeed.Consumers {
			w.writeComment(annotation("ptah:schema:changefeed:consumer", consumerAttrs(changefeed.Name, consumer)...))
		}
	}
	typeName := exportedIdentifier(firstNonEmpty(table.StructName, table.Name))
	w.writeLine("type " + typeName + " struct {")
	usedNames := make(map[string]struct{})
	for _, field := range ctx.fieldsByTable[table.StructName] {
		fieldName := ctx.fieldIdentifier(field, usedNames)
		w.writeComment("\t" + annotation("ptah:schema:field", fieldAttrs(field)...))
		w.writeLine("\t" + fieldName + " " + ctx.goType(field) + structTags(field, ctx.opts))
	}
	for _, index := range ctx.indexesByTable[table.StructName] {
		w.writeComment("\t" + annotation("ptah:schema:index", indexAttrs(index)...))
		w.writeLine("\t_ struct{}")
	}
	w.writeLine("}")
	w.writeLine("")
}

func (ctx *renderContext) fieldIdentifier(field schemamodel.Field, used map[string]struct{}) string {
	name := firstNonEmpty(field.FieldName, field.Name)
	identifier := exportedIdentifier(name)
	if ctx.opts.LowercaseFields {
		identifier = unexportedIdentifier(name)
	}
	base := identifier
	for i := 2; ; i++ {
		if _, exists := used[identifier]; !exists {
			used[identifier] = struct{}{}
			return identifier
		}
		identifier = fmt.Sprintf("%s%d", base, i)
	}
}

func (ctx *renderContext) goType(field schemamodel.Field) string {
	base, importPath := sqlTypeToGoType(field.Type), ""
	if base == "time.Time" {
		importPath = "time"
	}
	if platform.NormalizeDialect(ctx.opts.Dialect) == platform.YDB {
		// The YDB reader reports YDB's own type names, and internal/ydbtype
		// is the one place that knows what each holds.
		if goType, ok := ydbtype.GoTypeOf(field.Type); ok {
			base, importPath = goType.Name, goType.Import
		}
	}
	if _, ok := ctx.enumsByName[field.Type]; ok {
		base, importPath = exportedIdentifier(field.Type), ""
	}
	if importPath != "" {
		ctx.imports[importPath] = struct{}{}
	}
	if field.Nullable && base != "[]byte" {
		return "*" + base
	}
	return base
}

// dialectsAttr renders the dialect scope an object was declared with.
//
// It is one helper rather than an expression per annotation for the reason
// parseDialectScope gives on the reading side: a scope written differently in
// one place is a scope that omits an object from a target its author named.
// Here the failure runs the other way and is worse to debug -- an object whose
// scope is dropped on export reappears on every dialect, so the first symptom
// is a statement executed against an engine that was deliberately left out.
//
// The value is the canonical, sorted form dialectscope.Parse produced, joined
// the way the attribute is written, so exporting and re-reading is a fixed
// point rather than a spelling the parser has to normalize again.
func dialectsAttr(scope []string) attr {
	return attr{
		name:  dialectscope.Attribute,
		value: strings.Join(scope, ","),
		set:   len(scope) > 0,
	}
}

func tableAnnotation(table schemamodel.Table) string {
	attrs := []attr{
		{name: "name", value: table.Name, set: true},
		{name: "schema", value: table.Schema, set: table.Schema != ""},
		{name: "engine", value: table.Engine, set: table.Engine != ""},
		{name: "charset", value: table.Charset, set: table.Charset != ""},
		{name: "collate", value: table.Collate, set: table.Collate != ""},
		{name: "primary_key_comment", value: table.PrimaryKeyComment, set: table.PrimaryKeyComment != ""},
		{name: "primary_key_block_size", value: strconv.FormatUint(table.PrimaryKeyBlockSize, 10), set: table.PrimaryKeyBlockSize != 0},
		{name: "primary_key", value: strings.Join(table.PrimaryKey, ","), set: len(table.PrimaryKey) > 0},
		{name: "comment", value: table.Comment, set: table.Comment != ""},
	}
	attrs = append(attrs, rowDeletionAttrs(table.RowDeletionPolicy)...)
	return annotation("ptah:schema:table", append(attrs, tablePartitioningAttrs(table.YDBPartitioning)...)...)
}

// rowDeletionAttrs writes a table's row deletion policy as the attributes the
// annotation parser reads it from, and nothing for a table with no policy.
func rowDeletionAttrs(policy *ast.RowDeletionPolicySpec) []attr {
	if policy.IsZero() {
		return nil
	}
	return []attr{
		{name: rowdeletion.AttributeColumn, value: policy.Column, set: true},
		{name: rowdeletion.AttributeInterval, value: policy.Interval, set: true},
		{name: rowdeletion.AttributeUnit, value: policy.Unit, set: policy.Unit != ""},
	}
}

// columnFamilyAttrs writes a YDB column family as the attributes the
// annotation parser reads it from. A table's default family is written only
// where it holds something other than what YDB gives a family stating nothing
// (see [ydbfamily.Stated]), so a table nobody gave families exports none.
// keep_in_memory has no attribute: no statement writes it, and a declaration
// that leaves it out keeps what the table holds.
func columnFamilyAttrs(family ast.YDBColumnFamilySpec) []attr {
	return []attr{
		{name: ydbfamily.AttributeName, value: family.Name, set: true},
		{name: ydbfamily.AttributeData, value: family.Data, set: family.Data != ""},
		{name: ydbfamily.AttributeCompression, value: family.Compression, set: family.Compression != ""},
		{name: ydbfamily.AttributeCacheMode, value: family.CacheMode, set: family.CacheMode != ""},
		{name: ydbfamily.AttributeFields, value: strings.Join(family.Columns, ","), set: len(family.Columns) > 0},
	}
}

// changefeedAttrs writes a YDB changefeed as the attributes the annotation
// parser reads it from. A disabled changefeed is written as an enabled one:
// no annotation declares one disabled, because no statement disables one.
func changefeedAttrs(changefeed ast.ChangefeedSpec) []attr {
	flag := func(name string, on bool) attr { return attr{name: name, value: "true", set: on} }
	return []attr{
		{name: ydbchangefeed.AttributeName, value: changefeed.Name, set: true},
		{name: ydbchangefeed.AttributeMode, value: changefeed.Mode, set: true},
		{name: ydbchangefeed.AttributeFormat, value: changefeed.Format, set: true},
		flag(ydbchangefeed.AttributeVirtualTimestamps, changefeed.VirtualTimestamps),
		{name: ydbchangefeed.AttributeResolvedTimestamps, value: changefeed.ResolvedTimestamps,
			set: changefeed.ResolvedTimestamps != ""},
		flag(ydbchangefeed.AttributeInitialScan, changefeed.InitialScan),
		flag(ydbchangefeed.AttributeUserSIDs, changefeed.UserSIDs),
		flag(ydbchangefeed.AttributeSchemaChanges, changefeed.SchemaChanges),
		{name: ydbchangefeed.AttributeTopicMinActivePartitions,
			value: strconv.FormatUint(changefeed.TopicMinActivePartitions, 10), set: changefeed.TopicMinActivePartitions != 0},
		flag(ydbchangefeed.AttributeTopicAutoPartitioning, changefeed.TopicAutoPartitioning),
		{name: ydbchangefeed.AttributeRetentionPeriod, value: changefeed.RetentionPeriod, set: changefeed.RetentionPeriod != ""},
	}
}

// consumerAttrs writes a consumer of the changefeed named changefeed.
func consumerAttrs(changefeed string, consumer ast.TopicConsumerSpec) []attr {
	return []attr{
		{name: ydbchangefeed.AttributeChangefeed, value: changefeed, set: true},
		{name: ydbchangefeed.AttributeName, value: consumer.Name, set: true},
		{name: ydbchangefeed.AttributeImportant, value: "true", set: consumer.Important},
		{name: ydbchangefeed.AttributeReadFrom, value: consumer.ReadFrom, set: consumer.ReadFrom != ""},
		{name: ydbchangefeed.AttributeSupportedCodecs, value: strings.Join(consumer.SupportedCodecs, ","),
			set: len(consumer.SupportedCodecs) > 0},
		{name: ydbchangefeed.AttributeAvailabilityPeriod, value: consumer.AvailabilityPeriod,
			set: consumer.AvailabilityPeriod != ""},
	}
}

// tablePartitioningAttrs writes a YDB row table's settings as the attributes
// the annotation parser reads them from.
func tablePartitioningAttrs(spec *ast.YDBTablePartitioningSpec) []attr {
	if spec.IsZero() {
		return nil
	}
	shared := partitioningAttrs(&ast.IndexPartitioningSpec{
		BySize: spec.BySize, PartitionSizeMB: spec.PartitionSizeMB, ByLoad: spec.ByLoad,
		MinPartitions: spec.MinPartitions, MaxPartitions: spec.MaxPartitions, ReadReplicas: spec.ReadReplicas,
	})
	return append(shared,
		attr{name: ydbpartition.AttributeKeyBloomFilter, value: switchValue(spec.KeyBloomFilter), set: spec.KeyBloomFilter != nil},
		attr{name: ydbpartition.AttributeUniformPartitions, value: strconv.FormatUint(spec.UniformPartitions, 10),
			set: spec.UniformPartitions != 0},
		attr{name: ydbpartition.AttributePartitionAtKeys, value: ydbpartition.FormatSplitPoints(spec.PartitionAtKeys),
			set: len(spec.PartitionAtKeys) != 0},
	)
}

// switchValue writes a YDB setting that is switched on or off.
func switchValue(on *bool) string {
	if on != nil && *on {
		return "ENABLED"
	}
	return "DISABLED"
}

func fieldAttrs(field schemamodel.Field) []attr {
	return []attr{
		{name: "name", value: field.Name, set: true},
		{name: "type", value: field.Type, set: true},
		{name: "not_null", value: strconv.FormatBool(!field.Nullable), set: !field.Nullable},
		{name: "primary", value: strconv.FormatBool(field.Primary), set: field.Primary},
		{name: "auto_increment", value: strconv.FormatBool(field.AutoInc), set: field.AutoInc},
		{name: "identity_generation", value: field.IdentityGeneration, set: field.IdentityGeneration != ""},
		{name: "identity_start", value: field.IdentityStart, set: field.IdentityStart != ""},
		{name: "identity_increment", value: field.IdentityIncrement, set: field.IdentityIncrement != ""},
		{name: "identity_options", value: field.IdentityOptions, set: field.IdentityOptions != ""},
		{name: "unique", value: strconv.FormatBool(field.Unique), set: field.Unique},
		{name: "unique_expr", value: field.UniqueExpr, set: field.UniqueExpr != ""},
		{name: "default", value: field.Default, set: field.DefaultSet || field.Default != ""},
		{name: "default_expr", value: field.DefaultExpr, set: field.DefaultExpr != ""},
		{name: "foreign", value: field.Foreign, set: field.Foreign != ""},
		{name: "foreign_key_name", value: field.ForeignKeyName, set: field.ForeignKeyName != ""},
		{name: "on_delete", value: field.OnDelete, set: field.OnDelete != ""},
		{name: "on_update", value: field.OnUpdate, set: field.OnUpdate != ""},
		{name: "check", value: field.Check, set: field.Check != ""},
		{name: "check_name", value: field.CheckName, set: field.CheckName != ""},
		{name: "generated", value: field.GeneratedExpression, set: field.GeneratedExpression != ""},
		{name: "generated_kind", value: field.GeneratedKind, set: field.GeneratedKind != ""},
		{name: "comment", value: field.Comment, set: field.Comment != ""},
	}
}

func indexAttrs(index schemamodel.Index) []attr {
	return append(indexDefinitionAttrs(index), partitioningAttrs(index.Partitioning)...)
}

// partitioningAttrs writes a YDB global index's partitioning as the attributes
// the annotation parser reads it from.
func partitioningAttrs(spec *ast.IndexPartitioningSpec) []attr {
	if spec.IsZero() {
		return nil
	}
	count := func(n uint64) string { return strconv.FormatUint(n, 10) }
	return []attr{
		{name: ydbpartition.AttributeBySize, value: switchValue(spec.BySize), set: spec.BySize != nil},
		{name: ydbpartition.AttributePartitionSizeMB, value: count(spec.PartitionSizeMB), set: spec.PartitionSizeMB != 0},
		{name: ydbpartition.AttributeByLoad, value: switchValue(spec.ByLoad), set: spec.ByLoad != nil},
		{name: ydbpartition.AttributeMinPartitions, value: count(spec.MinPartitions), set: spec.MinPartitions != 0},
		{name: ydbpartition.AttributeMaxPartitions, value: count(spec.MaxPartitions), set: spec.MaxPartitions != 0},
		{name: ydbpartition.AttributeReadReplicas, value: spec.ReadReplicas, set: spec.ReadReplicas != ""},
	}
}

// indexDefinitionAttrs writes the attributes every dialect's index reads.
func indexDefinitionAttrs(index schemamodel.Index) []attr {
	return []attr{
		{name: "name", value: index.Name, set: true},
		{name: "fields", value: strings.Join(index.Fields, ","), set: len(index.Fields) > 0},
		{name: "include", value: strings.Join(index.IncludeColumns, ","), set: len(index.IncludeColumns) > 0},
		{name: "unique", value: strconv.FormatBool(index.Unique), set: index.Unique},
		{name: "type", value: index.Type, set: index.Type != ""},
		{name: "condition", value: index.Condition, set: index.Condition != ""},
		{name: "ops", value: index.Operator, set: index.Operator != ""},
		{name: "table", value: index.TableName, set: index.TableName != ""},
		{name: "granularity", value: strconv.Itoa(index.Granularity), set: index.Granularity > 0},
		{name: "comment", value: index.Comment, set: index.Comment != ""},
		{name: "invisible", value: strconv.FormatBool(index.Invisible), set: index.Invisible},
		{name: "key_block_size", value: strconv.FormatUint(index.KeyBlockSize, 10), set: index.KeyBlockSize != 0},
	}
}

func constraintAnnotation(constraint schemamodel.Constraint) string {
	return annotation("ptah:schema:constraint",
		attr{name: "name", value: constraint.Name, set: true},
		attr{name: "type", value: constraint.Type, set: true},
		attr{name: "table", value: constraint.Table, set: constraint.Table != ""},
		attr{name: "columns", value: strings.Join(constraint.Columns, ","), set: len(constraint.Columns) > 0},
		attr{name: "include", value: strings.Join(constraint.IncludeColumns, ","), set: len(constraint.IncludeColumns) > 0},
		attr{name: "key_block_size", value: strconv.FormatUint(constraint.KeyBlockSize, 10), set: constraint.KeyBlockSize != 0},
		attr{name: "using", value: constraint.UsingMethod, set: constraint.UsingMethod != ""},
		attr{name: "elements", value: constraint.ExcludeElements, set: constraint.ExcludeElements != ""},
		attr{name: "condition", value: constraint.WhereCondition, set: constraint.WhereCondition != ""},
		attr{name: "check", value: constraint.CheckExpression, set: constraint.CheckExpression != ""},
		attr{name: "foreign_table", value: constraint.ForeignTable, set: constraint.ForeignTable != ""},
		attr{name: "foreign_column", value: constraint.ForeignColumn, set: constraint.ForeignColumn != "" && len(constraint.ForeignColumns) <= 1},
		attr{name: "foreign_columns", value: strings.Join(constraint.ForeignColumns, ","), set: len(constraint.ForeignColumns) > 1},
		attr{name: "on_delete", value: constraint.OnDelete, set: constraint.OnDelete != ""},
		attr{name: "on_update", value: constraint.OnUpdate, set: constraint.OnUpdate != ""},
		attr{name: "comment", value: constraint.Comment, set: constraint.Comment != ""},
	)
}

// functionAnnotation writes a routine under the directive its kind names.
//
// A procedure is the same model with Kind set, and the parser has no attribute
// for that -- it reads a separate directive. Writing every routine as a
// function therefore turns a procedure read from a database into a function on
// the way out, which the grammar gives no way to say otherwise.
//
// A procedure returns nothing, so the returns attribute is left to the function
// arm rather than emitted and ignored.
func functionAnnotation(function schemamodel.Function) string {
	if function.IsProcedure() {
		return annotation("ptah:schema:procedure",
			attr{name: "name", value: function.Name, set: true},
			attr{name: "params", value: function.Parameters, set: function.Parameters != ""},
			attr{name: "language", value: function.Language, set: function.Language != ""},
			attr{name: "security", value: function.Security, set: function.Security != ""},
			attr{name: "volatility", value: function.Volatility, set: function.Volatility != ""},
			attr{name: "body", value: function.Body, set: true},
			attr{name: "comment", value: function.Comment, set: function.Comment != ""},
			dialectsAttr(function.Dialects),
		)
	}
	return annotation("ptah:schema:function",
		attr{name: "name", value: function.Name, set: true},
		attr{name: "params", value: function.Parameters, set: function.Parameters != ""},
		attr{name: "returns", value: function.Returns, set: function.Returns != ""},
		attr{name: "language", value: function.Language, set: function.Language != ""},
		attr{name: "security", value: function.Security, set: function.Security != ""},
		attr{name: "volatility", value: function.Volatility, set: function.Volatility != ""},
		// The planner attributes the parser reads; left out, an export read
		// back loses them (stokaro/ptah#3630).
		attr{name: "leakproof", value: "true", set: function.Leakproof},
		attr{name: "parallel", value: function.Parallel, set: function.Parallel != ""},
		attr{name: "strict", value: "true", set: function.Strict},
		attr{name: "settings", value: strings.Join(function.Settings, ";"), set: len(function.Settings) > 0},
		attr{name: "body", value: function.Body, set: true},
		attr{name: "comment", value: function.Comment, set: function.Comment != ""},
		dialectsAttr(function.Dialects),
	)
}

// domainAnnotation writes a domain.
//
// The base type is what makes this family load-bearing for `ptah introspect`:
// a column declared over a domain keeps type="<domain>", so an export without
// the domain describes a table whose column type nothing creates.
func domainAnnotation(domain schemamodel.Domain) string {
	return annotation("ptah:schema:domain",
		attr{name: "name", value: domain.Name, set: true},
		attr{name: "schema", value: domain.Schema, set: domain.Schema != ""},
		attr{name: "type", value: domain.BaseType, set: true},
		attr{name: "not_null", value: strconv.FormatBool(domain.NotNull), set: domain.NotNull},
		attr{name: "default", value: domain.Default, set: domain.Default != ""},
		attr{name: "default_expr", value: domain.DefaultExpr, set: domain.DefaultExpr != ""},
		attr{name: "check", value: domain.Check, set: domain.Check != ""},
		attr{name: "comment", value: domain.Comment, set: domain.Comment != ""},
		dialectsAttr(domain.Dialects),
	)
}

// compositeAnnotation writes a composite type.
//
// The field list is one attribute holding `name:type` pairs separated by
// commas, and its order is significant: the comparator joins the two sides
// positionally, so emitting the model's own order is what keeps a round trip
// quiet.
func compositeAnnotation(composite schemamodel.CompositeType) string {
	pairs := make([]string, 0, len(composite.Fields))
	for _, field := range composite.Fields {
		pairs = append(pairs, field.Name+":"+field.Type)
	}
	return annotation("ptah:schema:composite",
		attr{name: "name", value: composite.Name, set: true},
		attr{name: "schema", value: composite.Schema, set: composite.Schema != ""},
		attr{name: "fields", value: strings.Join(pairs, ","), set: len(pairs) > 0},
		attr{name: "comment", value: composite.Comment, set: composite.Comment != ""},
		dialectsAttr(composite.Dialects),
	)
}

// rangeAnnotation writes a range type.
func rangeAnnotation(rangeType schemamodel.Range) string {
	return annotation("ptah:schema:range",
		attr{name: "name", value: rangeType.Name, set: true},
		attr{name: "schema", value: rangeType.Schema, set: rangeType.Schema != ""},
		attr{name: "subtype", value: rangeType.Subtype, set: true},
		attr{name: "subtype_opclass", value: rangeType.SubtypeOpClass, set: rangeType.SubtypeOpClass != ""},
		attr{name: "collation", value: rangeType.Collation, set: rangeType.Collation != ""},
		attr{name: "canonical", value: rangeType.Canonical, set: rangeType.Canonical != ""},
		attr{name: "subtype_diff", value: rangeType.SubtypeDiff, set: rangeType.SubtypeDiff != ""},
		attr{name: "comment", value: rangeType.Comment, set: rangeType.Comment != ""},
		dialectsAttr(rangeType.Dialects),
	)
}

// sequenceAnnotation writes a standalone sequence.
//
// The numeric options are pointers on the model because "not stated" and
// "stated as zero" are different sequences, and a CACHE of 0 is a different
// declaration from no CACHE at all. Rendering the zero value for an unset
// option would write a sequence the database never had.
func sequenceAnnotation(sequence schemamodel.Sequence) string {
	return annotation("ptah:schema:sequence",
		attr{name: "name", value: sequence.Name, set: true},
		attr{name: "schema", value: sequence.Schema, set: sequence.Schema != ""},
		attr{name: "as", value: sequence.AsType, set: sequence.AsType != ""},
		sequenceNumberAttr("start", sequence.Start),
		sequenceNumberAttr("increment", sequence.Increment),
		sequenceNumberAttr("minvalue", sequence.MinValue),
		sequenceNumberAttr("maxvalue", sequence.MaxValue),
		sequenceNumberAttr("cache", sequence.Cache),
		attr{name: "cycle", value: strconv.FormatBool(sequence.Cycle), set: sequence.Cycle},
		attr{name: "owned_by", value: sequence.OwnedBy, set: sequence.OwnedBy != ""},
		attr{name: "if_not_exists", value: strconv.FormatBool(sequence.IfNotExists), set: sequence.IfNotExists},
		attr{name: "comment", value: sequence.Comment, set: sequence.Comment != ""},
		dialectsAttr(sequence.Dialects),
	)
}

// sequenceNumberAttr renders one of the sequence options a declaration may
// leave out, writing nothing when it was not stated.
func sequenceNumberAttr(name string, value *int64) attr {
	if value == nil {
		return attr{name: name}
	}
	return attr{name: name, value: strconv.FormatInt(*value, 10), set: true}
}

func rlsPolicyAnnotation(policy schemamodel.RLSPolicy) string {
	return annotation("ptah:schema:rls:policy",
		attr{name: "name", value: policy.Name, set: true},
		attr{name: "table", value: policy.Table, set: true},
		attr{name: "for", value: policy.PolicyFor, set: policy.PolicyFor != ""},
		attr{name: "to", value: policy.ToRoles, set: policy.ToRoles != ""},
		attr{name: "using", value: policy.UsingExpression, set: policy.UsingExpression != ""},
		attr{name: "with_check", value: policy.WithCheckExpression, set: policy.WithCheckExpression != ""},
		attr{name: "comment", value: policy.Comment, set: policy.Comment != ""},
		dialectsAttr(policy.Dialects),
	)
}

func triggerAnnotation(trigger schemamodel.Trigger) string {
	return annotation("ptah:schema:trigger",
		attr{name: "name", value: trigger.Name, set: true},
		attr{name: "table", value: trigger.Table, set: true},
		attr{name: "timing", value: trigger.Timing, set: trigger.Timing != ""},
		attr{name: "event", value: trigger.Event, set: trigger.Event != ""},
		attr{name: "for", value: trigger.ForEach, set: trigger.ForEach != ""},
		attr{name: "when", value: trigger.When, set: trigger.When != ""},
		attr{name: "old_table", value: trigger.OldTable, set: trigger.OldTable != ""},
		attr{name: "new_table", value: trigger.NewTable, set: trigger.NewTable != ""},
		attr{name: "body", value: trigger.Body, set: true},
		attr{name: "comment", value: trigger.Comment, set: trigger.Comment != ""},
		dialectsAttr(trigger.Dialects),
	)
}

// topicAnnotations writes a YDB topic as its annotation and one annotation
// per consumer, each naming only what differs from the zero value: a read
// fills every setting the server holds, and an attribute naming a setting at
// the value YDB gives a new topic declares the same topic as one leaving it
// out.
func topicAnnotations(topic schemamodel.Topic) []string {
	spec := topic.Spec
	count := func(name string, value uint64) attr {
		return attr{name: name, value: strconv.FormatUint(value, 10), set: value != 0}
	}
	text := func(name, value string) attr { return attr{name: name, value: value, set: value != ""} }
	comments := []string{annotation("ptah:schema:topic",
		attr{name: ydbtopic.AttributeName, value: topic.Name, set: true},
		text(ydbtopic.AttributeSchema, topic.Schema),
		count(ydbtopic.AttributeMinActivePartitions, spec.MinActivePartitions),
		count(ydbtopic.AttributeMaxActivePartitions, spec.MaxActivePartitions),
		text(ydbtopic.AttributeStrategy, spec.AutoPartitioningStrategy),
		count(ydbtopic.AttributeUpUtilizationPercent, uint64(spec.AutoPartitioningUpUtilizationPercent)),
		count(ydbtopic.AttributeDownUtilizationPercent, uint64(spec.AutoPartitioningDownUtilizationPercent)),
		text(ydbtopic.AttributeStabilizationWindow, spec.AutoPartitioningStabilizationWindow),
		text(ydbtopic.AttributeRetentionPeriod, spec.RetentionPeriod),
		count(ydbtopic.AttributeWriteSpeed, spec.PartitionWriteSpeedBytesPerSecond),
		count(ydbtopic.AttributeWriteBurst, spec.PartitionWriteBurstBytes),
		text(ydbtopic.AttributeSupportedCodecs, strings.Join(spec.SupportedCodecs, ",")),
	)}
	for _, consumer := range spec.Consumers {
		comments = append(comments, annotation("ptah:schema:topic:consumer",
			attr{name: ydbtopic.AttributeName, value: consumer.Name, set: true},
			attr{name: ydbtopic.AttributeTopic, value: topic.Name, set: true},
			text(ydbtopic.AttributeSchema, topic.Schema),
			attr{name: ydbtopic.AttributeImportant, value: "true", set: consumer.Important},
			text(ydbtopic.AttributeReadFrom, consumer.ReadFrom),
			text(ydbtopic.AttributeSupportedCodecs, strings.Join(consumer.SupportedCodecs, ",")),
			text(ydbtopic.AttributeAvailabilityPeriod, consumer.AvailabilityPeriod),
		))
	}
	return comments
}

// connectionAttrs writes a replication's or a transfer's connection as
// annotation attributes, each naming only what the connection names.
func connectionAttrs(connection ast.ReplicationConnectionSpec) []attr {
	text := func(name, value string) attr { return attr{name: name, value: value, set: value != ""} }
	return []attr{
		text(ydbreplication.AttributeConnectionString, connection.ConnectionString),
		text(ydbreplication.AttributeTokenSecretName, connection.TokenSecretName),
		text(ydbreplication.AttributeTokenSecretPath, connection.TokenSecretPath),
		text(ydbreplication.AttributeUser, connection.User),
		text(ydbreplication.AttributePasswordSecretName, connection.PasswordSecretName),
		text(ydbreplication.AttributePasswordSecretPath, connection.PasswordSecretPath),
	}
}

// replicationAnnotations writes a YDB async replication as its annotation and
// one annotation per item, each naming only what differs from the zero value.
func replicationAnnotations(replication schemamodel.AsyncReplication) []string {
	spec := replication.Spec
	text := func(name, value string) attr { return attr{name: name, value: value, set: value != ""} }
	attrs := append([]attr{
		{name: ydbreplication.AttributeName, value: replication.Name, set: true},
		text(ydbreplication.AttributeSchema, replication.Schema),
	}, connectionAttrs(spec.Connection)...)
	attrs = append(attrs,
		text(ydbreplication.AttributeConsistencyLevel, spec.ConsistencyLevel),
		text(ydbreplication.AttributeCommitInterval, spec.CommitInterval),
	)
	comments := []string{annotation("ptah:schema:async_replication", attrs...)}
	for _, item := range spec.Items {
		comments = append(comments, annotation("ptah:schema:async_replication:item",
			attr{name: ydbreplication.AttributeReplication, value: replication.Name, set: true},
			text(ydbreplication.AttributeSchema, replication.Schema),
			attr{name: ydbreplication.AttributeSource, value: item.Source, set: true},
			attr{name: ydbreplication.AttributeTarget, value: item.Target, set: true},
		))
	}
	return comments
}

// transferAnnotation writes a YDB transfer as its annotation, naming only what
// differs from the zero value.
func transferAnnotation(transfer schemamodel.Transfer) string {
	spec := transfer.Spec
	text := func(name, value string) attr { return attr{name: name, value: value, set: value != ""} }
	attrs := append([]attr{
		{name: ydbreplication.AttributeName, value: transfer.Name, set: true},
		text(ydbreplication.AttributeSchema, transfer.Schema),
	}, connectionAttrs(spec.Connection)...)
	attrs = append(attrs,
		attr{name: ydbreplication.AttributeSource, value: spec.Source, set: true},
		attr{name: ydbreplication.AttributeTarget, value: spec.Target, set: true},
		attr{name: ydbreplication.AttributeUsing, value: spec.Lambda, set: true},
		text(ydbreplication.AttributeConsumer, spec.Consumer),
		attr{name: ydbreplication.AttributeBatchSizeBytes, value: strconv.FormatUint(spec.BatchSizeBytes, 10),
			set: spec.BatchSizeBytes != 0},
		text(ydbreplication.AttributeFlushInterval, spec.FlushInterval),
	)
	return annotation("ptah:schema:transfer", attrs...)
}

func roleAnnotation(role schemamodel.Role) string {
	return annotation("ptah:schema:role",
		attr{name: "name", value: role.Name, set: true},
		attr{name: "login", value: strconv.FormatBool(role.Login), set: role.Login},
		attr{name: "superuser", value: strconv.FormatBool(role.Superuser), set: role.Superuser},
		attr{name: "create_db", value: strconv.FormatBool(role.CreateDB), set: role.CreateDB},
		attr{name: "create_role", value: strconv.FormatBool(role.CreateRole), set: role.CreateRole},
		attr{name: "inherit", value: strconv.FormatBool(role.Inherit), set: !role.Inherit},
		attr{name: "replication", value: strconv.FormatBool(role.Replication), set: role.Replication},
		attr{name: "group", value: strconv.FormatBool(role.Group), set: role.Group},
		attr{name: "member_of", value: strings.Join(role.MemberOf, ","), set: len(role.MemberOf) > 0},
		attr{name: "comment", value: role.Comment, set: role.Comment != ""},
		dialectsAttr(role.Dialects),
	)
}

func grantAnnotation(grant schemamodel.Grant) string {
	return annotation("ptah:schema:grant",
		attr{name: "role", value: grant.Role, set: true},
		attr{name: "privilege", value: strings.Join(grant.Privileges, ","), set: len(grant.Privileges) > 0},
		attr{name: "on_table", value: grant.OnTable, set: grant.OnTable != ""},
		attr{name: "on_schema", value: grant.OnSchema, set: grant.OnSchema != ""},
		attr{name: "on_sequence", value: grant.OnSequence, set: grant.OnSequence != ""},
		attr{name: "on_database", value: strconv.FormatBool(grant.OnDatabase), set: grant.OnDatabase},
		routineTargetAttr(grant),
		attr{name: "columns", value: strings.Join(grant.Columns, ","), set: len(grant.Columns) > 0},
		attr{name: "with_option", value: strconv.FormatBool(grant.WithOption), set: grant.WithOption},
		attr{name: "comment", value: grant.Comment, set: grant.Comment != ""},
		dialectsAttr(grant.Dialects),
	)
}

// revokeAnnotation writes one revoked grant back as a directive.
func revokeAnnotation(revoked schemamodel.Grant) string {
	return annotation("ptah:schema:revoke",
		attr{name: "role", value: revoked.Role, set: true},
		attr{name: "privilege", value: strings.Join(revoked.Privileges, ","), set: len(revoked.Privileges) > 0},
		attr{name: "on_table", value: revoked.OnTable, set: revoked.OnTable != ""},
		attr{name: "on_schema", value: revoked.OnSchema, set: revoked.OnSchema != ""},
		attr{name: "on_sequence", value: revoked.OnSequence, set: revoked.OnSequence != ""},
		attr{name: "on_database", value: strconv.FormatBool(revoked.OnDatabase), set: revoked.OnDatabase},
		routineTargetAttr(revoked),
		attr{name: "columns", value: strings.Join(revoked.Columns, ","), set: len(revoked.Columns) > 0},
		attr{name: "comment", value: revoked.Comment, set: revoked.Comment != ""},
		dialectsAttr(revoked.Dialects),
	)
}

// routineTargetAttr writes a routine target as on_function or on_procedure,
// with the argument types in parentheses the way the parser reads them. A
// ROUTINE target is written as on_function: PostgreSQL resolves the keyword to
// whichever kind the routine is, and the grant names the same routine.
func routineTargetAttr(grant schemamodel.Grant) attr {
	name := "on_function"
	if strings.EqualFold(grant.RoutineKind, "PROCEDURE") {
		name = "on_procedure"
	}
	return attr{
		name:  name,
		value: grant.OnRoutine + "(" + grant.RoutineArguments + ")",
		set:   grant.OnRoutine != "",
	}
}

// defaultPrivilegeAnnotation writes one default privilege back as a directive.
//
// The model holds one privilege list where the directive has two, so the
// grantable names are projected back out of the pairs. Writing every privilege
// into `grantable` instead would turn a plain SELECT into a grantable one on
// the next parse, and nothing between here and the server would notice.
func defaultPrivilegeAnnotation(privilege schemamodel.DefaultPrivilege) string {
	names := make([]string, 0, len(privilege.Privileges))
	var grantable []string
	for _, granted := range privilege.Privileges {
		names = append(names, granted.Privilege)
		if granted.WithOption {
			grantable = append(grantable, granted.Privilege)
		}
	}
	return annotation("ptah:schema:defaultprivilege",
		attr{name: "for_role", value: privilege.Grantor, set: true},
		// No schema is the global default, which the directive spells by leaving
		// the attribute out.
		attr{name: "schema", value: privilege.Schema, set: privilege.Schema != ""},
		attr{name: "object_type", value: privilege.ObjectType, set: true},
		attr{name: "grantee", value: privilege.Grantee, set: true},
		attr{name: "privileges", value: strings.Join(names, ","), set: len(names) > 0},
		attr{name: "grantable", value: strings.Join(grantable, ","), set: len(grantable) > 0},
		attr{name: "revoked", value: strings.Join(privilege.Revoked, ","), set: len(privilege.Revoked) > 0},
		attr{name: "comment", value: privilege.Comment, set: privilege.Comment != ""},
		dialectsAttr(privilege.Dialects),
	)
}

// coordinationNodeAnnotation declares a YDB coordination node with the
// settings it was given; a setting left unset takes YDB's default.
func coordinationNodeAnnotation(node schemamodel.CoordinationNode) string {
	attrs := []attr{
		{name: "name", value: node.Name, set: true},
		{name: "schema", value: node.Schema, set: node.Schema != ""},
	}
	for _, setting := range ydbcoordination.Attributes(node.Spec) {
		attrs = append(attrs, attr{name: setting[0], value: setting[1], set: true})
	}
	return annotation("ptah:schema:coordinationnode", attrs...)
}

func annotation(name string, attrs ...attr) string {
	var builder strings.Builder
	builder.WriteString("//")
	builder.WriteString(name)
	for _, attr := range attrs {
		if !attr.set {
			continue
		}
		builder.WriteByte(' ')
		builder.WriteString(attr.name)
		builder.WriteByte('=')
		builder.WriteString(strconv.Quote(attr.value))
	}
	return builder.String()
}

func structTags(field schemamodel.Field, opts Options) string {
	var tags []string
	if opts.AddDBTags {
		tags = append(tags, fmt.Sprintf("db:%q", field.Name))
	}
	if opts.AddJSONTags {
		tags = append(tags, fmt.Sprintf("json:%q", field.Name))
	}
	if len(tags) == 0 {
		return ""
	}
	return " `" + strings.Join(tags, " ") + "`"
}

func sqlTypeToGoType(sqlType string) string {
	normalized := strings.ToLower(strings.TrimSpace(sqlType))
	if before, _, ok := strings.Cut(normalized, "("); ok {
		normalized = strings.TrimSpace(before)
	}
	switch normalized {
	case "bool", "boolean":
		return "bool"
	case "smallint", "int2", "smallserial", "serial2":
		return "int16"
	case "int", "integer", "int4", "serial", "serial4", "mediumint":
		return "int"
	case "bigint", "int8", "bigserial", "serial8":
		return "int64"
	case "real", "float4":
		return "float32"
	case "double", "double precision", "float8", "float":
		return "float64"
	case "bytea", "blob", "binary", "varbinary":
		return "[]byte"
	case "date", "time", "timestamp", "timestamp without time zone", "timestamp with time zone", "timestamptz", "datetime":
		return "time.Time"
	default:
		return "string"
	}
}

func indexOwner(index schemamodel.Index) string {
	if index.StructName != "" {
		return index.StructName
	}
	return exportedIdentifier(index.TableName)
}

func constraintOwner(constraint schemamodel.Constraint) string {
	if constraint.StructName != "" {
		return constraint.StructName
	}
	return exportedIdentifier(constraint.Table)
}

// fileBaseForTable derives the name, without the .go extension, of the file a
// table is written to.
func fileBaseForTable(table schemamodel.Table) string {
	name := table.QualifiedName()
	if name == "" {
		name = table.StructName
	}
	return sanitizeFileName(name)
}

func isSafeFileName(name string) bool {
	return name == filepath.Base(name) && name != "." && name != ".." && !filepath.IsAbs(name)
}

func sanitizeFileName(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	name = strings.ReplaceAll(name, ".", "_")
	var builder strings.Builder
	for _, r := range name {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' || r == '_' {
			builder.WriteRune(r)
			continue
		}
		builder.WriteByte('_')
	}
	result := strings.Trim(builder.String(), "_")
	if result == "" {
		return "schema"
	}
	return result
}

func exportedIdentifier(name string) string {
	return upperFirst(identifierFromName(name))
}

func unexportedIdentifier(name string) string {
	return lowerFirst(identifierFromName(name))
}

func identifierFromName(name string) string {
	if hasUppercase(name) && token.IsIdentifier(name) && !token.Lookup(name).IsKeyword() {
		return name
	}
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	if len(parts) == 0 {
		parts = []string{"value"}
	}
	var builder strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(strings.ToLower(part))
		builder.WriteRune(unicode.ToUpper(runes[0]))
		for _, r := range runes[1:] {
			builder.WriteRune(r)
		}
	}
	result := builder.String()
	if result == "" {
		result = "Value"
	}
	if unicode.IsDigit([]rune(result)[0]) {
		result = "N" + result
	}
	if token.Lookup(result).IsKeyword() {
		result += "Value"
	}
	return result
}

func lowerFirst(name string) string {
	if name == "" {
		return name
	}
	runes := []rune(name)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func upperFirst(name string) string {
	if name == "" {
		return name
	}
	runes := []rune(name)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func hasUppercase(name string) bool {
	for _, r := range name {
		if unicode.IsUpper(r) {
			return true
		}
	}
	return false
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return ""
}

type sourceWriter struct {
	buf bytes.Buffer
}

func (w *sourceWriter) writeString(value string) {
	w.buf.WriteString(value)
}

func (w *sourceWriter) writeLine(value string) {
	w.buf.WriteString(value)
	w.buf.WriteByte('\n')
}

func (w *sourceWriter) writeComment(value string) {
	w.writeLine(value)
}

func sortedTables(values []schemamodel.Table) []schemamodel.Table {
	result := append([]schemamodel.Table(nil), values...)
	sort.Slice(result, func(i, j int) bool {
		return result[i].QualifiedName() < result[j].QualifiedName()
	})
	return result
}

func sortedEnums(values []schemamodel.Enum) []schemamodel.Enum {
	result := append([]schemamodel.Enum(nil), values...)
	sort.Slice(result, func(i, j int) bool { return result[i].Name < result[j].Name })
	return result
}

func sortedSchemas(values []schemamodel.Schema) []schemamodel.Schema {
	result := append([]schemamodel.Schema(nil), values...)
	sort.Slice(result, func(i, j int) bool { return result[i].Name < result[j].Name })
	return result
}

func sortedExtensions(values []schemamodel.Extension) []schemamodel.Extension {
	result := append([]schemamodel.Extension(nil), values...)
	sort.Slice(result, func(i, j int) bool { return result[i].Name < result[j].Name })
	return result
}

// The user-type sorters key on the schema-qualified name rather than the bare
// one. Two objects may share a name in different schemas, and a sort that
// cannot tell them apart leaves their order to the input, which `ptah
// introspect` promises not to do.
func sortedDomains(values []schemamodel.Domain) []schemamodel.Domain {
	result := append([]schemamodel.Domain(nil), values...)
	sort.Slice(result, func(i, j int) bool {
		return result[i].Schema+"."+result[i].Name < result[j].Schema+"."+result[j].Name
	})
	return result
}

func sortedCompositeTypes(values []schemamodel.CompositeType) []schemamodel.CompositeType {
	result := append([]schemamodel.CompositeType(nil), values...)
	sort.Slice(result, func(i, j int) bool {
		return result[i].Schema+"."+result[i].Name < result[j].Schema+"."+result[j].Name
	})
	return result
}

func sortedRanges(values []schemamodel.Range) []schemamodel.Range {
	result := append([]schemamodel.Range(nil), values...)
	sort.Slice(result, func(i, j int) bool {
		return result[i].Schema+"."+result[i].Name < result[j].Schema+"."+result[j].Name
	})
	return result
}

func sortedSequences(values []schemamodel.Sequence) []schemamodel.Sequence {
	result := append([]schemamodel.Sequence(nil), values...)
	sort.Slice(result, func(i, j int) bool {
		return result[i].Schema+"."+result[i].Name < result[j].Schema+"."+result[j].Name
	})
	return result
}

func sortedFunctions(values []schemamodel.Function) []schemamodel.Function {
	result := append([]schemamodel.Function(nil), values...)
	sort.Slice(result, func(i, j int) bool { return result[i].Name < result[j].Name })
	return result
}

func sortedTopics(values []schemamodel.Topic) []schemamodel.Topic {
	sorted := slices.Clone(values)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].QualifiedName() < sorted[j].QualifiedName() })
	return sorted
}

func sortedReplications(values []schemamodel.AsyncReplication) []schemamodel.AsyncReplication {
	sorted := slices.Clone(values)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].QualifiedName() < sorted[j].QualifiedName() })
	return sorted
}

func sortedTransfers(values []schemamodel.Transfer) []schemamodel.Transfer {
	sorted := slices.Clone(values)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].QualifiedName() < sorted[j].QualifiedName() })
	return sorted
}

func sortedViews(values []schemamodel.View) []schemamodel.View {
	result := append([]schemamodel.View(nil), values...)
	sort.Slice(result, func(i, j int) bool { return result[i].Name < result[j].Name })
	return result
}

func sortedCoordinationNodes(values []schemamodel.CoordinationNode) []schemamodel.CoordinationNode {
	result := append([]schemamodel.CoordinationNode(nil), values...)
	sort.Slice(result, func(i, j int) bool { return result[i].QualifiedName() < result[j].QualifiedName() })
	return result
}

func sortedMaterializedViews(values []schemamodel.MaterializedView) []schemamodel.MaterializedView {
	result := append([]schemamodel.MaterializedView(nil), values...)
	sort.Slice(result, func(i, j int) bool { return result[i].Name < result[j].Name })
	return result
}

func sortedRoles(values []schemamodel.Role) []schemamodel.Role {
	result := append([]schemamodel.Role(nil), values...)
	sort.Slice(result, func(i, j int) bool { return result[i].Name < result[j].Name })
	return result
}

func sortedGrants(values []schemamodel.Grant) []schemamodel.Grant {
	result := append([]schemamodel.Grant(nil), values...)
	sort.Slice(result, func(i, j int) bool { return grantSortKey(result[i]) < grantSortKey(result[j]) })
	return result
}

// grantSortKey orders a grant by each field that identifies one, so the export
// order follows what the grants say rather than the order they arrived in.
// Privileges belong in the key because a live read reports one grant per
// privilege row, which leaves role and target alone unable to separate them.
// The separator keeps the fields apart: concatenated, an on_table of "ab" reads
// the same as an on_table of "a" beside an on_schema of "b".
func grantSortKey(grant schemamodel.Grant) string {
	return strings.Join([]string{
		grant.Role,
		grant.OnTable,
		grant.OnSchema,
		grant.OnSequence,
		grant.OnRoutine,
		grant.RoutineArguments,
		strings.Join(grant.Columns, ","),
		strings.Join(grant.Privileges, ","),
		strconv.FormatBool(grant.WithOption),
	}, "\x00")
}

func sortedDefaultPrivileges(values []schemamodel.DefaultPrivilege) []schemamodel.DefaultPrivilege {
	result := append([]schemamodel.DefaultPrivilege(nil), values...)
	sort.Slice(result, func(i, j int) bool {
		return defaultPrivilegeSortKey(result[i]) < defaultPrivilegeSortKey(result[j])
	})
	return result
}

// defaultPrivilegeSortKey orders by the object's identity -- grantor, schema,
// object type, grantee -- so the export order follows the declarations rather
// than the order they arrived in.
//
// The privilege spelling joins the identity because two declarations sharing an
// identity are what an unfolded model still holds: sort.Slice is not stable, so
// equal keys would let two such declarations swap places between runs, and the
// export would stop being byte-identical over the same input.
//
// The separator keeps the fields apart: concatenated, a grantor of "ab" reads
// the same as a grantor of "a" beside a schema of "b".
func defaultPrivilegeSortKey(privilege schemamodel.DefaultPrivilege) string {
	names := make([]string, 0, len(privilege.Privileges))
	for _, granted := range privilege.Privileges {
		names = append(names, granted.Privilege+":"+strconv.FormatBool(granted.WithOption))
	}
	return strings.Join([]string{
		privilege.Grantor,
		privilege.Schema,
		privilege.ObjectType,
		privilege.Grantee,
		strings.Join(names, ","),
	}, "\x00")
}

func sortedImportPaths(values map[string]struct{}) []string {
	result := make([]string, 0, len(values))
	for value := range values {
		result = append(result, value)
	}
	sort.Strings(result)
	return result
}
