// Package docs carries Ptah's own documentation inside the binary.
//
// It exists so that the agent surface can answer a question about Ptah from
// Ptah rather than from a model's training data, with no network and no
// operator configuration -- stokaro/ptah#2123.
//
// The package sits in `docs/` because `go:embed` patterns cannot leave their
// package's directory, and the documentation is not going to move into a Go
// package to suit the loader. It holds the filesystem and nothing else: the
// splitting, indexing and searching live in internal/docsindex, so a change to
// how documentation is served does not touch where it is kept.
//
// The markdown is embedded as written rather than as a prebuilt index. A built
// index would have to be committed, regenerated by every documentation edit,
// and guarded by a gate that fails when the two drift -- and a compressed blob
// in the tree merges as binary, so two documentation changes landing together
// produce a file that matches neither. Embedding the source makes drift
// impossible to express: what the binary answers from is what the repository
// holds.
package docs

import "embed"

// FS holds Ptah's product documentation: the guides at the top of `docs/`, the
// decision records, and the pages the documentation site is built from.
//
// `docs/site/scripts` and the site's own README are not here. They describe how
// the site is built, which is not a question anyone asks Ptah about its own
// behavior.
//
//go:embed *.md
//go:embed adr/*.md
//go:embed site/src/content/docs
var FS embed.FS
