//go:build integration

package integration_test

import (
	"crypto/rand"
	"encoding/hex"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	qt "github.com/frankban/quicktest"

	"ptah.run/internal/devdocker"
)

// An atlas.hcl docker block declares the dev database a selected env names
// with docker.<type>.<name>.url (stokaro/ptah#4041). This test builds the
// block's image from a Dockerfile, runs its baseline, and replays a migration
// directory that reads the baseline's grant back: the migration inserts
// has_schema_privilege() into a column whose CHECK refuses false, so the
// replay fails unless the grant the baseline wrote is still there after the
// dev database was claimed and reset.
//
// That is ariga/atlas#3807's scenario: there the reset between the two uses of
// the dev database revoked every grant the image's baseline state held. Here
// the block pins public, so the claim judges public alone and leaves the
// baseline's schema, its grant included, as it was. The block names its
// database: cleanup refuses `postgres`, the default (stokaro/ptah#4035).

// dockerBlockBaseline creates a role, a schema and a grant on it.
const dockerBlockBaseline = `CREATE ROLE ptah_block_reader;
CREATE SCHEMA audit;
GRANT USAGE ON SCHEMA audit TO ptah_block_reader;
`

// dockerBlockMigration fails unless the baseline's grant exists.
const dockerBlockMigration = `CREATE TABLE probe (ok boolean NOT NULL, CONSTRAINT probe_ok CHECK (ok));
INSERT INTO probe (ok) VALUES (has_schema_privilege('ptah_block_reader', 'audit', 'USAGE'));
`

// dockerBlockSchema is the state the migration leaves.
const dockerBlockSchema = "CREATE TABLE probe (ok boolean NOT NULL, CONSTRAINT probe_ok CHECK (ok));\n"

// imageExists reports whether the runtime holds image.
func imageExists(image string) bool {
	// #nosec G204 -- the tag is generated by the test.
	return exec.Command("docker", "image", "inspect", image).Run() == nil
}

func TestCompatMigrateDiffProvisionsAnAtlasHCLDockerBlockE2E(t *testing.T) {
	c := qt.New(t)
	c.Assert(devdocker.DockerCLI{}.Available(t.Context()), qt.IsNil)
	suffix := make([]byte, 6)
	_, err := rand.Read(suffix)
	c.Assert(err, qt.IsNil)
	image := "ptah-docker-block-" + hex.EncodeToString(suffix) + ":1"
	c.Cleanup(func() {
		// #nosec G204 -- the tag is generated above.
		_ = exec.Command("docker", "rmi", "--force", image).Run()
	})

	dir := c.TempDir()
	c.Assert(os.MkdirAll(filepath.Join(dir, "db"), 0o755), qt.IsNil)
	c.Assert(os.WriteFile(filepath.Join(dir, "db", "Dockerfile"), []byte("FROM postgres:16-alpine\n"), 0o600), qt.IsNil)
	migrations := filepath.Join(dir, "migrations")
	c.Assert(os.MkdirAll(migrations, 0o755), qt.IsNil)
	c.Assert(os.WriteFile(filepath.Join(migrations, "20240101000000_probe.sql"), []byte(dockerBlockMigration), 0o600), qt.IsNil)
	_, err = runCompatVerb("migrate", "hash", "--dir", "file://"+migrations)
	c.Assert(err, qt.IsNil)
	c.Assert(os.WriteFile(filepath.Join(dir, "schema.sql"), []byte(dockerBlockSchema), 0o600), qt.IsNil)
	c.Assert(os.WriteFile(filepath.Join(dir, "atlas.hcl"), []byte(`docker "postgres" "dev" {
  image    = "`+image+`"
  database = "dev"
  schema   = "public"
  baseline = <<-SQL
`+dockerBlockBaseline+`  SQL
  build {
    context = "db"
  }
}

env "dev" {
  dev = docker.postgres.dev.url
  migration {
    dir = "file://migrations"
  }
  schema {
    src = "file://schema.sql"
  }
}
`), 0o600), qt.IsNil)
	t.Chdir(dir)

	out, err := runCompatVerb("migrate", "diff", "--env", "dev", "next")

	c.Assert(err, qt.IsNil, qt.Commentf("%s", out))
	c.Assert(out, qt.Contains, "The migration directory is synced with the desired state, no changes to be made")
	entries, err := os.ReadDir(migrations)
	c.Assert(err, qt.IsNil)
	c.Assert(entries, qt.HasLen, 2)
	// The image goes once the container is gone, so its absence says both
	// were removed: the runtime refuses to remove an image a container uses.
	c.Assert(imageExists(image), qt.IsFalse)
}
