//go:build integration

package integration_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	qt "github.com/frankban/quicktest"

	"ptah.run/dbschema"
	"ptah.run/internal/dbtarget"
)

// TestOracleManagedDataFullDeleteIdentityE2E drives `ptah migrations data`
// against a live Oracle server, emptying the desired rows of a populated table
// whose key is an identity column.
//
// Oracle decides the answer, and it decides it by generation mode. A GENERATED
// ALWAYS key refuses an explicit value with ORA-32795, so a rollback of INSERTs
// cannot restore the rows its up deleted; GENERATED BY DEFAULT accepts one, so
// the same rollback restores them with their keys. IDENTITY_COLUMN answers YES
// for both, which is why the reader has to ask ALL_TAB_IDENTITY_COLS.
//
// Measured on Oracle Free 23.26.3 before the fix (stokaro/ptah#3295): the
// ALWAYS table exited 0 and wrote a migration whose up emptied the table and
// whose down Oracle refused statement by statement.
func TestOracleManagedDataFullDeleteIdentityE2E(t *testing.T) {
	dbURL := dbtarget.URL(t, dbtarget.Oracle)
	c := qt.New(t)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	conn, err := dbschema.ConnectToDatabase(ctx, dbURL)
	c.Assert(err, qt.IsNil)
	defer dbschema.CloseAndWarn(conn)

	repoRoot := e2eRepoRoot(t)
	workDir := c.TempDir()
	binary := filepath.Join(workDir, "ptah")
	buildPtah(c, ctx, repoRoot, binary)

	suffix := time.Now().UnixNano() % 100000000

	t.Run("a GENERATED ALWAYS key is refused and the rows stay", func(t *testing.T) {
		c := qt.New(t)
		table := fmt.Sprintf("PTAH_MD3295_ALWAYS_%d", suffix)
		createOracleIdentityTable(c, ctx, conn, table, "ALWAYS")
		root, migrationsDir := writeOracleEmptyDataFixture(c, table)

		stdout, stderr, runErr := runCLIProcess(ctx, workDir, binary,
			"migrations", "data", "--db-url", dbURL, "--root-dir", root,
			"--migrations-dir", migrationsDir, "--allow-destructive", "--description", "identity")

		c.Check(exitStatusOf(c, runErr), qt.Equals, 2)
		c.Check(stdout, qt.Equals, "")
		c.Check(stderr, qt.Contains, fmt.Sprintf(`full delete for table %q`, table))
		c.Check(stderr, qt.Contains, `column(s) "ID" reject explicit inserts`)
		entries, readErr := os.ReadDir(migrationsDir)
		c.Assert(readErr, qt.IsNil)
		c.Check(entries, qt.HasLen, 0)

		// Whatever was written is applied the way a deploy and a rollback
		// would apply it. On a refusal there is nothing to apply; a migration
		// that should not exist gets the server's own answer to its down,
		// rather than an exit code alone.
		for _, statement := range oracleMigrationDirStatements(c, migrationsDir, "*.up.sql") {
			c.Check(conn.SchemaWriter().ExecuteSQL(ctx, statement), qt.IsNil)
		}
		for _, statement := range oracleMigrationDirStatements(c, migrationsDir, "*.down.sql") {
			c.Check(conn.SchemaWriter().ExecuteSQL(ctx, statement), qt.IsNil)
		}
		c.Assert(oracleIdentityRows(c, ctx, conn, table), qt.DeepEquals, []string{"1:US", "2:CZ"})
	})

	// The control. A guard that refused every Oracle identity would pass the
	// row above, so this one shows a BY DEFAULT key still generates, and that
	// the server takes its rollback back to the rows it started with.
	t.Run("a GENERATED BY DEFAULT key generates a rollback the server applies", func(t *testing.T) {
		c := qt.New(t)
		table := fmt.Sprintf("PTAH_MD3295_BYDEF_%d", suffix)
		createOracleIdentityTable(c, ctx, conn, table, "BY DEFAULT")
		root, migrationsDir := writeOracleEmptyDataFixture(c, table)

		stdout, stderr, runErr := runCLIProcess(ctx, workDir, binary,
			"migrations", "data", "--db-url", dbURL, "--root-dir", root,
			"--migrations-dir", migrationsDir, "--allow-destructive", "--description", "identity")

		c.Assert(exitStatusOf(c, runErr), qt.Equals, 0)
		c.Assert(stderr, qt.Equals, "")
		c.Assert(stdout, qt.Contains, "Wrote data migration version 1")
		down := readOracleMigrationFile(c, migrationsDir, "0000000001_identity.down.sql")
		c.Assert(down, qt.Contains, fmt.Sprintf(`INSERT INTO %q ("CODE", "ID") VALUES ('US', '1');`, table))
		c.Assert(down, qt.Contains, fmt.Sprintf(`INSERT INTO %q ("CODE", "ID") VALUES ('CZ', '2');`, table))

		for _, statement := range oracleMigrationStatements(readOracleMigrationFile(c, migrationsDir, "0000000001_identity.up.sql")) {
			c.Assert(conn.SchemaWriter().ExecuteSQL(ctx, statement), qt.IsNil)
		}
		c.Assert(oracleIdentityRows(c, ctx, conn, table), qt.HasLen, 0)

		for _, statement := range oracleMigrationStatements(down) {
			c.Assert(conn.SchemaWriter().ExecuteSQL(ctx, statement), qt.IsNil)
		}
		c.Assert(oracleIdentityRows(c, ctx, conn, table), qt.DeepEquals, []string{"1:US", "2:CZ"})
	})
}

// createOracleIdentityTable creates a table keyed by an identity column of the
// given generation mode, seeds two rows through the identity, and drops the
// table when the test ends.
func createOracleIdentityTable(c *qt.C, ctx context.Context, conn *dbschema.DatabaseConnection, table, generation string) {
	c.Helper()
	dropOracleTable(ctx, conn, table)
	c.Cleanup(func() { dropOracleTable(context.WithoutCancel(ctx), conn, table) })

	c.Assert(conn.SchemaWriter().ExecuteSQL(ctx, fmt.Sprintf(
		`CREATE TABLE %s (ID NUMBER(10) GENERATED %s AS IDENTITY PRIMARY KEY, CODE VARCHAR2(40) NOT NULL)`,
		table, generation)), qt.IsNil)
	c.Assert(conn.SchemaWriter().ExecuteSQL(ctx, fmt.Sprintf(`INSERT INTO %s (CODE) VALUES ('US')`, table)), qt.IsNil)
	c.Assert(conn.SchemaWriter().ExecuteSQL(ctx, fmt.Sprintf(`INSERT INTO %s (CODE) VALUES ('CZ')`, table)), qt.IsNil)
	// The precondition, read back from the server: the identity issued 1 and 2.
	c.Assert(oracleIdentityRows(c, ctx, conn, table), qt.DeepEquals, []string{"1:US", "2:CZ"})
}

// writeOracleEmptyDataFixture declares the table as managed data with no
// desired rows, and returns the source root and an empty migrations directory.
func writeOracleEmptyDataFixture(c *qt.C, table string) (root, migrationsDir string) {
	c.Helper()
	dir := c.TempDir()
	root = filepath.Join(dir, "entities")
	migrationsDir = filepath.Join(dir, "migrations")
	c.Assert(os.MkdirAll(root, 0o750), qt.IsNil)
	c.Assert(os.MkdirAll(migrationsDir, 0o750), qt.IsNil)

	source := fmt.Sprintf("package entities\n\n//ptah:schema:data table=%q key=\"ID\" file=\"rows.yaml\"\ntype Probe struct{}\n", table)
	c.Assert(os.WriteFile(filepath.Join(root, "schema.go"), []byte(source), 0o600), qt.IsNil)
	c.Assert(os.WriteFile(filepath.Join(root, "rows.yaml"), []byte("[]\n"), 0o600), qt.IsNil)
	return root, migrationsDir
}

// oracleIdentityRows reads the table back as "ID:CODE" pairs in key order.
func oracleIdentityRows(c *qt.C, ctx context.Context, conn *dbschema.DatabaseConnection, table string) []string {
	c.Helper()
	rows, err := conn.QueryContext(ctx, fmt.Sprintf(`SELECT ID, CODE FROM %s ORDER BY ID`, table))
	c.Assert(err, qt.IsNil)
	defer rows.Close()

	got := []string{}
	for rows.Next() {
		var (
			id   int64
			code string
		)
		c.Assert(rows.Scan(&id, &code), qt.IsNil)
		got = append(got, fmt.Sprintf("%d:%s", id, code))
	}
	c.Assert(rows.Err(), qt.IsNil)
	return got
}

func readOracleMigrationFile(c *qt.C, dir, name string) string {
	c.Helper()
	content, err := os.ReadFile(filepath.Join(dir, name))
	c.Assert(err, qt.IsNil)
	return string(content)
}

// oracleMigrationDirStatements reads every migration file in dir matching
// pattern and returns their statements in file-name order. It returns none when
// nothing matches.
func oracleMigrationDirStatements(c *qt.C, dir, pattern string) []string {
	c.Helper()
	paths, err := filepath.Glob(filepath.Join(dir, pattern))
	c.Assert(err, qt.IsNil)

	var statements []string
	for _, path := range paths {
		statements = append(statements, oracleMigrationStatements(readOracleMigrationFile(c, dir, filepath.Base(path)))...)
	}
	return statements
}

// oracleMigrationStatements splits a generated data migration into the
// statements it holds, one per line, without the terminator the Oracle driver
// refuses.
func oracleMigrationStatements(body string) []string {
	var statements []string
	for line := range strings.SplitSeq(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "--") {
			continue
		}
		statements = append(statements, strings.TrimSuffix(line, ";"))
	}
	return statements
}
