//go:build integration

package integration_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	qt "github.com/frankban/quicktest"

	"ptah.run/dbschema"
	"ptah.run/internal/atlasschema"
	"ptah.run/internal/dbtarget"
	"ptah.run/migration/migrator"
)

// A table created as items and renamed to products keeps the sequences its
// columns own under their old names, items_id_seq and items_code_seq, while a
// description writes the columns as BIGSERIAL and an identity clause, whose
// replay creates products_id_seq and products_code_seq. A grant on either
// sequence follows its column: the description names the sequence its replay
// creates, a comparison matches the two names, and a plan names the sequence
// the database holds. Described by the old name, the grant did not replay and
// every `schema apply --dev-url` on such a table failed in the rehearsal
// (stokaro/ptah#4064).

// renamedSerialFixture is a database holding the renamed table, with a role
// granted USAGE on both sequences, a dev database and an empty one.
type renamedSerialFixture struct {
	target devIdentityTarget
	dev    string
	empty  devIdentityTarget
	role   string
}

func newRenamedSerialFixture(c *qt.C) renamedSerialFixture {
	c.Helper()
	role := fmt.Sprintf("ptah_renamed_seq_%d", time.Now().UnixNano())
	admin, err := dbschema.ConnectToDatabase(c.Context(), dbtarget.URL(c, dbtarget.PostgreSQL))
	c.Assert(err, qt.IsNil)
	_, err = admin.ExecContext(c.Context(), "CREATE ROLE "+role)
	c.Assert(err, qt.IsNil)
	// The role outlives the databases that hold grants to it, so its cleanup
	// is registered first and runs last.
	c.Cleanup(func() {
		_, dropErr := admin.ExecContext(context.Background(), "DROP ROLE IF EXISTS "+role)
		c.Check(dropErr, qt.IsNil)
		dbschema.CloseAndWarn(admin)
	})
	target := newDevIdentityTarget(c, dbtarget.PostgreSQL, " WITH (FORCE)")
	c.Assert(atlasschema.ApplySQL(c.Context(), target.conn, migrator.MigrationTxModeNone, fmt.Sprintf(
		"DROP TABLE kept;\n"+
			"CREATE TABLE items (id bigserial PRIMARY KEY, code bigint GENERATED BY DEFAULT AS IDENTITY, title text);\n"+
			"ALTER TABLE items RENAME TO products;\n"+
			"GRANT USAGE ON SEQUENCE items_id_seq TO %[1]s;\n"+
			"GRANT USAGE ON SEQUENCE items_code_seq TO %[1]s;\n", role)), qt.IsNil)
	dev := newDevIdentityTarget(c, dbtarget.PostgreSQL, " WITH (FORCE)")
	c.Assert(atlasschema.ApplySQL(c.Context(), dev.conn, migrator.MigrationTxModeNone, "DROP TABLE kept;\n"), qt.IsNil)
	empty := newDevIdentityTarget(c, dbtarget.PostgreSQL, " WITH (FORCE)")
	c.Assert(atlasschema.ApplySQL(c.Context(), empty.conn, migrator.MigrationTxModeNone, "DROP TABLE kept;\n"), qt.IsNil)
	return renamedSerialFixture{target: target, dev: pinnedDevURL(c, dev.url, "public"), empty: empty, role: role}
}

// describe returns the target's SQL description.
func (f renamedSerialFixture) describe(c *qt.C) string {
	c.Helper()
	// Standard output alone: the notes on standard error are not part of the
	// document.
	output, diagnostics, err := runCompat(c.Context(), "schema", "inspect",
		"-u", pinnedDevURL(c, f.target.url, "public"), "--format", "{{ sql . }}")
	c.Assert(err, qt.IsNil, qt.Commentf("%s", diagnostics))
	return output
}

// writeRenamedSerialFile writes body to a schema file of its own and returns the path.
func writeRenamedSerialFile(c *qt.C, body string) string {
	c.Helper()
	path := filepath.Join(c.TempDir(), "schema.sql")
	c.Assert(os.WriteFile(path, []byte(body), 0o600), qt.IsNil)
	return path
}

// sequenceGrants reads back, from conn, the role's privileges on each
// sequence, as `sequence=privileges`.
func (f renamedSerialFixture) sequenceGrants(c *qt.C, conn *dbschema.DatabaseConnection) string {
	c.Helper()
	var grants string
	c.Assert(conn.QueryRowContext(c.Context(), `
		SELECT coalesce(string_agg(c.relname || '=' || acl.privilege_type, ' ' ORDER BY c.relname), '')
		FROM pg_class c
		CROSS JOIN LATERAL aclexplode(c.relacl) acl
		JOIN pg_roles r ON r.oid = acl.grantee
		WHERE c.relkind = 'S' AND r.rolname = $1`, f.role).Scan(&grants), qt.IsNil)
	return grants
}

// TestSchemaInspectOfRenamedSerialTableReplaysE2E replays the description on
// an empty database. The replay creates the sequences under the names the
// columns give them and grants on both, and the description compares synced
// with the database it came from.
func TestSchemaInspectOfRenamedSerialTableReplaysE2E(t *testing.T) {
	c := qt.New(t)
	f := newRenamedSerialFixture(c)
	described := writeRenamedSerialFile(c, f.describe(c))

	applied, err := runCompatVerb("schema", "apply", "-u", pinnedDevURL(c, f.empty.url, "public"),
		"--to", "file://"+described, "--dev-url", f.dev, "--auto-approve")
	c.Assert(err, qt.IsNil, qt.Commentf("%s", applied))
	compared, err := runCompatVerb("schema", "diff", "--from", pinnedDevURL(c, f.target.url, "public"),
		"--to", "file://"+described, "--dev-url", f.dev)

	c.Assert(err, qt.IsNil, qt.Commentf("%s", compared))
	c.Assert(f.sequenceGrants(c, f.empty.conn), qt.Equals, "products_code_seq=USAGE products_id_seq=USAGE")
	c.Assert(strings.TrimSpace(compared), qt.Equals, "Schemas are synced, no changes to be made.")
}

// TestSchemaApplyAddsColumnToRenamedSerialTableE2E applies the description
// with one column more to the database it came from. The rehearsal replays the
// database on the dev database first, which is where the old name failed. The
// column is added and the grants stay on the sequences the database holds.
func TestSchemaApplyAddsColumnToRenamedSerialTableE2E(t *testing.T) {
	c := qt.New(t)
	f := newRenamedSerialFixture(c)
	path := writeRenamedSerialFile(c, strings.Replace(f.describe(c), `"title" text`, `"title" text, "note" text`, 1))

	output, err := runCompatVerb("schema", "apply", "-u", pinnedDevURL(c, f.target.url, "public"),
		"--to", "file://"+path, "--dev-url", f.dev, "--auto-approve")

	c.Assert(err, qt.IsNil, qt.Commentf("%s", output))
	var columns int
	c.Assert(f.target.conn.QueryRowContext(c.Context(),
		"SELECT count(*) FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'note'").Scan(&columns), qt.IsNil)
	c.Assert(columns, qt.Equals, 1)
	c.Assert(f.sequenceGrants(c, f.target.conn), qt.Equals, "items_code_seq=USAGE items_id_seq=USAGE")
}

// TestSchemaDiffRenamedSerialGrantUnderEitherNameE2E compares the database with
// a schema file that writes the grants under either name. Both compare synced
// on both binaries.
func TestSchemaDiffRenamedSerialGrantUnderEitherNameE2E(t *testing.T) {
	tests := []struct {
		name      string
		sequences []string
	}{
		{name: "the names the database holds", sequences: []string{"items_id_seq", "items_code_seq"}},
		{name: "the names a replay creates", sequences: []string{"products_id_seq", "products_code_seq"}},
	}
	for binary, run := range columnSequenceGrantBinaries {
		for _, test := range tests {
			t.Run(binary+"/"+test.name, func(t *testing.T) {
				c := qt.New(t)
				f := newRenamedSerialFixture(c)
				path := writeRenamedSerialSchema(c, f.role, test.sequences...)

				output, err := run(pinnedDevURL(c, f.target.url, "public"), f.dev, path, nil)

				c.Assert(err, qt.IsNil, qt.Commentf("%s", output))
				c.Assert(output, qt.Not(qt.Contains), "SEQUENCE")
			})
		}
	}
}

// TestSchemaApplyGrantsRenamedSerialSequenceItLacksE2E revokes the grant on
// items_id_seq and applies a schema file that grants it under the name a
// replay creates. The plan grants on the sequence the database holds, which
// the server accepts, and the grant is back.
func TestSchemaApplyGrantsRenamedSerialSequenceItLacksE2E(t *testing.T) {
	c := qt.New(t)
	f := newRenamedSerialFixture(c)
	_, err := f.target.conn.ExecContext(c.Context(), "REVOKE USAGE ON SEQUENCE items_id_seq FROM "+f.role)
	c.Assert(err, qt.IsNil)
	path := writeRenamedSerialSchema(c, f.role, "products_id_seq", "products_code_seq")

	output, err := runCompatVerb("schema", "apply", "-u", pinnedDevURL(c, f.target.url, "public"),
		"--to", "file://"+path, "--dev-url", f.dev, "--auto-approve")

	c.Assert(err, qt.IsNil, qt.Commentf("%s", output))
	c.Assert(output, qt.Contains, `GRANT USAGE ON SEQUENCE "items_id_seq"`)
	c.Assert(f.sequenceGrants(c, f.target.conn), qt.Equals, "items_code_seq=USAGE items_id_seq=USAGE")
}

// writeRenamedSerialSchema writes a schema file declaring products as it was
// created, with a USAGE grant to role on each named sequence.
func writeRenamedSerialSchema(c *qt.C, role string, sequences ...string) string {
	c.Helper()
	var schema strings.Builder
	schema.WriteString("CREATE TABLE products (id bigserial PRIMARY KEY, code bigint GENERATED BY DEFAULT AS IDENTITY, title text);\n")
	for _, sequence := range sequences {
		fmt.Fprintf(&schema, "GRANT USAGE ON SEQUENCE %s TO %s;\n", sequence, role)
	}
	return writeRenamedSerialFile(c, schema.String())
}
