package schemacensus

// registry is the disposition of every field Fields() reports.
//
// It is sorted by field path so a diff over it reads as a diff over the model.
// Nothing here is trusted on its own: the gate in registry_test.go requires the
// set to match Fields() exactly, requires a reason on every entry that is not
// DDL, and requires Measure to agree with every entry that is.
var registry = []Entry{
	{Field: "ast.MatViewRefreshSpec.Append", Disposition: DDL},
	{Field: "ast.MatViewRefreshSpec.DependsOn", Disposition: DDL},
	{Field: "ast.MatViewRefreshSpec.Interval", Disposition: DDL},
	{Field: "ast.MatViewRefreshSpec.Mode", Disposition: DDL},
	{Field: "ast.MatViewRefreshSpec.Offset", Disposition: DDL},
	{Field: "ast.MatViewRefreshSpec.Randomize", Disposition: DDL},
	{Field: "ast.RowDeletionPolicySpec.Column", Disposition: DDL},
	{Field: "ast.RowDeletionPolicySpec.Interval", Disposition: DDL},
	{Field: "ast.RowTTLSpec.DeleteBatchSize", Disposition: DDL},
	{Field: "ast.RowTTLSpec.DeleteRateLimit", Disposition: DDL},
	{Field: "ast.RowTTLSpec.DisableChangefeedReplication", Disposition: DDL},
	{Field: "ast.RowTTLSpec.ExpirationExpression", Disposition: DDL},
	{Field: "ast.RowTTLSpec.ExpireAfter", Disposition: DDL},
	{Field: "ast.RowTTLSpec.JobCron", Disposition: DDL},
	{Field: "ast.RowTTLSpec.LabelMetrics", Disposition: DDL},
	{Field: "ast.RowTTLSpec.Pause", Disposition: DDL},
	{Field: "ast.RowTTLSpec.RowStatsPollInterval", Disposition: DDL},
	{Field: "ast.RowTTLSpec.SelectBatchSize", Disposition: DDL},
	{Field: "ast.RowTTLSpec.SelectRateLimit", Disposition: DDL},
	{Field: "coverage.Object.Kind", Disposition: Comparison, Reason: "which kind the undescribed object is"},
	{Field: "coverage.Object.Name", Disposition: Comparison, Reason: "which object was not described"},
	{Field: "coverage.Object.Provenance", Disposition: Comparison, Reason: "how Ptah learned the object was not described"},
	{Field: "coverage.Object.Reason", Disposition: Comparison, Reason: "why it was not described"},
	{Field: "coverage.Set.Objects", Disposition: Comparison, Reason: "the per-object half of that record"},
	{Field: "schemamodel.CompositeField.Name", Disposition: DDL},
	{Field: "schemamodel.CompositeField.Type", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Comment", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Dialects", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Fields", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Name", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Schema", Disposition: DDL},
	{Field: "schemamodel.CompositeType.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Constraint.CheckExpression", Disposition: DDL},
	{Field: "schemamodel.Constraint.Columns", Disposition: DDL},
	{Field: "schemamodel.Constraint.Comment", Disposition: DDL},
	{Field: "schemamodel.Constraint.Deferrable", Disposition: DDL},
	{Field: "schemamodel.Constraint.ExcludeElements", Disposition: DDL},
	{Field: "schemamodel.Constraint.ForeignColumn", Disposition: DDL},
	{Field: "schemamodel.Constraint.ForeignColumns", Disposition: DDL},
	{Field: "schemamodel.Constraint.ForeignTable", Disposition: DDL},
	{Field: "schemamodel.Constraint.IncludeColumns", Disposition: DDL},
	{Field: "schemamodel.Constraint.Initially", Disposition: DDL},
	{Field: "schemamodel.Constraint.Name", Disposition: DDL},
	{Field: "schemamodel.Constraint.NullsDistinct", Disposition: DDL},
	{Field: "schemamodel.Constraint.OnDelete", Disposition: DDL},
	{Field: "schemamodel.Constraint.OnUpdate", Disposition: DDL},
	{Field: "schemamodel.Constraint.RequiresExtensions", Disposition: Planning, Reason: "which extensions must exist before this constraint can be created; it orders the statements and appears in none of them"},
	{Field: "schemamodel.Constraint.StructName", Disposition: DDL},
	{Field: "schemamodel.Constraint.Table", Disposition: DDL},
	{Field: "schemamodel.Constraint.Type", Disposition: DDL},
	{Field: "schemamodel.Constraint.UsingMethod", Disposition: DDL},
	{Field: "schemamodel.Constraint.WhereCondition", Disposition: DDL},
	{Field: "schemamodel.ContinuousAggregate.Body", Disposition: DDL},
	{Field: "schemamodel.ContinuousAggregate.Comment", Disposition: DDL},
	{Field: "schemamodel.ContinuousAggregate.MaterializedOnly", Disposition: DDL},
	{Field: "schemamodel.ContinuousAggregate.Name", Disposition: DDL},
	{Field: "schemamodel.ContinuousAggregate.Schema", Disposition: DDL},
	{Field: "schemamodel.ContinuousAggregate.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Database.CompositeTypes", Disposition: DDL},
	{Field: "schemamodel.Database.Constraints", Disposition: DDL},
	{Field: "schemamodel.Database.ContinuousAggregates", Disposition: DDL},
	{Field: "schemamodel.Database.Dependencies", Disposition: Derived, Reason: "table creation order, derived by Finalize from the declared foreign keys"},
	{Field: "schemamodel.Database.Domains", Disposition: DDL},
	{Field: "schemamodel.Database.EmbeddedFields", Disposition: DDL},
	{Field: "schemamodel.Database.EmbeddedSources", Disposition: DDL},
	{Field: "schemamodel.Database.Enums", Disposition: DDL},
	{Field: "schemamodel.Database.ExtendedProperties", Disposition: DDL},
	{Field: "schemamodel.Database.Extensions", Disposition: DDL},
	{Field: "schemamodel.Database.Fields", Disposition: DDL},
	{Field: "schemamodel.Database.FunctionDependencies", Disposition: Derived, Reason: "function creation order, derived by Finalize from the declared bodies"},
	{Field: "schemamodel.Database.Functions", Disposition: DDL},
	{Field: "schemamodel.Database.Grants", Disposition: DDL},
	{Field: "schemamodel.Database.Hypertables", Disposition: DDL},
	{Field: "schemamodel.Database.Indexes", Disposition: DDL},
	{Field: "schemamodel.Database.ManagedData", Disposition: Data, Reason: "reference and seed rows; `ptah seed` writes them and `ptah schema render` does not"},
	{Field: "schemamodel.Database.MaterializedViews", Disposition: DDL},
	{Field: "schemamodel.Database.NotDescribed", Disposition: Comparison, Reason: "what the description does not claim to describe; it decides what a diff may conclude about an object nobody looked at, and reaches no statement"},
	{Field: "schemamodel.Database.RLSEnabledTables", Disposition: DDL},
	{Field: "schemamodel.Database.RLSPolicies", Disposition: DDL},
	{Field: "schemamodel.Database.Ranges", Disposition: DDL},
	{Field: "schemamodel.Database.Roles", Disposition: DDL},
	{Field: "schemamodel.Database.Schemas", Disposition: DDL},
	{Field: "schemamodel.Database.SelfReferencingForeignKeys", Disposition: Derived, Reason: "derived by Finalize from the declared foreign keys, so the planner can create the table before the reference to itself"},
	{Field: "schemamodel.Database.Sequences", Disposition: DDL},
	{Field: "schemamodel.Database.Synonyms", Disposition: DDL},
	{Field: "schemamodel.Database.Tables", Disposition: DDL},
	{Field: "schemamodel.Database.Triggers", Disposition: DDL},
	{Field: "schemamodel.Database.Views", Disposition: DDL},
	{Field: "schemamodel.Domain.BaseType", Disposition: DDL},
	{Field: "schemamodel.Domain.Check", Disposition: DDL},
	{Field: "schemamodel.Domain.Comment", Disposition: DDL},
	{Field: "schemamodel.Domain.Default", Disposition: DDL},
	{Field: "schemamodel.Domain.DefaultExpr", Disposition: DDL},
	{Field: "schemamodel.Domain.Dialects", Disposition: DDL},
	{Field: "schemamodel.Domain.Name", Disposition: DDL},
	{Field: "schemamodel.Domain.NotNull", Disposition: DDL},
	{Field: "schemamodel.Domain.Schema", Disposition: DDL},
	{Field: "schemamodel.Domain.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.EmbeddedField.Comment", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.EmbeddedTypeName", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Field", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Mode", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Name", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Nullable", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.OnDelete", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.OnUpdate", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Overrides", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Prefix", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Ref", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.StructName", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Type", Disposition: DDL},
	{Field: "schemamodel.EmbeddedSources.Definitions", Disposition: Derived, Reason: "the embedded declarations retained so materialization can run again after a merge; the columns they produce are what reaches DDL"},
	{Field: "schemamodel.EmbeddedSources.Fields", Disposition: DDL},
	{Field: "schemamodel.Enum.Name", Disposition: DDL},
	{Field: "schemamodel.Enum.Schema", Disposition: DDL},
	{Field: "schemamodel.Enum.Values", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Column", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Comment", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Name", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Schema", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.ExtendedProperty.Table", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Value", Disposition: DDL},
	{Field: "schemamodel.Extension.Comment", Disposition: DDL},
	{Field: "schemamodel.Extension.Dialects", Disposition: DDL},
	{Field: "schemamodel.Extension.IfNotExists", Disposition: DDL},
	{Field: "schemamodel.Extension.Name", Disposition: DDL},
	{Field: "schemamodel.Extension.Provides", Disposition: Planning, Reason: "what the extension supplies, so a declaration depending on it can be ordered after it"},
	{Field: "schemamodel.Extension.Schema", Disposition: DDL},
	{Field: "schemamodel.Extension.Version", Disposition: DDL},
	{Field: "schemamodel.Field.APIExpose", Disposition: Export, Reason: "whether the column reaches an exported API contract, and in which direction; Ptah emits no runtime that could enforce it"},
	{Field: "schemamodel.Field.APIName", Disposition: Export, Reason: "the name an exported API document carries when it differs from the database name"},
	{Field: "schemamodel.Field.APINames", Disposition: Export, Reason: "the per-format names an exported API document carries, overriding the general one"},
	{Field: "schemamodel.Field.APIType", Disposition: Export, Reason: "the type an exported document should project the column as, which changes no stored value"},
	{Field: "schemamodel.Field.AutoInc", Disposition: DDL},
	{Field: "schemamodel.Field.Charset", Disposition: DDL},
	{Field: "schemamodel.Field.Check", Disposition: DDL},
	{Field: "schemamodel.Field.CheckName", Disposition: DDL},
	{Field: "schemamodel.Field.Collate", Disposition: DDL},
	{Field: "schemamodel.Field.Comment", Disposition: DDL},
	{Field: "schemamodel.Field.Default", Disposition: DDL},
	{Field: "schemamodel.Field.DefaultExpr", Disposition: DDL},
	{Field: "schemamodel.Field.DefaultSet", Disposition: DDL},
	{Field: "schemamodel.Field.Deferrable", Disposition: DDL},
	{Field: "schemamodel.Field.Enum", Disposition: DDL, Gap: "https://github.com/stokaro/ptah/issues/2611"},
	{Field: "schemamodel.Field.FieldName", Disposition: DDL},
	{Field: "schemamodel.Field.Foreign", Disposition: DDL},
	{Field: "schemamodel.Field.ForeignKeyName", Disposition: DDL},
	{Field: "schemamodel.Field.GeneratedExpression", Disposition: DDL},
	{Field: "schemamodel.Field.GeneratedFromEmbedded", Disposition: Derived, Reason: "marks a column Finalize materialized from an embedded declaration, so a later finalization can rebuild it rather than duplicate it"},
	{Field: "schemamodel.Field.GeneratedKind", Disposition: DDL},
	{Field: "schemamodel.Field.IdentityGeneration", Disposition: DDL},
	{Field: "schemamodel.Field.IdentityIncrement", Disposition: DDL},
	{Field: "schemamodel.Field.IdentityOptions", Disposition: DDL},
	{Field: "schemamodel.Field.IdentityStart", Disposition: DDL},
	{Field: "schemamodel.Field.Initially", Disposition: DDL},
	{Field: "schemamodel.Field.Name", Disposition: DDL},
	{Field: "schemamodel.Field.NotNullConstraintName", Disposition: DDL},
	{Field: "schemamodel.Field.Nullable", Disposition: DDL},
	{Field: "schemamodel.Field.OnDelete", Disposition: DDL},
	{Field: "schemamodel.Field.OnUpdate", Disposition: DDL},
	{Field: "schemamodel.Field.Overrides", Disposition: DDL},
	{Field: "schemamodel.Field.Primary", Disposition: DDL},
	{Field: "schemamodel.Field.StructName", Disposition: DDL},
	{Field: "schemamodel.Field.Type", Disposition: DDL},
	{Field: "schemamodel.Field.TypeIsDeclaredText", Disposition: DDL},
	{Field: "schemamodel.Field.TypeRawSQL", Disposition: DDL},
	{Field: "schemamodel.Field.Unique", Disposition: DDL},
	{Field: "schemamodel.Field.UniqueExpr", Disposition: DDL},
	{Field: "schemamodel.Field.UpdateExpression", Disposition: DDL},
	{Field: "schemamodel.Function.Body", Disposition: DDL},
	{Field: "schemamodel.Function.Comment", Disposition: DDL},
	{Field: "schemamodel.Function.Dialects", Disposition: DDL},
	{Field: "schemamodel.Function.Kind", Disposition: DDL},
	{Field: "schemamodel.Function.Language", Disposition: DDL},
	{Field: "schemamodel.Function.Name", Disposition: DDL},
	{Field: "schemamodel.Function.Parameters", Disposition: DDL},
	{Field: "schemamodel.Function.Returns", Disposition: DDL},
	{Field: "schemamodel.Function.Security", Disposition: DDL},
	{Field: "schemamodel.Function.Settings", Disposition: DDL},
	{Field: "schemamodel.Function.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Function.Volatility", Disposition: DDL},
	{Field: "schemamodel.Grant.Comment", Disposition: DDL},
	{Field: "schemamodel.Grant.Dialects", Disposition: DDL},
	{Field: "schemamodel.Grant.GrantedBy", Disposition: DDL, Gap: "https://github.com/stokaro/ptah/issues/2611"},
	{Field: "schemamodel.Grant.OnSchema", Disposition: DDL},
	{Field: "schemamodel.Grant.OnSequence", Disposition: DDL},
	{Field: "schemamodel.Grant.OnTable", Disposition: DDL},
	{Field: "schemamodel.Grant.Privileges", Disposition: DDL},
	{Field: "schemamodel.Grant.Role", Disposition: DDL},
	{Field: "schemamodel.Grant.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Grant.WithOption", Disposition: DDL},
	{Field: "schemamodel.Hypertable.ChunkInterval", Disposition: DDL},
	{Field: "schemamodel.Hypertable.Column", Disposition: DDL},
	{Field: "schemamodel.Hypertable.Comment", Disposition: DDL},
	{Field: "schemamodel.Hypertable.IfNotExists", Disposition: DDL},
	{Field: "schemamodel.Hypertable.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Hypertable.Table", Disposition: DDL},
	{Field: "schemamodel.Index.Comment", Disposition: DDL},
	{Field: "schemamodel.Index.Concurrently", Disposition: Planning, Reason: "asks that the index be BUILT without locking when added to a live table; internal/concurrentindex owns that decision, and only a plan carries it into DDL"},
	{Field: "schemamodel.Index.Condition", Disposition: DDL},
	{Field: "schemamodel.Index.Fields", Disposition: DDL},
	{Field: "schemamodel.Index.Granularity", Disposition: DDL},
	{Field: "schemamodel.Index.IncludeColumns", Disposition: DDL},
	{Field: "schemamodel.Index.Name", Disposition: DDL},
	{Field: "schemamodel.Index.NullsDistinct", Disposition: DDL},
	{Field: "schemamodel.Index.Operator", Disposition: DDL},
	{Field: "schemamodel.Index.Parser", Disposition: DDL},
	{Field: "schemamodel.Index.Parts", Disposition: DDL},
	{Field: "schemamodel.Index.RequiresExtensions", Disposition: Planning, Reason: "the same ordering fact for an index"},
	{Field: "schemamodel.Index.StorageParams", Disposition: DDL},
	{Field: "schemamodel.Index.StructName", Disposition: DDL},
	{Field: "schemamodel.Index.TableName", Disposition: DDL},
	{Field: "schemamodel.Index.Type", Disposition: DDL},
	{Field: "schemamodel.Index.Unique", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Desc", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Expr", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Name", Disposition: DDL},
	{Field: "schemamodel.IndexPart.NullsOrder", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Operator", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Prefix", Disposition: DDL},
	{Field: "schemamodel.ManagedData.File", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.Keys", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.Schema", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.SourceDir", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.StructName", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.Table", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.MaterializedView.Body", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.Comment", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.Dialects", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.Name", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.Refresh", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.PartitionPart.Expr", Disposition: DDL},
	{Field: "schemamodel.PartitionPart.Name", Disposition: DDL},
	{Field: "schemamodel.PartitionSpec.Parts", Disposition: DDL},
	{Field: "schemamodel.PartitionSpec.Type", Disposition: DDL},
	{Field: "schemamodel.PrimaryKeyPart.Desc", Disposition: DDL},
	{Field: "schemamodel.PrimaryKeyPart.Name", Disposition: DDL},
	{Field: "schemamodel.PrimaryKeyPart.Prefix", Disposition: DDL},
	{Field: "schemamodel.RLSEnabledTable.Comment", Disposition: DDL},
	{Field: "schemamodel.RLSEnabledTable.Dialects", Disposition: DDL},
	{Field: "schemamodel.RLSEnabledTable.StructName", Disposition: DDL},
	{Field: "schemamodel.RLSEnabledTable.Table", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Comment", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Dialects", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Name", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.PolicyFor", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.StructName", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Table", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.ToRoles", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.UsingExpression", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.WithCheckExpression", Disposition: DDL},
	{Field: "schemamodel.Range.Canonical", Disposition: DDL},
	{Field: "schemamodel.Range.ClearedAttributes", Disposition: Comparison, Reason: "records the attributes a declaration explicitly cleared, so a comparison can tell a value nobody wrote from one somebody removed"},
	{Field: "schemamodel.Range.Collation", Disposition: DDL},
	{Field: "schemamodel.Range.Comment", Disposition: DDL},
	{Field: "schemamodel.Range.Dialects", Disposition: DDL},
	{Field: "schemamodel.Range.Name", Disposition: DDL},
	{Field: "schemamodel.Range.Schema", Disposition: DDL},
	{Field: "schemamodel.Range.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Range.Subtype", Disposition: DDL},
	{Field: "schemamodel.Range.SubtypeDiff", Disposition: DDL},
	{Field: "schemamodel.Range.SubtypeOpClass", Disposition: DDL},
	{Field: "schemamodel.Role.Comment", Disposition: DDL},
	{Field: "schemamodel.Role.CreateDB", Disposition: DDL},
	{Field: "schemamodel.Role.CreateRole", Disposition: DDL},
	{Field: "schemamodel.Role.Dialects", Disposition: DDL},
	{Field: "schemamodel.Role.Inherit", Disposition: DDL},
	{Field: "schemamodel.Role.Login", Disposition: DDL},
	{Field: "schemamodel.Role.Name", Disposition: DDL},
	{Field: "schemamodel.Role.Password", Disposition: DDL},
	{Field: "schemamodel.Role.Replication", Disposition: DDL},
	{Field: "schemamodel.Role.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Role.Superuser", Disposition: DDL},
	{Field: "schemamodel.Schema.Charset", Disposition: DDL},
	{Field: "schemamodel.Schema.Collate", Disposition: DDL},
	{Field: "schemamodel.Schema.Comment", Disposition: DDL},
	{Field: "schemamodel.Schema.Name", Disposition: DDL},
	{Field: "schemamodel.SelfReferencingFK.FieldName", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.SelfReferencingFK.Foreign", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.SelfReferencingFK.ForeignKeyName", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.SelfReferencingFK.OnDelete", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.SelfReferencingFK.OnUpdate", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.Sequence.AsType", Disposition: DDL},
	{Field: "schemamodel.Sequence.Cache", Disposition: DDL},
	{Field: "schemamodel.Sequence.Comment", Disposition: DDL},
	{Field: "schemamodel.Sequence.Cycle", Disposition: DDL},
	{Field: "schemamodel.Sequence.Dialects", Disposition: DDL},
	{Field: "schemamodel.Sequence.IfNotExists", Disposition: DDL},
	{Field: "schemamodel.Sequence.Increment", Disposition: DDL},
	{Field: "schemamodel.Sequence.MaxValue", Disposition: DDL},
	{Field: "schemamodel.Sequence.MinValue", Disposition: DDL},
	{Field: "schemamodel.Sequence.Name", Disposition: DDL},
	{Field: "schemamodel.Sequence.OwnedBy", Disposition: DDL},
	{Field: "schemamodel.Sequence.Schema", Disposition: DDL},
	{Field: "schemamodel.Sequence.Start", Disposition: DDL},
	{Field: "schemamodel.Sequence.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Synonym.Comment", Disposition: DDL},
	{Field: "schemamodel.Synonym.Name", Disposition: DDL},
	{Field: "schemamodel.Synonym.Schema", Disposition: DDL},
	{Field: "schemamodel.Synonym.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Synonym.Target", Disposition: DDL},
	{Field: "schemamodel.Table.APIName", Disposition: Export, Reason: "the name an exported API document carries when it differs from the database name"},
	{Field: "schemamodel.Table.APINames", Disposition: Export, Reason: "the per-format names an exported API document carries, overriding the general one"},
	{Field: "schemamodel.Table.AutoIncrement", Disposition: DDL},
	{Field: "schemamodel.Table.Charset", Disposition: DDL},
	{Field: "schemamodel.Table.Checks", Disposition: DDL},
	{Field: "schemamodel.Table.Collate", Disposition: DDL},
	{Field: "schemamodel.Table.Comment", Disposition: DDL},
	{Field: "schemamodel.Table.CustomSQL", Disposition: DDL},
	{Field: "schemamodel.Table.Engine", Disposition: DDL},
	{Field: "schemamodel.Table.Name", Disposition: DDL},
	{Field: "schemamodel.Table.Overrides", Disposition: DDL},
	{Field: "schemamodel.Table.Partition", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKey", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyInclude", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyName", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyParts", Disposition: DDL},
	{Field: "schemamodel.Table.RowDeletionPolicy", Disposition: DDL},
	{Field: "schemamodel.Table.RowTTL", Disposition: DDL},
	{Field: "schemamodel.Table.Schema", Disposition: DDL},
	{Field: "schemamodel.Table.Strict", Disposition: DDL},
	{Field: "schemamodel.Table.StructName", Disposition: DDL},
	{Field: "schemamodel.Table.VirtualArguments", Disposition: DDL},
	{Field: "schemamodel.Table.VirtualModule", Disposition: DDL},
	{Field: "schemamodel.Table.WithoutRowID", Disposition: DDL},
	{Field: "schemamodel.TargetNames.GraphQL", Disposition: Export, Reason: "the name one export format carries, overriding the general one"},
	{Field: "schemamodel.TargetNames.OpenAPI", Disposition: Export, Reason: "the name one export format carries, overriding the general one"},
	{Field: "schemamodel.TargetNames.Protobuf", Disposition: Export, Reason: "the name one export format carries, overriding the general one"},
	{Field: "schemamodel.Trigger.Body", Disposition: DDL},
	{Field: "schemamodel.Trigger.Comment", Disposition: DDL},
	{Field: "schemamodel.Trigger.Dialects", Disposition: DDL},
	{Field: "schemamodel.Trigger.Event", Disposition: DDL},
	{Field: "schemamodel.Trigger.ExecuteFunction", Disposition: DDL},
	{Field: "schemamodel.Trigger.ForEach", Disposition: DDL},
	{Field: "schemamodel.Trigger.Name", Disposition: DDL},
	{Field: "schemamodel.Trigger.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Trigger.Table", Disposition: DDL},
	{Field: "schemamodel.Trigger.Timing", Disposition: DDL},
	{Field: "schemamodel.View.Attributes", Disposition: DDL},
	{Field: "schemamodel.View.Body", Disposition: DDL},
	{Field: "schemamodel.View.Comment", Disposition: DDL},
	{Field: "schemamodel.View.Dialects", Disposition: DDL},
	{Field: "schemamodel.View.Name", Disposition: DDL},
	{Field: "schemamodel.View.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.View.WithCheck", Disposition: DDL},
}
