package schemacensus

// registry is the disposition of every field Fields() reports.
//
// It is sorted by field path so a diff over it reads as a diff over the model.
// Nothing here is trusted on its own: the gate in registry_test.go requires the
// set to match Fields() exactly, requires a reason on every entry that is not
// DDL, and requires Measure to agree with every entry that is.
var registry = []Entry{
	{Field: "chschema.DesiredIndex.Granularity", Disposition: DDL},
	{Field: "chschema.DesiredIndex.IndexType", Disposition: DDL},
	{Field: "chschema.DesiredRefresh.Schedule", Disposition: DDL},
	{Field: "chschema.DesiredRowPolicy.Composition", Disposition: DDL},
	{Field: "chschema.DesiredRowPolicy.Filter", Disposition: DDL},
	{Field: "chschema.DesiredRowPolicy.NormalizedFilter", Disposition: Comparison, Reason: "a connected server's spelling of the declared filter, attached before a live comparison; a statement writes the filter as declared"},
	{Field: "chschema.DesiredRowPolicy.Roles", Disposition: DDL},
	{Field: "chschema.DesiredRowPolicy.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the policy's database, table and name are its identity"},
	{Field: "chschema.DesiredTable.Engine", Disposition: DDL},
	{Field: "chschema.DesiredTable.OrderBy", Disposition: DDL},
	{Field: "chschema.DesiredTable.PartitionBy", Disposition: DDL},
	{Field: "chschema.DesiredTable.PrimaryKey", Disposition: DDL},
	{Field: "chschema.DesiredTable.SampleBy", Disposition: DDL},
	{Field: "chschema.DesiredTable.Settings", Disposition: DDL},
	{Field: "chschema.DesiredTable.TTL", Disposition: DDL},
	{Field: "chschema.GranularitySetting.State", Disposition: DDL},
	{Field: "chschema.GranularitySetting.Value", Disposition: DDL},
	{Field: "chschema.RoleSelection.All", Disposition: DDL},
	{Field: "chschema.RoleSelection.Except", Disposition: DDL},
	{Field: "chschema.RoleSelection.Names", Disposition: DDL},
	{Field: "chschema.Schedule.Append", Disposition: DDL},
	{Field: "chschema.Schedule.DependsOn", Disposition: DDL},
	{Field: "chschema.Schedule.Interval", Disposition: DDL},
	{Field: "chschema.Schedule.Mode", Disposition: DDL},
	{Field: "chschema.Schedule.Offset", Disposition: DDL},
	{Field: "chschema.Schedule.Randomize", Disposition: DDL},
	{Field: "chschema.Setting.State", Disposition: DDL},
	{Field: "chschema.Setting.Value", Disposition: DDL},
	{Field: "crdbschema.DesiredRowTTL.Policy", Disposition: DDL},
	{Field: "crdbschema.Policy.DeleteBatchSize", Disposition: DDL},
	{Field: "crdbschema.Policy.DeleteRateLimit", Disposition: DDL},
	{Field: "crdbschema.Policy.DisableChangefeedReplication", Disposition: DDL},
	{Field: "crdbschema.Policy.ExpirationExpression", Disposition: DDL},
	{Field: "crdbschema.Policy.ExpireAfter", Disposition: DDL},
	{Field: "crdbschema.Policy.JobCron", Disposition: DDL},
	{Field: "crdbschema.Policy.LabelMetrics", Disposition: DDL},
	{Field: "crdbschema.Policy.Pause", Disposition: DDL},
	{Field: "crdbschema.Policy.RowStatsPollInterval", Disposition: DDL},
	{Field: "crdbschema.Policy.SelectBatchSize", Disposition: DDL},
	{Field: "crdbschema.Policy.SelectRateLimit", Disposition: DDL},
	{Field: "mssqlschema.DesiredSecurityPolicy.Enabled", Disposition: DDL},
	{Field: "mssqlschema.DesiredSecurityPolicy.NotForReplication", Disposition: DDL},
	{Field: "mssqlschema.DesiredSecurityPolicy.Predicates", Disposition: DDL},
	{Field: "mssqlschema.DesiredSecurityPolicy.SchemaBinding", Disposition: DDL},
	{Field: "mssqlschema.DesiredSecurityPolicy.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the policy's schema and name are its identity"},
	{Field: "mssqlschema.ObjectName.Name", Disposition: DDL},
	{Field: "mssqlschema.ObjectName.Schema", Disposition: DDL},
	{Field: "mssqlschema.Predicate.Arguments", Disposition: DDL},
	{Field: "mssqlschema.Predicate.Function", Disposition: DDL},
	{Field: "mssqlschema.Predicate.Operation", Disposition: DDL},
	{Field: "mssqlschema.Predicate.Table", Disposition: DDL},
	{Field: "mssqlschema.Predicate.Type", Disposition: DDL},
	{Field: "pgpolicy.DesiredPolicy.Command", Disposition: DDL},
	{Field: "pgpolicy.DesiredPolicy.Comment", Disposition: DDL},
	{Field: "pgpolicy.DesiredPolicy.Composition", Disposition: DDL},
	{Field: "pgpolicy.DesiredPolicy.Normalized", Disposition: Comparison, Reason: "a connected server's spelling of the declared roles and clauses, attached before a live comparison; a statement writes the declaration"},
	{Field: "pgpolicy.DesiredPolicy.Roles", Disposition: DDL},
	{Field: "pgpolicy.DesiredPolicy.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the policy's schema, table and name are its identity"},
	{Field: "pgpolicy.DesiredPolicy.Using", Disposition: DDL},
	{Field: "pgpolicy.DesiredPolicy.WithCheck", Disposition: DDL},
	{Field: "pgpolicy.DesiredTableState.Comment", Disposition: DDL},
	{Field: "pgpolicy.DesiredTableState.Enabled", Disposition: DDL},
	{Field: "pgpolicy.DesiredTableState.Forced", Disposition: DDL},
	{Field: "pgpolicy.DesiredTableState.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the switches belong to the table that carries them"},
	{Field: "pgpolicy.NormalizedPolicy.Roles", Disposition: Comparison, Reason: "the server's resolution of the declared roles, compared with the catalog's and never rendered"},
	{Field: "pgpolicy.NormalizedPolicy.Using", Disposition: Comparison, Reason: "the server's spelling of a declared USING expression, compared with the catalog's and never rendered"},
	{Field: "pgpolicy.NormalizedPolicy.WithCheck", Disposition: Comparison, Reason: "the server's spelling of a declared WITH CHECK expression, compared with the catalog's and never rendered"},
	{Field: "pgpolicy.RoleSelector.Keyword", Disposition: DDL},
	{Field: "pgpolicy.RoleSelector.Name", Disposition: DDL},
	{Field: "tsschema.DesiredContinuousAggregate.Body", Disposition: DDL},
	{Field: "tsschema.DesiredContinuousAggregate.Comment", Disposition: DDL},
	{Field: "tsschema.DesiredContinuousAggregate.MaterializedOnly", Disposition: DDL},
	{Field: "tsschema.DesiredContinuousAggregate.Normalized", Disposition: Comparison, Reason: "a connected server's rewrite of the declared body, attached before a live comparison; a statement writes the body as declared"},
	{Field: "tsschema.DesiredContinuousAggregate.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the aggregate's schema and name are its identity"},
	{Field: "tsschema.DesiredHypertable.ChunkInterval", Disposition: DDL},
	{Field: "tsschema.DesiredHypertable.Column", Disposition: DDL},
	{Field: "tsschema.DesiredHypertable.Comment", Disposition: DDL},
	{Field: "tsschema.DesiredHypertable.IfNotExists", Disposition: DDL},
	{Field: "tsschema.NormalizedBody.Body", Disposition: Comparison, Reason: "the server's spelling of a declared body, compared with the catalog definition and never rendered"},
	{Field: "mysqlschema.DesiredColumnSettings.Charset", Disposition: DDL},
	{Field: "mysqlschema.DesiredColumnSettings.OnUpdate", Disposition: DDL},
	{Field: "mysqlschema.DesiredTable.AutoIncrement", Disposition: DDL},
	{Field: "mysqlschema.DesiredTable.Charset", Disposition: DDL},
	{Field: "mysqlschema.DesiredTable.Engine", Disposition: DDL},
	{Field: "spannerschema.DesiredRowDeletion.Policy", Disposition: DDL},
	{Field: "spannerschema.Policy.Column", Disposition: DDL},
	{Field: "spannerschema.Policy.Interval", Disposition: DDL},
	{Field: "ydbschema.ColumnStore.HashColumns", Disposition: DDL},
	{Field: "ydbschema.ColumnStore.Partitions", Disposition: DDL},
	{Field: "ydbschema.ColumnStore.TTL", Disposition: DDL},
	{Field: "ydbschema.DesiredColumnStore.ColumnStore", Disposition: DDL},
	{Field: "ydbschema.TTLTier.ExternalSource", Disposition: DDL},
	{Field: "ydbschema.TTLTier.Interval", Disposition: DDL},
	{Field: "ydbschema.TieredTTL.Column", Disposition: DDL},
	{Field: "ydbschema.TieredTTL.Tiers", Disposition: DDL},
	{Field: "ydbschema.TieredTTL.Unit", Disposition: DDL},
	{Field: "ydbschema.ColumnFamily.CacheMode", Disposition: DDL},
	{Field: "ydbschema.ColumnFamily.Columns", Disposition: DDL},
	{Field: "ydbschema.ColumnFamily.Compression", Disposition: DDL},
	{Field: "ydbschema.ColumnFamily.Data", Disposition: DDL},
	{Field: "ydbschema.ColumnFamily.KeepInMemory", Disposition: Comparison, Reason: "keep_in_memory as a read finds it on a YDB family; no YQL statement writes it, and it decides whether a change or a rebuild is refused"},
	{Field: "ydbschema.ColumnFamily.Name", Disposition: DDL},
	{Field: "ydbschema.DesiredColumnFamilies.Families", Disposition: DDL},
	{Field: "ydbschema.DesiredIndexPartitioning.IndexPartitioning", Disposition: DDL},
	{Field: "ydbschema.DesiredTablePartitioning.TablePartitioning", Disposition: DDL},
	{Field: "ydbschema.IndexPartitioning.ByLoad", Disposition: DDL},
	{Field: "ydbschema.IndexPartitioning.BySize", Disposition: DDL},
	{Field: "ydbschema.IndexPartitioning.MaxPartitions", Disposition: DDL},
	{Field: "ydbschema.IndexPartitioning.MinPartitions", Disposition: DDL},
	{Field: "ydbschema.IndexPartitioning.PartitionSizeMB", Disposition: DDL},
	{Field: "ydbschema.IndexPartitioning.ReadReplicas", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.ByLoad", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.BySize", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.KeyBloomFilter", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.MaxPartitions", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.MinPartitions", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.PartitionAtKeys", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.PartitionSizeMB", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.ReadReplicas", Disposition: DDL},
	{Field: "ydbschema.TablePartitioning.UniformPartitions", Disposition: DDL},
	{Field: "ydbschema.DesiredTTL.Policy", Disposition: DDL},
	{Field: "ydbschema.DesiredVectorIndex.Clusters", Disposition: DDL},
	{Field: "ydbschema.DesiredVectorIndex.Dimension", Disposition: DDL},
	{Field: "ydbschema.DesiredVectorIndex.Distance", Disposition: DDL},
	{Field: "ydbschema.DesiredVectorIndex.Levels", Disposition: DDL},
	{Field: "ydbschema.DesiredVectorIndex.Similarity", Disposition: DDL},
	{Field: "ydbschema.DesiredVectorIndex.VectorType", Disposition: DDL},
	{Field: "ydbschema.TTL.Column", Disposition: DDL},
	{Field: "ydbschema.TTL.Interval", Disposition: DDL},
	{Field: "ydbschema.TTL.Unit", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Facets", Disposition: DDL},
	{Field: "schemamodel.Constraint.Facets", Disposition: DDL},
	{Field: "schemamodel.Database.Facets", Disposition: DDL},
	{Field: "schemamodel.Domain.Facets", Disposition: DDL},
	{Field: "schemamodel.Enum.Facets", Disposition: DDL},
	{Field: "schemamodel.Field.Facets", Disposition: DDL},
	{Field: "schemamodel.Function.Facets", Disposition: DDL},
	{Field: "schemamodel.Index.Facets", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.Facets", Disposition: DDL},
	{Field: "schemamodel.Range.Facets", Disposition: DDL},
	{Field: "schemamodel.Role.Facets", Disposition: DDL},
	{Field: "schemamodel.Schema.Facets", Disposition: DDL},
	{Field: "schemamodel.Sequence.Facets", Disposition: DDL},
	{Field: "schemamodel.Table.Facets", Disposition: DDL},
	{Field: "schemamodel.Trigger.Facets", Disposition: DDL},
	{Field: "schemamodel.View.Facets", Disposition: DDL},
	{Field: "schemamodel.Database.FeatureObjects", Disposition: DDL},
	{Field: "ydbschema.DesiredChangefeed.Spec", Disposition: DDL},
	{Field: "ydbschema.DesiredChangefeed.RetainedReplication", Disposition: Planning, Reason: "retains an observed controller binding and refuses independent changefeed creation or mutation"},
	{Field: "ydbschema.ReplicationBinding.DestinationPath", Disposition: Planning, Reason: "records the observed replica destination without interpreting it as a local replication object"},
	{Field: "ydbschema.ReplicationBinding.ItemID", Disposition: Planning, Reason: "identifies the observed replication target item whose stream must not be managed independently"},
	{Field: "ydbschema.ReplicationBinding.SupportsTopicAutopartitioning", Disposition: Planning, Reason: "preserves observed controller behavior through snapshots and codecs"},
	{Field: "schemamodel.Database.FeatureCoverage", Disposition: Comparison, Reason: "records source knowledge for exact feature models and subjects; limits which state can be compared or reconstructed"},

	{Field: "ydbstreaming.Desired.Spec", Disposition: DDL},
	{Field: "ydbstreaming.Desired.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of query identity"},
	{Field: "ydbstreaming.Desired.AllowStateReset", Disposition: DDL},
	{Field: "ydbstreaming.Spec.Text", Disposition: DDL},
	{Field: "ydbstreaming.Spec.Run", Disposition: DDL},
	{Field: "ydbstreaming.Spec.ResourcePool", Disposition: DDL},
	{Field: "ydbsecret.Desired.ValueEnv", Disposition: DDL},
	{Field: "ydbexternal.Column.Name", Disposition: DDL},
	{Field: "ydbexternal.Column.NotNull", Disposition: DDL},
	{Field: "ydbexternal.Column.Type", Disposition: DDL},
	{Field: "ydbexternal.DataSource.AuthMethod", Disposition: DDL},
	{Field: "ydbexternal.DataSource.Location", Disposition: DDL},
	{Field: "ydbexternal.DataSource.Options", Disposition: DDL},
	{Field: "ydbexternal.DataSource.SourceType", Disposition: DDL},
	{Field: "ydbexternal.DesiredSource.Spec", Disposition: DDL},
	{Field: "ydbexternal.DesiredSource.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of the data source's path"},
	{Field: "ydbexternal.DesiredTable.Spec", Disposition: DDL},
	{Field: "ydbexternal.DesiredTable.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of the external table's path"},
	{Field: "ydbexternal.Table.Columns", Disposition: DDL},
	{Field: "ydbexternal.Table.DataSource", Disposition: DDL},
	{Field: "ydbexternal.Table.Location", Disposition: DDL},
	{Field: "ydbexternal.Table.Options", Disposition: DDL},
	{Field: "ydbreplication.DesiredReplication.Spec", Disposition: DDL},
	{Field: "ydbreplication.DesiredReplication.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of the replication's path"},
	{Field: "ydbreplication.DesiredTransfer.Spec", Disposition: DDL},
	{Field: "ydbreplication.DesiredTransfer.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of the transfer's path"},
	{Field: "ydbtopic.Desired.Spec", Disposition: DDL},
	{Field: "ydbtopic.Desired.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of the topic's path"},
	{Field: "ydbtopic.Spec.AutoPartitioningDownUtilizationPercent", Disposition: DDL},
	{Field: "ydbtopic.Spec.AutoPartitioningStabilizationWindow", Disposition: DDL},
	{Field: "ydbtopic.Spec.AutoPartitioningStrategy", Disposition: DDL},
	{Field: "ydbtopic.Spec.AutoPartitioningUpUtilizationPercent", Disposition: DDL},
	{Field: "ydbtopic.Spec.Consumers", Disposition: DDL},
	{Field: "ydbtopic.Spec.MaxActivePartitions", Disposition: DDL},
	{Field: "ydbtopic.Spec.MinActivePartitions", Disposition: DDL},
	{Field: "ydbtopic.Spec.PartitionWriteBurstBytes", Disposition: DDL},
	{Field: "ydbtopic.Spec.PartitionWriteSpeedBytesPerSecond", Disposition: DDL},
	{Field: "ydbtopic.Spec.RetentionPeriod", Disposition: DDL},
	{Field: "ydbtopic.Spec.SupportedCodecs", Disposition: DDL},
	{Field: "ydbtopic.ConsumerSpec.AvailabilityPeriod", Disposition: DDL},
	{Field: "ydbtopic.ConsumerSpec.Important", Disposition: DDL},
	{Field: "ydbtopic.ConsumerSpec.Name", Disposition: DDL},
	{Field: "ydbtopic.ConsumerSpec.ReadFrom", Disposition: DDL},
	{Field: "ydbtopic.ConsumerSpec.SupportedCodecs", Disposition: DDL},
	{Field: "ydbsecret.Desired.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of the secret's path"},
	{Field: "ydbcoordination.Desired.Spec", Disposition: DDL},
	{Field: "ydbcoordination.Desired.StructName", Disposition: SourceOrigin, Reason: "the Go holder recorded by the source; node identity is independent of the holder"},
	{Field: "ydbcoordination.Spec.AttachConsistencyMode", Disposition: DDL},
	{Field: "ydbcoordination.Spec.RateLimiterCountersMode", Disposition: DDL},
	{Field: "ydbcoordination.Spec.ReadConsistencyMode", Disposition: DDL},
	{Field: "ydbcoordination.Spec.SelfCheckPeriodMillis", Disposition: DDL},
	{Field: "ydbcoordination.Spec.SessionGracePeriodMillis", Disposition: DDL},
	{Field: "ydbreplication.Item.Source", Disposition: DDL},
	{Field: "ydbreplication.Item.Target", Disposition: DDL},
	{Field: "ydbreplication.ReplicationSpec.CommitInterval", Disposition: DDL},
	{Field: "ydbreplication.ReplicationSpec.Connection", Disposition: DDL},
	{Field: "ydbreplication.ReplicationSpec.ConsistencyLevel", Disposition: DDL},
	{Field: "ydbreplication.ReplicationSpec.Items", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.Consumers", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.Disabled", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.Format", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.InitialScan", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.Mode", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.Name", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.ResolvedTimestamps", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.RetentionPeriod", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.SchemaChanges", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.TopicAutoPartitioning", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.TopicMinActivePartitions", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.UserSIDs", Disposition: DDL},
	{Field: "ydbschema.ChangefeedSpec.VirtualTimestamps", Disposition: DDL},

	{Field: "ydbreplication.Connection.ConnectionString", Disposition: DDL},
	{Field: "ydbreplication.Connection.PasswordSecretName", Disposition: DDL},
	{Field: "ydbreplication.Connection.PasswordSecretPath", Disposition: DDL},
	{Field: "ydbreplication.Connection.TokenSecretName", Disposition: DDL},
	{Field: "ydbreplication.Connection.TokenSecretPath", Disposition: DDL},
	{Field: "ydbreplication.Connection.User", Disposition: DDL},
	{Field: "ydbworkload.ClassifierSpec.MemberName", Disposition: DDL},
	{Field: "ydbworkload.ClassifierSpec.Rank", Disposition: DDL},
	{Field: "ydbworkload.ClassifierSpec.ResourcePool", Disposition: DDL},
	{Field: "ydbworkload.PoolSpec.ConcurrentQueryLimit", Disposition: DDL},
	{Field: "ydbworkload.PoolSpec.DatabaseLoadCPUThreshold", Disposition: DDL},
	{Field: "ydbworkload.PoolSpec.QueryCPULimitPercentPerNode", Disposition: DDL},
	{Field: "ydbworkload.PoolSpec.QueryMemoryLimitPercentPerNode", Disposition: DDL},
	{Field: "ydbworkload.PoolSpec.QueueSize", Disposition: DDL},
	{Field: "ydbworkload.PoolSpec.ResourceWeight", Disposition: DDL},
	{Field: "ydbworkload.PoolSpec.TotalCPULimitPercentPerNode", Disposition: DDL},
	{Field: "ydbreplication.TransferSpec.BatchSizeBytes", Disposition: DDL},
	{Field: "ydbreplication.TransferSpec.Connection", Disposition: DDL},
	{Field: "ydbreplication.TransferSpec.Consumer", Disposition: DDL},
	{Field: "ydbreplication.TransferSpec.FlushInterval", Disposition: DDL},
	{Field: "ydbreplication.TransferSpec.Lambda", Disposition: DDL},
	{Field: "ydbreplication.TransferSpec.Source", Disposition: DDL},
	{Field: "ydbreplication.TransferSpec.Target", Disposition: DDL},
	{Field: "coverage.Object.Kind", Disposition: Comparison, Reason: "which kind the undescribed object is"},
	{Field: "coverage.Object.Name", Disposition: Comparison, Reason: "which object was not described"},
	{Field: "coverage.Object.Provenance", Disposition: Comparison, Reason: "how Ptah learned the object was not described"},
	{Field: "coverage.Object.Reason", Disposition: Comparison, Reason: "why it was not described"},
	{Field: "coverage.Set.Objects", Disposition: Comparison, Reason: "the per-object half of that record"},
	{Field: "schemamodel.CompositeField.Name", Disposition: DDL},
	{Field: "schemamodel.CompositeField.Type", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Comment", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Dialects", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Fields", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Name", Disposition: DDL},
	{Field: "schemamodel.CompositeType.Schema", Disposition: DDL},
	{Field: "schemamodel.CompositeType.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Constraint.CheckExpression", Disposition: DDL},
	{Field: "schemamodel.Constraint.Columns", Disposition: DDL},
	{Field: "schemamodel.Constraint.Comment", Disposition: DDL},
	{Field: "schemamodel.Constraint.Deferrable", Disposition: DDL},
	{Field: "schemamodel.Constraint.ExcludeElements", Disposition: DDL},
	{Field: "schemamodel.Constraint.ForeignColumn", Disposition: DDL},
	{Field: "schemamodel.Constraint.ForeignColumns", Disposition: DDL},
	{Field: "schemamodel.Constraint.ForeignTable", Disposition: DDL},
	{Field: "schemamodel.Constraint.IncludeColumns", Disposition: DDL},
	{Field: "schemamodel.Constraint.Initially", Disposition: DDL},
	{Field: "schemamodel.Constraint.Match", Disposition: DDL},
	{Field: "schemamodel.Constraint.Name", Disposition: DDL},
	{Field: "schemamodel.Constraint.NotEnforced", Disposition: DDL},
	{Field: "schemamodel.Constraint.NotValid", Disposition: DDL},
	{Field: "schemamodel.Constraint.NullsDistinct", Disposition: DDL},
	{Field: "schemamodel.Constraint.OnDelete", Disposition: DDL},
	{Field: "schemamodel.Constraint.OnDeleteColumns", Disposition: DDL},
	{Field: "schemamodel.Constraint.OnUpdate", Disposition: DDL},
	{Field: "schemamodel.Constraint.RequiresExtensions", Disposition: Planning, Reason: "which extensions must exist before this constraint can be created; it orders the statements and appears in none of them"},
	{Field: "schemamodel.Constraint.StructName", Disposition: DDL},
	{Field: "schemamodel.Constraint.Table", Disposition: DDL},
	{Field: "schemamodel.Constraint.Type", Disposition: DDL},
	{Field: "schemamodel.Constraint.UsingMethod", Disposition: DDL},
	{Field: "schemamodel.Constraint.WhereCondition", Disposition: DDL},
	{Field: "schemamodel.Database.CompositeTypes", Disposition: DDL},
	{Field: "schemamodel.Database.Constraints", Disposition: DDL},
	{Field: "schemamodel.Database.DefaultPrivileges", Disposition: DDL},
	{Field: "schemamodel.Database.DatabasePath", Disposition: DDL},
	{Field: "schemamodel.Database.Dependencies", Disposition: Derived, Reason: "table creation order, derived by Finalize from the declared foreign keys"},
	{Field: "schemamodel.Database.Domains", Disposition: DDL},
	{Field: "schemamodel.Database.EmbeddedFields", Disposition: DDL},
	{Field: "schemamodel.Database.EmbeddedSources", Disposition: DDL},
	{Field: "schemamodel.Database.Enums", Disposition: DDL},
	{Field: "schemamodel.Database.ExtendedProperties", Disposition: DDL},
	{Field: "schemamodel.Database.Extensions", Disposition: DDL},

	{Field: "schemamodel.Database.Fields", Disposition: DDL},
	{Field: "schemamodel.Database.FunctionDependencies", Disposition: Derived, Reason: "function creation order, derived by Finalize from the declared bodies"},
	{Field: "schemamodel.Database.Functions", Disposition: DDL},
	{Field: "schemamodel.Database.Grants", Disposition: DDL},
	{Field: "schemamodel.Database.Indexes", Disposition: DDL},
	{Field: "schemamodel.Database.ManagedData", Disposition: Data, Reason: "reference and seed rows; `ptah seed` writes them and `ptah schema render` does not"},
	{Field: "schemamodel.Database.MaterializedViews", Disposition: DDL},
	{Field: "schemamodel.Database.NotDescribed", Disposition: Comparison, Reason: "what the description does not claim to describe; it decides what a diff may conclude about an object nobody looked at, and reaches no statement"},
	{Field: "schemamodel.Database.RLSEnabledTables", Disposition: DDL},
	{Field: "schemamodel.Database.RLSPolicies", Disposition: DDL},
	{Field: "schemamodel.Database.Ranges", Disposition: DDL},
	{Field: "schemamodel.Database.RevokedGrants", Disposition: DDL},
	{Field: "schemamodel.Database.Roles", Disposition: DDL},
	{Field: "schemamodel.Database.Schemas", Disposition: DDL},
	{Field: "schemamodel.Database.SelfReferencingForeignKeys", Disposition: Derived, Reason: "derived by Finalize from the declared foreign keys, so the planner can create the table before the reference to itself"},
	{Field: "schemamodel.Database.Sequences", Disposition: DDL},
	{Field: "schemamodel.Database.Synonyms", Disposition: DDL},
	{Field: "schemamodel.Database.Tables", Disposition: DDL},
	{Field: "schemamodel.Database.Triggers", Disposition: DDL},
	{Field: "schemamodel.Database.Views", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.Comment", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.Dialects", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.Grantee", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.Grantor", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.ObjectType", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.Privileges", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.Revoked", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.Schema", Disposition: DDL},
	{Field: "schemamodel.DefaultPrivilege.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Domain.BaseType", Disposition: DDL},
	{Field: "schemamodel.Domain.Check", Disposition: DDL},
	{Field: "schemamodel.Domain.Comment", Disposition: DDL},
	{Field: "schemamodel.Domain.Default", Disposition: DDL},
	{Field: "schemamodel.Domain.DefaultExpr", Disposition: DDL},
	{Field: "schemamodel.Domain.Dialects", Disposition: DDL},
	{Field: "schemamodel.Domain.Name", Disposition: DDL},
	{Field: "schemamodel.Domain.NotNull", Disposition: DDL},
	{Field: "schemamodel.Domain.Schema", Disposition: DDL},
	{Field: "schemamodel.Domain.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.EmbeddedField.Comment", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.EmbeddedTypeName", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Field", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Mode", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Name", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Nullable", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.OnDelete", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.OnUpdate", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Overrides", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Prefix", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Ref", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.StructName", Disposition: DDL},
	{Field: "schemamodel.EmbeddedField.Type", Disposition: DDL},
	{Field: "schemamodel.EmbeddedSources.Definitions", Disposition: Derived, Reason: "the embedded declarations retained so materialization can run again after a merge; the columns they produce are what reaches DDL"},
	{Field: "schemamodel.EmbeddedSources.Fields", Disposition: DDL},
	{Field: "schemamodel.Enum.Comment", Disposition: DDL},
	{Field: "schemamodel.Enum.Name", Disposition: DDL},
	{Field: "schemamodel.Enum.Schema", Disposition: DDL},
	{Field: "schemamodel.Enum.Values", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Column", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Comment", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Name", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Schema", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.ExtendedProperty.Table", Disposition: DDL},
	{Field: "schemamodel.ExtendedProperty.Value", Disposition: DDL},
	{Field: "schemamodel.Extension.Comment", Disposition: DDL},
	{Field: "schemamodel.Extension.Dialects", Disposition: DDL},
	{Field: "schemamodel.Extension.IfNotExists", Disposition: DDL},
	{Field: "schemamodel.Extension.Name", Disposition: DDL},
	{Field: "schemamodel.Extension.Provides", Disposition: Planning, Reason: "what the extension supplies, so a declaration depending on it can be ordered after it"},
	{Field: "schemamodel.Extension.Schema", Disposition: DDL},
	{Field: "schemamodel.Extension.Version", Disposition: DDL},
	{Field: "schemamodel.Field.APIExpose", Disposition: Export, Reason: "whether the column reaches an exported API contract, and in which direction; Ptah emits no runtime that could enforce it"},
	{Field: "schemamodel.Field.APIName", Disposition: Export, Reason: "the name an exported API document carries when it differs from the database name"},
	{Field: "schemamodel.Field.APINames", Disposition: Export, Reason: "the per-format names an exported API document carries, overriding the general one"},
	{Field: "schemamodel.Field.APIType", Disposition: Export, Reason: "the type an exported document should project the column as, which changes no stored value"},
	{Field: "schemamodel.Field.AutoInc", Disposition: DDL},
	{Field: "schemamodel.Field.Check", Disposition: DDL},
	{Field: "schemamodel.Field.CheckName", Disposition: DDL},
	{Field: "schemamodel.Field.CheckNotEnforced", Disposition: DDL},
	{Field: "schemamodel.Field.Collate", Disposition: DDL},
	{Field: "schemamodel.Field.Comment", Disposition: DDL},
	{Field: "schemamodel.Field.Default", Disposition: DDL},
	{Field: "schemamodel.Field.DefaultExpr", Disposition: DDL},
	{Field: "schemamodel.Field.DefaultSet", Disposition: DDL},
	{Field: "schemamodel.Field.Deferrable", Disposition: DDL},
	{Field: "schemamodel.Field.Enum", Disposition: DDL},
	{
		Field: "schemamodel.Field.FieldName", Disposition: SourceOrigin,
		Reason: "the Go struct field the column was read from; the column's own name is its identity. The only render that moves under " +
			"its ablation is the PostgreSQL-family renderer walking table options in map order",
	},
	{Field: "schemamodel.Field.Foreign", Disposition: DDL},
	{Field: "schemamodel.Field.ForeignKeyMatch", Disposition: DDL},
	{Field: "schemamodel.Field.ForeignKeyName", Disposition: DDL},
	{Field: "schemamodel.Field.ForeignKeyNotEnforced", Disposition: DDL},
	{Field: "schemamodel.Field.GeneratedExpression", Disposition: DDL},
	{Field: "schemamodel.Field.GeneratedFromEmbedded", Disposition: Derived, Reason: "marks a column Finalize materialized from an embedded declaration, so a later finalization can rebuild it rather than duplicate it"},
	{Field: "schemamodel.Field.GeneratedKind", Disposition: DDL},
	{Field: "schemamodel.Field.IdentityGeneration", Disposition: DDL},
	{Field: "schemamodel.Field.IdentityIncrement", Disposition: DDL},
	{Field: "schemamodel.Field.IdentityOptions", Disposition: DDL},
	{Field: "schemamodel.Field.IdentityStart", Disposition: DDL},
	{Field: "schemamodel.Field.Initially", Disposition: DDL},
	{Field: "schemamodel.Field.Name", Disposition: DDL},
	{Field: "schemamodel.Field.NotNullConstraintName", Disposition: DDL},
	{Field: "schemamodel.Field.Nullable", Disposition: DDL},
	{Field: "schemamodel.Field.OnDelete", Disposition: DDL},
	{Field: "schemamodel.Field.OnUpdate", Disposition: DDL},
	{Field: "schemamodel.Field.Overrides", Disposition: DDL},
	{Field: "schemamodel.Field.Primary", Disposition: DDL},
	{Field: "schemamodel.Field.StructName", Disposition: DDL},
	{Field: "schemamodel.Field.Type", Disposition: DDL},
	{Field: "schemamodel.Field.TypeIsDeclaredText", Disposition: DDL},
	{Field: "schemamodel.Field.TypeRawSQL", Disposition: DDL},
	{Field: "schemamodel.Field.Unique", Disposition: DDL},
	{Field: "schemamodel.Field.UniqueExpr", Disposition: DDL},
	{Field: "schemamodel.Function.Body", Disposition: DDL},
	{Field: "schemamodel.Function.Comment", Disposition: DDL},
	{Field: "schemamodel.Function.Dialects", Disposition: DDL},
	{Field: "schemamodel.Function.Kind", Disposition: DDL},
	{Field: "schemamodel.Function.Language", Disposition: DDL},
	{Field: "schemamodel.Function.Leakproof", Disposition: DDL},
	{Field: "schemamodel.Function.Name", Disposition: DDL},
	{Field: "schemamodel.Function.Parallel", Disposition: DDL},
	{Field: "schemamodel.Function.Parameters", Disposition: DDL},
	{Field: "schemamodel.Function.Returns", Disposition: DDL},
	{Field: "schemamodel.Function.Security", Disposition: DDL},
	{Field: "schemamodel.Function.Settings", Disposition: DDL},
	{Field: "schemamodel.Function.Strict", Disposition: DDL},
	{Field: "schemamodel.Function.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Function.Volatility", Disposition: DDL},
	{Field: "schemamodel.Grant.Columns", Disposition: DDL},
	{Field: "schemamodel.Grant.Comment", Disposition: DDL},
	{Field: "schemamodel.Grant.Dialects", Disposition: DDL},
	{
		Field: "schemamodel.Grant.GrantedBy", Disposition: Export,
		Reason: "the grantor a catalog read observed, carried so that a generated document " +
			"can report it cannot represent one; PostgreSQL accepts GRANTED BY only for the " +
			"role that IS the current user, so rendering the observed grantor would fail on " +
			"every apply by another role",
	},
	{Field: "schemamodel.Grant.OnDatabase", Disposition: DDL},
	{Field: "schemamodel.Grant.OnRoutine", Disposition: DDL},
	{Field: "schemamodel.Grant.OnSchema", Disposition: DDL},
	{Field: "schemamodel.Grant.OnSequence", Disposition: DDL},
	{Field: "schemamodel.Grant.OnTable", Disposition: DDL},
	{Field: "schemamodel.Grant.Privileges", Disposition: DDL},
	{Field: "schemamodel.Grant.Role", Disposition: DDL},
	{Field: "schemamodel.Grant.RoutineArguments", Disposition: DDL},
	{Field: "schemamodel.Grant.RoutineKind", Disposition: DDL},
	{Field: "schemamodel.Grant.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Grant.WithOption", Disposition: DDL},
	{Field: "schemamodel.Index.Comment", Disposition: DDL},
	{Field: "schemamodel.Index.Concurrently", Disposition: Planning, Reason: "asks that the index be BUILT without locking when added to a live table; internal/concurrentindex owns that decision, and only a plan carries it into DDL"},
	{Field: "schemamodel.Index.Condition", Disposition: DDL},
	{Field: "schemamodel.Index.Fields", Disposition: DDL},
	{Field: "schemamodel.Index.IncludeColumns", Disposition: DDL},
	{Field: "schemamodel.Index.Invisible", Disposition: DDL},
	{Field: "schemamodel.Index.KeyBlockSize", Disposition: DDL},
	{Field: "schemamodel.Index.Name", Disposition: DDL},
	{Field: "schemamodel.Index.NullsDistinct", Disposition: DDL},
	{Field: "schemamodel.Index.Operator", Disposition: DDL},
	{Field: "schemamodel.Index.Overrides", Disposition: DDL},
	{Field: "schemamodel.Index.Parser", Disposition: DDL},
	{Field: "schemamodel.Index.Parts", Disposition: DDL},
	{Field: "schemamodel.Index.RequiresExtensions", Disposition: Planning, Reason: "the same ordering fact for an index"},
	{Field: "schemamodel.Index.StorageParams", Disposition: DDL},
	{Field: "schemamodel.Index.StructName", Disposition: DDL},
	{Field: "schemamodel.Index.TableName", Disposition: DDL},
	{Field: "schemamodel.Index.Type", Disposition: DDL},
	{Field: "schemamodel.Index.Unique", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Desc", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Expr", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Name", Disposition: DDL},
	{Field: "schemamodel.IndexPart.NullsOrder", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Operator", Disposition: DDL},
	{Field: "schemamodel.IndexPart.Prefix", Disposition: DDL},
	{Field: "schemamodel.ManagedData.File", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.Keys", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.Rows", Disposition: Data, Reason: "the declared rows themselves, read from File; the schema artifact carries these because it cannot carry the working copy File names"},
	{Field: "schemamodel.ManagedData.Schema", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.SourceDir", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.StructName", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedData.Table", Disposition: Data, Reason: "part of the reference-row declaration; `ptah seed` reads it and no renderer does"},
	{Field: "schemamodel.ManagedValue.Null", Disposition: Data, Reason: "a declared cell that is null, which is not the same as a column the row never names"},
	{Field: "schemamodel.ManagedValue.Tag", Disposition: Data, Reason: "the YAML tag a declared cell resolved to; it separates 007 from \"007\" in one column"},
	{Field: "schemamodel.ManagedValue.Text", Disposition: Data, Reason: "the exact text that declared a cell, kept because resolving it to a Go value loses leading zeros, decimal scale and date spelling"},
	{Field: "schemamodel.MaterializedView.Body", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.Comment", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.DependsOn", Disposition: Planning, Reason: "the same ordering edge, on a materialized view"},
	{Field: "schemamodel.MaterializedView.Dialects", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.Name", Disposition: DDL},
	{Field: "schemamodel.MaterializedView.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.PartitionPart.Expr", Disposition: DDL},
	{Field: "schemamodel.PartitionPart.Name", Disposition: DDL},
	{Field: "schemamodel.PartitionSpec.Parts", Disposition: DDL},
	{Field: "schemamodel.PartitionSpec.Type", Disposition: DDL},
	{Field: "schemamodel.PrimaryKeyPart.Desc", Disposition: DDL},
	{Field: "schemamodel.PrimaryKeyPart.Name", Disposition: DDL},
	{Field: "schemamodel.PrimaryKeyPart.Prefix", Disposition: DDL},
	{Field: "schemamodel.PrivilegeGrant.Privilege", Disposition: DDL},
	{Field: "schemamodel.PrivilegeGrant.WithOption", Disposition: DDL},
	{Field: "schemamodel.RLSEnabledTable.Comment", Disposition: Export, Reason: "the comment a shared enablement carries for the HCL and Go writers; SQL Server and ClickHouse, the targets left on the shared model, have no enablement statement to write it on"},
	{Field: "schemamodel.RLSEnabledTable.Dialects", Disposition: DDL},
	{Field: "schemamodel.RLSEnabledTable.Forced", Disposition: Comparison, Reason: "FORCE is PostgreSQL's, whose switches the row-security owner holds; the dialect-neutral comparison of two shared declarations still compares it"},
	{Field: "schemamodel.RLSEnabledTable.StructName", Disposition: DDL},
	{Field: "schemamodel.RLSEnabledTable.Table", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Comment", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Dialects", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Name", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.PolicyFor", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Restrictive", Disposition: Comparison, Reason: "the shared targets write every policy permissive; the dialect-neutral comparison of two shared declarations still compares AS"},
	{Field: "schemamodel.RLSPolicy.StructName", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.Table", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.ToRoles", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.UsingExpression", Disposition: DDL},
	{Field: "schemamodel.RLSPolicy.WithCheckExpression", Disposition: DDL},
	{Field: "schemamodel.Range.Canonical", Disposition: DDL},
	{Field: "schemamodel.Range.ClearedAttributes", Disposition: Comparison, Reason: "records the attributes a declaration explicitly cleared, so a comparison can tell a value nobody wrote from one somebody removed"},
	{Field: "schemamodel.Range.Collation", Disposition: DDL},
	{Field: "schemamodel.Range.Comment", Disposition: DDL},
	{Field: "schemamodel.Range.Dialects", Disposition: DDL},
	{Field: "schemamodel.Range.Name", Disposition: DDL},
	{Field: "schemamodel.Range.Schema", Disposition: DDL},
	{Field: "schemamodel.Range.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Range.Subtype", Disposition: DDL},
	{Field: "schemamodel.Range.SubtypeDiff", Disposition: DDL},
	{Field: "schemamodel.Range.SubtypeOpClass", Disposition: DDL},
	{Field: "schemamodel.Role.Comment", Disposition: DDL},
	{Field: "schemamodel.Role.CreateDB", Disposition: DDL},
	{Field: "schemamodel.Role.CreateRole", Disposition: DDL},
	{Field: "schemamodel.Role.Dialects", Disposition: DDL},
	{Field: "schemamodel.Role.Group", Disposition: DDL},
	{Field: "schemamodel.Role.Inherit", Disposition: DDL},
	{Field: "schemamodel.Role.Login", Disposition: DDL},
	{Field: "schemamodel.Role.MemberOf", Disposition: DDL},
	{Field: "schemamodel.Role.Name", Disposition: DDL},
	{Field: "schemamodel.Role.Password", Disposition: DDL},
	{Field: "schemamodel.Role.Replication", Disposition: DDL},
	{Field: "schemamodel.Role.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Role.Superuser", Disposition: DDL},
	{Field: "schemamodel.Schema.Charset", Disposition: DDL},
	{Field: "schemamodel.Schema.Collate", Disposition: DDL},
	{Field: "schemamodel.Schema.Comment", Disposition: DDL},
	{Field: "schemamodel.Schema.Name", Disposition: DDL},
	{Field: "schemamodel.SelfReferencingFK.FieldName", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.SelfReferencingFK.Foreign", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.SelfReferencingFK.ForeignKeyName", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.SelfReferencingFK.OnDelete", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.SelfReferencingFK.OnUpdate", Disposition: Derived, Reason: "part of that derived record"},
	{Field: "schemamodel.Sequence.AsType", Disposition: DDL},
	{Field: "schemamodel.Sequence.Cache", Disposition: DDL},
	{Field: "schemamodel.Sequence.Comment", Disposition: DDL},
	{Field: "schemamodel.Sequence.Cycle", Disposition: DDL},
	{Field: "schemamodel.Sequence.Dialects", Disposition: DDL},
	{Field: "schemamodel.Sequence.IfNotExists", Disposition: DDL},
	{Field: "schemamodel.Sequence.Increment", Disposition: DDL},
	{Field: "schemamodel.Sequence.MaxValue", Disposition: DDL},
	{Field: "schemamodel.Sequence.MinValue", Disposition: DDL},
	{Field: "schemamodel.Sequence.Name", Disposition: DDL},
	{Field: "schemamodel.Sequence.OwnedBy", Disposition: DDL},
	{Field: "schemamodel.Sequence.Schema", Disposition: DDL},
	{Field: "schemamodel.Sequence.Start", Disposition: DDL},
	{Field: "schemamodel.Sequence.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Synonym.Comment", Disposition: DDL},
	{Field: "schemamodel.Synonym.Name", Disposition: DDL},
	{Field: "ydbworkload.DesiredPool.Spec", Disposition: DDL},
	{Field: "ydbworkload.DesiredPool.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of pool identity"},
	{Field: "ydbworkload.DesiredClassifier.Spec", Disposition: DDL},
	{Field: "ydbworkload.DesiredClassifier.StructName", Disposition: SourceOrigin, Reason: "the annotation holder, independent of classifier identity"},
	{Field: "schemamodel.Synonym.Schema", Disposition: DDL},
	{Field: "schemamodel.Synonym.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Synonym.Target", Disposition: DDL},
	{Field: "schemamodel.Table.APIName", Disposition: Export, Reason: "the name an exported API document carries when it differs from the database name"},
	{Field: "schemamodel.Table.APINames", Disposition: Export, Reason: "the per-format names an exported API document carries, overriding the general one"},
	{Field: "schemamodel.Table.Checks", Disposition: DDL},
	{Field: "schemamodel.Table.Collate", Disposition: DDL},
	{Field: "schemamodel.Table.Comment", Disposition: DDL},
	{Field: "schemamodel.Table.CustomSQL", Disposition: DDL},
	{Field: "schemamodel.Table.DependsOn", Disposition: Planning, Reason: "an ordering edge the author declares because no foreign key states it; the CREATE TABLE it orders does not mention it"},
	{Field: "schemamodel.Table.Engine", Disposition: DDL},
	{Field: "schemamodel.Table.Name", Disposition: DDL},
	{Field: "schemamodel.Table.Overrides", Disposition: DDL},
	{Field: "schemamodel.Table.Partition", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKey", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyDeferrable", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyInclude", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyInitially", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyMethod", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyComment", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyBlockSize", Disposition: DDL},
	{Field: "schemamodel.Constraint.KeyBlockSize", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyName", Disposition: DDL},
	{Field: "schemamodel.Table.PrimaryKeyParts", Disposition: DDL},
	{Field: "schemamodel.Table.Schema", Disposition: DDL},
	{Field: "schemamodel.Table.Strict", Disposition: DDL},
	{Field: "schemamodel.Table.StructName", Disposition: DDL},
	{Field: "schemamodel.Table.Unlogged", Disposition: DDL},
	{Field: "schemamodel.Table.VirtualArguments", Disposition: DDL},
	{Field: "schemamodel.Table.VirtualModule", Disposition: DDL},
	{Field: "schemamodel.Table.WithoutRowID", Disposition: DDL},
	{Field: "schemamodel.TargetNames.GraphQL", Disposition: Export, Reason: "the name one export format carries, overriding the general one"},
	{Field: "schemamodel.TargetNames.OpenAPI", Disposition: Export, Reason: "the name one export format carries, overriding the general one"},
	{Field: "schemamodel.TargetNames.Protobuf", Disposition: Export, Reason: "the name one export format carries, overriding the general one"},
	{Field: "schemamodel.Trigger.Body", Disposition: DDL},
	{Field: "schemamodel.Trigger.Comment", Disposition: DDL},
	{Field: "schemamodel.Trigger.Dialects", Disposition: DDL},
	{Field: "schemamodel.Trigger.Event", Disposition: DDL},
	{Field: "schemamodel.Trigger.ExecuteFunction", Disposition: DDL},
	{Field: "schemamodel.Trigger.ForEach", Disposition: DDL},
	{Field: "schemamodel.Trigger.Name", Disposition: DDL},
	{Field: "schemamodel.Trigger.NewTable", Disposition: DDL},
	{Field: "schemamodel.Trigger.OldTable", Disposition: DDL},
	{Field: "schemamodel.Trigger.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.Trigger.Table", Disposition: DDL},
	{Field: "schemamodel.Trigger.Timing", Disposition: DDL},
	{Field: "schemamodel.Trigger.When", Disposition: DDL},
	{Field: "schemamodel.View.Attributes", Disposition: DDL},
	{Field: "schemamodel.View.Body", Disposition: DDL},
	{Field: "schemamodel.View.Comment", Disposition: DDL},
	{Field: "schemamodel.View.DependsOn", Disposition: Planning, Reason: "an ordering edge the author declares because the view's body does not reveal it; the CREATE VIEW it orders does not mention it"},
	{Field: "schemamodel.View.Dialects", Disposition: DDL},
	{Field: "schemamodel.View.Name", Disposition: DDL},
	{Field: "schemamodel.View.StructName", Disposition: SourceOrigin, Reason: "the Go struct the declaration was read from; the object's own name is its identity"},
	{Field: "schemamodel.View.WithCheck", Disposition: DDL},
}
